[[aap-2.1-intro]]
= Ansible Automation Platform 2.1

Red Hat Ansible Automation Platform simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles. It works across multiple IT domains including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, Red Hat Ansible Automation Platform provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

.Enhancements

* Automation Mesh introduces separate execution capacity and update your cluster without downtime with Automation Mesh that connects the cluster with a flexible communication method using receptor
* The platform installer can deploy a Highly Available (HA) Automation Hub cluster
* Automation Hub connects instances to external Red Hat SSO instances and for the installer to deploy Red Hat SSO
* Bundle installer provides the execution environment as part of the bundle
* In the platform installer, rsync is not required anymore
* The platform installer supports both with rsync and without rsync environment
* Added support for `sshpass 1.09`
* The platform operator has been upgraded to `operator-sdk 1.11`
* Added support for OpenShift Container Platform 4.10
* Added support for disconnected environment in the platform operator
* Added support for SSO configuration for Hub in the platform operator
* Added a must-gather container to help troubleshoot operator issues in the platform operator
* Upgraded execution environment to ansible-core 2.12
* Updated execution environment collections to `core-2.12` compatible collections
