[[platform-124-intro]]
= Red Hat Ansible Automation Platform 1.2.4

Red Hat Ansible Automation Platform simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles. It works across multiple IT domains including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, Red Hat Ansible Automation Platform provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

.Bug fixes

* Added the ability for Ansible Automation Platform 1.2.x to transition from venvs to execution environments smoothly to platform 2.x This includes three new `awx-manage` commands, check associations, and export venvs for building an execution environment.

* Added Ansible 2.9.25 to the platform installer package

* Fixed Tower’s NGINX Instance vulnerability (CVE-2021-23017). For any deployments on RHEL 8, the package comes from RHEL, and just applying the RHEL update resolves this.

* Updated the backup and restore to now work without the `automationhub` group
