[id="ref-navigator-overview-settings_{context}"]

= Creating an {Navigator} settings file

[role="_abstract"]
You can alter the default {Navigator} settings through:

* The command line
* Within a settings file
* As an environment variable

{Navigator} checks for a settings file in the following order and uses the first match:

* `ANSIBLE_NAVIGATOR_CONFIG` - The settings file path environment variable if set.
* `./ansible-navigator.<ext>` - The settings file within the current project directory, with no dot in the file name.
* `\~/.ansible-navigator.<ext>` - Your home directory, with a dot in the file name.

Consider the following when you create an {Navigator} settings file:

* The settings file can be in ``JSON`` or ``YAML`` format.
* For settings in `JSON` format, the extension must be `.json`.
* For settings in `YAML` format, the extension must be `.yml` or `.yaml`.
* The project and home directories can only contain one settings file each.
* If {Navigator} finds more than one settings file in either directory, it results in an error.

You can copy the example settings file below into one of those paths to start your ``ansible-navigator`` settings file.


[source,yaml]
----
    ---
    ansible-navigator:
    #   ansible:
    #     config: /tmp/ansible.cfg
    #     cmdline: "--forks 15"
    #     inventories:
    #     - /tmp/test_inventory.yml
    #     playbook: /tmp/test_playbook.yml
    #   ansible-runner:
    #     artifact-dir: /tmp/test1
    #     rotate-artifacts-count: 10
    #     timeout: 300
    #   app: run
    #   collection-doc-cache-path: /tmp/cache.db
    #   color:
    #     enable: False
    #     osc4: False
    #   editor:
    #     command: vim_from_setting
    #     console: False
    #   documentation:
    #     plugin:
    #       name: shell
    #       type: become
    #   execution-environment:
    #     container-engine: podman
    #     enabled: False
    #     environment-variables:
    #       pass:
    #         - ONE
    #         - TWO
    #         - THREE
    #       set:
    #         KEY1: VALUE1
    #         KEY2: VALUE2
    #         KEY3: VALUE3
    #     image: test_image:latest
    #     pull-policy: never
    #     volume-mounts:
    #     - src: "/test1"
    #       dest: "/test1"
    #       label: "Z"
    #   help-config: True
    #   help-doc: True
    #   help-inventory: True
    #   help-playbook: False
    #   inventory-columns:
    #     - ansible_network_os
    #     - ansible_network_cli_ssh_type
    #     - ansible_connection
      logging:
    #     append: False
        level: critical
    #     file: /tmp/log.txt
    #   mode: stdout
    #   playbook-artifact:
    #     enable: True
    #     replay: /tmp/test_artifact.json
    #     save-as: /tmp/test_artifact.json
----
