
[id="con-about-ansible-navigator_{context}"]


= About Ansible content navigator

[role="_abstract"]

Ansible content navigator (Ansible-navigator) is a tool that produces consistent and portable artifacts that describe the outcome of your automation tasks. You can use Ansible-navigator on local development machines, Execution Environments or the Ansible Automation Platform, with seamless and predictable results across them all.

Ansible-navigator is a command-line, developer-focused tool with a textual user interface that allows you to:

* Launch and watch jobs and playbooks.
* Share stored, completed playbook and job run artifacts in JSON format.
* Browse, introspect, and update multiple Execution Environments.
* Browse your file-based inventory. 
* Render Ansible module documentation and extract examples you can put in your playbooks.

== Why use Ansible-navigator?

Currently, the Ansible commands that are part of Ansible core, such as the `ansible-playbook` command, cannot execute in containers. To fill this need, Ansible-navigator enables a set of these Ansible CLI commands within Execution Environments or forwards commands to the Ansible Automation Platform automation controller. The job output in the automation controller is the same as a playbook, just within the context of a graphical user interface. Ansible-navigator has a more detailed output within its textual user interface, which is useful when running jobs at a high scale.

Ansible-navigator makes the previous methods of inspecting and executing automation easy and frictionless (whether someone comes from a community contributor background or is an Ansible Automation Platform user, since all that is required for the Ansible Automation Platform is to add automation controller credentials into an Ansible-navigator configuration file. In this way, Ansible-navigator is a bridge between the worlds of the developer who is used to working with the command line and the administrator, auditor or team user who is more familiar with the Ansible Automation Platform.  
