
[id="con-about-ansible-navigator_{context}"]


= About {Navigator}

[role="_abstract"]

{Navigator} is a command line, developer-focused tool with a textual user interface that allows you to:

* Launch and watch jobs and playbooks.
* Share stored, completed playbook and job run artifacts in JSON format.
* Browse, introspect, and update multiple {ExecEnvName}.
* Browse your file-based inventory. 
* Render Ansible module documentation and extract examples you can use in your playbooks.

== Why use {Navigator}?

Currently, the Ansible commands that are part of Ansible core, such as the `ansible-playbook` command, cannot execute in containers. To fill this need, {Navigator} enables a set of these Ansible CLI commands within {ExecEnvName} or forwards commands to the {PlatformName} {ControllerName}. The job output in the {ControllerName} is the same as a playbook, just within the context of a graphical user interface. {Navigator} has a more detailed output within its textual user interface, which is useful when running jobs at a high scale.

{Navigator} makes the previous methods of inspecting and executing automation easy and frictionless (whether someone comes from a community contributor background or is an {PlatformName} user) since all that is required for the {PlatformName} is to add {ControllerName} credentials into an {Navigator} configuration file. In this way, {Navigator} is a bridge between the worlds of the developer who is used to working with the command line and the administrator, auditor or team user who is more familiar with the {PlatformName}.  
