
[id="con-navigator-mode_{context}"]

= {Navigator} modes

{Navigator} operates in two modes:

[role="_abstract"]

passthrough mode:: Accepts most of the existing Ansible commands and extensions at the command line.
textual user interface mode:: Provides an interactive, text-based interface to the Ansible commands for an enhanced set of capabilities that allow you to evaluate content, run playbooks, and troubleshoot playbooks after they run using artifact files.

== Passthrough mode

Passthrough mode uses the familiar Ansible commands, such as `ansible-playbook` within {ExecEnvName}, or on your local development environment. This mode allows you to continue using commands you are familiar with for quick tasks.

----
$ ansible-navigator --help
usage: ansible-navigator [-h] [--ce {podman,docker}] [--ee]
                         [--eei EE_IMAGE] [--ic INVENTORY_COLUMNS]
                         [--ide {pycharm,vim,vscode}] [--lf LOGFILE]
                         [--ll {debug,info,warning,error,critical}]
                         [--no-osc4] [--web] [-m {stdout,interactive}]
                         {command} --help ...

optional arguments:
  -h, --help            show this help message and exit
  --ce {podman,docker}, --container-engine {podman,docker}
                        Specify the container engine to run the
                        Execution Environment (default: podman)
  --ee, --execution-environment
                        Run the playbook in an Execution Environment
                        (default: False)
  --eei EE_IMAGE, --ee-image EE_IMAGE
                        Specify the name of the container image
                        containing an Execution Environment (default:
                        quay.io/ansible/ansible-runner:devel)
  --ic INVENTORY_COLUMNS, --inventory-columns INVENTORY_COLUMNS
                        Additional columns to be shown in the inventory
                        views, comma delimited, eg 'xxx,yyy,zzz'
                        (default: )
  --ide {pycharm,vim,vscode}
                        Specify the current ide (default: vim)
  --lf LOGFILE, --logfile LOGFILE
                        Specify the application log file location
                        (default: ./ansible_navigator.log)
  --ll {debug,info,warning,error,critical}, --loglevel {debug,info,warning,error,critical}
                        Specify the application log level (default:
                        info)
  --no-osc4             Disable OSC-4 support (xterm.js color fix)
                        (default: False)
  --web                 Run the application in a browser rather than
                        the current terminal (default: False)
  -m {stdout,interactive}, --mode {stdout,interactive}
                        Specify the navigator mode to run (default:
                        stdout)

subcommands:
  valid subcommands

  {command} --help      additional help
    collections         Explore installed collections
    config              Explore the current ansible configuration
    doc                 Show a plugin doc
    inventory           Explore inventories
    load                Load an artifact
    run                 Run Ansible playbook in either interactive or
                        stdout mode
----


== Textual user interface mode

The Textual user interface mode provides enhanced interaction with {ExecEnvName}, collections, playbooks, and inventory. This mode is compatible with integrated development environments (IDE), such as Visual Studio Code.

----
 0│## Welcome
 1│---------------------------------------------------------------------------------------------------
 2│
 3│Some things you can try from here:
 4│- `:config`                                               Explore the current Ansible configuration
 5│- `:collections`                                          Explore installed collections
 6│- `:doc <plugin>`                                         Show a plugin doc
 7│- `:r, :run <playbook> -i <inventory> -m interactive`     Run a playbook in interactive mode
 8│- `:help`                                                 Show the main help page
 9│- `:inventory <inventory>`                                Explore an inventory
10│- `:log`                                                  Review the application log
11│- `:open`                                                 Open current page in the IDE
12│- `:quit`                                                 Quit the application
13│
14│happy automating,
15│
16│-ansible-navigator
----
