
[id="proc-review-config-tui_{context}"]



= Reviewing your Ansible configuration from {Navigator}

[role="_abstract"]

You can review your Ansible configuration with the {Navigator} text-based user interface in interactive mode and delve into the settings. {Navigator} pulls in the results from an accessible Ansible configuration file, or returns the defaults if no configuration file is present.


.Procedure


. Start {Navigator}
+
```
$ ansible-navigator
```
+
You can optionally type `ansible-navigator config` from the command line to directly access the Ansible configuration settings.

. Review the Ansible configuration.
+
```
 :config

 OPTION                                  DEFAULT SOURCE  VIA                             CURRENT VALUE
  0│ACTION_WARNINGS                      True default default                         True
  1│AGNOSTIC_BECOME_PROMPT               True default default                         True
  2│ALLOW_WORLD_READABLE_TMPFILES        True default default                         False
  3│ANSIBLE_CONNECTION_PATH              True default default                         None
  4│ANSIBLE_COW_ACCEPTLIST               False env    ANSIBLE_COW_ACCEPTLIST          ['bud-frogs', 'dragon']
  5│ANSIBLE_COW_PATH                     True default default                         None
  6│ANSIBLE_COW_SELECTION                True default default                         default
  7│ANSIBLE_FORCE_COLOR                  True default default                         False
  8│ANSIBLE_NOCOLOR                      True default default                         False
  9│ANSIBLE_NOCOWS                       True default default                         False
 10│ANSIBLE_PIPELINING                   True default default                         False
 11│ANY_ERRORS_FATAL                     True default default                         False
 12│BECOME_ALLOW_SAME_USER               True default default                         False
 13│BECOME_PLUGIN_PATH                   True default default                         ['/home/runner/.ansible/plugins/become', '/usr/share/ansible/plugins/become']
 14│CACHE_PLUGIN                         False env    ANSIBLE_CACHE_PLUGIN            jsonfile
 15│CACHE_PLUGIN_CONNECTION              False env   ANSIBLE_CACHE_PLUGIN_CONNECTION /runner/artifacts/d2e5510d-b518-4625-8067-5a4da2a1d32c/fact_cac
 16│CACHE_PLUGIN_PREFIX                  True default default                         ansible_facts

```
+
Some values reflect settings from within the {ExecEnvName} needed for the {ExecEnvName} to function.  These display as non-default settings you cannot set in your Ansible configuration file.

. Type the number corresponding to the setting you want to delve into, or type `:<number>` for numbers greater than 9.
+
```
CACHE PLUGIN (current: jsonfile)  (default: memory)
 0│---
 1│current: jsonfile
 2│default: memory
 3│description: Chooses which cache plugin to use, the default 'memory' is ephemeral.
 4│env:
 5│- name: ANSIBLE_CACHE_PLUGIN
 6│ini:
 7│- key: fact_caching
 8│  section: defaults
 9│name: Persistent Cache plugin
10│option: CACHE_PLUGIN
11│source: env
12│via: ANSIBLE_CACHE_PLUGIN
13│yaml:
14│  key: facts.cache.plugin

^f/PgUp page up     ^b/PgDn page down     ↑↓ scroll     esc back     - previous     + next     [0-9] goto     :help help

```
The output shows the current setting as well as the default.

.Verification

*  Review the configuration output.
+
```
 :config
    OPTION                                  DEFAULT SOURCE  VIA                             CURRENT VALUE
  0│ACTION_WARNINGS                          True default default                         True
  1│AGNOSTIC_BECOME_PROMPT                   True default default                         True
  2│ALLOW_WORLD_READABLE_TMPFILES            True default default                         False
  3│ANSIBLE_CONNECTION_PATH                  True default default                         None
  4│ANSIBLE_COW_ACCEPTLIST                   False env    ANSIBLE_COW_ACCEPTLIST          ['bud-frogs', 'dragon']
  5│ANSIBLE_COW_PATH                         True default default                         None
  6│ANSIBLE_COW_SELECTION                    True default default                         default

  <...output truncated...>

```

[role="_additional-resources"]
.Additional resources

* https://docs.ansible.com/ansible/latest/cli/ansible-config.html[ansible-config].
* https://docs.ansible.com/ansible/latest/installation_guide/intro_configuration.html[Introduction to Ansible configuration].
