[id="ref-navigator-faq-{context}"]

= {Navigator} Frequently asked questions

[role="_abstract"]
Use the following {Navigator} FAQ to help you troubleshoot problems in your environment.


Where should the `ansible.cfg` file go when using an {ExecEnvNameSing}?:: The easiest place to have the `ansible.cfg` is in the project directory adjacent to the playbook. The playbook directory is automatically mounted in the execution environment and the `ansible.cfg` file will be found.  If the `ansible.cfg` file is in another directory, the `ANSIBLE_CONFIG` variable needs to be set and the directory specified as a custom volume mount. (See {Navigator} settings for `execution-environment-volume-mounts`)
+
Where should the `ansible.cfg` file go when not using an {ExecEnvNameSing} Ansible looks for the `ansible.cfg` in the typical locations when not using an {ExecEnvNameSing}. See https://docs.ansible.com/ansible/latest/reference_appendices/config.html[Ansible configuration settings] for details.

Where should Ansible collections be placed when using an {ExecEnvNameSing}?:: The easiest place to have Ansible collections is in the project directory, in a playbook adjacent collections directory (for example, `ansible-galaxy collections install ansible.utils -p ./collections`).  The playbook directory is automatically mounted in the {ExecEnvNameSing} and {Navigator} finds the collections there. Another option is to build the collections into an {ExecEnvNameSing} using {Builder}. This helps content creators author playbooks that are production ready, since {ControllerName} supports playbook adjacent collection directories. If the collections are in another directory, set the `ANSIBLE_COLLECTIONS_PATHS` variable  and configure a custom volume mount for the directory. (See xref:ref-navigator-general-settings_settings-navigator[Automation content navigator general settings] for `execution-environment-volume-mounts`).

Where should ansible collections be placed when not using an {ExecEnvNameSing}?:: When not using an {ExecEnvNameSing}, Ansible looks in the default locations for collections. See the https://docs.ansible.com/ansible/latest/user_guide/collections_using.html[Ansible Collections User Guide].

Why does the playbook hang when `vars_prompt` or `pause/prompt` is used?:: By default, {Navigator} runs the playbook in the same manner that {ControllerName} runs the playbook. This was done to help content creators author playbooks that would be ready for production. If the use of `vars_prompt` or `pause\prompt` can not be avoided, disabling `playbook-artifact` creation causes {Navigator} to run the playbook in a manner that is compatible with `ansible-playbook` and allows for user interaction.

Why does {Navigator} change the terminal colors or look terrible?:: {Navigator} queries the terminal for its OSC4 compatibility. OSC4, 10, 11, 104, 110, 111 indicate the terminal supports color changing and reverting. It is possible that the terminal is misrepresenting its ability.  OSC4 detection can be disabled by setting `--osc4 false`. (See xref:ref-navigator-general-settings_settings-navigator[Automation content navigator general settings] for how to handle this with an environment variable or in the settings file).

How can I change the colors used by {Navigator}?:: Use `--osc4 false` to force {Navigator} to use the terminal defined colors. (See xref:ref-navigator-general-settings_settings-navigator[Automation content navigator general settings] for how to handle this with an environment variable or in the settings file).

What's with all these `site-artifact-2021-06-02T16:02:33.911259+00:00.json` files in the playbook directory?:: {Navigator} creates a playbook artifact for every playbook run.  These can be helpful for reviewing the outcome of automation after it is complete, sharing and troubleshooting with a colleague, or keeping for compliance or change-control purposes.  The playbook artifact file contains the detailed information about every play and task, as well as the `stdout` from the playbook run. UYou can review playbook artifacts with `ansible-navigator replay <filename>` or `:replay <filename>` while in an {Navigator} session. All playbook artifacts can be reviewed with both `--mode stdout` and `--mode interactive`, depending on the desired view. You can disable playbook artifacts writing and the default file naming convention. (See xref:ref-navigator-general-settings_settings-navigator[Automation content navigator general settings] for how to handle this with an environment variable or in the settings file).

Why does `vi` open when I use `:open`?:: {Navigator} opens anything showing in the terminal in the default editor.  The default is set to either `vi +{line_number} {filename}` or the current value of the `EDITOR` environment variable. Related to this is the `editor-console` setting which indicates if the editor is console/terminal based. Here are examples of alternate settings that may be useful:
+
[source,yaml]
----
# emacs
ansible-navigator:
  editor:
    command: emacs -nw +{line_number} {filename}
    console: true
----
+
[source,yaml]
----
# vscode
ansible-navigator:
  editor:
    command: code -g {filename}:{line_number}
    console: false
----
+
[source,yaml]
----
#pycharm
ansible-navigator:
  editor:
    command: charm --line {line_number} {filename}
    console: false
----

What is the order in which configuration settings are applied?:: The {Navigator} configuration system pulls in settings from various sources and applies them hierarchically in the following order (where the last applied changes are the most prevalent):
+
. Default internal values
. Values from a settings file
. Values from environment variables
. Flags and arguments specified on the command line
. While issuing `:` commands within the text-based user interface

Something didn't work, how can I troubleshoot it?:: {Navigator} has reasonable logging messages. You can enable `debug` logging  with `--log-level debug`. If you think you might have found a bug, please log an issue and include the details from the log file.
