

ifdef::context[:parent-context: {context}]



[id="upgrading-platform"]
= Upgrading to {PlatformName}


:context: upgrading-platform



[role="_abstract"]
{HubNameStart} acts as a content provider for {ControllerName}, which requires both an {ControllerName} deployment and an {HubName} deployment running alongside each other. The {PlatformName} installer contains both of these. This section covers each component of the upgrading process:

* Upgrade planning
* Obtaining the installer
* Setting up the inventory file
* Running the setup playbook
* Migrating from virtual environments to {ExecEnvName}

[NOTE]
====
All upgrades should be no more than two major versions behind what you are currently upgrading to. For example, in order to upgrade to {ControllerName} 4.0, you must first be on version 3.8.x. There is no direct upgrade path from version 3.7.x or earlier. Refer to the article, link:https://access.redhat.com/articles/4098921[Recommended upgrade path] on the Red Hat customer portal for more information.

In order to run {ControllerName} 4.0, you must also have Ansible 2.10.
====


include::platform/con-upgrade-planning.adoc[leveloffset=+1]
include::platform/proc-choosing-obtaining-installer.adoc[leveloffset=+1]

== Setting up the inventory file

To upgrade using the {PlatformName} installer, edit the inventory file found in the installer using the same parameters as used in your previous {PlatformName} setup.

NOTE: To review information about the inventory file requirements for your specific intsallation scenario, see the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_installation_guide/planning-installation#supported_installation_scenarios[{PlatformName} Installation Guide].

.Procedure
. Navigate to the installer
.. [bundled installer]
+
-----
$ cd ansible-automation-platform-setup-bundle-<latest-version>
-----
+
.. [online installer]
+
-----
$ cd ansible-automation-platform-setup-<latest-version>
-----
+
. Open the `inventory` file with a text editor.
. Edit the `inventory` file parameters to match the `inventory` file in your previous version of {PlatformName}.

== Running the {PlatformName} installer setup script

You can run the setup script once you have finished updating the `inventory` file to match your previous {PlatformNameShort} installation.

.Procedure

. Run the `setup.sh` script
+
-----
$ ./setup.sh
-----

The installation will begin.


////
[role="_additional-resources"]
== Additional resources (or Next steps)
Optional. Delete if not used.
* A bulleted list of links to other material closely related to the contents of the assembly, including xref links to other assemblies in your collection.
* For more details on writing assemblies, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
