[id="assembly-inventory-file-importing"]

= Inventory File Importing

{ControllerNameStart} enables you to choose an inventory file from source control, rather than creating one from scratch. 
This function is the same as for custom inventory scripts, except that the contents are obtained from source control instead of editing their contents in a browser. 
This means that the files are non-editable, and as inventories are updated at the source, the inventories within the projects are also updated accordingly, including the `group_vars` and `host_vars` files or directory associated with them. 
SCM types can consume both inventory files and scripts. 
Both inventory files and custom inventory types use scripts.

Imported hostss have a description of _imported_ by default.
This can be overridden by setting the `_awx_description` variable on a given host. 
For example, if importing from a sourced '.ini` file, you can add the following host variables:

[literal, options="nowrap" subs="+attributes"]
----
[main]
127.0.0.1 _awx_description="my host 1"
127.0.0.2 _awx_description="my host 2"
----

Similarly, group descriptions also default to _imported_, but can also be overridden by `_awx_description`.

To use old inventory scripts in source control, see [Export old inventory scripts] in the _{ControllerUG}_.

include::platform/con-controller-custom-dynamic-inv-scripts.adoc[leveloffset=+1]
include::platform/ref-controller-scm-inv-source-fields.adoc[leveloffset=+1]


