[id="controller-credentials"]

ifdef::controller-GS[]
= Managing credentials


Credentials authenticate the controller user to launch Ansible playbooks. The passwords and SSH keys are used to authenticate against inventory hosts. 
By using the credentials feature of {ControllerName}, you can require the {ControllerName} user to enter a password or key phrase when a playbook launches.

include::platform/proc-controller-create-credential.adoc[leveloffset=+1]
include::platform/proc-controller-edit-credential.adoc[leveloffset=+1]
endif::controller-GS[]
ifdef::controller-UG[]
= Credentials

Credentials authenticate the {ControllerName} user when launching jobs against machines, synchronizing with inventory sources, and importing project content from a version control system.

You can grant users and teams the ability to use these credentials, without exposing the credential to the user. 
If a user moves to a different team or leaves the organization, you don't have to re-key all of your systems just because that credential was available in {ControllerName}.

[NOTE]
====
{ControllerNameStart} encrypts passwords and key information in the database and never makes secret information visible through the API. 
For further information, see the _Automation Controller Administration Guide_.
====

== How Credentials Work
{ControllerNameStart} uses SSH to connect to remote hosts. 
To pass the key from {ControllerName} to SSH, the key must be decrypted before it can be written to a named pipe. 
{ControllerNameStart} uses that pipe to send the key to SSH (so that it is never written to disk).
If passwords are used, {ControllerName} handles those by responding directly to the password prompt and decrypting the password before writing it to the prompt.

include::platform/ref-controller-credentials-getting-started.adoc[leveloffset=+1]
include::platform/proc-controller-create-credential.adoc[leveloffset=+1]
include::platform/ref-controller-credential-types.adoc[leveloffset=+1]

endif::controller-UG[]

