
ifdef::context[:parent-context: {context}]



[id="planning-installation"]
= Planning your {PlatformName} installation


:context: planning

[role="_abstract"]
To help plan your {PlatformName} installation, review information on the setup installer, system requirements, and supported installation scenarios.

include::platform/ref-system-requirements.adoc[leveloffset=+1]
include::platform/ref-platform-components.adoc[leveloffset=+1]
include::platform/ref-controller-system-requirements.adoc[leveloffset=+1]
include::platform/ref-automation-hub-requirements.adoc[leveloffset=+1]
include::platform/ref-postgresql-requirements.adoc[leveloffset=+1]
include::platform/ref-network-ports-protocols.adoc[leveloffset=+1]

include::platform/proc-attaching-subscriptions.adoc[leveloffset=+1]

include::platform/proc-choosing-obtaining-installer.adoc[leveloffset=+1]

//New section here
include::platform/con-inventory-introduction.adoc[leveloffset=+1]
include::platform/ref-guidelines-hosts-groups.adoc[leveloffset=+2]
include::platform/ref-deprovisioning.adoc[leveloffset=+2]
include::platform/con-inventory-variables-intro.adoc[leveloffset=+2]
include::platform/con-declaring-variables.adoc[leveloffset=+2]
include::platform/proc-securing-secrets-in-inventory.adoc[leveloffset=+2]
include::platform/con-editing-inventory-files.adoc[leveloffset=+2]
//End of new section

== Supported installation scenarios

Red Hat supports the following installations scenarios for {PlatformName}

include::platform/con-SM-standalone-contr-non-inst-database.adoc[leveloffset=+2]

//[dcd 12/7/22] Changing xrefs to links because information is in a separate document due to restructuring.

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/single-machine-scenario#standalone-controller-non-inst-database[Installing {ControllerName} with a database on the same node] to get started.

//See xref:standalone-controller-non-inst-database[Installing {ControllerName} with a database on the same node] in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-SM-standalone-contr-ext-database.adoc[leveloffset=+2]

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/single-machine-scenario#assembly-standalone-controller-ext-database[Installing {ControllerName} with an external managed database] to get started.

//See xref:assembly-standalone-controller-ext-database[Installing {ControllerName} with an external managed database] in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-SM-standalone-hub-non-inst-database.adoc[leveloffset=+2]

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/single-machine-scenario#assembly-standalone-hub-non-inst-database[Installing {HubName} with a database on the same node] to get started.

//See xref:assembly-standalone-hub-non-inst-database[Installing {HubName} with a database on the same node] in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-SM-standalone-hub-ext-database.adoc[leveloffset=+2]

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/single-machine-scenario#assembly-standalone-hub-ext-database[Installing {HubName} with an external database] to get started.

//See xref:assembly-standalone-hub-ext-database[Installing {HubName} with an external database] in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-platform-non-inst-database.adoc[leveloffset=+2]

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#assembly-platform-non-inst-database[Installing {PlatformName} with a database on the {ControllerName} node or non-installer managed database] to get started.

//See xref:assembly-platform-non-inst-database[Installing {PlatformName} with a database on the {ControllerName} node or non-installer managed database] in _Installing {PlatformName}_ to get started.

include::platform/con-platform-ext-database.adoc[leveloffset=+2]

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#assembly-platform-ext-database[Installing {PlatformName} with an external managed database] to get started.

//See xref:assembly-platform-ext-database[Installing {PlatformName} with an external managed database] in _Installing {PlatformName}_ to get started.

include::platform/con-cluster-platform-ext-database.adoc[leveloffset=+2]

See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/assembly-multi-machine-cluster-scenario[Installing a multi-node {PlatformName} with an external managed database] to get started.

//See xref:assembly-multi-machine-cluster-scenario[Installing a multi-node {PlatformName} with an external managed database] in _Multi-machine cluster installation_ to get started.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
