////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]


[id="installing-hub-operator"]
= Installing and configuring {HubName} on {OCP} web console

:context: installing-hub-operator

[role="_abstract"]
You can use these instructions to install the {HubName} operator on {OCP}, specify custom resources, and deploy {PlatformNameShort} with an external database.

[NOTE]
====
When an instance of {HubName} is removed, the PVCs are not automatically deleted. This can cause issues during migration if the new deployment has the same name as the previous one. Therefore, it is recommended that you manually remove old PVCs before deploying a new {HubName} instance in the same namespace. See xref:proc-find-delete-PVCs_{context}[Finding and deleting PVCs] for more information.
====


// mirrors AWX operator flow

== Prerequisites

* You have installed the {PlatformName} operator in Operator Hub.

== Installing the {HubName} operator

. Navigate to menu:Operators[Installed Operators].
. Locate the *Automation hub* entry, then click *Create instance*.

include::platform/con-storage-options-for-operator-installation-on-ocp.adoc[leveloffset=+2]
include::platform/proc-provision-ocp-storage-with-readwritemany.adoc[leveloffset=+3]
include::platform/proc-hub-route-options.adoc[leveloffset=+2]
include::platform/proc-hub-ingress-options.adoc[leveloffset=+2]

Once you have configured your {HubName} operator, click *Create* at the bottom of the form view. {OCP} will now create the pods. This may take a few minutes.

* View progress by navigating to menu:Workloads[Pods] and locating the newly created instance.

include::platform/proc-access-hub-operator-ui.adoc[leveloffset=+1]

include::platform/proc-operator-external-db-hub.adoc[leveloffset=+1]

include::platform/proc-find-delete-PVCs.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources

* For more information on running operators on OpenShift Container Platform, navigate to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/[OpenShift Container Platform product documentation] and click the _Operators - Working with Operators in OpenShift Container Platform_ guide.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
