[id="assembly-controller-log-files"]

= {ControllerNameStart} logfiles

{ControllerNameStart} logfiles can be accessed from two centralized locations:

* `/var/log/tower/`
* `/var/log/supervisor/`

In the `/var/log/tower/` directory, you can view logfiles captured by:

* *tower.log:* Captures the log messages such as runtime errors that occur when the job is executed.
* *callback_receiver.log:* Captures callback receiver logs that handles callback events when running ansible jobs.
* *dispatcher.log:* Captures log messages for the {ControllerName} dispatcher worker service.
* *job_lifecycle.log:* Captures details of the job run, whether it is blocked, and what condition is blocking it.
* *management_playbooks.log:* Captures the logs of management playbook runs, and isolated job runs such as copying the metadata.
* *rsyslog.err:* Captures rsyslog errors authenticating with external logging services when sending logs to them.
* *task_system.log:* Captures the logs of tasks that {ControllerName} is running in the background, such as adding cluster instances and logs related to information gathering or processing for analytics.
* *tower_rbac_migrations.log:* Captures the logs for rbac database migration or upgrade.
* *tower_system_tracking_migrations.log:* Captures the logs of the controller system tracking migration or upgrade.
* *wsbroadcast.log:* Captures the logs of websocket connections in the controller nodes.

In the `/var/log/supervisor/` directory, you can view logfiles captured by:

* *awx-callback-receiver.log:* Captures the log of callback receiver that handles callback events when running ansible jobs, managed by `supervisord`.
* *awx-daphne.log:* Captures the logs of Websocket communication of WebUI.
* *awx-dispatcher.log:* Captures the logs that occur when dispatching a task to an {ControllerName} instance, such as when running a job.
* *awx-rsyslog.log:* Captures the logs for the `rsyslog` service.
* *awx-uwsgi.log:* Captures the logs related to uWSGI, which is an application server.
* *awx-wsbroadcast.log:* Captures the logs of the websocket service that is used by {ControllerName}.
* *failure-event-handler.stderr.log:* Captures the standard errors for `/usr/bin/failure-event-handler` supervisord's subprocess.
* *supervisord.log:* Captures the logs related to `supervisord` itself.

The `/var/log/supervisor/` directory includes `stdout` files for all services as well.

You can expect the following log paths to be generated by services used by {ControllerName} (and {PlatformNameShort}):

* */var/log/nginx/*
* */var/lib/pgsql/data/pg_log/*
* */var/log/redis/*

.Troubleshooting

Error logs can be found in the following locations:

* {ControllerNameStart} server errors are logged in `/var/log/tower`. 
* Supervisors logs can be found in `/var/log/supervisor/`. 
* Nginx web server errors are logged in the httpd error log. 
* Configure other {ControllerName} logging needs in `/etc/tower/conf.d/`.

Explore client-side issues using the JavaScript console built into most browsers and report any errors to Ansible through the Red Hat Customer portal at: https://access.redhat.com/.
