ifdef::context[:parent-context: {context}]

[id="using-rhsso-operator-with-automation-hub"]

:context: using-a-rhsso-operator

= Using a Red Hat Single Sign On Operator with {HubName}

The _{PlatformName}_ (AAP) _{PrivateHubNameStart}_ (PAH) uses Red Hat Single Sign-On (RH-SSO) for external authentication.

The Red Hat Single Sign-On Operator automates Red Hat Single Sign-On administration in Openshift.
Use this Operator to create custom resources, which automate administrative tasks.

When installing AAP on VMs the installer can automatically install and configure RH-SSO for use with PAH.
RH-SSO integration has not been implemented when installing AAP on _{OCP}_ (OCP) using the AAP Operator.
This chapter describes the process to configure RH-SSO and integrate it with PAH when AAP is installed on {OCPShort}.

For more information on running operators on {OCPShort}, see Operators - Working with Operators in {OCPShort} in the {OCPShort} product documentation.

.Prerequisites
* You have access to {OCP} using an account with operator installation permissions.
* You have installed the catalog containing the {PlatformName} operators

include::platform/proc-install-rh-sso-operator.adoc[leveloffset=2]
include::platform/proc-create-keycloak-instance.adoc[leveloffset=2]
include::platform/proc-create-keycloak-realm.adoc[leveloffset=2]
include::platform/proc-create-keycloak-client.adoc[leveloffset=2]
include::platform/proc-create-a-user.adoc[leveloffset=2]
include::platform/proc-installing-the-ansible-platform-operator.adoc[leveloffset=2]
include::platform/proc-creating-a-secret.adoc[leveloffset=2]
include::platform/proc-installing-hub-using-operator.adoc[leveloffset=2]
include::platform/proc-determine-hub-route.adoc[leveloffset=2]
include::platform/proc-update-rhsso-client.adoc[leveloffset=2]
include::platform/proc-verify-connectivity.adoc[leveloffset=2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
