////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]


[id="installing-contr-operator-external"]
= Installing {ControllerName} on {OCP} with an external database


:context: installing-contr-operator-external


[role="_abstract"]
You can use these instructions to install the {ControllerName} operator on {OCP} with an external PostgreSQL 12 database and route, as well as specify customer resources.

// mirrors AWX operator flow

== Prerequisites

* You have installed the catalog containing the {PlatformName} operators

== Installing the {ControllerName} operator

. Log in to {OCP}.
. Navigate to *Operators* -> *Operator Hub*.
. Locate the {PlatformName} catalog and click *Create Instance*.

[NOTE]
====
{OCP} clusters running on AWS do not support ReadWriteMany without adding NFS or other storage.
====

.Optional - Configure your {ControllerName} operator route options
. Click *Advanced configuration*.
. Under “Tower Ingress type”, click the dropdown menu and select *Route*.
. Under “Route DNS host”, enter a common host name that the route answers for
. Under “Route TLS termination mechanism”, click the dropdown menu and select *Edge* or *Passthrough*.
. Under “Route TLS credential secret”, click the dropdown menu and select a secret from the list.


.Optional - Configure the Ingress type for your {ControllerName} operator
. Click *Advanced Configuration*.
. Under “Tower Ingress type”, click the dropdown menu and select *Ingress*.
. Under “Tower Ingress annotations”, enter any annotations to add to the ingress.
. Under “Tower Ingress TLS secret”, click the dropdown menu and select a secret from the list.

Once you have configured your {ControllerName} operator, click *Create* at the bottom of the form view. {OCP} will now create the pods. This may take a few minutes.

* View progress by navigating to *Workloads* -> *Pods* and locating the newly created instance.

[role="_additional-resources"]
== Additional resources

* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/operators/index[Working with Operators in OpenShift Container Platform] for more information on running operators on OpenShift Container Platform.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
