

[id="proc-attaching-subscriptions_{context}"]

= Attaching your {PlatformName} subscription

[role="_abstract"]
You *must* have valid subscriptions attached on all nodes before installing {PlatformName}. Attaching your {PlatformNameShort} subscription allows you to access subcription-only resources necessary to proceed with the installation.

NOTE: Attaching a subscription is unnecessary if you have enabled link:https://access.redhat.com/articles/simple-content-access[Simple Content Access Mode] on your Red Hat account. Once enabled, you will need to register your systems to either Red Hat Subscription Management (RHSM) or Satellite before installing the {PlatformNameShort}. See link:https://access.redhat.com/articles/simple-content-access[Simple Content Access Mode] for more information.

.Procedure

. Obtain the `pool_id` for your {PlatformName} subscription:
+
-----
# subscription-manager list --available --all | grep "Ansible Automation Platform" -B 3 -A 6
-----
+
[NOTE]
====
Do not use MCT4022 as a `pool_id` for your subscription because it can cause {PlatformNameShort} subscription attachment to fail.
====
+
.Example
An example output of the `*subsciption-manager list*` command. Obtain the `pool_id` as seen in the `Pool ID:` section:
+
-----
Subscription Name: Red Hat Ansible Automation, Premium (5000 Managed Nodes)
  Provides: Red Hat Ansible Engine
  Red Hat Ansible Automation Platform
  SKU: MCT3695
  Contract: ````
  Pool ID: <pool_id>
  Provides Management: No
  Available: 4999
  Suggested: 1
-----
+
. Attach the subscription:
+
-----
# subscription-manager attach --pool=<pool_id>
-----

You have now attached your {PlatformName} subscriptions to all nodes.

.Verification

* Verify the subscription was successfully attached:

-----
# subscription-manager list --consumed
-----

.Troubleshooting

* If you are unable to locate certain packages that came bundled with the {PlatformNameShort} installer, or if you are seeing a `_Repositories disabled by configuration_` message, try enabling the repository using the command:
+
{PlatformName} {PlatformVers} for RHEL 8
+
----
subscription-manager repos --enable ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms
----
+
{PlatformName} {PlatformVers} for RHEL 9
+
----
subscription-manager repos --enable ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms
----
