ifdef::context[:parent-context: {context}]

[id="migrate-isolated-execution-nodes"]

= Migrating isolated nodes to execution nodes

[role="_abstract"]
Upgrading from version 1.x to the latest version of the {PlatformName} requires platform administrators to migrate data from isolated legacy nodes to execution nodes. This migration is necessary to deploy the automation mesh.

This guide explains how to perform a side-by-side migration. This ensures that the data on your original automation environment remains untouched during the migration process.

The migration process involves the following steps:

. Verify upgrade configurations.
. Backup original instance.
. Deploy new instance for a side-by-side upgrade.
. Recreate instance groups in the new instance using ansible controller.
. Restore original backup to new instance.
. Set up execution nodes and upgrade instance to {PlatformName} {PlatformVers}.
. Configure upgraded controller instance.

include::platform/con-aap-upgrade-prereq.adoc[leveloffset=+1]

include::platform/con-backup-aap.adoc[leveloffset=+1]

This backup will be necessary later to migrate content from your old instance to the new one.

include::platform/proc-new-aap-instance-upgrade.adoc[leveloffset=+1]

include::platform/proc-restore-aap-backup.adoc[leveloffset=+1]

You will upgrade this new instance to {PlatformNameShort} {PlatformVers} so that you keep all your previous data without overwriting your original instance.

include::platform/proc-upgrade-installer.adoc[leveloffset=+1]

include::platform/proc-configure-upgraded-aap.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

