ifdef::context[:parent-context: {context}]

[id="using-rhsso-operator-with-automation-hub"]

:context: using-a-rhsso-operator

= Using a Red Hat Single Sign On Operator with {HubName}

The _{PlatformName}_ (AAP) _{PrivateHubNameStart}_ (PAH) uses Red Hat Single Sign-On (RH-SSO) for authentication.

The _Red Hat Single Sign-On_ (RH-SSO) Operator creates and manages resources.
Use this Operator to create custom resources to automate Red Hat Single Sign-On administration in Openshift.

When installing AAP on _Virtual Machines_ (VMs) the installer can automatically install and configure RH-SSO for use with PAH.
When installing AAP on _{OCP}_ (OCP) you must install Single Sign-On seperately.
This chapter describes the process to configure RH-SSO and integrate it with PAH when AAP is installed on {OCPShort}.

For more information on running operators on {OCPShort}, see Operators - Working with Operators in {OCPShort} in the {OCPShort} product documentation.

.Prerequisites
* You have access to {OCP} using an account with operator installation permissions.
* You have installed the catalog containing the {PlatformName} operators.
* You have installed the Red Hat Single Sign-On Operator.
To install the Single Sign-On Operator, follow the procedure in link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.6/html/server_installation_and_configuration_guide/operator#doc-wrapper[ Installing Red Hat Single Sign-On using a custom resource] in the Red Hat Single Sign-On documentation.

include::platform/proc-create-keycloak-instance.adoc[leveloffset=2]
include::platform/proc-create-keycloak-realm.adoc[leveloffset=2]
include::platform/proc-create-keycloak-client.adoc[leveloffset=2]
include::platform/proc-create-a-user.adoc[leveloffset=2]
include::platform/proc-installing-the-ansible-platform-operator.adoc[leveloffset=2]
include::platform/proc-creating-a-secret.adoc[leveloffset=2]
include::platform/proc-installing-hub-using-operator.adoc[leveloffset=2]
include::platform/proc-determine-hub-route.adoc[leveloffset=2]
include::platform/proc-update-rhsso-client.adoc[leveloffset=2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
