

ifdef::context[:parent-context: {context}]



[id="upgrading-platform"]
= Upgrading your {PlatformName}


:context: upgrading-platform



[role="_abstract"]

To upgrade your {PlatformName} to the later version, download the desired version of the {PlatformNameShort} installer. Configure it with the same parameters you have used in previous installations, configure any new parameters, then run the installer.

In same cases, you may need to configure other settings if you plan on upgrading other components of your {PlatformNameShort}, such as {ControllerName}. The following sections describes these steps in further detail.

include::platform/con-upgrade-planning.adoc[leveloffset=+1]

Once you have necessary changes during upgrade planning, proceed by downloading the desired version of the {PlatformNameShort} installer.

include::platform/proc-choosing-obtaining-installer.adoc[leveloffset=+1]
include::platform/proc-editing-inventory-file-for-updates.adoc[leveloffset=+1]
include::platform/proc-running-setup-script-for-updates.adoc[leveloffset=+1]


////
[role="_additional-resources"]
== Additional resources (or Next steps)
Optional. Delete if not used.
* A bulleted list of links to other material closely related to the contents of the assembly, including xref links to other assemblies in your collection.
* For more details on writing assemblies, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
