
ifdef::context[:parent-context: {context}]



[id="assembly-platform-install-scenario"]
= Installing {PlatformName}


:context: platform-install-scenario

[role="_abstract"]
{PlatformName} installation involves deploying {ControllerName} and {HubName}.

[IMPORTANT]
====
The {PlatformNameShort} installer allows you to deploy *only one* {HubName} per inventory. You can use the {PlatformNameShort} installer for a standalone instance of {HubName} and run the installer any number of times with any number of different inventories to deploy multiple {HubName} nodes.
====

[IMPORTANT]
====
Installer does not require a user to be logged as root to run `./setup.sh`. The user will need to properly configure the environment variable `ANSIBLE_BECOME_METHOD` for the preferred method of privilege escalation to root. The default method is `sudo`.
====

This installation option includes two supported scenarios:

include::assembly-platform-non-inst-database.adoc[leveloffset=+1]
include::assembly-platform-ext-database-install.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
