
ifdef::context[:parent-context: {context}]

[id="assembly-platform-non-inst-database"]
= Installing {PlatformName} with a database on the {ControllerName} node or non-installer managed database

:context: platform-non-inst-database

[role="_abstract"]
You can use these instructions to install {PlatformName} (both {ControllerName} and {HubName}) with a database on the {ControllerName} node, or a non-installer managed database.


== Prerequisites

* You chose and obtained a platform installer from the https://access.redhat.com/downloads/content/480/ver=2.1/rhel---8/2.1/x86_64/product-software[Red Hat Ansible Automation Platform Product Software].
* You are installing on a machine that meets base system requirements.
* You have created a Red Hat Registry Service Account, following the instructions in the https://access.redhat.com/RegistryAuthentication#creating-registry-service-accounts-6[Creating Registry Service Accounts guide].
* A container registry service is required to install the {PlatformNameShort}. Access to a container registry enables you to load automation execution environments onto the {PlatformNameShort}, giving you a consistent and containerized environment for executing Ansible playbooks and roles. 
By default, the {PlatformNameShort} uses `registry.redhat.io`, which requires a Red Hat registry service account. 
See the https://access.redhat.com/RegistryAuthentication#creating-registry-service-accounts-6[Creating Registry Service Accounts] guide to create a registry service account.

[IMPORTANT]
====
* Root access to remote machines is required. With Ansible, this can be achieved in different ways:
* `ansible_user=root ansible_ssh_pass=”your_password_here”` inventory host or group variables
* `ansible_user=root ansible_ssh_private_key_file=”path_to_your_keyfile.pem”` inventory host or group variables
* `ANSIBLE_BECOME_METHOD=’sudo’ ANSIBLE_BECOME=True ./setup.sh`

For more information on `become` plugins, see link:https://docs.ansible.com/ansible/latest/user_guide/become.html#understanding-privilege-escalation[Understanding privilege escalation].

For more information on inventory file variables, see [About the installer inventory file]
====

//include::platform/ref-platform-install-settings.adoc[leveloffset=3]
include::platform/proc-editing-inventory-file.adoc[leveloffset=3]
include::platform/ref-platform-non-inst-database-inventory.adoc[leveloffset=3]
include::platform/ref-setup-script-args.adoc[leveloffset=3]
include::platform/proc-running-setup-script.adoc[leveloffset=3]
include::platform/proc-verify-controller-installation.adoc[leveloffset=3]
include::platform/ref-controller-configs.adoc[leveloffset=4]
include::platform/proc-verify-hub-installation.adoc[leveloffset=3]
include::platform/ref-hub-configs.adoc[leveloffset=4]

include::assembly-platform-whats-next.adoc[leveloffset=3]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
