[id="assembly-controller-secret-management"]

= Secret Management System

Users and system administrators upload machine and cloud credentials so that automation can access machines and external services on their behalf. 
By default, sensitive credential values such as SSH passwords, SSH private keys, and API tokens for cloud services are stored in the database after being encrypted. 

With external credentials backed by credential plugins, you can map credential fields (such as a password or an SSH Private key) to values stored in a `secret management system` instead of providing them to {ControllerName} directly. 

{ControllerNameStart} provides a secret management system that include integrations for:

* Centrify Vault Credential Provider Lookup
* _CyberArk Central Credential Provider_ Lookup (CCP)
* CyberArk Conjur Secrets Manager Lookup
* HashiCorp Vault _Key-Value_ Store (KV)
* HashiCorp Vault SSH Secrets Engine
* {Azure} _Key Management System_ (KMS)
* Thycotic DevOps Secrets Vault
* Thycotic Secret Server

These external secret values are fetched before running a playbook that needs them. 
For more information on specifying these credentials in the User Interface, see xref:controller-credentials[Credentials].

include::platform/proc-controller-configure-secret-lookups.adoc[leveloffset=+1]
include::platform/ref-controller-metadata-credential-input.adoc[leveloffset=+2]
include::platform/ref-centrify-vault-lookup.adoc[leveloffset=+2]
include::platform/ref-cyberark-ccp-lookup.adoc[leveloffset=+2]
include::platform/ref-cyberark-conjur-lookup.adoc[leveloffset=+2]
include::platform/ref-hashicorp-vault-lookup.adoc[leveloffset=+2]
include::platform/ref-hashicorp-signed-ssh.adoc[leveloffset=+2]
include::platform/ref-azure-key-vault-lookup.adoc[leveloffset=+2]
include::platform/ref-thycotic-devops-vault.adoc[leveloffset=+2]
include::platform/ref-thycotic-secret-server.adoc[leveloffset=+2]



