

ifdef::context[:parent-context: {context}]



[id="upgrading-to-ees"]
= Migrating to {ExecEnvName}


:context: upgrading-to-ees



// [role="_abstract"]

include::platform/con-why-ee.adoc[leveloffset=+1]

== About migrating legacy venvs to {ExecEnvName}

When upgrading from older versions of {ControllerName} to version 4.0 or later, the controller can detect previous versions of virtual environments associated with Organizations, Inventory and Job Templates and informs you to migrate to the new {ExecEnvName} model. A new installation of {ControllerName} creates two virtualenvs during the installation; one runs the controller and the other runs Ansible. Like legacy virtual environments, {ExecEnvName} allow the controller to run in a stable environment, while allowing you to add or update modules to your {ExecEnvName} as necessary to run your playbooks.

You can duplicate your setup in an {ExecEnvNameSing} from a previous custom virtual environment by migrating them to the new {ExecEnvNameSing}. Use the `awx-manage` commands in this section to:

* list of all the current custom virtual environments and their paths (`list_custom_venvs`)
* view the resources that rely a particular custom virtual environment (`custom_venv_associations`)
* export a particular custom virtual environment to a format that can be used to migrate to an {ExecEnvNameSing} (`export_custom_venv`)

The below workflow describes how to migrate from legacy venvs to {ExecEnvName} using the `awx-manage` command.

include::dev-guide/assembly-virt-env-to-ee.adoc[leveloffset=+1]

// [role="_additional-resources"]
// Remove comments once 2.2 version of the docs are published.
//== Additional resources

//* See the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/ansible_navigator_creator_guide/index[Red Hat Ansible Automation Platform Creator Guide] for more information on migrating to {ExecEnvName}.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
