
ifdef::context[:parent-context: {context}]



[id="operator-install-planning"]
= Planning your {PlatformName} operator installation on {OCP}


:context: operator-install-planning

[role="_abstract"]
{PlatformName} is supported on both Red Hat Enterprise Linux 8 and Red Hat Openshift.

OpenShift operators help install and automate day-2 operations of complex, distributed software on {OCP}. The {OperatorPlatform} enables you to deploy and manage {PlatformNameShort} components on {OCP}.

You can use this section to help plan {PlatformName} installation on your {OCP} environment. Before installing, review the individual scenarios to determine which meets your requirements.

== About {OperatorPlatform}

The {OperatorPlatform} provides cloud-native, push-button deployment of new {PlatformNameShort} instances in your OpenShift environment. 
The {OperatorPlatform} includes resource types to deploy and manage instances of {ControllerNameStart} and Private Automation hub. It also includes {ControllerName} job resources for defining and launching jobs inside your {ControllerName} deployments. 
You can install the {OperatorPlatform} from the Red Hat Operators catalog in OperatorHub.

Deploying {PlatformNameShort} instances with a Kubernetes native operator offers advantages over launching instances from a playbook deployed on {OCP}. The {OperatorPlatform} supports upgrades and provides full lifecycle support for your {PlatformName} deployments. 

== Supported installation scenarios for {OCP}

You can install the {PlatformName} operator following one of the below workflows:

* {ControllerNameStart} and customer resources first, then {HubName} and customer resources;
* {HubNameStart} and customer resources first, then {ControllerName} and customer resources;
* {ControllerNameStart} and customer resources;
* {HubNameStart} and custom resources.

== Custom resources

You can define custom resources for each primary installation workflows.
[role="_additional-resources"]
== Additional resources

* See link:https://docs.openshift.com/container-platform/4.7/operators/understanding/olm-understanding-operatorhub.html#olm-understanding-operatorhub[Understanding OperatorHub] to learning more OpenShift Container Platform OperatorHub.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
