ifdef::context[:parent-context: {context}]

[id="assembly-migrate-isolated-execution-nodes]
= Upgrading isolated nodes to execution nodes

[role="_abstract"]
When upgrading from version 1.x to the latest version of the {PlatformName}, platform administrators will need to migrate the data from their legacy isolated nodes into execution nodes, which will be necessary to deploy automation mesh.

To do so, this guide outlines the steps to perform a side-by-side migration. This migration involves duplicating your original {PlatformName} instance with all its data and nodes, then performing an upgrade on the duplicate instance. This ensures that the data on your original automation environment will remain untouched while performing your upgrade and migration process.

Below is a summary of steps needed to complete the migration process:

. Backup original instance
. Deploy new instance for a side-by-side upgrade
.. Recreate instance groups in the new instance using Ansible Tower
. Restore original backup to new instance
. Set up execution nodes and upgrade instance to {PlatformName} {PlatformVers}
. Configure upgraded Controller instance

include::platform/con-backup-aap.adoc[leveloffset=+1]

This backup will be necessary later to migrate content from your old instance to the new one.

include::platform/proc-new-aap-instance-upgrade.adoc[leveloffset=+1]

include::platform/proc-restore-aap-backup.adoc[leveloffset=+1]

You will upgrade this new instance to {PlatformNameShort} {PlatformVers} so that you keep all your previous data without overwriting your original instance.

include::platform/proc-upgrade-installer.adoc[leveloffset=+1]

include::platform/proc-configure-upgraded-controller.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
