////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]


[id="installing-controller-operator"]
= Installing and configuring {ControllerName} on {OCP} web console


:context: installing-contr-operator


[role="_abstract"]
You can use these instructions to install the {ControllerName} operator on {OCP}, specify custom resources, and deploy {PlatformNameShort} with an external database.

{ControllerNameStart} configuration can be done through the {ControllerName} extra_settings or directly in the user interface after deployment. However, it is important to note that configurations made in extra_settings take precedence over settings made in the user interface.

[NOTE]
====
When an instance of {ControllerName} is removed, the associated PVCs are not automatically deleted. This can cause issues during migration if the new deployment has the same name as the previous one. Therefore, it is recommended that you manually remove old PVCs before deploying a new {ControllerName} instance in the same namespace. See xref:proc-find-delete-PVCs_{context}[Finding and deleting PVCs] for more information.
====


// mirrors AWX operator flow

== Prerequisites

* You have installed the {PlatformName} catalog in Operator Hub.
* For Controller, a default StorageClass must be configured on the cluster for the operator to dynamically create needed PVCs. This is not necessary if an external PostgreSQL database is configured.
* For Hub a StorageClass that supports ReadWriteMany must be available on the cluster to dynamically created the PVC needed for the content, redis and api pods. If it is not the default StorageClass on the cluster, you can specify it when creating your AutomationHub object.

== Installing the {ControllerName} operator
Use this procedure to install the {ControllerName} operator.

.Procedure

. Navigate to menu:Operators[Installed Operators], then click on the *Ansible Automation Platform* operator.
. Locate the *Automation controller* tab, then click btn:[Create instance].

You can proceed with configuring the instance using either the Form View or YAML view.


include::platform/proc-creating-controller-form-view.adoc[leveloffset=+2]
include::platform/proc-configuring-controller-image-pull-policy.adoc[leveloffset=+2]
include::platform/proc-configuring-controller-ldap-security.adoc[leveloffset=+2]
include::platform/proc-configuring-controller-route-options.adoc[leveloffset=+2]
include::platform/proc-controller-ingress-options.adoc[leveloffset=+2]
include::platform/proc-operator-external-db-controller.adoc[leveloffset=+1]

include::platform/proc-find-delete-PVCs.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources

* For more information on running operators on OpenShift Container Platform, navigate to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/[OpenShift Container Platform product documentation] and click the _Operators - Working with Operators in OpenShift Container Platform_ guide.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
