
ifdef::context[:parent-context: {context}]



[id="planning-installation"]
= Planning your {PlatformName} installation


:context: planning

[role="_abstract"]
You can use this section to help plan your {PlatformName} installation. Before installation, review information on the setup installer, system requirements, and supported installation scenarios.

include::platform/ref-system-requirements.adoc[leveloffset=+1]

include::platform/proc-choosing-obtaining-installer.adoc[leveloffset=+1]
include::platform/proc-attaching-subscriptions.adoc[leveloffset=+1]

== Supported installation scenarios

Red Hat supports the following installations scenarios for {PlatformName}

include::platform/con-SM-standalone-contr-non-inst-database.adoc[leveloffset=+2]

See "Installing {ControllerName} with a database on the same node" in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-SM-standalone-contr-ext-database.adoc[leveloffset=+2]

See "Installing {ControllerName} with an external managed database" in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-SM-standalone-hub-non-inst-database.adoc[leveloffset=+2]

See "Installing {HubName} with a database on the same node" in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-SM-standalone-hub-ext-database.adoc[leveloffset=+2]

See "Installing {HubName} with an external database" in _Installing {PlatformName} components on a single machine_ to get started.

include::platform/con-platform-non-inst-database.adoc[leveloffset=+2]

See "Installing {PlatformName} with a database on the {ControllerName} node or non-installer managed database" in _Installing {PlatformName}_ to get started.

include::platform/con-platform-ext-database.adoc[leveloffset=+2]

See "Installing {PlatformName} with an external managed database" in _Installing {PlatformName}_ to get started.

include::platform/con-cluster-platform-ext-database.adoc[leveloffset=+2]

See "Installing a multi-node {PlatformName} with an external managed database" in _Multi-machine cluster intallation_ to get started.



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
