ifdef::context[:parent-context: {context}]

[id="assembly-planning-mesh"]
ifdef::mesh-VM[]
= Planning for {AutomationMesh} in your VM-based {PlatformName} environment
endif::mesh-VM[]
ifdef::operator-mesh[]
= Planning for {AutomationMesh} in your operator-based {PlatformName} environment
endif::operator-mesh[]
:context: planning-mesh


[role="_abstract"]
ifdef::mesh-VM[]
The following topics contain information to help plan an {AutomationMesh} deployment in your VM-based {PlatformNameShort} environment. 
The subsequent sections explain the concepts that comprise {AutomationMesh} in addition to providing examples on how you can design {AutomationMesh} topologies. 
Simple to complex topology examples are included to illustrate the various ways you can deploy {AutomationMesh}.
endif::mesh-VM[]
ifdef::operator-mesh[]
The following topics contain information to help plan an {AutomationMesh} deployment in your operator-based {PlatformName} environment. 
The document covers the setting up of {AutomationMesh} on operator-based deployments, such as {OCPShort} and {PlatformNameShort} on {Azure} managed application. 
endif::operator-mesh[]

include::platform/con-about-automation-mesh.adoc[leveloffset=+1]

include::platform/con-automation-mesh-node-types.adoc[leveloffset=+1]

ifdef::mesh-VM[]
include::platform/proc-defining-node-types.adoc[leveloffset=+2]
endif::mesh-VM[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
