////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]


[id="installing-hub-operator-external"]
= Installing {HubName} on {OCP} with an external database


:context: installing-hub-operator-external


[role="_abstract"]
You can use these instructions to install the {HubName} operator on {OCP} with an external PostgreSQL 12 database and route, as well as specify customer resources.

// mirrors AWX operator flow

== Prerequisites

* You have installed the catalog containing the {PlatformName} operators

== Installing the {HubName} operator

. Log in to {OCP}.
. Navigate to *Operators* -> *Operator Hub*.
. Locate the {PlatformName} catalog and click on it.
. Click *Install*
+
.Instantiating an instance of {HubName}
[NOTE]
====
{OCP} clusters running on AWS do not support ReadWriteMany without adding NFS or other storage.
====
. Navigate to *Operators* -> *Installed Operators*.
. Locate the {HubName} operator and click *Create AutomationHub*.

.Optional - Configure your {HubName} operator route options
. Click *Advanced configuration*.
. Under “Ingress type”, click the dropdown menu and select *Route*.
. Under “Route DNS host”, enter a common host name that the route answers to.
. Under “Route TLS termination mechanism”, click the dropdown menu and select *Edge* or *Passthrough*.
. Under “Route TLS credential secret”, click the dropdown menu and select a secret from the list.


.Optional - Configure the Ingress type for your {HubName} operator
. Click *Advanced Configuration*.
. Under “Ingress type”, click the dropdown menu and select *Ingress*.
. Under “Ingress annotations”, enter any annotations to add to the ingress.
. Under “Ingress TLS secret”, click the dropdown menu and select a secret from the list.

Once you have configured your {HubName} operator, click *Create* at the bottom of the form view. {OCP} will now create the pods. This may take a few minutes.

* View progress by navigating to *Workloads* -> *Pods* and locating the newly created instance.

== Accessing the {HubName} user interface

You can access the {HubName} interface once all pods have successfully launched.

. Navigate to *Networking* -> *Routes*.
. Under *Location*, click on the URL for your {HubName} instance.

The {HubName} user interface will launch, You can sign in with the admin credentials specified during the operator configuration process.





[role="_additional-resources"]
== Additional resources

* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/operators/index[Working with Operators in OpenShift Container Platform] for more information on running operators on OpenShift Container Platform.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
