[id="con-aap-azure-architecture"]

= Application Architecture

{AAPonAzureName} is installed as a managed application.
Red Hat manages both the underlying Azure resources and the software running on it while that infrastructure runs in your Azure tenant.

The managed application resource group is completely separate from other resource groups in your tenant.
Red Hat only has access to the managed application resource group, with no visibility into other tenant resources.

For information about how this works and how resources and access are isolated from the rest of your Azure resources, refer to link:https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/overview[Azure managed applications overview] in the Microsoft _Azure managed applications_ guide.

{AAPonAzureNameShort} uses two resource groups:

* A resource group in your tenant. This resource group includes a single resource referring to the {AAPonAzureNameShort} managed app deployment.
Red Hat has access to this managed app to perform support, maintenance, and upgrades.
* A multi-tenant managed resource group that contains all the infrastructure needed to operate {AAPonAzureNameShort}. This multi-tenant resource group is shared between the Red Hat tenant and your tenant. Red Hat has full administrative control and you have read-only access to the resource group.

When you install {AAPonAzureNameShort}, you choose whether the deployment is public or private.
This affects how users can access the {PlatformNameShort} user interfaces.

Regardless of whether you choose a public or private deployment, you must configure network peering for outbound communication from {PlatformNameShort} to the networks of the resources that you want to automate against.
You can configure network peering from {AAPonAzureNameShort} to your private Azure VNets and to on-premises or multi-cloud networks where transit routing with Azure exists.

