[id="con-aap-azure-infrastructure-usage_{context}"]

= {AAPonAzureNameShort} infrastructure usage

When you install {AAPonAzureNameShort}, the following infrastructure is deployed into your Azure subscription:

Azure Kubernetes service (AKS):: The Kubernetes cluster used to deploy {PlatformNameShort} applications and services.
+
**Service Shape:**
+
* Compute nodes: Standard_D4s_v3 (4 vCPUs x 16 GiB)
* Autoscaling minimum nodes: 2
* Autoscaling maximum nodes: 20
Managed identity:: An Azure service that enables {PlatformNameShort} components to communicate with other Azure services such as database, DNS, storage, and other services.
Key vault:: A secure key vault used to store secrets that are unique to the {PlatformNameShort} deployment.
Log Analytics Workspace:: An Azure service that enables Red Hat site reliability engineers to inspect the operations of {AAPonAzureNameShort}.
Private DNS Zone:: Manages local DNS requests for the services used by {AAPonAzureNameShort}.
Azure Database for PostgreSQL:: An Azure database service used for {PlatformNameShort}’s PostgreSQL database.
+
**Service Shape:** 1 TB
Storage account:: The Azure service is used for file and block storage for local storage of projects, containers, etc.
+
**Service Shape:** StorageV2 - Standard_LRS
Virtual network:: The Azure service is used to manage all internal networking and dependent services such as the Azure Application Gateway.
+
**Service Shape:** Application Gateway: WAF_v2

Exact infrastructure usage depends on the length of time that the managed application is deployed in your tenancy, and the automation requirements that might cause the Kubernetes cluster to autoscale to meet the demands of your workload.

Microsoft provides a link:https://azure.microsoft.com/en-us/pricing/calculator/[Pricing calculator] to estimate your costs for Azure products and services.
Red Hat has configured an example scenario in the pricing calculator: use the link:https://azure.com/e/d12a08795a4942c1801c610810791764[Red Hat Ansible Automation Platform on Azure Infrastructure Estimate] to tune Kubernetes expected auto scaling variables based on your organization’s workloads.

