////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="con-azure-predef-about-migrate"]

= About the migrating resources between regions template

// [role="_abstract"]

About the migrating resources between regions template
The “migrating resources between regions” template executes the vmss_migrate.yml playbook from the cloud.azure_roles git repository. 
The playbook removes a deployed application from one region and moves the resources to another region. 
For multi-regional applications, it is useful to be able to migrate the application deployment to an Azure region closer to the application's users.
Prerequisites
Describe the information needed before launching the template
Execution sequence
The list below shows the sequence in which the resources are generated in the destination region and deleted in the source region. Links are provided to the roles, tasks and modules that complete the job.
The vmss_migrate.yml playbook invokes the scale_virtual_machine role, specifying the create operation, to create the application infrastructure in another Azure region. Variables representing the destination region and the source resource group properties are passed to the role.
This role executes the create.yml task, which implements the following:
Creates a resource group in the destination Azure region using the resource_group role:
Creates a network security group by invoking the azure.azcollection azure_rm_securitygroup module. 
Creates an Azure networking stack using the networking_stack role in cloud.azure_roles.
Deploys a load balancer with a public IP address by invoking the azure.azcollection azure_rm_loadbalancer module.
Creates a bastion host with a public IP address, and adds it to the inventory. The create_bastion.yml task invokes the azure_rm_publicipaddress, azure_rm_virtualmachine, and azure_rm_networkinterface modules from the azure.azcollection.
Creates a virtual machine scale set by invoking the azure_rm_virtualmachinescaleset module from the azure.azcollection.
Adds the bastion host to the inventory by invoking the ansible.builtin.add_host module.
Installs Python3 and Ansible on the bastion host in the destination region.
Copies the deploy_app.yml playbook to play.yml on the bastion host.
Deploys the app from the bastion host by executing a shell command on the bastion host to run the play.yml playbook.
Invokes the scale_virtual_machine role, specifying the delete operation, to delete the resource group for the application from the source Azure region.
Deletes the bastion host from the source region by setting the azure_rm_virtualmachine module to the absent state. 
Deletes the virtual machine scale set from the source region by setting the azure_rm_virtualmachinescaleset module to the absent state. 
Deletes the virtual network set from the source region by setting the azure_rm_virtualnetwork module to the absent state. 
Deletes the subnet from the source region by setting the azure_rm_subnet module to the absent state. 
Deletes the load balancer from the source region by setting the azure_rm_loadbalancer module to the absent state. 
Deletes the public IP address for the load balancer in the source region by setting the azure_rm_publicipaddress module to the absent state. 
Deletes the networking security group from the source region by setting the azure_rm_securitygroup module to the absent state. 
Prints a message displaying the URL for the application in the destination region.





