[id="con-aap-azure-infrastructure-usage"]

= {AAPonAzureNameShort} infrastructure usage

When you install {AAPonAzureNameShort}, the following infrastructure is deployed into your Azure subscription:

Azure Kubernetes service (AKS):: Kubernetes cluster used to deploy Ansible Automation Platform applications and services.
+
**Service Shape:**
+
* Compute nodes: Standard_D4s_v3 ((4 vCPUs x 16 GiB)
* Autoscaling Min Nodes: 1
* Autoscaling Max Nodes: 20
Managed identity:: The Azure service used to allow for Ansible components to communicate with other Azure services (such as database, DNS, storage, and other services).
Key vault:: A secure key vault used to store secrets that are unique to the Ansible Automation Platform deployment.
Log Analytics Workspace:: The Azure service that allows for Red Hat SREs to inspect the operations of Ansible Automation Platform on Azure.
Private DNS Zone:: Manages local DNS requests for the services used by the Ansible Automation Platform on Azure.
Azure Database for PostgreSQL:: The Azure database service used for Ansible Automation Platform’s PostgreSQL database.
+
**Service Shape:** 1 TB
Storage account:: The Azure service is used for file and block storage for local storage of projects, containers, etc.
+
**Service Shape:** StorageV2 - Standard_LRS
Virtual network:: The Azure service is used to manage all internal networking and dependent services such as the Azure Application Gateway.
+
**Service Shape:** 1 TB

Exact infrastructure usage depends on the length of time that the managed application is deployed in your tenancy and the automation requirements that may cause the Kubernetes cluster to autoscale to meet the demands of your workload.

You can use the link:https://azure.com/e/d12a08795a4942c1801c610810791764
[Azure cost estimator] to tune kubernetes expected auto scaling variables based on your organization’s workloads.

