[id="proc-peer-vwan-hub-to-aap"]

= Peering VWAN Hub to the {AAPonAzureNameShort} Network

.Prerequisites

* A pre-configured Azure VWAN that is already tested and working.
* One (or more) of the following connectivity options to the VWAN
** A DMZ network that contains Azure virtual machines that your employees will use to access Ansible Automation Platform on Azure.
** A DMZ network that contains an Azure virtual machine that can be used with SSH tunneling to access Ansible Automation Platform on Azure.
** A VPN or Direct Connect service to your local network that is operational so that PCs from your local network can route traffic to Ansible Automation Platform on Azure.

Peering the Ansible Automation Platform on Azure VNET to your VWAN is the same as peering to any other VNET or network that you can connect to a VWAN.
In the Azure console, open the VWAN that you plan to peer with your instance of Ansible Automation Platform.
Click the “Virtual Network Connections” link on the left menu.
There should be at least one “hub” listed (since you meet the prerequisites listed at the start of this section).
Click the “Add Connection” button.
Fill out the form with the following information:
Connection Name: AnsibleAutomationPlatformConnection (or a name of your choosing).
Hubs: Select one or more VWAN hub networks that the managed application VNET will peer with.
Subscription: The subscription that contains the managed application.
Resource group: The managed resource group of the managed application.  It will typically be prefixed with “mrg-”.
Virtual network: The VNET of the managed application.  There should only be one to select from in the managed resource group.
Propagate to none: No
Associate Route Table: Select the default route table or the appropriate route table that your organization has configured for VWAN. 
Propagate to Route Tables: Select the default route table(s) or the appropriate route table that your organization has configured for VWAN. 
Propagate to labels: This can be selected based on your organization’s use of labels.  It may be left blank if unused.
Static routes: These should be left blank.
Click “Create” at the bottom of the form.
After peering completes then traffic should successfully route traffic to-and-from Ansible Automation Platform on Azure though your VWAN hub network.


