////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="proc-azure-find-cluster-cidr"]

= Finding the CIDR Block of the managed application Kubernetes cluster

. Open the **Virtual Networks** page in the Azure portal to list your VNETs.
+
The VNET name for the AKS cluster of your managed application deployment follows the format: `aks-vnet-<digits>`.
. Select a VNET to view its settings in the **Overview** page.
+
The CIDR block of the cluster is displayed in the **Address Space**.

If there are multiple VNET names with the `aks-vnet-<digits>` format, open the **Overview** page for each VNET until you find the network within your {AAPonAzureNameShort} managed application resource group.

For further information, refer to link:https://docs.microsoft.com/en-us/azure/virtual-network/manage-virtual-network#view-virtual-networks-and-settings[View virtual networks and settings] in the Microsoft Azure _Virtual network_ guide.

