////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="proc-azure-hub-spoke-peering"]

= Hub-and-spoke peering process overview

.Prerequisites

* You have deployed Ansible Automation Platform on Microsoft Azure.
* You have configured and tested an Azure VNet hub-and-spoke implementation in your Azure tenant. This prerequisite requires many Azure resources to be configured, including a Virtual Network Gateway.
* You have configured transit routing between your spoke networks, including your VPNs. Refer to link:https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-peering-gateway-transit[Configure VPN gateway transit for virtual network peering] in the Microsoft Azure documentation for instructions.
* You have identified the following:
** The CIDR block(s) of your existing VNets (including VPNs & direct connects) that will need access to Ansible Automation Platform on Azure UIs.
** The CIDR block(s) of your existing VNets (including VPNs & direct connects) that will contain hosts or endpoints for Ansible automation.
** The CIDR blocks of the Ansible Automation Platform VNet from the managed resource group of the application. Refer to xref:proc-azure-find-cluster-cidr[Finding the CIDR Block of the managed resource group] for instructions.

Before peering any networks, ensure that there is no network address space overlap between your private VNets and your Ansible Automation Platform on Azure network.

.Procedure

. Find the CIDR Block for the {AAPonAzureNameShort} managed application Kubernetes cluster. See xref:proc-azure-find-cluster-cidr[Finding the CIDR Block of the managed application Kubernetes cluster].
. Configure Network Peering with the {PlatformNameShort} Subnet. See xref:proc-azure-nw-peering-aap-subnet[Configuring Network Peering with the {PlatformNameShort} Subnet].
. Update the route tables:
.. Configure route tables from your existing networks to send traffic to the managed application CIDR. You must add routes to the routing tables of every network requesting {PlatformNameShort} user interfaces and of every network that will have automation performed against its resources.
See xref:routing-to-aap[Routing to {AAPonAzureNameShort}].
.. Configure routing to your VNets for each spoke network that you would like PlatformNameShortAnsible Automation Platform to communicate with, for automation or for accessing the user interfaces.
See xref:routing-to-private-nw[Routing to your VNets].

