////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="proc-azure-nw-private-deploy"]

= Private deployments

If you selected private access when deploying {AAPonAzureNameShort},
then the DNS record issued to the {AAPonAzureName} application points to a private Class C network address: 192.168.0.68.
You must configure access to this address after you have created network peering.
// This address is not accessible from external sources

The configuration and access method that you choose to connect to {AAPonAzureNameShort} will depend on how your organization manages Azure infrastructure.
Your Azure administrators must determine the right model for your organization and configure the setup for you.

The following are the most common options:

* xref:proc-azure-nw-private-deploy-az-hosted-vm[Azure hosted virtual machine]
* xref:proc-azure-nw-private-deploy-vpn[VPN]
* xref:proc-azure-nw-private-deploy-ssh-tunnel[SSH tunnel]

