////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="proc-azure-nw-direct-peering"]

= Configuring Network Peering

You can configure network peering between your Azure network and your VNET in the *Virtual Networks* page of the Azure Portal. 

Within the Azure console, the Azure virtual network is known as _this virtual network_, and the VNET that you want to peer with is known as _remote virtual network_.

In the *Virtual Networks* page in the Azure portal, use the following settings to configure the Azure network and the VNET that you want to peer with the {AAPonAzureNameShort} app:

* Under *This virtual network*, select settings for the {AAPonAzureNameShort} virtual network:
** *Peering link name*: `hub_to_aap` or another memorable name
** *Traffic* to remote virtual network: _Allow_
** *Traffic* forwarded from remote virtual network: _Allow_
** *Virtual network gateway or Route Server*: _Use this network’s gateway or Route server_

* Under *Remote virtual network*, select settings for the virtual network that you want to peer with Azure:
** *Peering link name*: `aap_to_hub` or another memorable name
** *Traffic to remote virtual network*: _Allow_
** *Traffic forwarded from remote virtual network*: _Allow_
** *Virtual network gateway or Route Server*: _Use the remote virtual network’s gateway or Route server_

For more detailed instructions for configuring peering, refer to link:https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-peering#create-a-peering[Create a peering] in the Microsoft Azure _Virtual network_ guide.

For further information on direct peering, refer to link:https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview[Virtual network peering] in the Microsoft Azure _Virtual network_ guide.

