[id="proc-azure-resource-quotas_{context}"]

= Azure resource quotas and infrastructure limits

Microsoft imposes resource limits within each Azure region. The CPU limit is the most likely to impact {AAPonAzureName}.

Before you install {AAPonAzureNameShort}, ensure that you have capacity to deploy the managed application into your desired region.
Refer to xref:con-aap-azure-infrastructure-usage_aap-azure-intro[Azure infrastructure usage] for infrastructure requirements.

== Regional vCPU limits

The Azure resources used during the deployment of the managed application temporarily exceed the resource requirements in xref:con-aap-azure-infrastructure-usage_aap-azure-intro[Azure infrastructure usage].
The `Total Regional vCPUs` quota is temporarily consumed when deploying the managed application.

Every Azure region has a separate `Total Regional vCPUs` quota.
To prevent installation failure, ensure that you have at least 80 DS2_V3 vCPUs available in the Azure region where you want to deploy the managed application.

The following steps describe how to view the resource quotas for your subscription the Azure console:

. In the Azure console, search for *Quotas* and open the *My Quotas* page.
. Select the region where you wish to deploy the managed application to view your allocation and usage metrics for that region.
Ensure that you have selected a single region. Viewing all regions at once will not show the limitations of a single Azure region.

== Regional StandardCore limits

The `StandardCore` limit is a compute metric for the resources that are temporarily consumed when deploying the managed application.

It is possible that the {AAPonAzureNameShort} can deploy without hitting the `StandardCore` limit.
When a deployment fails because the consumed resources hit the `StandardCore` limit, the error message includes `container group quota 'StandardCores' exceeded`:

----
code: DeploymentFailed
message:
  At least one resource deployment operation failed. Please list deployment operations for details.
  Please see https://aka.ms/DeployOperations for usage details.
details:
  - code: DeploymentScriptContainerGroupInvalidSettings
    message:
      Resource type 'Microsoft.ContainerInstance/containerGroups'
      container group quota 'StandardCores' exceeded in region 'eastus'.
      Limit: '10', Usage: '10' Requested: '1'.
----

.Requesting StandardCore limit increase

The `StandardCore` metric is not displayed in the *My Quotas* page in the Azure console. To request the value of your regional limit, contact Microsoft directly.

If your deployments fail because the consumed resources reach this limit, you must submit a resource increase request for `StandardCore` to Microsoft.
Only submit a quota increase request if you encounter a deployment failure due to this issue.

Use the following information to respond to questions from Microsoft support:

Will the container groups be run in Linux or Windows?:: Linux	
What will the core and memory be in your Container Group instance?:: Red Hat recommends 20 cores, 16 GB	
When will you create all the Container Group Instances?:: During managed application deployment of {AAPonAzureName}
How frequent will you create/delete the container groups?:: Only during managed application deployment of {AAPonAzureName}

