[id="proc-peer-vwan-hub-to-aap"]

= Peering a VWAN Hub to the {AAPonAzureNameShort} Network

Before you can peer a VWAN with the {AAPonAzureNameShort} VNET, you must have connected a hub network and at least one spoke network to the hub network of the Azure VWAN that you intend to connect {AAPonAzureNameShort} to.

.Prerequisites

* A pre-configured Azure VWAN that is already tested and working.
* One or more of the following connections to the VWAN:
** A DMZ network that contains Azure virtual machines that users will use to access {AAPonAzureNameShort}.
** A DMZ network that contains an Azure virtual machine that can be used with SSH tunneling to access {AAPonAzureNameShort}.
** A VPN or Direct Connect service to your local network that routes traffic from machines on your local network to {AAPonAzureNameShort}.

Peering the {AAPonAzureNameShort} VNET to your VWAN follows the same approach as peering any other VNET or network with a VWAN.

. Navigate to the *Virtual Network Connections* page for the VWAN that you want to peer with your {PlatformNameShort} instance.
. Use the following settings to create a connection between the VWAN hub and your {PlatformNameShort} instance:
** *Connection Name*: _<Ansible_Automation_Platform_connection_name>_
** *Hubs*: Select one or more VWAN hub networks that the managed application VNET will peer with.
** *Subscription*: Select the subscription where {AAPonAzureNameShort} has been deployed.
** *Resource group*: The managed resource group of the managed application. It will typically be prefixed with “mrg-”.
** *Virtual network*: The VNET of the managed application. There is only one VNET in the managed resource group.
** *Propagate to none*: _No_
** *Associate Route Table*: Select the default route table or the appropriate route table that your organization has configured for VWAN. 
** *Propagate to Route Tables*: Select one or more default route tables or the appropriate route table that your organization has configured for VWAN. 
** *Propagate to labels*: Select labels if your organization uses them.
** *Static routes*: Do not complete this field.

When network peering completes, traffic routes to and from {AAPonAzureNameShort} though your VWAN hub network.

For further information on connecting a VNET to a VWAN, refer to link:https://docs.microsoft.com/en-us/azure/virtual-wan/howto-connect-vnet-hub[Connect a virtual network to a Virtual WAN hub - portal] in the Microsoft Azure Virtual WAN documentation.

