[id="proc-azure-update-route-tables_{context}"]

= Updating the route tables

Before you update the route tables, confirm that you satisfy the xref:proc-azure-hub-spoke-peering_aap-azure-hub-spoke-peering[prerequisites] for the hub-and-spoke peering process.

[#routing-to-aap]
.Routing to {AAPonAzureNameShort}

. Navigate to *Route Tables* in the Azure portal.
. As part of your hub-and-spoke configuration, you created one or more route tables to define the routes between the networks. Click on one of these route tables.
. From the route table menu bar, click *Routes* > *Add*.
. Configure routes from your existing networks to send traffic to {PlatformNameShort}. You must configure routes for any network requesting {PlatformNameShort} user interfaces and for any network that will have automation performed against its resources.
For each route that you add, enter the following information:
** *Route name*: Enter a route name for the {PlatformNameShort} managed application network
** *Address Prefix*: The CIDR block of the managed application kubernetes cluster
** *Next Hop Type*: _Virtual network gateway_
. Click *OK* to save the new route to the route list.

Repeat this procedure for all other route tables where you want to route traffic to {PlatformNameShort}.

[#routing-to-private-nw]
.Routing to your VNets

Add a route for each spoke network that you would like {PlatformNameShort} to communicate with, for automation or for accessing the user interfaces.

. Navigate to *Route Tables* in the Azure portal.
. In the list of route tables, select the route table for the {AAPonAzureNameShort} managed application.
+
The name of the {PlatformNameShort} route table uses the following convention:
+
----
aks-agentpool-<numbers>-routetable
----
. From the route table menu bar, click *Routes* > *Add*.
. Configure routing to your VNets for each spoke network that you would like {PlatformNameShort} to communicate with, for both automation or accessing the user interfaces.
. For each route that you add, enter the following information:
** *Route name*: Enter a route name for the spoke network that you want {PlatformNameShort} to route to
** *Address Prefix*: The CIDR block of the spoke network
** *Next Hop Type*: _Virtual network gateway_
. Click *OK* to save the new route to the route list.


After you have configured the routing rules, traffic is routed to and from {PlatformNameShort} on Azure through your hub network.

[#outbound-routing-virtual-appliances]

.Outbound routing through virtual appliances

If your organization uses Azure firewall services or third-party firewall appliances through a Virtual Appliance connection, you must configure outbound connectivity from the managed application, to enable Red Hat to maintain your application and to enable automation against external resources.

The easiest way to implement this is to create a firewall rule that allows all outbound traffic from port 443.

If you choose not to allow all outbound traffic from  port 443, you must configure routes.

* For Red Hat to manage and upgrade {AAPonAzureNameShort} and execute security patching, any machine in the Azure Kubernetes service (AKS) cluster must be allowed to submit a request to pull updates for containers used by {PlatformNameShort}.
Add routes in the {PlatformNameShort} route table for outbound traffic from the full CIDR range of the {AAPonAzureNameShort} managed application to the following domains:

** `registry.redhat.io`
** `quay.io`

* You must also allow traffic from your firewall to any other external domain or IP address that you want {PlatformNameShort} to run automation jobs against.
Otherwise, your firewall will block connectivity between {PlatformNameShort} and destinations for automation.

== Additional resources

For further information about adding routes to a route table in Azure, refer to link:https://docs.microsoft.com/en-us/azure/virtual-network/manage-route-table#create-a-route[Create a route] in the Microsoft Azure _Virtual network_ guide.

