////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="proc-azure-nw-private-deploy-vpn"]

= VPN

If your organization requires that many users connect to Ansible Automation Platform over a private connection, or if your organization already uses VPNs or Direct Connections with Azure, then this approach is likely suitable for your needs.

In this case, your on-premises infrastructure is connected to Azure through a Network Application Gateway and has routing rules that can enable access to Ansible Automation Platform to any connected computer on the local network.
The VNET connected to the Virtual Network Gateway would be connected to other Azure VNETs through network peering with routing rules established to send network traffic for 192.168.0.0/24 to the Ansible Automation Platform VNET.

With this configuration, users would not need to perform any extra configuration; they would be able to access Ansible Automation Platform through the application URLs as if they were using the public access approach.

