[id="proc-azure-nw-peering-aap-subnet_{context}"]

= Configuring network peering with the {PlatformNameShort} subnet

Within the Azure console, the Azure virtual network (VNet) is known as _this virtual network_, and the VNet that you want to peer with is known as _remote virtual network_.

In the *Virtual Networks* page in the Azure portal, use the following settings to configure peering between the Azure VNet and the VNet that you want to peer with the {AAPonAzureNameShort} app:

* Under *This virtual network*, select settings for the {AAPonAzureNameShort} virtual network:
** *Peering link name*: _<hub_to_aap_peering_link_name>_
** *Traffic to remote virtual network*: _Allow_
** *Traffic forwarded from remove virtual network*: _Allow_
** *Virtual network gateway or Route Server*: _Use this network’s gateway or Route server_

* Under *Remote virtual network*, select settings for the virtual network that you want to peer with Azure:
** *Peering link name*: _<aap_to_hub_peering_link_name>_
** *Traffic to remote virtual network*: _Allow_
** *Traffic forwarded from remote virtual network*: _Allow_
** *Virtual network gateway or Route Server*: _Use the remote virtual network’s gateway or Route server_

For further information on configuring peering, refer to link:https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-peering#create-a-peering[Create a peering] in the Microsoft Azure _Virtual network_ guide.

