////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

[id="proc-azure-nw-private-deploy-az-hosted-vm"]

= Azure hosted virtual machine

Likely, the easiest way to configure access for a small set of users is to create a jump box in a DMZ VNET where users can remote into from the public internet to gain access to private network resources on Azure networks.
The VM would need to have workstation features (a GUI and browser installed in the case of Linux) since users will leverage the browser on this machine in order to navigate to Ansible Automation Platform web UIs.  

The DMZ would be connected to other Azure VNETs through network peering with routing rules established to send network traffic for 192.168.0.0/24 to the Ansible Automation Platform VNET.  

PCs from office locations can remote into the publicly accessible virtual machine through VNC, RDP, or other screen-sharing protocols.
Then, using a browser on the virtual machine, you may enter the Ansible Automation Platform URLs to access the platform on the private network.

