[id="assembly-planning-ITSM-integration"]

= Planning your ITSM integration with Automation Services Catalog

Plan for the updates and modifications required to your Ansible Automation Platform and playbook inventory to integrate with your ITSM system. Some changes will require specific levels of administrative permissions in both Ansible Tower and Automation Services Catalog.

This section will detail the exact roles required to perform updates, and the artifacts you will need to modify.

.Required permissions

You will require the following roles to complete the integration workflow:

* You can write or update the playbooks used for ITSM integration.
* You are an Ansible Tower administrator and can create job templates and add surveys.
* You are a Catalog Administrator and can create portfolios, edit surveys, and set order processes.



.Playbooks

Write or update those playbooks used in the job templates and workflows you intend to use for ITSM integration with Automation Services Catalog.

.Ansible Tower job and workflow template surveys

Update surveys attached to job templates running the before and after playbooks to support substitutable values.

.Automation Services Catalog

Update surveys set to products in your ITSM integration workflow to enable substitution.
