

ifdef::context[:parent-context: {context}]



[id="installing-catalog-worker"]
= Installing the automation services catalog worker


:context: installing-catalog-worker



[role="_abstract"]
You can use the following instructions to extend your {PlatformName} to connect to {Catalog} hosted service on cloud.redhat.com.


== Prerequisites

* Automation controller and any instance group nodes associated with an organization service account specified in  /inventory  must be running on a RHEL 8.4 virtual machine.
* You have registered the RHEL 8.4 virtual machine with Red Hat Subscription Manager. Installation generates a certificate used to authenticate with cloud.redhat.com.
* You have attached the Ansible Automation Platform SKU to the Catalog Worker node.
* You have enabled SSH on the RHEL 8.4 virtual machine running the automation services catalog worker.
* Automation controller with at least one organization configured, including inventories, projects and job templates.
* A service account is created for each organization that has write permissions on all objects mentioned above. Application token is created when the installer is run and not required as a prerequisite.

include::catalog/proc-preparing-worker-installer.adoc[leveloffset=+1]




ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
