[id="proc-eda-set-up-new-decision-environment"]

= Setting up a new decision environment

Decision Environments are a container image to run Ansible rulebooks.
They create a common language for communicating automation dependencies, and provide a standard way to build and distribute the automation environment.
The default decision environment is found at link:https://quay.io/repository/ansible/ansible-rulebook[Ansible-Rulebook]. 

To create your own decision environment refer to [PLACEHOLDER FOR LINK TO KCS].

The following steps describe how to import a decision environment into your {EDAcontroller} Dashboard.

== Prerequisites

* You are logged in to the {EDAcontroller} Dashboard as a Content Consumer.
* You have set up a credential, if necessary. 
For more information, refer to the link:https://docs.ansible.com/automation-controller/latest/html/userguide/credentials.html[Credentials] section
of the {ControllerNameStart} documentation.
* You have pushed a decision environment image to an image repository or you chose to use the provided image `de-supported` provided at link:http://registry.redhat.io/[registry.redhat.io].

== Procedure

. Navigate to the {EDAcontroller} Dashboard.
. From the navigation bar, select btn:[Decision Environments] → btn:[Create decision environment].
. Insert the following: 
** *Name*
** *Description*: This field is optional.
** *Image*: This is the full image location, including the container registry, image name, and version tag.
** *Credential*: This is the token needed to utilize the decision environment image. 
. Select btn:[Create decision environment].

Your decision environment is now created and can be managed on the *Decision Environments* screen.

After saving the new decision environment, you are brought to the decision environment's details page. 
From there or the *Decision Environment* list view you can edit or delete it.