[id="eda-set-up-credential"]

= Setting up credentials

Create a credential to use with a private repository (GitHub or GitLab) or a private container registry.

[IMPORTANT]
====
If you are using a GitHub or GitLab repository, use the `basic auth` method. 
Both SCM servers are officially supported. 
You can use any SCM provider that supports `basic auth`.
====

.Procedure

. Log in to the {EDAcontroller} Dashboard.
. From the navigation panel, select menu:Resources[Credentials].
. Click btn:[Create credential].
. Insert the following:
+
Name:: Insert the name.
Description:: This field is optional.
Credential type:: The options available are a GitHub personal access token, a GitLab personal access token, or a container registry.
Username:: Insert the username.
Token:: Insert a token that allows you to authenticate to your destination.
+
[NOTE]
====
If you are using a container registry, the token field can be a token or a password, depending on the registry provider.
If you are using the {PlatformNameShort} hub registry, insert the password for that in the token field. 
====
+
. Click btn:[Create credential].

After saving the credential, the credentials details page is displayed. 
From there or the *Credentials* list view, you can edit or delete it.
