[id="eda-build-a-custom-decision-environment"]

= Building a custom decision environment for {EDAName} within {PlatformNameShort}

Use the following instructions if you need a custom decision environment to provide a custom maintained or third-party event source plugin that is not available in the default decision environment.

.Prerequisites

* {PlatformNameShort} > = 2.4
* {EDAName}
* {Builder} > = 3.0

.Procedure

* Add the `de-supported` decision environment. This image is built from a base image provided by Red Hat called `de-minimal`.
+
[NOTE]
====
Red Hat recommends using `de-minimal` as the base image with {Builder} to build your custom decision environments.
====

The following is an example of the {Builder} definition file that uses `de-minimal` as a base image to build a custom decision environment with the ansible.eda collection:
-----
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
-----

Additionally, if you need other Python packages or RPMs, you can add the following to a single definition file:
-----
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python:
    - six
    - psutil
  system:
    - iputils [platform:rpm]
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
-----
