[id="proc-eda-set-up-token"]

= Setting up token to authenticate to Ansible Automation Platform Controller

Automation Controller must contain a project based on a repository with certain playbooks designed to work with the {EDANameShort} rulebooks. 
Automation Controller must also have corresponding job templates set up based on the playbooks in that project.

== Prerequisites

* You are logged in as a Content Consumer.
* You have created a user.
* You can log in to the {EDANameShort} Controller Dashboard or you are added as a user in the organization.

== Procedure

. Navigate to the {EDANameShort} Controller Dashboard.
. From the top navigation bar, select your profile.
. Go to *User details*.
. Select btn:[Controller Tokens] → btn:[Create controller token].
. Insert the following: 
** *Name*
** *Description*: This field is optional.
** *Token* 
. Select btn:[Create controller token].

After saving the new token, you are brought to the *Controller Tokens* tab where you can delete the token.