[id="eda-set-up-token-to-authenticate"]

= Setting up a token to authenticate to {PlatformNameShort} Controller

.Prerequisites

* You are logged in to the {EDAcontroller} Dashboard as a Content Consumer.
* You have created a user.
* You can log in to the {EDAcontroller} Dashboard or you are added as a user in the organization.

.Procedure

. Navigate to the {EDAcontroller} Dashboard.
. From the top navigation panel, select your profile.
. Go to *User details*.
. Select menu:Controller Tokens[Create controller token].
. Insert the following: 
+
Name:: Insert the name.
Description:: This field is optional.
Token:: Create the token in {ControllerName}. 
For more information on creating the token, refer to the link:https://docs.ansible.com/automation-controller/latest/html/userguide/users.html#users-tokens[Users - Tokens] section of the Automation controller User Guide.
+
[NOTE]
====
The token must be in write-scope.
====
. Select btn:[Create controller token].

After saving the new token, you are brought to the *Controller Tokens* tab where you can delete the token.