[id="eda-set-up-new-decision-environment"]

= Setting up a new decision environment

The following steps describe how to import a decision environment into your {EDAcontroller} Dashboard.

.Prerequisites

* You are logged in to the {EDAcontroller} Dashboard as a Content Consumer.
* You have set up a credential, if necessary. 
For more information, see the xref:eda-set-up-credential[Setting up credentials] section.
* You have pushed a decision environment image to an image repository or you chose to use the image `de-supported` provided at link:http://registry.redhat.io/[registry.redhat.io].

.Procedure

. Navigate to the {EDAcontroller} Dashboard.
. From the navigation panel, select menu:Decision Environments[Create decision environment].
. Insert the following: 
+
Name:: Insert the name.
Description:: This field is optional.
Image:: This is the full image location, including the container registry, image name, and version tag.
Credential:: This field is optional. This is the token needed to utilize the decision environment image. 
. Select btn:[Create decision environment].

Your decision environment is now created and can be managed on the *Decision Environments* screen.

After saving the new decision environment, the decision environment's details page is displayed. 
From there or the *Decision Environments* list view, you can edit or delete it.