[id="installing-eda-controller-on-red-hat-aap_{context}"]

= Installing {EDAcontroller} on {PlatformName}

To prepare for installation of {EDAcontroller}, review the following information in the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/index[Red Hat Ansible Automation Platform Planning Guide]: 

* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/aap_architecture#aap_example_architecture_planning[Example Ansible Automation Platform architecture], including the {EDAcontroller}
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/ref-aap-components#about-event-driven-ansible-controller_planning[Event-Driven Ansible controller] general information
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements#event-driven-ansible-system-requirements[Event-Driven Ansible controller system requirements] 

When you are ready to install the {EDAcontroller}, see the procedures in the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/index[Red Hat Ansible Automation Platform Installation Guide] beginning with link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario[Chapter 3. Installing {PlatformName}].  

Lastly, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/appendix-inventory-files-vars#event-driven-ansible-controller_platform-install-scenario[Appendix A. 5. Event-Driven Ansible controller variables] in the {PlatformName} Installation Guide to view predefined variables for {EDAcontroller}.

