[id="installing-eda-controller-on-red-hat-aap_{context}"]

= Installing {EDAcontroller} on {PlatformName}

To prepare for installation of {EDAcontroller}, review the following information in the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/index[Red Hat Ansible Automation Platform Planning Guide]: 

* link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/aap_architecture#aap_example_architecture_planning[Example Ansible Automation Platform architecture], including the {EDAcontroller}
* link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/ref-aap-components#about-event-driven-ansible-controller_planning[Event-Driven Ansible controller] general information
* link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements#event-driven-ansible-system-requirements[Event-Driven Ansible controller system requirements] 

When you are ready to install the {EDAcontroller}, refer to the procedures in the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/index[Red Hat Ansible Automation Platform Installation Guide] beginning with link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario[Chapter 3. Installing {PlatformName}]. For a specific code example related to  {EDAcontroller}, refer to the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html-single/red_hat_ansible_automation_platform_installation_guide/index#ref-single-eda-controller-with-internal-db_platform-install-scenario[Single Event-Driven Ansible controller node with internal database] scenario in this chapter. 

To further assist you in getting started with {EDAName}, review the following existing installation scenarios that have been updated with code examples and variables that are required to install {EDAcontroller}:

* link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-standlone-platform-ext-database-inventory_platform-install-scenario[Ansible Automation Platform with an external (installer managed) database].
* link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-scenario[Ansible Automation Platform with an external (customer provided) database].

Lastly, refer to link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/appendix-inventory-files-vars#event-driven-ansible-controller_platform-install-scenario[Appendix A. 5. Event-Driven Ansible controller variables] in the Red Hat Ansible Automation Platform Installation Guide to view pre-defined variables for {EDAcontroller}.

