

ifdef::context[:parent-context: {context}]


[id="assembly-evaluating-automation-return"]

:context: assembly-evaluating-automation-return-ctxt

= About Automation Calculator

The automation calculator provides graphs, metrics and calculations that help you determine the total savings on your investment in automated processes.

.Automation savings

Automation savings is produced by an analysis of the time and cost of performing a task manually, such as deploying a server, versus the time and cost associated with automating the same task. Automation savings calculations extend across all organizations, clusters, hosts and templates in an environment. Include your own estimated costs to produce a more accurate calculation.

[NOTE]
====
The initial total savings is based on default values for each variable.
====

.Variables

Several variables are used in evaluating costs:

* *Manual cost of automation* - the approximate cost for a mid-level resource to perform a task or series of tasks.
* *Cost of automation* - costs associated with automating tasks as job templates.
* *Automation time* - the time required to run a job template.
* *Number of hosts* - the number of hosts in inventory the template runs on.

.Automation formula

Automation savings is based on the following formulas:

* *Manual cost per template* = (time for a manual run on one host * (sum of all hosts across job runs)) * cost per hour.
* *Automation cost per template* = cost of automation per hour * sum of total elapsed hours for a template.
* *Savings* = sum of (manual cost - automation costs) across all templates.

include::analytics/proc-calculating-automation.adoc[leveloffset=+1]

include::analytics/con-top-templates.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
