ifdef::context[:parent-context: {context}]

[id="assembly-automation-savings-planner"]

:context: assembly-automation-savings-planner-ctxt

= About the {planner}

An automation savings plan gives you the ability to plan, track, and analyze the potential efficiency and cost savings of your automation initiatives. Use {InsightsName} to create an automation savings plan by defining a list of tasks needed to complete an automation job. You can then link your automation savings plans to an Ansible job template in order to accurately measure the time and cost savings upon completion of an automation job. 

To create an automation savings plan, you can utilize the {planner} to prioritize the various automation jobs throughout your organization and understand the potential time and cost savings for your automation initiatives.

include::analytics/proc-create-savings-plan.adoc[leveloffset=+1]

include::analytics/proc-edit-savings-plan.adoc[leveloffset=+1]

include::analytics/proc-link-plan-job-template.adoc[leveloffset=+1]

include::analytics/con-review-savings-calculations.adoc[leveloffset=+1]

include::analytics/proc-filter-plans.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]