[id="troubleshoot-use-in-controller"]
= Issue - Cannot select the "Use in Controller" option for {ExecEnvShort} image on {PrivateHubName}

You cannot use the *Use in Controller* option for an {ExecEnvShort} image on {PrivateHubName}. You also receive the error message: “No Controllers available”.

To resolve this issue, connect {ControllerName} to your {PrivateHubName} instance.

.Procedure

. Change the `/etc/pulp/settings.py` file on {PrivateHubName} and add one of the following parameters depending on your configuration:
* Single controller
+
[subs="+quotes"]
----
CONNECTED_ANSIBLE_CONTROLLERS = ['_<https://my.controller.node>_']
----
+
* Many controllers behind a load balancer
+
[subs="+quotes"]
----
CONNECTED_ANSIBLE_CONTROLLERS = ['_<https://my.controller.loadbalancer>_']
----
+
* Many controllers without a load balancer
+
[subs="+quotes"]
----
CONNECTED_ANSIBLE_CONTROLLERS = ['_<https://my.controller.node1>_', '_<https://my.controller2.node2>_']
----
+

. Stop all of the {PrivateHubName} services:
+
----
# systemctl stop pulpcore.service pulpcore-api.service pulpcore-content.service pulpcore-worker@1.service pulpcore-worker@2.service nginx.service redis.service
----
+

. Restart all of the {PrivateHubName} services:
+
----
# systemctl start pulpcore.service pulpcore-api.service pulpcore-content.service pulpcore-worker@1.service pulpcore-worker@2.service nginx.service redis.service
----
+


.Verification
* Verify that you can now use the *Use in Controller* option in {PrivateHubName}.




