[id="troubleshoot-invalid-credentials"]
= Issue - Logging in to the {ControllerName} UI results in “Invalid username or password. Please try again.”

When you try to log in to the {ControllerName} UI, the login fails and you see the error message: “Invalid username or password. Please try again.”.

One reason this could be happening is if the value for *Maximum number of simultaneous logged in sessions* is `0`. The *Maximum number of simultaneous logged in sessions* value determines the maximum number of sessions allowed per user per device. If this value is `0`, no users can log in to {ControllerName}.

The default value is `-1`, which disables the maximum sessions allowed. This means that you can have as many sessions without an imposed limit.

.Procedure

* As root user, run the following command from the command line to set the `SESSIONS_PER_USER` variable to `-1` which disables the maximum sessions allowed:
+
----
# echo "settings.SESSIONS_PER_USER = -1" | awx-manage shell_plus --quiet
----
+


.Verification

* Verify that you can log in successfully to {ControllerName}.


[role="_additional-resources"]
.Additional resources

* For more information about installing and using the controller node CLI, see link:https://docs.ansible.com/automation-controller/latest/html/controllercli/index.html[AWX Command Line Interface] and link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/automation_controller_administration_guide/index#assembly-controller-awx-manage-utility[AWX manage utility].

* For more information about session limits, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/automation_controller_administration_guide/controller-session-limits[Session Limits] in the Automation Controller Administration Guide.

