[[aap-2.3-intro]]
= Ansible Automation Platform 2.3

Red Hat Ansible Automation Platform simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles. It works across multiple IT domains including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, Red Hat Ansible Automation Platform provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

.Enhancements

* Added a configurable automatic logout time. Set a minimum password length for internal users. 
* Added visibility for EE's created by ansible-builder in the automation hub UI.
* Fixed a race condition where the UI would not properly populate upon launch.
* Fixed an issue where the pulp resource manager was not removed on upgrade from Automation Platform Operator 2.1 to Automation Platform Operator 2.2
* Fixed an issue where puppet managed files are not handled properly by the setup script.

Other noteworthy developer tooling updates include the following:

* Added new pre-flight checks to ansible-core CLI start up to enforce assumptions made about handling display and text encoding.
* Added official support for Python 3.11 to ansible-core CLIs and target node execution.
* Drop Python 3.8 support for ansible-core CLIs and controller side code.
