[[catalog-05-2022]]
= Automation Services Catalog

Automation Services Catalog provides an easy way to extend automation in your Ansible controller to a broader user base. It offers multi-level approval to ensure extending automation is done safely. And, Role Based Access allows you to restrict automation access to specified users. Automation Services Catalog is the shop window into the Ansible Automation Platform.

[NOTE]
====
Automation Services Catalog is a Technology Preview supported feature.
====

The following languages are supported for internalization:

* English
* French
* Spanish
* Japanese
* Korean
* Dutch
* Chinese

.Enhancements

* Private Automation Services Catalog can now be installed. Installation must be on a physical/virtual instance.
* Red Hat Single Sign-On can now be installed. Installation must be on a separate physical/virtual instance.
* Added role-based access for users and groups.
* Added ability to order products that contain job templates or workflows within portfolios.
* Extended metadata to describe products.
* Added functionality for an admin to share Portfolios to users.
* Added functionality to copy products and portfolios.
* Added option for multi-level approval process before a product can be executed.
* Added the approver role, who can approve, deny, or memo approval requests in a queue.
* Added ability to email approval requests.
* Added re-branding functionality to allow customers to change the default product icons and logos to match their organization.
