[[controller-41-intro]]
= Automation controller 4.1.1

Automation controller replaces Ansible Tower.
Automation controller introduces a distributed, modular architecture with a decoupled control and execution plane.
The name change reflects these enhancements and the overall position within the Ansible Automation Platform suite.

Automation controller provides a standardized way to define, operate and delegate automation across the enterprise. It also introduces new, exciting technologies and an enhanced architecture that enables automation teams to scale and deliver automation rapidly to meet ever-growing business demand.

.Enhancements and Bug fixes

* Added the ability to specify additional nginx headers
* Fixed analytics gathering to collect all the data the controller needed to collect
* Fixed the controller to no longer break subsequent installer runs when deleting the demo organization

See https://docs.ansible.com/automation-controller/latest/html/release-notes/relnotes.html#release-notes-for-4-x[automation controller Release Notes for 4.x] for a full list of new features and enhancements.
