[[hub-450-intro]]
= Automation Hub 4.5

Automation Hub allows you to discover and utilize new certified automation content from Red Hat Ansible and Certified Partners. On Ansible Automation Hub, you can discover and manage Ansible Collections, which is supported automation content developed by both partners and Red Hat for use cases such as cloud automation, network automation, security automation, and more.

.Enhancements

* Added the capability to configure LDAP with Private Automation Hub.
* Allow option for execution environment images to be pulled from Hub only.
* Fixed an issue during Hub installation during the collect static content task.
* Fixed an issue when a 500 error would populate when listing roles on a group.
* Fixed an issue when imports contained more than 100 namespaces.
* Fixed an issue where certified content would display incorrectly in private automation hub when synced.
* Fixed an issue where group_admin users could not view groups.
* Fixed an issue where pressing the enter key would reload a form instead of submitting.