[[platform-introduction]]
= Overview

Red Hat Ansible Automation Platform simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles. It works across multiple IT domains including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, Red Hat Ansible Automation Platform provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

[[whats-included]]
== What's included in Ansible Automation Platform

[cols="a,a,a,a,a"]
|===
| Ansible Automation Platform | Automation controller | Automation hub | Automation services catalog | Insights for Ansible Automation Platform

|2.1.1 | 4.1.1 | 4.4.1 | hosted service | hosted service

|===

== Red Hat Ansible Automation Platform life cycle

Red Hat publishes a product life cycle page that identifies the levels of maintenance for each Ansible Automation Platform release.
See link:https://access.redhat.com/support/policy/updates/ansible-automation-platform[Red Hat Ansible Automation Platform Life Cycle] for additional information.

