[id="assembly-central-auth-group-perms"]

== Managing group permissions with {AAPCentralAuth}

You can manage user access on the {PlatformNameShort} by assigning specific permissions to user groups. As users log in to the {PlatformNameShort} for the first time, their groups will appear in the user access page in {HubName}, allowing you to assign user access and permissions to each group.

=== Assigning permissions to Groups

You can assign permissions to groups in {HubName}that enable users to access specific features in the system.

.Prerequisites
You are signed in as a `hubadmin` user.

.Procedure
. Log in to your local {HubName}.
. Navigate to *Groups*.
. Click on a group name.
. Click *Edit*.
. Click in the field for the permission type and select permissions that appear in the list.
. Click *Save* when finished assigning permissions.

The group can now access features in {HubName} associated with their assigned permissions.

include::automation-hub/ref-permissions.adoc[leveloffset=+2]
