
[id="con-content-workflows_introduction"]


= About content workflows


[role="_abstract"]
Before {PlatformName} 2.0, an automation content developer may have needed so many Python virtual environments that they required their own automation in order to manage them. To reduce this level of complexity, {PlatformNameShort} 2.0 is moving away from virtual environments and using containers, referred to as {ExecEnvName}, instead, as they are straightforward to build and manage and are more shareable across teams and orgs.

As {ControllerName} shifts to using {ExecEnvName}, tools like {Navigator} and {Builder} ensure that you can take advantage of those {ExecEnvName} locally within your own development system.


[role="_additional-resources"]
.Additional resources

* See the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_creator_guide/tools#con-about-ansible-navigator_tools[Automation Content Navigator Creator Guide] for more on using {Navigator}.
* For more information on {Builder}, see link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/creating_and_consuming_execution_environments/index[Creating and Consuming Execution Environments].
