[id="creating-roles"]



= Creating roles

[role="_abstract"]
You can create roles by using the {Galaxy} CLI tool. You can access Role-specific commands from the `roles` subcommand.

-----
ansible-galaxy role init <role_name>
-----

Standalone roles outside of Collections are still supported, but create new roles inside of a Collection to take advantage of all the features {PlatformNameShort} has to offer.

.Procedure

. In your terminal, go to the `roles` directory inside a collection.
. Create a role called `role_name` inside the collection:
+
-----
$ ansible-galaxy role init my_role
-----
+
The collection now includes a role named `my_role` inside the `roles` directory:
+
-----
    ~/.ansible/collections/ansible_collections/<my_namespace>/<my_collection_name>
    ...
    └── roles/
        └── my_role/
            ├── .travis.yml
            ├── README.md
            ├── defaults/
            │   └── main.yml
            ├── files/
            ├── handlers/
            │   └── main.yml
            ├── meta/
            │   └── main.yml
            ├── tasks/
            │   └── main.yml
            ├── templates/
            ├── tests/
            │   ├── inventory
            │   └── test.yml
            └── vars/
                └── main.yml
-----
+
. A custom role skeleton directory can be supplied by using the `--role-skeleton` argument. This allows organizations to create standardized templates for new roles to suit their needs.

    ansible-galaxy role init my_role --role-skeleton ~/role_skeleton

This will create a role named `my_role` by copying the contents of `~/role_skeleton` into `my_role`. The contents of `role_skeleton` can be any files or folders that are valid inside a role directory.


[role="_additional-resources"]
.Additional resources

* For more information about creating roles, see link:https://galaxy.ansible.com/docs/contributing/creating_role.html[Creating roles] in the {Galaxy} documentation.
