[id="con-central-auth-reqs"]

= System Requirements

There are several minimum requirements to install and run {AAPCentralAuth}:

* Any operating system that runs Java
* Java 8 JDK
* zip or gzip and tar
* At least 512mb of RAM
* At least 1gb of disk space
* A shared external database like PostgreSQL, MySQL, Oracle, etc. if you want to run {CentralAuth} in a cluster.
See the link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RHSSOVers}/html-single/server_installation_and_configuration_guide/index#database_configuration[Database Configuration section of the _{RHSSO} Server Installation and Configuration guide_] for more information.
* Network multicast support on your machine if you want to run in a cluster. {CentralAuth} can be clustered without multicast, but this requires some configuration changes.
See the link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.6/html-single/server_installation_and_configuration_guide/index#clustering[Clustering section of the _{RHSSO} Server Installation and Configuration guide_] for more information.
* On Linux, it is recommended to use `/dev/urandom` as a source of random data to prevent {CentralAuth} hanging due to lack of available entropy, unless `/dev/random` usage is mandated by your security policy. To achieve that on Oracle JDK 8 and OpenJDK 8, set the `*java.security.egd*` system property on startup to `*file:/dev/urandom*`.
