// Module included in the following assemblies:
// assembly-view-only-access.adoc


[id="con-enable-view-only"]

Enable view-only access for your private {HubName} by editing the inventory file found on your {PlatformName} installer.

* If you are installing a new instance of {PlatformNameShort}, follow these steps to add the `automationhub_enable_unauthenticated_collection_access` parameter to your `inventory` file along with your other installation configurations:
* If you are updating an existing {PlatformNameShort} installation to include view-only access, add the `automationhub_enable_unauthenticated_collection_access` parameter to your `inventory` file then run the `setup.sh` script to apply the updates:

.Procedure
. Navigate to the installer.
Bundled installer::
+
-----
$ cd ansible-automation-platform-setup-bundle-<latest-version>
-----
+
Online installer::
+
-----
$ cd ansible-automation-platform-setup-<latest-version>
-----
+
. Open the `inventory` file with a text editor.
. Add the `automationhub_enable_unauthenticated_collection_access` parameter to the inventory file and set to `True`, following the example below:
+
----
[all:vars]

automationhub_enable_unauthenticated_collection_access = True
----
. Run the `setup.sh` script. The installer will now enable view-only access to your {HubName}.

.Verification
Once the installation completes, you can verify that you have view-only access on your private {HubName} by attempting to view content on your {HubName} without logging in.

. Navigate to your private {HubName}.
. On the login screen, click *View only mode*.

Verify that you are able to view content on your {HubName}, such as namespaces or collections, without having to log in.
