// Module included in the following assemblies:
// assembly-view-only-access.adoc


[id="con-enable-view-only"]

To enable view-only access for your private {HubName}, you will need to edit the inventory file found on your {PlatformName} installer, following the instructions below:

.Procedure
. Navigate to the installer.
.. [bundled installer]
+
-----
$ cd ansible-automation-platform-setup-bundle-<latest-version>
-----
+
.. [online installer]
+
-----
$ cd ansible-automation-platform-setup-<latest-version>
-----
+
. Open the `inventory` file with a text editor.
. Add the `GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS` parameter to the inventory file and set to `TRUE`, following the example below:
+
----
[all:vars]

GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS = True
----
. Run the `setup.sh` script. The installer will now enable view-only access to your {HubName}.

.Verification
Once the installation completes, you can verify that you have view-only access on your private {HubName} by attempting to view content on your {HubName} without logging in.

. Navigate to your private {HubName}.
. On the login screen, click *View only mode*.

Verify that you are able to view content on your {HubName}, such as namespaces or collections, without having to log in.
