[id="con-user-access"]

= About user access

You can manage user access to content and features in Automation Hub by creating groups of users that have specific permissions.

== How to implement user access

User access is based on managing permissions to system objects (users, groups, namespaces) rather than by assigning permissions individually to specific users.

You assign permissions to the groups you create. You can then assign users to these groups. This means that each user in a group has the permissions assigned to that group.

Groups created in Automation Hub can range from system administrators responsible for governing internal collections, configuring user access, and repository management to groups with access to organize and upload internally developed content to Automation Hub.

*  See xref:ref-permissions[Automation Hub permissions] for information on system permissions.

== Default user access

When you install Automation hub, the default *admin* user is created in the *Admin* group. This group is assigned all permissions in the system.

== Getting started

Log in to your local Automation Hub using credentials for the *admin* user configured during installation.
