// Module included in the following assemblies:
// obtaining-token/master.adoc
[id="proc-create-synclist"]

= Creating a synclist of Red Hat Certified collections

You can create a synclist of curated Red Hat Certified and Vaidated Collections in {HubName} on console.redhat.com. 
Your synclist repository is located under menu:Automation Hub[Repo Management], which is updated whenever you choose to manage content within Red Hat Certified or Validated Collections.

By default, all Red Hat Certified and and Validated Collections are included in your initial organization synclist.

.Prerequisites

* You have a valid {PlatformNameShort} subscription.
* You have Organization Administrator permissions for console.redhat.com.
* Ensure that the following domain names are part of either the firewall or the proxy's allowlist for successful connection and download of collections from {HubName} or Galaxy server:
** `galaxy.ansible.com`
** `cloud.redhat.com`
** `console.redhat.com`
** `sso.redhat.com`
* {HubNameStart} resources are stored in Amazon Simple Storage.
Add the following domain name to the allow list:
** `automation-hub-prd.s3.us-east-2.amazonaws.com`
* SSL inspection must be disabled either when using self signed certificates or for the Red Hat domains.


.Procedure

. Log in to console.redhat.com.
. Navigate to menu:Automation Hub[Collections].
. Use the toggle switch on each collection to determine whether to exclude it from your synclist.


When you finish managing collections for your synclist, you can navigate to menu:Automation Hub[Repo Management] to initiate the remote repository sync to your local {HubName}. 
If your remote repository is already configured, you can manually sync Red Hat Certified and Validated Collections to your local {HubName} to update the collections content that you made available to local users.
