:_content-type: PROCEDURE

[id="proc-sync-image-adoc_{context}"]
= Syncing images from a container repository

You can pull images from the {HubName} container registry to sync an image to your local machine.


.Prerequisites

You must have permission to view and pull from a private container repository.

.Procedure

To sync an image from a remote container registry, you need to configure a
remote registry.

. Navigate to menu:Execution Environments[Remote Registries].

. Add https://registry.redhat.io to the registry.

. Add any required credentials to authenticate.

NOTE: Some container registries are aggressive with rate limiting. It is
advisable to set a rate limit under Advanced Options.

. Navigate to menu:Execution Environments[Execution Environments].

. Click btn:[Add execution environment].

. Select the registry you want to pull from. The *name* field displays the name of the image shown on your local registry.

NOTE: The *Upstream name* field is the name of the image on the remote server. For example, if the upstream name is set to _alpine_ and the *Name* field to _local/alpine_, the alpine image is downloaded from the remote and renamed to _local/alpine_.

It is advisable to set a list of tags to include or exclude. Syncing images with a large number of tags is time consuming and uses a lot of disk space.


//ddacosta- moved this to the assembly to avoid duplication of Additional resources heading in the chapter
//[role="_additional-resources"]
//.Additional resources
//* See link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication] for a list of registries.
