

[id="obtain-images"]


= Obtaining images for use in {HubName}

[role="_abstract"]
Before you can push container images to your {PrivateHubName}, you must first pull them from an existing registry and tag them for use. This example details how to pull an image from the Red Hat Ecosystem Catalog (registry.redhat.io).

.Prerequisites
You have permissions to pull images from registry.redhat.io.

.Procedure

. Log in to Podman using your registry.redhat.io credentials:
+
-----
$ podman login registry.redhat.io
-----
+
. Enter your username and password at the prompts.
. Pull a container image:
+
[subs="+quotes"]
-----
$ podman pull registry.redhat.io/__<container_image_name>__:__<tag>__
-----


.Verification


. List the images in local storage:
+
-----
$ podman images
-----
+
. Verify that the image you recently pulled is contained in the list.
. Verify that the tag is correct.

[role="_additional-resources"]
.Additional resources

* See link:https://redhat-connect.gitbook.io/catalog-help/[Red Hat Ecosystem Catalog Help] for information on registering and getting images.
