:_content-type: PROCEDURE

[id="proc-sync-image-adoc_{context}"]
= Syncing images from a container repository

You can pull images from the {HubName} container registry to sync an image to your local machine. 


.Prerequisites

You must have permission to view and pull from a private container repository.

.Procedure

To sync an image from a remote container registry, you need to configure a 
remote registry.

. Navigate to menu:Execution Environments[Remote Registries].

. Add https://registry.redhat.io to the registry.

. Add any required credentials to authenticate. 

NOTE: Some container registries are aggressive with rate limiting. It is  
advisable to set a rate limit under Advanced Options.

. Navigate to menu:Execution Environments[Execution Environments].

. Click *Add execution environment* in the page header.

. Select the registry you wish to pull from. The "name" field displays the name of the image that will show up as on your local registry. 

NOTE: The "Upstream name" field is the name of the image on the remote server. For example if the upstream name is set to "alpine" and the “name” field to "local/alpine", the alpine image will be downloaded from the remote and renamed to local/alpine.

It is advisable to set a list of tags to include or exclude. Syncing images with a large number of tags is time consuming and will use a lot of disk space.



[role="_additional-resources"]
.Additional resources

* See link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication] for a list of registries.


