// Module included in the following assemblies:
// obtaining-token/master.adoc
[id="proc-create-content-developers"]

= Creating a new group for content curators

You can create a new group in {HubName} designed to support content curation in your organization that contributes internally developed collections for publication in {HubName}.

This section shows you how to create a new group and assign the required permissions to help content developers create namespaces and upload their collections to {HubName}.

.Prerequisites

* You have administrative permissions in {HubName} and create groups.

.Procedure

. Log in to your local {HubName}.
. Navigate to menu:User Access[Groups] and click btn:[Create].
. Enter *Content Engineering* as a *Name* for the group in the modal and click btn:[Create]. You have created the new group and the *Groups* page appears.
. On the *Permissions* tab, click btn:[Edit].
. Under *Namespaces*, add permissions for *Add Namespace*, *Upload to Namespace* and *Change Namespace*.
. Click btn:[Save].
+
The new group is created with the permissions you assigned. You can then add users to the group.
+
. Click the *Users* tab on the *Groups* page.
. Click btn:[Add].
. Select users from the modal and click btn:[Add].

.Conclusion

You now have a new group who can use {HubName} to:

* Create a namespace.
* Edit the namespace details and resources page.
* Upload internally developed collections to the namespace.
