[id="proc-configure-content-signing-on-pah"]

= Configuring content signing on private automation hub

To successfully sign and publish {CertifiedName}, you must configure {PrivateHubName} for signing.

.Prerequisites

* Your GnuPG key pairs have been securely set up and managed by your organization.
* Your public/private key pair has proper access for configuring content signing on {PrivateHubName}.

.Procedure

. Create a signing script that accepts only a filename.
+
[NOTE]
====
This script acts as the signing service and must generate an ascii-armored detached `gpg` signature for that file using the key specified through the `PULP_SIGNING_KEY_FINGERPRINT` environment variable.
====
+
The script then prints out a JSON structure with the following format.
+
----
{"file": "filename", "signature": "filename.asc"}
----
+
All the file names are relative paths inside the current working directory. The file name must remain the same for the detached signature, as shown.
+
The following example shows a script that produces signatures for content:
+
[source,shell]
----
#!/usr/bin/env bash

FILE_PATH=$1
SIGNATURE_PATH="$1.asc"

ADMIN_ID="$PULP_SIGNING_KEY_FINGERPRINT"
PASSWORD="password"

# Create a detached signature
gpg --quiet --batch --pinentry-mode loopback --yes --passphrase \
   $PASSWORD --homedir ~/.gnupg/ --detach-sign --default-key $ADMIN_ID \
   --armor --output $SIGNATURE_PATH $FILE_PATH

# Check the exit status
STATUS=$?
if [ $STATUS -eq 0 ]; then
   echo {\"file\": \"$FILE_PATH\", \"signature\": \"$SIGNATURE_PATH\"}
else
   exit $STATUS
fi
----

+
After you deploy a {PrivateHubName} with signing enabled to your {PlatformNameShort} cluster, new UI additions display when you interact with collections.

. Review the {PlatformNameShort} installer inventory file for options that begin with `automationhub_*`.
+
[source,highlight=67-68]
----
[all:vars]
.
.
.
automationhub_create_default_collection_signing_service = True
automationhub_auto_sign_collections = True
automationhub_require_content_approval = True
automationhub_collection_signing_service_key = /abs/path/to/galaxy_signing_service.gpg
automationhub_collection_signing_service_script = /abs/path/to/collection_signing.sh
----
+
The two new keys (*automationhub_auto_sign_collections* and *automationhub_require_content_approval*) indicate that the collections must be signed and require approval after they are uploaded to {PrivateHubName}.
