
[id="delete-collection"]

= Deleting a collection on {HubName}

You can further manage your collections by deleting unwanted  collections, provided that the collection is not dependent on other collections. Click the *Dependencies* tab on a collection to see a list of other collections that uses the current collection.

.Prerequisites
* The collection being deleted does not have dependencies with other collections.
* You have *Delete Collections* permissions

.Procedure
. Log in to {PlatformName}.
. Navigate to menu:Automation Hub[Collections].
. Click a collection to delete.
. Click the btn:[More Actions] icon *{MoreActionsIcon}* then select an option:
.. *Delete entire collection* to delete all versions in this collection.
.. *Delete version [number]* to delete the current version of this collection. You can change versions using the *Version* dropdown menu.
+
NOTE: If the selected collection has any dependencies with other collections, these actions will be unavailable to you until you delete those dependencies. Click the *Dependencies* tab to see a list of dependencies to delete before you proceed.
+
. When the confirmation window appears, verify that the collection or version number is correct, then select *Delete*.
