[id="proc-configure-content-signing-on-pah"]

= Configuring content signing on private automation hub

To successfully sign and publish {CertifiedName}, you must configure {PrivateHubName} for signing.

.Prerequisites

* Your GnuPG key pairs have been securely set up and managed by your organization.
* Your public/private key pair has proper access for configuring content signing on {PrivateHubName}.

.Procedure

. Create a signing script that accepts only a filename.
+
[NOTE]
====
This script acts as the signing service and must generate an ascii-armored detached `gpg` signature for that file using the key specified through the `PULP_SIGNING_KEY_FINGERPRINT` environment variable.
====
+
Example signing script:
+
----
#!/usr/bin/env bash

# This GPG_TTY variable might be needed on a container image that is not running as root.
# export GPG_TTY=$(tty)

# pulp_container SigningService will pass the next 4 variables to the script.
MANIFEST_PATH=$1
FINGERPRINT="$PULP_SIGNING_KEY_FINGERPRINT"
IMAGE_REFERENCE="$REFERENCE"
SIGNATURE_PATH="$SIG_PATH"

# Create container signature using skopeo
skopeo standalone-sign \
  $MANIFEST_PATH \
  $IMAGE_REFERENCE \
  $FINGERPRINT \
  --output $SIGNATURE_PATH

# Optionally pass the passphrase to the key if password protected.
# --passphrase-file /path/to/key_password.txt

# Check the exit status
STATUS=$?
if [ $STATUS -eq 0 ]; then
  echo {\"signature_path\": \"$SIGNATURE_PATH\"}
else
  exit $STATUS
fi
----
. Review the AAP installer inventory file for options that begin with `automationhub_*`.
+
[source,highlight=67-68]
----
[all:vars]
.
.
.
automationhub_create_default_collection_signing_service = True
automationhub_container_signing_service_key = /absolute/path/to/key/to/sign
automationhub_container_signing_service_script =  /absolute/path/to/script/that/signs
----
+
If `automationhub_create_default_container_signing_service` is *True*, then the path to signing key and path to script need to be provided.
