[id="proc-create-credential"]

= Creating a credential in {ControllerName}

Previously, you were required to deploy a registry to store execution environment images. On {PlatformNameShort} 2.0 and later, it is assumed that you already have a container registry up and running. Therefore, you are only required to add the credentials of a container registry of your choice to store execution environment images.

To pull container images from a password or token-protected registry, create a credential in {ControllerName}:

.Procedure
. Navigate to {ControllerName}.
. In the side-menu bar, click menu:Resources[Credentials].
. Click btn:[Add] to create a new credential.
. Enter an authorization *Name*, *Description*, and *Organization*.
. Select the *Credential Type*.
. Enter the *Authentication URL*. This is the container registry address.
. Enter the *Username* and *Password or Token* required to log in to the container registry.
. Optionally, select *Verify SSL* to enable SSL verification.
. Click btn:[Save].

//[dcd-This should be replaced with a link; otherwise, it's not helpful]For more information, please reference the Pulling from Protected Registries section of the Execution Environment documentation.
