////
Base the file name and the ID on the module title. For example:
* file name: proc-doing-procedure-a.adoc
* ID: [id="doing-procedure-a_{context}"]
* Title: = Doing procedure A

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
////

[id="providing-access-to-containers"]

////
The `context` attribute enables module reuse. Every module ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
////

= Providing access to your container repository

[role="_abstract"]
Provide access to your container repository to users who need to work the images. Adding a group allows you to modify the permissions the group can have to the container repository. You can use this option to extend or restrict permissions based on what the group is assigned.

.Prerequisites

* You have *change container namespace* permissions.

.Procedure

. Navigate to *Execution Environments*.
. Select your container repository.
. Click *Edit*.
. Under *Groups with access*, select a group or groups to grant access to.
** Optional: Add or remove permissions for a specific group using the drop down under that group name.
. Click *Save*.


[role="_additional-resources"]
.Additional resources

* See <<container-registry-group-permissions, Container registry group permissions>> to learn more about specific permissions.
