

[id="push-containers"]


= Pushing a container image to private {HubName}


[role="_abstract"]
You can push tagged container images to private {HubName} to create new containers and populate the container registry.

.Prerequisites

* You have permissions to create new containers.
* You have the FQDN or IP address of the {HubName} instance.

.Procedure

. Log in to Podman using your {HubName} location and credentials:
+
[subs="+quotes"]
-----
$ podman login -u=_<username>_ -p=_<password>_ _<automation_hub_url>_
-----
+
. Push your container image to your {HubName} container registry:
+
[subs="+quotes"]
-----
$ podman push _<automation_hub_url>_/_<container_image_name>_ --remove-signatures
-----
+
NOTE: The `--remove-signatures` flag is required when signed images from registry.redhat.io are pushed to the {HubName} container registry. The `push` operation re-compresses image layers during the upload, which is not guaranteed to be reproducible and is client implementation dependent. This may lead to image-layer digest changes and a failed push operation, resulting in `Error: Copying this image requires changing layer representation, which is not possible (image is signed or the destination specifies a digest)`.



.Verification


. Log in to your {HubName}.

. Navigate to *Container Registry*.

. Locate the container in the container repository list.
