[id="proc-using-content-signing-services-in-pah"]

= Using content signing services in private automation hub

After you have configured content signing on your {PrivateHubName}, you can manually sign a new collection or replace an existing signature with a new one so that users who want to download a specific collection have the assurance that the collection is intended for them and has not been modified after certification.

Content signing on {PrivateHubName} provides solutions for the following scenarios:

* Your system does not have automatic signing configured and you must use a manual signing process to sign collections.
* The current signatures on the automatically configured collections are corrupted and must be replaced with new signatures.
* Additional signatures are required for previously signed content.
* You want to rotate signatures on your collections.

.Procedure

. Log in to your {PrivateHubName} instance in the {HubName} UI.

. In the left navigation, click menu:Collections[Approval].
The Approval dashboard is displayed with a list of collections.

. Click btn:[Sign and approve] for each collection you want to sign.

. Verify that the collections you signed and manually approved are displayed in the *Collections* tab.
