// Module included in the following assemblies:
// assembly-collection-import-export.adoc

[id="proc-import-collection"]

= Importing an automation content collection in {HubName}

As an automation content creator, you can import a collection for use in a custom repository. Collections must be imported into your namespace and approved by the {HubName} administrator before they can be accessed.

.Procedure
. Log in to {PlatformName}.
. Navigate to menu:Automation Hub[Namespaces]. The Namepaces page displays all of the namespaces available.
. Click btn:[View Collections].
. Click btn:[Upload Collection].
. Navigate to the collection tarball file, select the file and click btn:[Open].
. Click btn:[Upload].
+
The My Imports screen provides a summary of tests and notifies you whether the collection uploaded successfully or failed.
+
[NOTE]
====
If the collection is not approved, it is not displayed in the published repository.
====

[role="_additional-resources"]
.Additional resources
* See xref:con-approval-pipeline[Approval pipeline] for more information about collection and repository approvals.
