// Module included in the following assemblies:
// obtaining-token/master.adoc
[id="proc-create-content-developers"]

= Creating a new group for content curators

You can create a new group in Automation Hub designed to support content curation in your organization who will contribute internally developed collections for publication in Automation Hub.

In this section you will create a new group and assign the required permissions to help content developers create namespaces and upload their collections to Automation Hub.

.Prerequisites

* You have *admin* permissions in Automation Hub and create groups.

.Procedure

. Log in to your local Automation Hub.
. Navigate to *Groups* and click *Create*.
. Enter *Content Engineering* as a *Name* for the group in the modal and click *Create*. The new group is created and the *Groups* page will appear.
. On the *Permissions* tab, click *Edit*.
. Under *Namespaces* add permissions for *Add Namespace*, *Upload to Namespace* and *Change Namespace*.
. Click *Save*.
+
The new group is created with the permissions you assigned.  Next you can add users to the group.
+
. Click the *Users* tab on the *Groups* page.
. Click *Add*.
. Select users from the modal and click *Add*.

.Conclusion

You now have a new group who can use Automation Hub to:

* create a namespace,
* edit the namespace details and resources page
* upload internally developed collections to the namespace.
