

[id="push-containers"]


= Pushing a container image to private {HubName}


[role="_abstract"]
You can push tagged container images to private {HubName} to create new containers and populate the container registry.

.Prerequisites

* You have permissions to create new containers.
* You have the FQDN or IP address of the {HubName} instance.

.Procedure

. Log in to Podman using your {HubName} location and credentials:
+
-----
$ podman login -u=[username] -p=[password] [automation-hub-url]
-----
+
. Push your container image to your {HubName} container registry:
+
-----
$ podman push [automation-hub-url]/[container image name] --remove-signatures
-----
+
NOTE: The `--remove-signatures` flag is required when signed images from registry.redhat.io are pushed to the {HubName} container registry. The `push` operation re-compresses image layers during the upload, which is not guaranteed to be reproducible and is client implementation dependent. The `--remove-signatures` flag prevents possible image-layer digest changes during the `push` operation, which will cause the operation to fail.

.Verification


. Log in to your {HubName}.

. Navigate to *Container Registry*.

. Locate the container in the container repository list.
