[id="ref-variables-connect-hub-sso"]
= Inventory file variables for connecting {HubName} to a {RHSSO} instance

If you are installing {HubName} and {RHSSO} together for the first time or you have an existing {PlatformNameShort} managed {RHSSO}, configure the variables for {PlatformNameShort} managed {RHSSO}.

If you are installing {HubName} and you intend to connect it to an existing externally managed {RHSSO} instance, configure the variables for externally managed {RHSSO}.

For more information about these inventory variables, refer to link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/appendix-inventory-files-vars#ref-hub-variables[Ansible automation hub variables] in the _{PlatformName} Installation Guide_.

The following variables can be configured for both {PlatformNameShort} managed and external {RHSSO}:

[cols="50%,50%",options="header"]
|====
| *Variable* | *Required or optional*
| *`sso_console_admin_password`* | Required
| *`sso_console_admin_username`* | Optional
| *`sso_use_https`* | Optional
| *`sso_redirect_host`* | Optional
| *`sso_ssl_validate_certs`* | Optional
| *`sso_automation_platform_realm`* | Optional
| *`sso_automation_platform_realm_displayname`* | Optional
| *`sso_automation_platform_login_theme`* | Optional
|====

The following variables can be configured for {PlatformNameShort} managed {RHSSO} only:

[cols="50%,50%",options="header"]
|====
| *Variable* | *Required or optional*
| *`sso_keystore_password`* | Required only if `sso_use_https` = `true`
| *`sso_custom_keystore_file`* | Optional
| *`sso_keystore_file_remote`* | Optional
| *`sso_keystore_name`* | Optional
|====

The following variable can be configured for external {RHSSO} only:

[cols="50%,50%",options="header"]
|====
| *Variable* | *Description*
| *`sso_host`* | Required
// | *`sso_http_port or sso_https_port`* | Optional
|====

