[id="proc-eda-set-up-rulebook-activation"]

= Setting up a Rulebook Activation

[role="_abstract"]

Rulebook activations are rulebooks that have been activated to run.

== Prerequisites

* You are logged in as a Content Consumer.

== Procedure

. Navigate to the {EDANameShort} Controller Dashboard.
. From the navigation bar, select btn:[Rulebook Activations] → btn:[Create rulebook activation].
. Insert the following: 
** *Name*
** *Description*: This field is optional.
** *Project*: Projects are a logical collection of rulebooks.
** *Rulebook*: Rulebooks will be shown according to the project selected.
** *Decision environment*: Decision environments are a container image to run Ansible rulebooks.
** *Restart policy*: This is a policy to decide when to restart a rulebook.
*** Policies:
... Always: restarts when a rulebook finishes
... Never: never restarts a rulebook when it finishes
... On failure: only restarts when it fails
** *Rulebook activation enabled?*: This automatically enables the rulebook activation to run.
** *Variables*: Pass extra command line variables to the playbook in the Variables section. This is the `-e or --extra-vars` command line parameter for ansible-rulebook. 
Provide key/value pairs using either YAML or JSON. Refer to the documentation for example syntax.
. Select btn:[Create Create rulebook activation].

Your Rulebook Activation is now created and can be managed in the *Rulebook Activations* screen.