[id="configuring_ansible_galaxy_client"]

= Updating the Ansible Galaxy client as your primary source of Ansible content

The Ansible Galaxy client, `ansible-galaxy`, manages roles and collections from the command line. To ensure that the `ansible-galaxy` client uses certified, supported Ansible collections whenever possible, you should update your `ansible.cfg` file to use Red Hat Automation Hub as your primary source of Ansible collections.

In addition to configuring Red Hat Automation Hub as your default source of Ansible content, you can also configure Ansible Galaxy as a second source.


.Prerequisites

* Obtain the API token for the Automation Hub server. See Creating the Automation Hub API token for more information.


include::modules/automation-hub/proc-configure-automation-hub-server.adoc[leveloffset=+1]

You have now configured Automation Hub as your default server and can proceed to download and install supported collections.

For more information on server list configuration options and using Ansible Galaxy as an Ansible content source, see the https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#configuring-the-ansible-galaxy-client[Ansible Galaxy User Guide].
