:imagesdir: images
[[catalog_support_matrix]]
= Automation Services Catalog product support matrix

This document describes the supported products that Automation Services Catalog is dependent against.

Automation Services Catalog is a hosted service at cloud.redhat.com and therefore does not itself have any public support matrix. Red Hat will own the maintaining and updating of the hosted service.

include::aap-common/making-open-source-more-inclusive.adoc[leveloffset=+1]

== Dependent Products Support Matrix

Automation Services Catalog is dependent on and integrated with Ansible Tower server in the Ansible Automation Platform. The following table details supported versions of Ansible Tower server for use with *all* versions of Automation Services Catalog.


.Ansible Tower
[width="100%",cols="60%,40%",options="header",]
|====
|Ansible Tower Version|Status
|3.7|Supported
|3.6|Supported
|3.5|Not supported
|====

[NOTE]
====
Automation Services Catalog support of a Ansible Tower version ends at the same time as that of the Ansible Tower version going end of life.
====

== Related information
For more information on Ansible Tower support and dependencies, see:

* link:https://access.redhat.com/support/policy/updates/ansible-tower[Red Hat Ansible Tower life cycle] for support details.
* link:https://access.redhat.com/articles/3382771[Ansible Tower support matrix] for dependencies.
