[id="ref-permissions"]

= Substitute variables reference

A substitution has the format of ``{{substitution_express}}``. Do not use a space between the curly brackets and the expression.

Substituted values are set in Ansible Tower jobs template surveys. Substituted variables pass from one product in the order process to another, depending on your configuration.

See https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html#surveys[Surveys] in the Ansible Tower _User Guide_ for more information on updating job template surveys.

Follow the table below when including substitutable variables in your surveys.

.Object model reference table
[cols="15%,45%,40%"]
|===
| Object | Expression | Notes

h| Order |

`order.order_id`

`order.created_at`

`order.ordered_by.name`

`order.ordered_by.email`

`order.approval.updated_at`

`order.approval.decision`

`order.approval.reason`|

 order.created_at` is the date and time when the order started.

 Date format: `2007-02-10T20:30:45Z`

Example:
{{order.approval.reason}}

h| Before order |

`before.<order_process_name>.artifacts.<fact_name>`

`before.<order_process_name>.parameters.<parameter_name>`

`before.<order_process_name>.status` |

No quotes are needed for the order_process_name if it contains space.

Example:
{{before.Sample Order.artifacts.ticket_number}}

h| Product |

`product.name`

`product.description`

`product.long_description`

`product.help_url`

`product.support_url`

`product.vendor`

`product.platform`

`product.portfolio.name`

`product.portfolio.description`

`product.artifacts.<fact_name>`

`product.parameters.<parameter_name>`

`product.status` |

Example:
{{product.artifacts.after_data}}


h| After order |

`after.<order_process_name>.artifacts.<fact_name>`

`after.<order_process_name>.parameters.<parameter_name>`

`after.<order_process_name>.status` |

No quotes are needed for the order_process_name if it contains space.

Example:
{{after.SampleOrder.status}}

|===
