:imagesdir: images
:numbered:
include::attributes/attributes.adoc[]

= Deploying a high availability automation hub

This guide provides an overview of the requirements and procedures for a high availability deployment of your {HubName}.

A high availability (HA) configuration increases reliability and scalablility for {HubName} deployments.

To set up a HA deployment of {HubName}, configure your system so that multiple nodes run the same service simultaneously with workload being distributed by a load balancer (i.e., an "active-active" configuration), thereby eliminating the single point of failure and minimizing downtime for the customer. You can configure your
Ansible automation environment for a high availability deployment by editing and running the {PlatformName} installer.

Please note that this guide covers deployment of a HA {HubName} application stack only. Other HA components, such as database and file system HA, or setting up DNS load balancing, are out of scope for this guide.

include::hub/assembly-deploying-high-availability-hub.adoc[leveloffset=+1]]
