// Module included in the following assemblies:
// assembly_Administration_guide.adoc
[id="Approval"]
= Working with approval

Catalog supports group-based approval workflows, providing the flexibility that includes selected organizational groups. Administrators can assign approval groups, view request details, approve or deny requests, and monitor status of existing requests. Once created, an approval workflow can be assigned to Catalog portfolios.

== Creating approval workflows

Create approval workflows and assign them to Catalog portfolios.

To create an approval workflow:

include::proc_Approval_workflow.adoc[]

== Approving or denying requests

Once a user places an order a request is created, which users with approval admin roles can approve or deny. Detailed information is provided for each request, with information on the ordered product and its associated requester and project. A stage transcript is also provided. Denied requests require justification and the approver must enter a reason.

To approve or deny a request:

include::proc_Approve_deny_request.adoc[]

== Commenting on requests

Comment on requests as an administrator or approver. Comments are captured by the system and visible at each stage of approval.

To comment on a request:

include::proc_Comment_on_request.adoc[]
