// Module included in the following assemblies:
// assembly_Administration_guide.adoc
[id="Approval"]
= Working with approval

Catalog supports group-based approval processes applied to portfolios, products, and platform inventories, providing the flexibility to include selected organizational groups in approving requests.

Approval administrators can create approval groups and processes, view request details, approve or deny requests, and monitor status of existing requests.

[NOTE]
====
To create and list groups when creating Approval processes, the Approval Administrator must also have Organization Administrator privileges.
====


== Creating approval workflows

Create approval processes and assign them to Catalog portfolios, products and platform inventories.

To create an approval process:

include::proc_Approval_workflow.adoc[]

== Approving or denying requests

Once a user places an order a request is created, which Approval Administrators or Approval Approvers can approve or deny. Each request includes product, portfolio, and requester information, as well as order request parameter details. A stage transcript is also provided. Denied requests require justification and the approver must enter a reason.

To approve or deny a request:

include::proc_Approve_deny_request.adoc[]

== Commenting on requests

Comment on requests as an administrator or approver. Comments are captured by the system and visible at each stage of approval.

To comment on a request:

include::proc_Comment_on_request.adoc[]
