:imagesdir: images
:numbered:
:toclevels: 1

:experimental:
// :numbered:

include::attributes/attributes.adoc[]

// Book Title
= Getting started with {HubName}

Red Hat Ansible {HubName} provides a place for Red Hat subscribers to quickly find and use content that is supported by Red Hat and our technology partners to deliver additional reassurance for the most demanding environments.

The {Galaxy} client, `ansible-galaxy`, manages roles and collections from the command line.
To ensure that the `ansible-galaxy` client uses certified, supported Ansible collections whenever possible, update your `ansible.cfg` file to use Red Hat {HubName} as your primary source of Ansible collections.

This guide walks you through the steps required to configure your `ansible.cfg` file to use Red Hat {HubName} as the default source for certified Ansible collections content.

include::aap-common/making-open-source-more-inclusive.adoc[leveloffset=+1]

include::automation-hub/proc-create-api-token.adoc[leveloffset=+1]

The API token is now available for configuring {HubName} as your default collections server or uploading collections using the `ansible-galaxy` command line tool.

include::automation-hub/con-offline-token-active.adoc[leveloffset=+2]

include::automation-hub/proc-configure-automation-hub-server.adoc[leveloffset=+1]

You have now configured {HubName} as your default server and can proceed to download and install supported collections.

For more information on server list configuration options and using {Galaxy} as an Ansible content source, see the https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#configuring-the-ansible-galaxy-client[{Galaxy} User Guide].

