[id='getting_started_with_catalog']
= Getting started with Catalog

This guide describes the initial workflows required to get started using Catalog. In the following section you will learn how to connect to a source, create a portfolio, add products to it, and share it with groups of users.

include::modules/con_Adding_sources.adoc[]

Now that a source has been added, we can create a portfolio that will group products available on the platform.

include::modules/con_Portfolios.adoc[]

Once the portfolio is created, we can add products to it.

include::modules/con_Adding_products.adoc[]

Next we will edit the portfolio, to assign an approval workflow to it.

include:con_Editing_portfolios.adoc[]

Before sharing the portfolio with users, you may need to remove products that aren't relevant to the users who will share access to the portfolio.

include::con_Deleting_products_from_portfolios.adoc[]

The final step in this workflow is to share the portfolio with groups of users. Once shared, users will have access to order products.

include::modules/con_Sharing_portfolios.adoc[]

In this section we have learned how to connect to a source, create a portfolio and add products to it, and share that portfolio with groups of users. In the next section, we will describe Approval and how to assign an approval workflow to a portfolio.
