:imagesdir: images
:numbered:
:toclevels: 1

:experimental:

include::attributes/attributes.adoc[]


// Book Title
= {PlatformName} Performance Considerations for Operator Based Installations

Deploying applications to a container orchestration platform such as {OCP} provides a number of advantages from an operational perspective. 
For example, an update to the base image of an application can be consumed through a simple in-place upgrade with little to no disruption, while a change to the required operating system of an application deployed to traditional virtual machines can be a much more disruptive and risky upgrade process.

However, while application and operator developers can provide many options to {OCCPShort} users regarding the deployment of the application, these configurations must be provided by the end user because they are dependent on the configuration of {OCPShort}. 
For example, use of node labels in the Openshift cluster can help ensure different workloads are run on specific nodes. This type of configuration must be provided by the user as the {PlatformNameShort} Operator has no way of inferring this.

//include::aap-common/making-open-source-more-inclusive.adoc[leveloffset=+1]

include::platform/assembly-pod-spec-modifications.adoc[leveloffset=+1]
include::platform/assembly-control-plane-adjustments.adoc[leveloffset=+1]
include::platform/assembly-specify-dedicated-nodes.adoc[leveloffset=+1]

