:experimental:
:toclevels: 4
include::attributes/attributes-catalog.adoc[]

[[getting-started]]
= Getting started with Automation Services Catalog


== About {ProductName}

{ProductName} is a service within the Red Hat Ansible Automation Platform.
{ProductName} allows customers to organize and govern product catalog sources on Ansible Tower across various environments.

Using {ProductName} you can:

* Apply multi-level approval to individual platform inventories
* Organize content in the form of products from your platforms into portfolios
* Choose portfolios to share with specific groups of users
* Set boundaries around values driving execution of user requests


== Getting started with {ProductName}

This guide provides instructions to begin using {ProductName}, including prerequisites and procedures for connecting your Ansible Tower provider, as well as configuring users and permissions. We also provide instructions for working with platforms, portfolios, and products.

After completing the setup described and following the steps in this guide, you will have a portfolio of products, governed by an approval process, accessible to users.

[NOTE]
====
*Entitlements*

To begin using Automation Service Catalog, you need:

At least one Red Hat account user with Organization Administrator entitlements.
The account number for this Red Hat corporate account.
====

== User access for {ProductName}

When configuring {ProductName} for your organization, consider the scope of your user environments, how those users are grouped, and the roles to assign. You can manage this workflow through *User Access*.

{ProductName} features and workflows are governed by *groups* that have specific *roles* attached to them. The *Organization Administrator* role performs the initial creation of groups, assigns roles, and adds users.

.Groups
Groups are user-defined and flexible to include many users and have multiple roles.  Create new groups based on your organization’s requirements for working with {ProductName}.

.Roles
Roles provide a defined set of actions each group performs. Determine the required level of access for your users based on the following roles {ProductName} uses:

* *Organization Administrator*: a Red Hat account user who can manage users and control their access and permissions.
* *Approval Administrator*: 	An Approval administrator role that grants create, read, update and destroy permissions. This role creates approval processes.
* *Approval Approver*: 	An Approval approver role that grants read and create permissions.
* *Approval User*: An approval user role which grants permissions to read/create a request.
* *Catalog Administrator*: A catalog administrator roles grants create, read, update, delete and order permissions.
* *Catalog User*: A catalog user roles grants read and order permissions.


[NOTE]
====
By default, all users will have Catalog User and Approval User roles assigned to them.
====

[IMPORTANT]
====
Because of security implications, limit the number of users in cloud.redhat.com with Organization Administrator privileges.
====

=== Creating administrator groups

The Organization Administrator can create new groups of administrators and users in {ProductName}. Catalog and Approval administrators are required to perform initial workflows in configuring {ProductName}. In this section, we will create groups for both Catalog and Approval administrators.

==== Creating a Catalog Administrator group

The Catalog Administrator is a role that grants create, read, update and order permissions. This role is used in creating and managing processes associated with portfolios and products.

To create a *Catalog Administrator* group:


. Navigate to *Settings* ➔ *User Access*.
. Click *Create group*.
. Enter group *name* and set the *description*.
. Click *Next*.
. In the *Add members* modal, check each user to add to the group. Click *Next* when finished.
. Check *Catalog Administrator* on the *Assign roles* modal.
. Review details for the new group and click *Confirm*.

We have created a group of *Catalog Administrators* and will now create a group of Approval administrators.

==== Creating an Approval Administrator group

The Approval Administrator is a role that grants create, read, update and order permissions. This role is used in creating and managing processes associated with portfolios and products.

To create an *Approval Administrator* group:

. Navigate to *Settings* ➔ *User Access*.
. Click *Create group*.
. Enter group *name* and set the *description*.
. Click *Next*.
. In the *Add members* modal, check each user to add to the group. Click *Next* when finished.
. Check *Approval Administrator* on the *Assign roles* modal.
. Review details for the new group and click *Confirm*.

The new group of Approval Administrators has been created. Approval Administrators can create new approval processes to set to platforms, portfolios, and products.

==== Creating Approval Approver Groups

The Approval Approver is a role that grants create and read permissions to users who will approve or deny requests generated when a {ProductName} user orders a product.

To create an Approval Approver group:

. Navigate to *Settings* ➔ *User Access*.
. Click *Create group*.
. Enter group *name* and set the *description*.
. Click *Next*.
. In the *Add members* modal, check each user to add to the group. Click *Next* when finished.
. Check *Approval Approvers* on the *Assign roles* modal.
. Review details for the new group and click *Confirm*.

The new group of Approval Approvers has been created..

==== Adding new users to existing Groups

The *Catalog Administrator* can add new users to existing groups. Once added, users will have the level of permissions associated with that group.

You can add users to a group in the *Groups* view in *User Access*.

. Navigate to *Settings* ➔ *User Access*.
. Click *Groups*.
. Select a group from the list.
. Click *Members* and then click *Add Member*.
. Check those users that appear in the modal that you wish to add to the group.
. Click *Add to group*.

A message will appear notifying you if the member was added successfully.

== Configuring Approval

{ProductName} supports group-based approval processes applied to portfolios, products, and platform inventories, providing the flexibility to include selected organizational groups in approving requests utilizing the *Approval* service.

Approval administrators can create approval groups and processes, view request details, approve or deny requests, and monitor the status of existing requests.


=== Approval requests

Approval requests are created when a user orders a product that has an approval policy attached to it. The order will initiate the approval processes assigned  to the product and users designated as approvers in each approval process receive an email notifying them that a request is ready. Approvers can then log in to Catalog and view the request to approve or deny it.

=== Approval processes

Approval processes consist of one or many groups required to approve a request. Each group is notified through the email address associated with that user when requests are created that require approval.

Approval administrators can design approval processes for a product to execute in serial or parallel when set to a portfolio. Simple serial and parallel approval processes are described below:

Set approval processes at the platform, portfolio, or product level. Approval processes set to a platform will apply to all products originating from that platform.

* *Serial process* - a product has multiple approval processes that must execute in a hierarchical sequence. If two approval processes are assigned to a product in serial, the approval group in the first approval process must approve the request before notification is sent to the second approval group. Priority of approval process execution is based on the sequence ID for that process.

* *Parallel process* -  a product has one approval process containing multiple groups. All groups are notified simultaneously when a request is created and the order is not granted until all groups approve it. Any group that declines the request ends the process and the user is notified the order has been denied.

[NOTE]
====
To create and list groups when creating Approval processes, the Approval Administrator must also have Organization Administrator privileges.
====

==== Creating an approval process

Creating an approval process designates specific groups required to approve product orders placed by {ProductName} users.

You can create an approval process from the *Approval processes* list view.

. Select *Approval* from the main navigation.
. Select the *Approval processes* tab.
. Click *Create approval process*.
. Provide an *Approval process name* and *Description* and click *Continue*.
. For *Set groups* click *Add a group*.
. Select a group from the drop-down menu.
. Click *Add another group* to continue to add groups. Click *Next* when finished.
. Review the new approval process details and click *Confirm*.

Implement an approval process against a platform, portfolio, or product.

=== Approval process sequences

Each approval process is assigned a sequence ID that determines the priority in which it executes when included in a serial approval process set to a portfolio. An approval process with the sequence ID of 1 will execute and notify groups in that approval process of a new request before a process with a sequence ID greater than 1.

==== Editing an approval process sequence

You can edit the sequence number for an approval process from the Approval process list view.

. Select *Approval* from the main navigation.
. Click the *Approval processes* tab.
. Select an approval process and click *more actions*.
. Select *Edit sequence* and enter the desired sequence number.
. Click *Save*.


The approval process list view will update to reflect the newly sequence.



== Working with platforms, portfolios, and products

This section demonstrates the basic workflows for platforms, portfolios, and products to get started using Automation Service Catalog.

We will demonstrate how to:

* connect to a source platform
* create portfolios
* add products from the source platform into the portfolio
* set approval processes for the portfolio
* share the portfolio with users


=== Adding Ansible Tower as a source platform

To begin, we will add an Ansible Tower instance as a source of products.

include::modules/proc_Adding_ansible_tower_source.adoc[]

=== Creating a portfolio and adding products to it

Now that we have a source for products, we can proceed to create an example portfolio and add a few products from our Ansible Tower to it.

include::modules/proc_Creating_portfolios.adoc[]

Our initial portfolio is empty, and we can start adding products from this empty state.

include::modules/proc_Add_products_from_platforms.adoc[]

=== Setting approval processes for the portfolio

We have now created a portfolio and added some products to it. Our next step is to set the approval process for the portfolio. Setting the approval process for our portfolio ensure that specific groups are designated to approve any orders placed by a user.

include::modules/proc_Assigning_approval_workflow.adoc[]

=== Sharing the portfolio with users

The portfolio is now ready to share with groups of users. These designated user groups can order products collected in the portfolio, and their orders are approved or denied using the approval process set for the portfolio.

include::modules/proc_Sharing_portfolios.adoc[]

Our portfolio is now accessible to the groups of users, who can order the products we collected in it.

== Conclusion

This onboarding guide demonstrated how to perform the basic actions for platforms, portfolios and products necessary to get started using Automation Service Catalog.

The workflows in this guide demonstrated how to:

* add entitlements to access Automation Service Catalog
* create the necessary groups and users
* connect to a source platform
* create portfolios
* add products from the source platform into the portfolio
* set approval processes for the portfolio
* share the portfolio with users

== Using the survey editor

When ordering a product in {ProductName}, users may be required to provide additional information to complete the request. This prompt is created by a survey associated with the product. Initially created and edited in Ansible Tower, Catalog Administrators and portfolio users with update permissions can edit the survey in {ProductName}. Once submitted and validated, the surveys pass user-submitted extra variables to the job or workflow template run on Ansible Tower on the execution of an order.

See _Surveys_ in the linkhttps://docs.ansible.com/ansible-tower/latest/html/userguide/index.html[Ansible Tower User Guide] to learn more creating and editing surveys for job templates.

Using the survey properties editor, you can:

* Set labels, helper text or placeholders to enhance the user experience of users providing information
* Further restrict existing validation parameters.
* Change validation messages.
* Hide, disable or set to read-only chosen fields in the survey.

=== Survey properties editor

Values for surveys are defined in Ansible Tower and the {ProductName} properties editor allows Catalog Administrators to restrict survey options, such as adjusting default values and removing items from drop-down menus.

Additionally, use the properties editor to hide, disable, or set a field to read only.

[NOTE]
====
Provide an initial value for any required field set to Hidden or Disabled. This includes `read only` fields.
====

=== Editing surveys

You can edit fields in the surveys from the product detail view. Edit each field individually using the Properties editor.

.Prerequisites
The product has an associated survey, created in Ansible Tower.

.Procedure
. Click *Products*.
. Locate the product and click on its title.
. Click  and select *Edit survey*.
. Select a field in the survey. The *Properties* editor will appear.
. Click *Properties* to view the elements to edit for that field.
. Select *Validation* to configure the validator types used to validate user input.
. Click *Save* when finished.

== Managing orders

Orders are created once a user successfully submits the request and provides any required validation. The approval process then governs the user’s order status.

=== Approving or denying requests

Once a user places an order it is created and available for review on the orders page.  Groups assigned the Approval Approver role can then approve or deny orders. Detailed information is provided for each request, with information on the ordered product and its associated requester and project. A stage transcript is also provided. Denied requests require justification and the approver must enter a reason.

To approve or deny a request:

. Navigate to *Approval*.
. Click the *Requests* tab and then click on a request to expand it to detailed view.
. Click *Approve* or *Deny*. Provide a *Reason* when denying a request.
. Click *Submit*.

=== Commenting on requests

Comment on requests as an administrator or approver. Comments are captured by the system and visible at each stage of approval.


To comment on a request:

. Navigate to *Approval*.
. Click the *Requests* tab and then click on a request..
. Click *Comment*.
. Add a comment and click *Submit*.

== Conclusion

In the previous sections of this onboarding guide we walked through the primary workflows necessary to get started using {ProductName}.


Following these workflows you have:

* Created the necessary groups and users to use both Catalog and Approval through the User access,
* Connected to a source platform,
* Created portfolios,
* Added products from the source platform into the portfolio,
* Created and set approval processes for the portfolio,
* Shared the portfolio with users,
* Approved or denied orders created by users,
* and comment on orders where necessary.
