// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Base the file name and the ID on the module title. For example:
* file name: proc-Creating-approval-approver-group.adoc
* ID: [id="proc-Creating-approval-approver-group_{context}"]
* Title: = Creating an Approval Approver Group

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
////

[id="proc-Creating-approval-approver-group_{context}"]

= Creating an Approval Approver Group

The Approval Approver is a role that approves or deny requests generated when a {ProductName} user orders a product.

To create and assign users to an *Approval Approver* group:

. Navigate to menu:Settings[User Access].
. Click btn:[Create group].
. Enter group *name* and set the *description*, then click btn:[Next].
. In the *Assign roles* modal, check *Approval Approvers*.
. Click btn:[Next].
. In the *Add members* modal, check each user to add to the group. Click btn:[Next] when finished.
. Review details for the new group and click btn:[Confirm].

You have now created and assigned users to an *Approval Approver* group.
