// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Base the file name and the ID on the module title. For example:
* file name: proc-Creating-catalog-administrator-group.adoc
* ID: [id="proc-Creating-catalog-administrator-group_{context}"]
* Title: = Creating a Catalog Administrator Group

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
////

[id="proc-Creating-catalog-administrator-group_{context}"]

= Creating a Catalog Administrator Group

The Catalog Administrator is a role that creates and manages order processes associated with portfolios and products.

To create and assign users to a *Catalog Administrator* group:

. Navigate to menu:Settings[User Access].
. Click btn:[Create group].
. Enter group *name* and set the *description*, then click btn:[Next].
. In the *Assign roles* modal, check *Catalog Administrator*.
. Click btn:[Next].
. In the *Add members* modal, check each user to add to the group. Click btn:[Next] when finished.
. Review details for the new group and click btn:[Confirm].

You have now created and assigned users to a *Catalog Administrator* group.
