// Module included in the following assemblies:
// assembly-order-process.adoc

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="proc_Create_order_process.adoc_{context}"]
= Create Order Process

As a catalog administrator, create order processes to allow you to execute your Ansible Tower playbooks before and after a product is ordered.

.Prerequisites

* To create an order process with your Ansible Tower playbooks, you must have an Ansible Tower cluster added as a source.

.Procedure

. Navigate to menu:Order Processes[].

. Click btn:[Create].

. Provide an order process name and description.

. From the drop-down menus, select actions that will occur before and after an order provision.

+
NOTE: The drop-down menus will display playbooks pulled from your Ansible Tower source. Only one Before and After action is supported for each order process.

. Review the new Order Process details, then click btn:[Create].
