// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Base the file name and the ID on the module title. For example:
* file name: proc-Adding-users-to-existing-group.adoc
* ID: [id="proc-Adding-users-to-existing-group._{context}"]
* Title: = Adding New Users to Existing Groups

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
////

[id="proc-Adding-users-to-existing-group_{context}"]

= Adding New Users to Existing Groups

The *Catalog Administrator* can add new users to existing groups. Once added, users will have the level of permissions associated with that group.

You can add users to a group in the *Groups* view in *User Access*.

. Navigate to menu:Settings[User Access].
. Click btn:[Groups].
. Select a group from the list.
. Click the *Members* tab, then click btn:[Add Member].
. Check the users that appear in the modal that you wish to add to the group.
. Click btn:[Add to group].

A message will appear notifying you if the member was added successfully.
