[id="assembly-intro-to-builder"]

= Introduction to {ExecEnvNameStart}

Using Ansible content that depends on non-default dependencies can be complicated because the packages must be installed on each node, interact with other software installed on the host system, and be kept in sync.

{ExecEnvNameStart} help simplify this process and can easily be created with {Builder}.

include::builder/con-about-ee.adoc[leveloffset=+1]
include::builder/con-why-ee.adoc[leveloffset=+2]
//include::builder/con-about-builder.adoc[leveloffset=+1]
//include::builder/con-why-builder.adoc[leveloffset=+2]

////
Consider adding a link to future Builder docs here
[role="_additional-resources"]
.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
