[id="proc-azure-provisioning-aap_{context}"]

= Provisioning {AAPonAzureName}

[role="_abstract"]
When you initiate the deployment of the {PlatformName} managed app from Azure marketplace, a form is displayed in the *Create Red Hat Ansible Automation Platform on Microsoft Azure* window.

Before you fill in the form, decide whether you want to create a public or private deployment of {AAPonAzureNameShort}:

* Public deployments allow ingress to the {AAPonAzureNameShort} user interfaces over the public internet. No configuration is required to access the application URLs.
* Private deployments are created in an isolated Azure VNet that blocks access from the public internet. To access {AAPonAzureNameShort} user interfaces, you must configure network peering and routing.

You create the network configuration for the {AAPonAzureNameShort} VNet when you initiate the deployment.
Refer to your network configuration plan before deploying the managed application. For information about planning your network configuration, see xref:con-aap-azure-network_aap-azure-intro[Networking configuration].

Complete the form to provision {PlatformName} infrastructure and resources into your Azure tenant.

. Enter values for your deployment in the following fields in the form:
  * *Subscription*: Select *Ansible on Clouds*.
  * *Resource Group*: Create or select a resource group where you want to deploy the managed application.
  * *Region*: The Azure region where the application will be deployed.
  * *Application Name*: A unique name for the managed application.
  * *Administrator Password*: Create an adminstrator password for your deployment.
+
The _Administrator Password_ must contain at least 8 characters, and must include uppercase letters, lowercase letters, and numbers.
  * *Confirm Administrator Password*: Confirm the _Administrator Password_.
  * *Access*: Choose whether your deployment will be public or private.
  * *Managed Resource Group*: A resource group for the managed application infrastructure.
+
Keep this resource group isolated from other resource groups, including the _Resource Group_ where you will deploy the managed application.
. Store the information that you entered in the form in a secure place. You will need to provide the _Administrator password_ to access {ControllerName} and private {HubName}.
. Click btn:[Next]
. Follow the steps in link:https://access.redhat.com/articles/6973251[Red Hat Ansible Automation Platform on Microsoft Azure VNet Preparation] to configure your network configuration.
. Click btn:[Review + Create].
. If the information you entered in the form is valid, the window displays *Validation Passed*.
. Select *I agree* to accept the Co-Admin Access Permissions terms and conditions.
. Click btn:[Create] to begin the provisioning process for the application.

The application will begin provisioning.

It may take 30 minutes or longer for the infrastructure and software to fully provision.

Once provisioning is complete, you can access and login to your new {PlatformNameShort} instance and launch {ControllerName} and {HubName}.
