[id="proc-azure-nw-private-deploy_{context}"]

= Private deployments

If you selected private access when deploying {AAPonAzureNameShort},
then the DNS record issued to the {AAPonAzureName} application points to a private address within the CIDR block selected when the managed application was deployed.
You must configure access to this address after you have created network peering.
// This address is not accessible from external sources

The configuration and access method that you choose to connect to {AAPonAzureNameShort} depends on how your organization manages Azure infrastructure.
Your Azure administrators must determine the right model for your organization and configure the setup for you.

The following are the most common options:

* xref:proc-azure-nw-private-deploy-az-hosted-vm_aap-azure-connecting-to-aap[Azure hosted virtual machine]
* xref:proc-azure-nw-private-deploy-vpn_aap-azure-connecting-to-aap[VPN]
* xref:proc-azure-nw-private-deploy-ssh-tunnel_aap-azure-connecting-to-aap[SSH tunnel]

