[id="proc-peer-vwan-hub-to-aap_{context}"]

= Peering a VWAN Hub to the {AAPonAzureNameShort} Network

Before peering, you must connect a hub network, and at least one spoke network, to the hub network of the Azure VWAN to which you intend to connect {AAPonAzureNameShort}.

.Prerequisites

* A pre-configured Azure VWAN.
* One or more of the following connections to the VWAN:
** A DMZ network that contains Azure virtual machines that users can remotely log into to access {AAPonAzureNameShort}.
** A DMZ network that contains an Azure virtual machine that local machines can connect to with SSH tunneling to access {AAPonAzureNameShort}.
** A VPN or Direct Connect service to your local network that routes traffic from local machines to {AAPonAzureNameShort}.

.Procedure

. Navigate to the *Virtual Network Connections* page for the VWAN that you want to peer with your {PlatformNameShort} instance.
. To create a connection between the VWAN hub and your {PlatformNameShort} instance, use the following settings:
** *Connection Name*: _<Ansible_Automation_Platform_connection_name>_
** *Hubs*: Select one or more VWAN hub networks that the managed application VNet will peer with.
** *Subscription*: Select the subscription where {AAPonAzureNameShort} has been deployed.
** *Resource group*: The managed resource group of the managed application. It is typically prefixed with “mrg-”.
** *Virtual network*: The VNet of the managed application. There is only one VNet in the managed resource group.
** *Propagate to none*: _No_
** *Associate Route Table*: Select the default route table or the appropriate route table that your organization has configured for VWAN. 
** *Propagate to Route Tables*: Select one or more default route tables or the appropriate route table that your organization has configured for VWAN. 
** *Propagate to labels*: Select labels if your organization uses them.
** *Static routes*: Do not complete this field.

When network peering completes, traffic routes to and from {AAPonAzureNameShort} though your VWAN hub network.

.Additional resources

* link:https://docs.microsoft.com/en-us/azure/virtual-wan/howto-connect-vnet-hub[Connect a virtual network to a Virtual WAN hub - portal] (Microsoft Azure Virtual WAN documentation)

