[id="con-optional-build-command-arguments"]

= Optional build command arguments

The `-t` flag will tag your {ExecEnvNameSing} image with a specific name. For example, the following command will build an image named `my_first_ee_image`:

====
----
$ ansible-builder build -t my_first_ee_image
----
====

[NOTE]
====
If you do not use `-t` with `build`, an image called `ansible-execution-env`` is created and loaded into the local container registry.
====

If you have multiple definition files, you can specify which one to use by utilizing the `-f` flag:

[[example1]]
====
----
$ ansible-builder build -f another-definition-file.yml -t another_ee_image
----
====

In <<example1, the previous example,>> {Builder} will use the specifications provided in the file `another-definition-file.yml` instead of the default `execution-environment.yml` to build an {ExecEnvNameSing} image named `another_ee_image`.

For other specifications and flags that are possible to use with the build command, enter `ansible-builder build --help` to see a list of additional options.
