[id="proc-customize-ee-image"]

= Customizing an existing {ExecEnvName} image

Ansible Controller ships with three default execution environments:

* `Ansible 2.9` - no collections are installed other than Controller modules
* `Minimal` - contains the latest Ansible 2.15 release along with Ansible Runner, but contains no collections or other additional content
* `EE Supported` - Minimal, plus all Red Hat-supported collections and dependencies

While these environments cover many automation use cases, you can add additional items to customize these containers for your specific needs. The following procedure adds the `kubernetes.core` collection to the `ee-minimal` default image:

.Procedure
. Log in to `registry.redhat.io` via Podman:
+
----
$ podman login -u="[username]" -p="[token/hash]" registry.redhat.io
----
. Ensure that you can pull the desired {ExecEnvNameSing} base image:
+
-----
podman pull registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
-----
+
. Configure your {Builder} files to specify the desired base image and any additional content to add to the new execution environment image.
.. For example, to add the link:https://galaxy.ansible.com/kubernetes/core[Kubernetes Core Collection from Galaxy] to the image, use the Galaxy entry:
+
====
----
collections:
  - kubernetes.core
----
====
.. For more information on definition files and their content, refer to <<assembly-definition-file-breakdown,to definition file breakdown section>>.
. In the {ExecEnvShort} definition file, specify the original `ee-minimal` container's URL and tag in the `EE_BASE_IMAGE` field. In doing so, your final `execution-environment.yml` file will look like the following:
+
.A customized `execution-environment.yml` file
[example]
====
----
version: 3

images:
  base_image: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - kubernetes.core
----
====
+
[NOTE]
====
Since this example uses the community version of `kubernetes.core` and not a certified collection from {HubName}, we do not need to create an `ansible.cfg` file or reference that in our definition file.
====
. Build the new {ExecEnvShort} image using the following command:
+
[subs=+quotes]
----
$ ansible-builder build -t _[username]_/_new-ee_
----
where `[username]` specifies your username, and `new-ee` specifies the name of your new container image.
+
[NOTE]
====
If you do not use `-t` with `build`, an image called `ansible-execution-env` is created and loaded into the local container registry.
====
+
* Use the `podman images` command to confirm that your new container image is in that list:
+
.Output of a `podman images` command with the image `new-ee`
====
----
REPOSITORY          TAG     IMAGE ID      CREATED        SIZE
localhost/new-ee    latest  f5509587efbb  3 minutes ago  769 MB
----
====
. Verify that the collection is installed:
+
-----
$ podman run [username]/new-ee ansible-doc -l kubernetes.core
-----
+
. Tag the image for use in your {HubName}:
+
-----
$ podman tag [username]/new-ee [automation-hub-IP-address]/[username]/new-ee
-----
+
. Log in to your {HubName} using Podman:
+
[NOTE]
=====
You must have `admin` or appropriate container repository permissions for {HubName} to push a container. See _Managing containers in private automation hub_ in the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform[Red Hat Ansible Automation Platform documentation] for more information.
=====
+
-----
$ podman login -u="[username]" -p="[token/hash]" [automation-hub-IP-address]
-----
+
. Push your image to the container registry in {HubName}:
+
----
$ podman push [automation-hub-IP-address]/[username]/new-ee
----
+
. Pull your new image into your {ControllerName} instance:
.. Navigate to {ControllerName}.
.. From the navigation panel, click menu:Administration[Execution Environments].
.. Click btn:[Add].
.. Enter the appropriate information then click btn:[Save] to pull in the new image.
+
[NOTE]
====
If your instance of {HubName} is password or token protected, ensure that you have the appropriate container registry credential set up.
====
