[id="proc-customize-ee-image"]

= Customizing an existing execution environment image

Ansible Controller ships with three default execution environments:

* `Ansible 2.9` - no collections are installed other than Controller modules
* `Minimal` - contains the latest Ansible 2.11 release along with Ansible Runner, but contains no collections or other additional content
* `EE Supported` - contains all Red Hat-supported content

While these environments cover many automation use cases, you can add additional items to customize these containers for your specific needs. The following procedure adds the `kubernetes.core` collection to the `ee-minimal` default image:

.Procedure
. Log in to `quay.io` via Podman:
+
----
$ podman login -u="[username]" -p="[token/hash]" quay.io
----
. Verify that you have access to pull the base image that you want to use.
.. For example, to pull a `ee-minimal` image, check that you have access to https://quay.io/repository/aap/ansible-automation-platform-20-ee-minimal-rhel8[this repository].
. Configure your {Builder} files to specify any additional content to add to the new {ExecEnvShort} image which is based off of `ee-minimal`.
.. For example, to add the https://galaxy.ansible.com/kubernetes/core[Kubernetes Core Collection from Galaxy] to the image, fill out the `requirements.yml` file as such:
+
====
----
---
collections:
  - kubernetes.core
----
====
.. For more information on definition files and their content, refer to <<assembly-definition-file-breakdown,to definition file breakdown section>>.
. In the {ExecEnvShort} definition file, specify the filepath to the original `ee-minimal` container via the `EE_BASE_IMAGE` field. In doing so, your final `execution-environment.yml` file will look like the following:
+
.A customized `execution-environment.yml` file
[example]
====
----
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: ‘quay.io/aap/ansible-automation-platform-20-ee-minimal-rhel8’

dependencies:
  galaxy: requirements.yml
----
====
+
NOTE: Since this example uses the community version of `kubernetes.core` and not a certified collection from {HubName}, we do not need to create an `ansible.cfg` nor reference that in our definition file.
. Build the new {ExecEnvShort} image using the following command:
+
[subs=+quotes]
----
$ ansible-builder build -t quay.io/_[username]_/_new-ee_
----
where `[username]` specifies your username, and `new-ee` specifies the name of your new container image.
.. Use the `podman images` command to confirm that your new container image is indeed in that list:
+
.Output of a `podman images` command with the image `new-ee`
====
----
REPOSITORY          TAG     IMAGE ID      CREATED        SIZE
localhost/new-ee    latest  f5509587efbb  3 minutes ago  769 MB
----
====
. Verify your newly-created {ExecEnvShort} image via Ansible Navigator
. Push your image to the container registry {HubName}:
+
----
$ podman push quay.io/[username]/new-ee
----
. Pull your new image in your automation controller instance:
.. Navigate to automation controller
.. From the side-navigational bar, click *Administration* > *Execution Environments*.
.. Click *Add*.
.. Enter the appropriate information then hit *Save* to pull in the new image.
+
NOTE: if your instance of {HubName} is password or token protected, ensure that you have the appropriate container registry credential set up.
