// This is the release notes for AAP 2.3, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[aap-2.3-intro]]
= Ansible Automation Platform

Red Hat Ansible Automation Platform simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles. It works across multiple IT domains including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, Red Hat Ansible Automation Platform provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

.Enhancements

* Fixed a race condition where the UI would not properly populate upon launch.
* Fixed an issue where puppet managed files are not handled properly by the set-up script.
* Fixed an issue where self-signed certs were being recreated on every run of `setup.sh`.
* Added an option for execution environment images to be pulled from Hub only.
* Fixed an issue where the bundled installer was failing when DNF was trying to fetch gpg keys remotely.
* Upgraded pulp_installer to 3.20.5+ .
* Implemented sidecar documentation to allow easy documentation of filter and test plugins, as well as documentation for non-python modules without requiring a .py file for documentation.
* Migrated display for `stdout` and `stderr` from the display class to proxy over the queue for dispatch in the main process to improve reliability of displaying information to the terminal.
* Moved handler processing into the configured strategy, so that handlers operate within the configured strategy, instead of using a non-configurable linear like execution of handlers.
* Updated internal FieldAttribute classes to act as Python data descriptors to reduce code complexity and use of metaclasses.
* Fixed an issue when ansible-runner was not properly removed from hybrid nodes when upgrading to Ansible Automation Platform 2.2.

.Technology preview features

Some features in this release are currently classified as Technology Preview. Technology Preview features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. Please note that Red Hat does not recommend using technology preview features for production, and Red Hat SLAs do not support technology preview functions.

The following are the technology preview features:

* Added the ability to use external execution nodes when running AAP as a managed service in Azure.
* Added the ability to use external execution nodes when running the AAP Operator in Openshift.
//[DCD removed following per PG see AAP-7858]
//* Simplified addition and removal of execution node capacity. In the technology preview, requirements for using platform installer to add or remove execution nodes have been removed.
//* Enhancements for job utilization on multiple execution nodes. A more efficient task manager can make efficient use of execution nodes, increasing your automation capacity.

Other noteworthy developer tooling updates include the following:

* Added new pre-flight checks to ansible-core CLI start up to enforce assumptions made about handling display and text encoding.
* Added official support for Python 3.11 to ansible-core CLIs and target node execution.
* Dropped Python 3.8 support for ansible-core CLIs and controller side code.
* Added lint profile support for content pipelines.

[role="_additional-resources"]
.Additional resources

* For information regarding execution node enhancements on Openshift deployments, see link:https://docs.ansible.com/automation-controller/latest/html/administration/instances.html[Managing Capacity With Instances].
