[[tower-382-intro]]
= Ansible Tower 3.8.2

.Bug fixes and enhancements

* Upgraded to the latest oVirt inventory plugin to resolve a number of inventory syncing issues that can occur on RHEL7
* Upgraded to the latest theforeman.foreman inventory plugin to resolve a few bugs and performance regressions
* Upgraded to a more recent version of Django to address link:https://access.redhat.com/security/cve/cve-2021-3281[CVE-2021-3281]
* Upgraded to a more recent version of autobahn to address link:https://access.redhat.com/security/cve/cve-2020-35678[CVE-2020-35678]
* Fixed a security issue that allowed a malicious playbook author to elevate to the awx user from outside the isolated environment link:https://access.redhat.com/security/cve/cve-2021-20253[CVE-2021-20253]
* Fixed several issues related to how Tower rotates its log files
* Fixed the installer to no longer prevent Tower from installing on RHEL8 with certain non-en_US.UTF-8 locales
* Fixed unanticipated delays in certain playbook output
* Fixed job runs to no longer fail for playbooks that print certain types of raw binary data
* Fixed the generation of unnecessary records in the Activity Stream when Ansible Automation data is collected
* Fixed PostgreSQL backups to no longer fail when a non-default PostgreSQL username is specified
* Fixed access to encrypted Tower settings to prevent intermittent failures that caused failed job launches
* Fixed unexpected failures on certain long-running jobs running on isolated nodes
* Deprecated the global `/api/v2/job_events/` endpoint, which will be removed in a future release

See https://docs.ansible.com/ansible-tower/latest/html/release-notes/index.html[Ansible Tower Release Notes v3.8.2] for a full list of new features and enhancements.
