[id="scaffolding-playbook-project"]

= Scaffolding a playbook project

[role="_abstract"]

The following steps describe the process for scaffolding a new playbook project with the Ansible {VSCode} extension.

. Prerequisites

* You have installed {ToolsName}.
* You have installed and opened the Ansible {VSCode} extension. 
* You have set up and activated a Python virtual environment in {VSCode}.

.Procedure

. Click the Ansible icon in the {VSCode} activity bar to open the Ansible extension.
. In the *ANSIBLE CREATOR* section of the Ansible extension, click btn:[Get Started].
. Check that the system requirements are met.
All requirements that are satisfied have green ticks next to them.
You can check the versions of your installed Ansible components by running `rpm -aq | grep ansible` in a terminal.
. Scroll past the system requirements and click btn:[Create Ansible content].
. Click btn:[Create] to begin creating your project.

----
ansible-project/
 |── .devcontainer/
 |    └── docker/
 |        └── devcontainer.json
 |    └── podman/
 |        └── devcontainer.json
 |    └── devcontainer.json
 |── .github/
 |    └── workflows/
 |        └── tests.yml
 |    └── ansible-code-bot.yml
 |── .vscode/
 |    └── extensions.json
 |── collections/
 |   └── requirements.yml
 |   └── ansible_collections/
 |       └── project_org/
 |           └── project_repo/
 |               └── README.md
 |               └── roles/sample_role/
 |                         └── README.md
 |                         └── tasks/main.yml
 |── inventory/
 |   └── groups_vars/
 |   └── host_vars/
 |   └── hosts.yml
 |── ansible-navigator.yml
 |── ansible.cfg
 |── README.md
 |── site.yml
----

// == Navigating the playbook project directory
