[id="devtools-install_context"]

= Installing {ToolsName} from an RPM package

[role="_abstract"]

{ToolsName} is bundled in the {PlatformNameShort} RPM (Red Hat Package Manager) package.
// As an {PlatformNameShort} administrator, you can install {ToolsName} when you are installing {PlatformNameShort}.
Refer to the {PlatformNameShort} guide for more information on installing {PlatformNameShort}.

.Prerequisites
* You have installed RHEL
* You have registered your system with Red Hat Subscription Manager.

.Procedure

. Run the following command to check whether Simple Content Access (SCA) is enabled:
+
[source,shell]
----
$ su subscription-manager status
----
+
If Simple Content Access is enabled, the output contains the following message:
+
----
Content Access Mode is set to Simple Content Access.
----
. If Simple Content Access is not enabled, attach the Red Hat Ansible Automation Platform SKU: 
+
[source,shell]
----
$ subscription-manager attach --pool=<sku-pool-id>
----
. Install {Toolsname} with the following command:
+
[source,shell]
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms ansible-dev-tools
----
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms ansible-dev-tools
----

.Verification:

Verify that the {AnsibleDevTools} components have been installed:
[source,shell]
----
$ rpm -aq | grep ansible
----
The output displays the Ansible packages that are installed:
----
ansible-sign-0.1.1-2.el9ap.noarch
ansible-creator-24.4.1-1.el9ap.noarch
python3.11-ansible-runner-2.4.0-0.1.20240412.git764790f.el9ap.noarch
ansible-runner-2.4.0-0.1.20240412.git764790f.el9ap.noarch
ansible-builder-3.1.0-0.2.20240413.git167ed5c.el9ap.noarch
ansible-dev-environment-24.1.0-2.el9ap.noarch
ansible-core-2.16.6-0.1.20240413.gite636132.el9ap.noarch
python3.11-ansible-compat-4.1.11-2.el9ap.noarch
python3.11-pytest-ansible-24.1.2-1.el9ap.noarch
ansible-lint-6.14.3-4.el9ap.noarch
ansible-navigator-3.4.1-2.el9ap.noarch
python3.11-tox-ansible-24.2.0-1.el9ap.noarch
ansible-dev-tools-2.5-2.el9ap.noarch
----


On successful installation, you can view the help documentation for ansible-creator:

----
$ ansible-creator --help

usage: ansible-creator [-h] [--version] {init} ...

Tool to scaffold Ansible Content. Get started by looking at the help text.

options:
  -h, --help  show this help message and exit
  --version   Print ansible-creator version and exit.

Commands:
  {init}      The subcommand to invoke.
    init      Initialize an Ansible Collection.
----
