ifdef::context[:parent-context: {context}]

[id="hardening-aap"]
= Hardening {PlatformNameShort}

:context: hardening-aap

[role="_abstract"]
This guide takes a practical approach to hardening the {PlatformNameShort} security posture, starting with the planning and architecture phase of deployment and then covering specific guidance for the installation phase.  As this guide specifically covers {PlatformNameShort} running on Red Hat Enterprise Linux (RHEL), hardening guidance for RHEL will be covered where it affects the automation platform components.

//
[role="_additional-resources"]
.Additional resources
* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].