
ifdef::context[:parent-context: {context}]



[id="managing-container-registry"]
= Managing your private {HubName} container registry

:context: managing-container-registry

[role="_abstract"]
Manage container image repositories in your {PlatfomNameShort} infrastructure using the {HubName} container registry. {HubNameStart} provides features to govern who can access individual container repositories, change tags on images, view activity and image layers, and provide additional information related to each container repository.



////
The following include statements pull in the module files that comprise the assembly. Include any combination of concept, procedure, or reference modules required to cover the user story. You can also include other assemblies.
////

include::automation-hub/con-container-registry.adoc[leveloffset=+1]


[role="_additional-resources"]
==  Next steps

* Push a container image to the {HubName} container registry.
* Create a group with access to the container repository in the registry.
* Add the new group to the container repository.
* Add a README to the container repository to provide users with information and relevant links.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
