

ifdef::context[:parent-context: {context}]

[id="populate-container-registry"]
= Populating your {PrivateHubName} container registry


:context: populate-container-registry


[role="_abstract"]
By default, {PrivateHubName} does not include container images. 
To populate your container registry, you must push a container image to it. 

You must follow a specific workflow to populate your {PrivateHubName} container registry: 

* Pull images from the Red Hat Ecosystem Catalog (registry.redhat.io)
* Tag them
* Push them to your {PrivateHubName} container registry

[IMPORTANT]
====
Image manifests and filesystem blobs were both originally served directly from `registry.redhat.io` and `registry.access.redhat.com`. 
As of 1 May 2023, filesystem blobs are served from `quay.io` instead. 

* Ensure that the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/ref-network-ports-protocols_planning[Network ports and protocols] listed in _Table 5.10. Execution Environments (EE)_ are available to avoid problems pulling container images.

Make this change to any firewall configuration that specifically enables outbound connections to `registry.redhat.io` or `registry.access.redhat.com`.

Use the hostnames instead of IP addresses when configuring firewall rules. 

After making this change you can continue to pull images from `registry.redhat.io` and `registry.access.redhat.com`. You do not require a `quay.io` login, or need to interact with the `quay.io` registry directly in any way to continue pulling Red Hat container images.
====

include::hub/proc-obtain-images.adoc[leveloffset=+1]
include::hub/proc-tag-pulled-image.adoc[leveloffset=+1]
include::hub/proc-push-container.adoc[leveloffset=+1]



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
