[id="assembly-high-availability-hub-selinux"]

= Setting up a high availability automation hub on SELinux

To set up a high availability (HA) deployment of {HubName} on SELinux, you will need to create two mount points, one for `/var/lib/pulp` and one for `/var/lib/pulp/pulpcore_static`, before you run the installer.

.Pre-installation procedure
. Create a mount point at `/var/lib/pulp`:
+
----
$ mkdir -p /var/lib/pulp/
----
. Open `/etc/fstab` using a text editor, then add the following values:
+
----
srv_rhel8:/data /var/lib/pulp nfs defaults,_netdev 0 0
srv_rhel8:/data/pulpcore_static /var/lib/pulp/pulpcore_static nfs defaults,_netdev,context="system_u:object_r:httpd_sys_content_rw_t:s0" 0 0
----
. Run the mount command:
+
----
$ mount -a
----
. With the mount points set up, run the {PlatformNameShort} installer:
+
----
$ setup.sh -- -b --become-user root
----

Once the installation is complete, unmount the two mount points then add the appropriate SELinux contexts.

.Post-installation procedure
. Shut down the Pulp service:
+
----
$ systemctl stop pulpcore.service
----
. Unmount `/var/lib/pulp/`:
+
----
$ umount /var/lib/pulp
----
. Open `/etc/fstab` using a text editor, then add the following context to the `/var/lib/pulp/` mount point:
+
----
srv_rhel8:/data /var/lib/pulp nfs defaults,_netdev,nosharecache,context="system_u:object_r:pulpcore_var_lib_t:s0" 0 0
----
. Run the mount command:
+
----
$ mount -a
----
. Edit `pulpcore.service` using `systemctl`:
+
----
$ systemctl edit pulpcore.service
----
. Add the following entry to `pulpcore.service` to ensure that {HubName} services only starts after starting the network and mounting the remote mount points:
+
----
[Unit]
After=network.target var-lib-pulp.mount
----
. Enable `remote-fs.target`:
+
----
$ systemctl enable remote-fs.target
----
. Reboot the system:
+
----
$ reboot
----

.Troubleshooting
Currently, a bug in the pulpcore SELinux policies can cause the token authentication public/private keys in `etc/pulp/certs/` to not have the proper SELinux labels, causing the pulp process to fail. When this occurs, run the following command to temporarily attach the proper labels:
----
chcon system_u:object_r:pulpcore_etc_t:s0 /etc/pulp/certs/token_{private,public}_key.pem
----
NOTE: Repeat this command whenever you relabel your system to reattach the proper SELiux labels.

.Additional Resources
* See the link:https://docs.pulpproject.org/en/2.16/user-guide/scaling.html#selinux-requirements[SELinux Requirements on the Pulp Project documentation] for a list of SELinux contexts.
