[id="assembly-working-with-namespaces"]

= Using namespaces to manage collections in {HubName}

Namespaces are unique locations in {HubName} to which you can upload and publish content collections. Access to namespaces in {HubName} is governed by groups with permission to manage the content and related information that appears there.

You can use namespaces in {HubName} to organize collections developed within your organization for internal distribution and use.

If you are working with namespaces, you must have a group that has permissions to create, edit and upload collections to namespaces. Collections uploaded to a namespace require administrative approval before you can publish them and make them available for use.

include::hub/proc-create-content-developers.adoc[leveloffset=+1]

include::hub/proc-create-namespace.adoc[leveloffset=+1]

include::hub/proc-edit-namespace.adoc[leveloffset=+1]

When you create a namespace, groups with permissions to upload to it can start adding their collections for approval. Collections in the namespace appear in the *Published* repository after approval.

include::hub/proc-uploading-collections.adoc[leveloffset=+1]

include::hub/proc-review-collection-imports.adoc[leveloffset=+1]

include::hub/proc-delete-namespace.adoc[leveloffset=+1]
