[id="assembly-faq"]
== Frequently asked questions about {CertifiedCon}

The following is a list of Frequently Asked Questions for the {PlatformName} Certification Program. 
If you have any questions regarding the items below, please email ansiblepartners@redhat.com.


=== Why certify Ansible collections?

The Ansible certification program enables a shared statement of support for {certifiedCon} between Red Hat and the ecosystem partner. 
An end customer, experiencing trouble with Ansible and certified partner content, can open a support ticket (request for information, a problem, etc.) with Red Hat and expect the ticket will be resolved by Red Hat and the ecosystem partner. 

Red Hat offers go-to-market benefits for Certified Partners to grow market awareness, demand generation and collaborative selling.

Red Hat {CertifiedName} are distributed through {HubNameMain} (subscription required), a centralized repository for jointly supported Ansible Content. 
As a certified partner, publishing Collections to {HubNameMain} provides end customers the power to manage how trusted automation content is used in their production environment with a well known support life cycle.

For more information about getting started with certifying a solution, please refer to https://www.ansible.com/partners for details.

//As a partner, publishing Collections to the Automation Hub gives your end customer organizations the power to manage how trusted automation content is used in the customer environment.

=== How do I get a collection certified?

Refer to our partner website http://www.ansible.com/partners for the Ansible certification policy guide to understand how to certify your collection.

=== What’s the difference between {Galaxy} and {HubNameMain}

Collections published to {Galaxy} are the latest content published by the Ansible community and have no joint support claims associated. 
{Galaxy} is the recommended frontend “directory” for the Ansible community accessing all content.

Collections published to {HubNameMain} are targeted for joint customers of Red Hat and selected partners. 
Customers need an Ansible subscription to access and download collections on {HubNameMain}. 
A certified collection means that Red Hat and partners have a strategic relationship in place and are ready to support joint customers, and may have had additional testing and validation done against them.

=== How do I request a namespace on Galaxy?

Send an email to ansiblepartners@redhat.com after you request a namespace through an {Galaxy} GitHub Issue. 
You must provide us with the GitHub username which you have used to sign up on {Galaxy}, and must log in at least once in order for the system to validate. 
Once users are added as administrators of the namespace, then additional administrators can be added by the self-serve process.

=== Are there any restrictions for Galaxy namespace naming?

Collection namespaces must follow python module name convention. 
This means cCollections should have short, all lowercase names. 
Underscores may be used in the collection name if it improves readability.

=== Are there any naming recommendations for cCollection naming?

A general suggestion is to create a collection with `company_name.product` format. 
This way multiple products may have different collections under the company namespace.

=== How do I get a namespace on {HubNameMain}

By default namespaces used on {Galaxy} are also utilized on {HubNameMain} by the Ansible partner team. 
For any queries and clarifications please contact ansiblepartners@redhat.com.

=== How do I run sanity tests on my collection?

Ansible sanity tests are made up of scripts and tools used to perform static code analysis. 
The primary purpose of these tests is to enforce Ansible coding standards and requirements. 
Ansible collections must be in a very specific path, such as the following:

[options="nowrap" subs="=quotes, attributes"]
----
{...}/ansible_collections/{namespace}/{collection}/
----

You must ensure your collection is in that specific path—with an empty directory named ansible_collections, then a directory for the namespace, and finally a directory for the collection itself.

=== Does Galaxy house the source code for my Collection?

No, Galaxy does not house the source for the collections. 
The actual collection source must be housed outside of {Galaxy}, for example GitHub. 
{Galaxy} contains the collection build tarball to publish the collection. 
You can include the link to the source for community users in the `galaxy.yml` file contained in the collection. 
This provides information to users of where they should go if they want to contribute to the cllection or even file issues against it.

=== How does the joint support agreement on certified collections work?

If a customer raises an issue with the Red Hat support team about on a certified collection, Red Hat support will triage the issue and check if the problem exists within Ansible or Ansible usage and they will also check if the issue is with a certified collection. If there is a problem with the certified collection, support teams will transfer the issue to the vendor owner of the certified collection through an agreed upon tool such as TSANet.

---------
=== How does the certification process work?
Are there any restrictions for Galaxy namespace naming?


Please visit Ansible.com/partners and review the Ansible certification policy guide to learn more about the certification process.

=== Why should I publish my collection to Automation Hub?

Collections present in Automation Hub are meant to be for joint customers of Red Hat and partners. Customers will need a subscription to download these collections and the collections present on Automation Hub will be marked as Certified. Certified Collection means that Red Hat and partners have a strategic relationship in place and are ready to support joint customers.

=== What value do my customers get after downloading a collection from Automation Hub?

Any customer facing a collection-related issue can raise a support case to Red Hat and our support teams will then triage the issue. If the problem is related to the certified collection, the issue is forwarded to the partner support teams or affiliated contact. If partners do not meet the obligation, Red Hat keeps the right to revoke that certification at any time and remove the collection from Automation Hub.

=== How does certification affect free and enterprise versions of your software?

Collections are version agnostic and work with free or enterprise software. Support for certified collections will determine where the issue exists only within Ansible. Once an Ansible issue is triaged, a vendor can then determine if the customer is using the community or enterprise version and decide how to move forward with the issue.

=== How do I migrate existing modules and plugins to collections?

Please review _Developing Collections_ in the Ansible Developer guide to learn about developing a collection.

=== How do I test my collection?

Please see _Using Collections_ in the Ansible documentation to learn more about testing collections.

=== Can I create and certify a collection containing only roles?

Yes, but a collection containing only roles is not presently supported or certified for publication to Automation Hub.

=== How will my collection documentation be visible on Automation hub

Collection documentation is visible on Automation Hub. Each collection includes a documentation tab where user can review included documentation.
