[id="assembly-faq"]
== Frequently asked questions about certification

=== Why certify Ansible collections?

The Ansible Certification Program is a shared statement of support for Certified Ansible collections between Red Hat and the ecosystem partner. An end customer, experiencing trouble with Ansible and certified partner content, can open a support ticket with Red Hat and expect the ticket will be resolved by Red Hat and the ecosystem partner. As a partner, publishing Collections to the Automation Hub gives your end customer organizations the power to manage how trusted automation content is used in the customer environment.

=== How does the certification process work?

Please visit Ansible.com/partners and review the Ansible certification policy guide to learn more about the certification process.

=== Why should I publish my collection to Automation Hub?

Collections present in Automation Hub are meant to be for joint customers of Red Hat and partners. Customers will need a subscription to download these collections and the collections present on Automation Hub will be marked as Certified. Certified Collection means that Red Hat and partners have a strategic relationship in place and are ready to support joint customers.

=== What value do my customers get after downloading a collection from Automation Hub?

Any customer facing a collection-related issue can raise a support case to Red Hat and our support teams will then triage the issue. If the problem is related to the certified collection, the issue is forwarded to the partner support teams or affiliated contact. If partners do not meet the obligation, Red Hat keeps the right to revoke that certification at any time and remove the collection from Automation Hub.

=== How does certification affect free and enterprise versions of your software?

Collections are version agnostic and work with free or enterprise software. Support for certified collections will determine where the issue exists only within Ansible. Once an Ansible issue is triaged, a vendor can then determine if the customer is using the community or enterprise version and decide how to move forward with the issue.

=== How do I migrate existing modules and plugins to collections?

Please review _Developing Collections_ in the Ansible Developer guide to learn about developing a collection.

=== How do I test my collection?

Please see _Using Collections_ in the Ansible documentation to learn more about testing collections.

=== Can I create and certify a collection containing only roles?

Yes, but a collection containing only roles is not presently supported or certified for publication to Automation Hub.

=== How will my collection documentation be visible on Automation hub

Collection documentation is visible on Automation Hub. Each collection includes a documentation tab where user can review included documentation.
