////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]

////
 Base the file name and the ID on the assembly title. For example:
* file name: assembly-my-user-story.adoc
* ID: [id="assembly-my-user-story_{context}"]
* Title: = My user story

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken. Include {context} in the ID so the assembly can be reused.
////

[id="pulling-images-container-repository"]
= Pulling images from a container repository


:context: pulling-images-container-repository



[role="_abstract"]
Pull images from the {HubName} container registry to make a copy to your local machine. {HubNameStart} provides the `podman pull` command for each `latest` image in the container repository. You can copy and paste this command into your terminal, or use `podman pull` to copy an image based on an image tag.

== Prerequisites

* You have permission to view and pull from a private container repository.

include::automation-hub/proc-pull-image.adoc[leveloffset=+1]



[role="_additional-resources"]
== Additional resources

* See the link:http://docs.podman.io/en/latest/index.html[Podman documentation] for options to use when pulling images.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
