[id="assembly-synclists"]
= Managing Ansible Content Collections in {HubName}

[IMPORTANT]
====
As of the 2.4 release you can still synchronize content, but synclists are deprecated, and will be removed in a future version.

From Ansible Automation Platform 2.4 a private automation hub administrator can go to the rh-certified remote and upload a manually-created requirements file.

Remotes are configurations that allow you to synchronize content to your custom repositories from an external collection source.
====

You can use {HubNameMain} to distribute the relevant Red Hat Certified collections content to your users by creating synclists or a requirements file. For more information about using requirements files, see link:https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#install-multiple-collections-with-a-requirements-file[Install multiple collections with a requirements file] in the {Galaxy} User Guide.

include::automation-hub/con-rh-certified-synclist.adoc[leveloffset=+1]

include::automation-hub/proc-create-synclist.adoc[leveloffset=+1]
