ifdef::context[:parent-context: {context}]

[id="delete-container"]
= Deleting a container repository

:context: delete-container

[role="_abstract"]
Delete a container repository from your local {HubName} to manage your disk space. 
You can delete repositories from the {PlatformName} interface in the *Container Repository* list view.

.Prerequisites
* You have permissions to manage repositories.

.Procedure
. Navigate to {HubName}.
. From the navigation panel, select menu:Execution Environments[Execution Environments].
. On the container repository that you want to delete, click the btn:[More Actions] icon *{MoreActionsIcon}*, and click btn:[Delete].
. When the confirmation message is displayed, click the checkbox and click btn:[Delete].

.Verification
* Return to the *Execution Environments* list view. 
If the container repository has been successfully deleted, the container repository is no longer on the list.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
