ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="ppah-installation_{context}"]

= Private Partner Automation Hub Installation Guide

:context: ppah-installation

Red Hat Ansible private partner automation hub enables Red Hat partners to curate, host, and serve their own Ansible content to their consultants, customers, or users. Private partner automation hub gives partners the ability to serve content to multiple different parties simultaneously using comprehensive role-based access controls. This offering is designed to help partners expedite their solutions using Ansible's proven automation technology.

This guide contains a collection of Ansible playbooks that install a containerized private partner automation hub. You can choose from two types of installation based on your organization's needs:

* a xref:ppah-install-dev[development option]
* a xref:ppah-install-ha[production option]

.Prerequisites

* A RHEL 9.2 based host. A minimal OS base install is recommended.
* A non-root user for the RHEL host, with sudo or other Ansible supported privilege escalation (sudo recommended). This user is responsible for the installation of the private partner automation hub.
* It is recommended to set up an *SSH public key authentication* for the non-root user. For guidelines on setting up an SSH public key authentication for the non-root user, see link:https://access.redhat.com/solutions/4110681[How to configure SSH public key authentication for passwordless login].
* SSH keys are only required when installing on remote hosts. If doing a self contained local VM based installation, you can use *ansible_connection: local*, which does not require SSH.

== System requirements

Your system must meet the following minimum system requirements to install and run private partner automation hub. 

[cols=2]
|======================
| Memory     | 8Gb RAM at minimum
| CPU        | 2 CPU at minimum   
| Disk space | 60Gb, with a minimum of 40Gb dedicated to `/var` for collection storage    
| Disk IOPs  | 1500    
|======================

include::hub/proc_ppah-prepare-rhel-host.adoc[leveloffset=+1]
include::hub/proc_ppah-install-ansible-core.adoc[leveloffset=+1]
include::hub/proc_ppah-download-aap.adoc[leveloffset=+1]
include::hub/proc_ppah-online-offline-install.adoc[leveloffset=+1]
include::hub/proc_ppah-install-dev.adoc[leveloffset=+1]
include::hub/proc_ppah-install-ha.adoc[leveloffset=+1]
//include::hub/ref_ppah-config.adoc[leveloffset=+1]
include::hub/ref_ppah-access.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]

