[id="assembly-working-with-namespaces"]

= Using namespaces to manage collections in Automation Hub

You can use namespaces in {HubName} to organize collections developed within your organization for internal distribution and use.

Working with namespaces requires a group that has permissions to create, edit and upload collections to namespaces. Collections uploaded to a namespace may require administrative approval before you can publish them and make them available for use. See https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/1.0/html/managing_user_access_in_automation_hub/index[Managing user access in Automation Hub] for more information on groups and permissions to determine how to configure Automation Hub for your content curators and developers.

include::automation-hub/con-namespaces.adoc[leveloffset=+1]

include::automation-hub/proc-create-content-developers.adoc[leveloffset=+1]

include::automation-hub/proc-create-namespace.adoc[leveloffset=+1]

include::automation-hub/proc-edit-namespace.adoc[leveloffset=+1]

Once a namespace is created, groups with permissions to upload to it can start adding their collections for approval. Upon approval, collections in the namespace will appear in the *Published* repository.

include::automation-hub/proc-uploading-collections.adoc[leveloffset=+1]

include::automation-hub/proc-review-collection-imports.adoc[leveloffset=+1]

include::automation-hub/proc-delete-namespace.adoc[leveloffset=+1]
