
ifdef::context[:parent-context: {context}]



[id="managing-container-registry"]
= Manage your {PrivateHubName} container registry

:context: managing-container-registry

[role="_abstract"]
Manage container image repositories in your {PlatformNameShort} infrastructure by using the {HubName} container registry. 
You can perform the following tasks with {HubNameStart}:

* Control who can access individual container repositories
* Change tags on images
* View activity and image layers 
* Provide additional information related to each container repository



////
The following include statements pull in the module files that comprise the assembly. Include any combination of concept, procedure, or reference modules required to cover the user story. You can also include other assemblies.
////

include::hub/con-container-registry.adoc[leveloffset=+1]


.Next steps

* Push a container image to the {HubName} container registry.
* Create a group with access to the container repository in the registry.
* Add the new group to the container repository.
* Add a README to the container repository to provide users with information and relevant links.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
