
:imagesdir: images
= Managing Red Hat Certified, validated, and Ansible Galaxy content in automation hub
:numbered:
:experimental:

include::attributes/attributes.adoc[]

{CertifiedColl} is included in your subscription to {PlatformName}. Red Hat Ansible content inclues two types of content: {CertifiedName} and {Valid}.
Using {HubNameMain}, you can access and curate a unique set of collections from all forms of Ansible content.

Ansible validated collections are available in your {PrivateHubName} through the Platform Installer.
When you download {PlatformName} with the bundled installer, validated content is pre-populated into the {PrivateHubName} by default, but only if you enable the {PrivateHubName} as part of the inventory.

If you are not using the bundle installer, a Red Hat supplied Ansible playbook can be used to install validated content.
For further information, see xref:assembly-validated-content[{Valid}]

You can  update these collections manually by downloading their packages.

include::aap-common/making-open-source-more-inclusive.adoc[leveloffset=+1]
include::aap-common/providing-direct-documentation-feedback.adoc[leveloffset=+1]

include::hub/assembly-synclists.adoc[leveloffset=+1]

include::hub/assembly-syncing-to-cloud-repo.adoc[leveloffset=+1]

include::hub/assembly-private-automation-hub.adoc[leveloffset=+1]

include::hub/assembly-collections-and-content-signing-in-pah.adoc[leveloffset=+1]

include::hub/assembly-faq.adoc[leveloffset=+1]

include::hub/assembly-validated-content.adoc[leveloffset=+1]

== Conclusion

When you complete all of the previous procedures, you will have:

* created a synclist for {CertifiedCon} content.
* synchronized that content to your {PrivateHubName}.
* designated community collections from {Galaxy} to distribute to your users.
* configured content signing on {PrivateHubName}.
* signed and approved collections for your organization's specific needs.
* configured Ansible-Galaxy CLI to verify collections before signing them.

Users can now view and download collections content from your {PrivateHubName}.
