:imagesdir: images
= Managing Red Hat Ansible Content Collections and Ansible Galaxy collections in automation hub
:numbered:
:experimental:

include::attributes/attributes.adoc[]

Included with a subscription to {PlatformName}, {CertifiedColl} feature {CertifiedName} and {Valid}, as well as {Galaxy} content from the community. 
Using {HubNameMain}, your organization can access and curate a unique set of collections from all forms of Ansible content. 

You can also synchronize {HubNameMain} to create a custom list of collections from either {CertifiedCon}, {valid}, or {Galaxy} community content. 

Initially, Ansible validated collections will only be available in your {PrivateHubName}
These collections can be preloaded into {PrivateHubName} using the installer and can be updated manually by downloading their packages.

include::aap-common/making-open-source-more-inclusive.adoc[leveloffset=+1]

include::hub/assembly-synclists.adoc[leveloffset=+1]

include::hub/assembly-syncing-to-cloud-repo.adoc[leveloffset=+1]

include::hub/assembly-private-automation-hub.adoc[leveloffset=+1]

include::hub/assembly-collections-and-content-signing-in-pah.adoc[leveloffset=+1]

include::hub/assembly-faq.adoc[leveloffset=+1]

include::hub/assembly-validated-content.adoc[leveloffset=+1]

== Conclusion

When you complete all of the previous procedures, you will have:

* created a synclist for Red Hat Certified collections content.
* synced that content to your local {HubName}.
* designated community collections from {Galaxy} to distribute to your users.
* configured content signing on {PrivateHubName}.
* signed and approved collections for your organization's specific needs.
* configured Ansible-Galaxy CLI to verify collections before signing them.

Users can now view and download collections content from your {HubName}.
