[id="controller-capacity-determination"]

= {ControllerNameStart} capacity determination and job impact

The {ControllerNameStart} capacity system determines how many jobs can run on an instance given the amount of resources available to the instance and the size of the jobs that are running (referred to as Impact). 
The algorithm used to determine this is based on the following two things:

* How much memory is available to the system (`mem_capacity`)
* How much processing capacity is available to the system (`cpu_capacity`)

Capacity also impacts instance groups. 
Since groups are made up of instances, instances can also be assigned to multiple groups. 
This means that impact to one instance can affect the overall capacity of other groups.

Instance groups, not instances themselves, can be assigned to be used by jobs at various levels. 
For more information, see link:http://docs.ansible.com/automation-controller/4.4/html/administration/clustering.html#ag-clustering[Clustering] in the _{ControllerAG}_.

When the Task Manager prepares its graph to determine which group a job runs on, it commits the capacity of an instance group to a job that is not ready to start yet.

In smaller configurations, if only one instance is available for a job to run, the Task Manager enables that job to run on the instance even if it pushes the instance over capacity. 
This guarantees that jobs do not get stuck as a result of an under-provisioned system.

.Additional resources

* For information on container groups, see link:http://docs.ansible.com/automation-controller/4.4/html/administration/containers_instance_groups.html#ag-container-capacity[Container capacity limits] in the _{ControllerAG}_.
* For information on sliced jobs and their impact to capacity, see xref:controller-job-slice-execution-behavior[Job slice execution behavior].
