

[id="aap-upgrade-planning_{context}"]

= {PlatformNameShort} upgrade planning

[role="_abstract"]
Before you begin the upgrade process, review the following considerations to plan and prepare your {PlatformNameShort} deployment:

[discrete]
== {ControllerNameStart}

* Even if you have a valid license from a previous version, you must provide your credentials or a subscriptions manifest upon upgrading to the latest version of {ControllerName}.
* If you need to upgrade {RHEL} and {ControllerName}, you must first backup and restore your {ControllerName} data.
* Clustered upgrades require special attention to instance and instance groups before upgrading.

[role="_additional-resources"]
.Additional resources
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/automation_controller_user_guide/controller-managing-subscriptions#controller-importing-subscriptions[Importing a subscription]
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/automation_controller_administration_guide/controller-backup-and-restore[Backup and restore]
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/automation_controller_administration_guide/controller-clustering[Clustering]

[discrete]
== {HubNameStart}

* When upgrading to {PlatformNameShort} {PlatformVers}, you can either add an existing {HubName} API token or generate a new one and invalidate any existing tokens.

[role="_additional-resources"]
.Additional resources
* <<editing-inventory-file-for-updates_{context}, Setting up the inventory file >>

[discrete]
== {EDAcontroller}
//ATTENTION: Remove this section for EDA 1.0.4; customers will no longer need to perform deactivation because services will be automatically restored after upgrade and migration. 

* If you are currently running {EDAcontroller} and plan to deploy it when you upgrade to {PlatformNameShort} {PlatformVers}, it is recommended that you disable all {EDAName} activations before upgrading to ensure that only new activations run after the upgrade process has completed. This prevents possibilities of orphaned containers running activations from the previous version.