
[id="con-automation-mesh"]

= About {AutomationMesh}

[role="_abstract"]
{AutomationMeshStart} is an overlay network intended to ease the distribution of work across a large and dispersed collection of workers through nodes that establish peer-to-peer connections with each other using existing networks.

{PlatformName} 2 replaces Ansible Tower and isolated nodes with {ControllerName} and {HubName}. 
{ControllerNameStart} provides the control plane for automation through its UI, RESTful API, RBAC, workflows and CI/CD integration, while {AutomationMesh} can be used for setting up, discovering, changing or modifying the nodes that form the control and execution layers.

ifdef::operator-mesh[]
{AutomationMeshStart} is useful for:

* traversing difficult network topologies
* bringing execution capabilities (the machine running `ansible-playbook`) closer to your target hosts

The nodes (control, hop, and execution instances) are interconnected through a receptor mesh, forming a virtual mesh.
endif::operator-mesh[]

{AutomationMeshStart} uses TLS encryption for communication, so traffic that traverses external networks (the internet or other) is encrypted in transit.

{AutomationMeshStart} introduces:

* Dynamic cluster capacity that scales independently, enabling you to create, register, group, ungroup and deregister nodes with minimal downtime.
* Control and execution plane separation that enables you to scale playbook execution capacity independently from control plane capacity.
* Deployment choices that are resilient to latency, reconfigurable without outage, and that dynamically re-reroute to choose a different path when outages occur.
* Connectivity that includes bi-directional, multi-hopped mesh communication possibilities which are _Federal Information Processing Standards_ (FIPS) compliant.
