[id="controller-instance-groups"]

= Instance groups

Instances can be grouped into one or more instance groups. 
Instance groups can be assigned to one or more of the following listed resources:

* Organizations
* Inventories
* Job templates

When a job associated with one of the resources executes, it is assigned to the instance group associated with the resource. 
During the execution process, instance groups associated with job templates are checked before those associated with inventories. 
Instance groups associated with inventories are checked before those associated with organizations.
Therefore, instance group assignments for the three resources form the hierarchy: 

Job Template > Inventory > Organization

Consider the following when working with instance groups:

* You can define other groups and group instances in those groups. 
These groups must be prefixed with `instance_group_`. 
Instances are required to be in the `automationcontroller` or `execution_nodes` group alongside other `instance_group_` groups. 
In a clustered setup, at least one instance must be present in the `automationcontroller` group, which appears as `controlplane` in the API instance groups. 
For more information and example scenarios, see xref:controller-group-policies-automationcontroller[Group policies for `automationcontroller`].

* You cannot modify the `controlplane` instance group, and attempting to do so results in a permission denied error for any user. 
+
Therefore, the *Disassociate* option is not available in the *Instances* tab of `controlplane`.
+
* A `default` API instance group is automatically created with all nodes capable of running jobs. 
This is like any other instance group but if a specific instance group is not associated with a specific resource, then the job execution always falls back to the default instance group. 
The default instance group always exists, and you cannot delete or rename it.
* Do not create a group named `instance_group_default`.
* Do not name any instance the same as a group name.
