[id="con-websocket-setup_{context}"]

= Websocket configuration for {ControllerName}

[role="_abstract"]
{ControllerNameStart} nodes connect to all other {ControllerName} nodes via websockets. This interconnect is used to distribute all websocket emitted messages to all other {ControllerName} nodes. This is required because any browser client websocket can subscribe to any job that may be running on any {ControllerName} node. Websocket clients are not routed to specific {ControllerName} nodes. Any {ControllerName} node can handle any websocket request and each {ControllerName} node must know about all websocket messages destined for all clients.

{ControllerNameStart} will automatically handle discovery of other {ControllerName} nodes via the Instance record in the database.

[IMPORTANT]
====
* Ensure that your nodes are broadcasting websocket traffic across a private, trusted subnet (and not the open Internet). Therefore, if you turn off HTTPS for websocket broadcasting, the websocket traffic, comprised mostly of Ansible playbook stdout, is sent unencrypted between {ControllerName} nodes.
====
