

[id="aap-upgrades-legacy_{context}"]

= {PlatformNameShort} legacy upgrades

Upgrading to version {PlatformVers} from {PlatformNameShort} 2.0 or earlier requires you to migrate Ansible content for compatibility.

The following steps provide an overview of the legacy upgrade process:

* Duplicate your custom virtual environments into automation execution environments using the `awx-manage` command.
* Migrate data from isolated legacy nodes to execution nodes by performing a side-by-side upgrade so nodes are compatible with the latest {AutomationMesh} features.
* Import or generate a new {HubName} API token.
* Reconfigure your Ansible content to include Fully Qualified Collection Names (FQCN) for compatibility with `ansible-core` {AnsibleCoreVers}.

[role="_additional-resources"]
.Additional resources

* <<upgrading-to-ees,Migrate virtual environments to automation execution environments>>
* <<migrate-isolated-execution-nodes,Migrate isolated nodes to execution nodes>>
* <<content-migration,Migrate Ansible content>>
