

[id="aap-upgrade-planning_{context}"]

= {PlatformNameShort} upgrade planning

[role="_abstract"]
Before you begin the upgrade process, review the following considerations to plan and prepare your {PlatformNameShort} deployment:

[discrete]
== ControllerName}

* Even if you have a valid license from a previous version, you must provide your credentials or a subscriptions manifest upon upgrading to the latest version of {ControllerName}. +
See _Import a subscription_ in the Automation Controller User Guide.
* If you need to upgrade Red Hat Enterprise Linux and {ControllerName}, you must first backup and restore of your {ControllerName} data. +
See _Back up and restore Controller_.
* Clustered upgrades require special attention to instance and instance groups before upgrading. +
See _Clustering_.

[discrete]
== {HubName}

* When upgrading to {PlatformNameShort} {PlatformVers}, you can either add an existing {HubName} API token or generate a new one and invalidate any existing tokens. +
See _Setting up the inventory file_ for details.

[role="_additional-resources"]
.Additional resources
* link:https://docs.ansible.com/automation-controller/latest/html/userguide/import_license.html[Import a subscription]
* link:https://docs.ansible.com/automation-controller/latest/html/administration/backup_restore.html#ag-backup-restore[Back up and restoring Controller]
* link:https://docs.ansible.com/automation-controller/latest/html/administration/clustering.html#ag-clustering[Clustering]
* <<editing-inventory-file-for-updates_{context}, Setting up the inventory file >>
