[id="controller-cluster-job-runs"]

= Job runs

By default, when a job is submitted to the {ControllerName} queue, it can be picked up by any of the workers. 
However, you can control where a particular job runs, such as restricting the instances from which a job runs on.

To support taking an instance offline temporarily, there is a property enabled defined on each instance. 
When this property is disabled, no jobs are assigned to that instance. 
Existing jobs finish, but no new work is assigned.

.Troubleshooting 

When you issue a `cancel` request on a running {ControllerName} job, {ControllerName} issues a `SIGINT` to the ansible-playbook process. 
While this causes Ansible to stop dispatching new tasks and exit, in many cases, module tasks that were already dispatched to remote hosts will run to completion. 
This behavior is similar to pressing `Ctrl-c` during a command-line Ansible run.

With respect to software dependencies, if a running job is canceled, the job is removed but the dependencies remain.
