[id="con-why-migrate-venvs-ee"]

= Migrating from legacy virtual environments (venvs) to {ExecEnvName}

{PlatformNameShort} {PlatformVers} moves you away from custom Python virtual environments (venvs) in favor of {ExecEnvName} - containerized images that package the necessary components needed to run and scale your Ansible automation. These components include Ansible Core, Ansible Content Collections, Python dependencies, {RHEL} UBI 8, and any additional package dependencies.

To migrate your venvs to execution environments, you must use the `awx-manage` command to list and export a list of venvs from your original instance, and then use `ansible-builder` to create execution environments.

[role="_additional-resources"]
.Additional resources

* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_upgrade_and_migration_guide/upgrading-to-ees[Upgrading to Automation Execution Environments guide]
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/creating_and_consuming_execution_environments/index[Creating and Consuming Execution Environments].
