[id="con-controller-monitor-controller"]

= Monitoring {ControllerName}

It is best practice to monitor your hosts both from a system level as well as at the application level. 
System level monitoring includes information about disk I/O, RAM use, CPU use, and network traffic.

For application level monitoring, {ControllerName} provides Prometheus-style metrics on an API endpoint `/api/v2/metrics`. 
This can be used to monitor aggregate data about job status and subsystem performance, such as for job output processing or job scheduling.
For more information, see xref:assembly-controller-metrics[Metrics].

Monitoring the CPU and memory use of your hosts is important because capacity management for instances does not dynamically view the resource use of hosts. 
The resource impact of automation varies based on what the playbooks are doing.
For example, many cloud or networking modules do most of the actual processing on the node running the Ansible playbook (the execution node), which can have a significantly different impact on {ControllerName} than running `yum update` across many hosts, where the execution node spends much of the time during this task waiting on results.

If CPU or memory use is very high, consider lowering the capacity adjustment on affected instances in {ControllerName}. 
This limits how many jobs are run on or controlled by this instance.

Using this in combination with application level metrics can help identify what was happening in the application when and if any service degradation occurred. 
If you are working with Red Hat support or account teams, having information about {ControllerName}'s performance over time can be very useful in diagnosing problems or doing capacity planning for future growth.

Additional insights into automation use are available when users enable data collection for Automation Analytics. 

For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4[Product documentation for Automation Analytics], and link:https://www.ansible.com/products/insights-for-ansible[Automation analytics and Red Hat Insights for Red Hat Ansible Automation Platform].

.Troubleshooting 

The `sosreport` is a utility that collects diagnostic information for support to be able to use to analyze and investigate the issues that you report. 
To provide technical support this information, see the Knowledgebase article link:https://access.redhat.com/solutions/3592[What is an sos report and how to create one in Red Hat Enterprise Linux?] from the Red Hat Customer portal.

.Procedure

. Install the `sosreport` utility.
For more information see the link:https://access.redhat.com/solutions/3592#install[Installing sos package] section of the Knowledgebase article.
. Generate an `sosreport`.
For more information, see the link:https://access.redhat.com/solutions/3592#command[How can I generate an sos report?] section of the Knowledgebase article.
. Provide the `sosreport` to link:https://access.redhat.com/[Red Hat Support]. 
