

[id="con-websocket-setup_{context}"]

= Websocket configuration for {ControllerName}

[role="_abstract"]
{ControllerNameStart} nodes connect to all other {ControllerName} nodes through websockets. 
This interconnect is used to distribute all websocket emitted messages to all other {ControllerName} nodes. 
This is required because any browser client websocket can subscribe to any job that may be running on any {ControllerName} node. 
Websocket clients are not routed to specific {ControllerName} nodes. 
Any {ControllerName} node can handle any websocket request and each {ControllerName} node must know about all websocket messages destined for all clients.

== Automatic discovery of other automation controller nodes

{ControllerNameStart} automatically handles discovery of other {ControllerName} nodes using the Instance record in the database.

[IMPORTANT]
====
Your nodes broadcast websocket traffic across a private, trusted subnet, not the open Internet. 
Therefore, if you turn off HTTPS for websocket broadcasting, the websocket traffic, comprised mostly of Ansible playbook stdout, is sent between {ControllerName} nodes unencrypted.
====
