

[id="con-aap-installation-on-disconnected-rhel_{context}"]


= {PlatformNameShort} installation on disconnected RHEL

[role="_abstract"]
Install Ansible Automation Platform (AAP) automation controller and a private automation hub, with an installer-managed database located on the automation controller without an Internet connection.

== Prerequisites

To install AAP on a disconnected network, complete the following prerequisites
before you install AAP on a disconnected network.
* Create a subscription manifest
* Download the AAP setup bundle
* Create DNS records for the automation controller and private automation hub
servers

. Create a subscription manifest.
. Download the AAP setup bundle.
. Create DNS records for the automation controller and private automation hub servers.

NOTE: The setup bundle includes additional components that make installing AAP easier in a disconnected environment. These include the AAP RPMs and the default execution environment (EE) images.

== System Requirements

Hardware requirements are documented in the Automation Platform Installation Guide. Reference the "Red Hat Ansible Automation Platform Installation Guide" in the
link::https://access.redhat.com/documentation/en-us/
red_hat_ansible_automation_platform[AAP Product Documentation]
for your version of AAP.


== RPM Source

RPM dependencies for AAP that come from the BaseOS and AppStream repositories are not included in the setup bundle.To add these dependencies, you must obtain access to BaseOS and AppStream repositories.
*
link::/https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html
/installing_satellite_server_in_a_disconnected_network_environment/index[
Satellite] is the recommended method from Red Hat to synchronize repositories
* reposync - Makes full copies of the required RPM repositories and hosts them on the disconnected network
* RHEL Binary DVD - Use the RPMs available on the RHEL 8 Binary DVD

NOTE: The RHEL Binary DVD method requires the DVD for RHEL 8.5 or higher
