[id="con-controller-task-manager-settings"]

= Task Manager (Job Scheduling) Settings

The task manager is a periodic task that collects tasks to be scheduled and determines what instances have capacity and are eligible to run them. 
Its job is to find and assign the control and execution instances, update the job's status to waiting, and send the message to the control node through `pg_notify` for the dispatcher to pick up the task and start running it.

//Avoid talking about what used to happen.
//As mentioned in xref:ref-controller-performance-improvements[Performance improvements], a number of optimizations and refactors of this process were implemented in version 4.3. One such refactor was to fix a defect that when the task manager did reach its timeout, it was terminated in such a way that it did not make any progress. Multiple changes were implemented to fix this, so that as the task manager approaches its timeout, it makes an effort to exit and commit any progress made on that run. These issues generally arise when there are thousands of pending jobs, so may not be applicable to your use case.

One way to limit how much work the task manager attempts to do in one run is to use `START_TASK_LIMIT`. 
The default is 100 jobs, which is a safe default. 
If there are remaining jobs to schedule, a new run of the task manager is scheduled to run immediately after the current run. 
If you are willing to risk potentially longer individual runs of the task manager to start more jobs in individual runs, you can consider increasing the value of `START_TASK_LIMIT`. 
The Prometheus metrics, available in `/api/v2/metrics` observe how long individual runs of the task manager take in `task_manager__schedule_seconds`.

For more information, see xref:assembly-controller-metrics[Metrics].

As a safeguard against excessively long runs of the task manager, there is a timeout which is determined by the setting `TASK_MANAGER_TIMEOUT``.
This is when the task manager begins to exit any loops and attempts to commit any progress it made. 
The task is not killed until `TASK_MANAGER_TIMEOUT` + `TASK_MANAGER_TIMEOUT_GRACE_PERIOD` seconds have passed.