[id="con-install-scenario-recommendations"]

= Inventory file recommendations based on installation scenarios

[role="_abstract"]
Before selecting your installation method for {PlatformNameShort}, review the following recommendations. Familiarity with these recommendations will streamline the installation process.

* For {PlatformName} or {HubName}: Add an {HubName} host in the `[automationhub]` group.
// Removed for AAP-20847 and until such time as a decision is made regarding database support.
//* Internal databases `[database]` are not supported. See the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/containerized_ansible_automation_platform_installation_guide/index[Containerized {PlatformName} Installation Guide] for further information on using the containerized installer for environments requiring a monolithc deployment. 
* Do not install {ControllerName} and {HubName} on the same node for versions of {PlatformNameShort} in a production or customer environment.
This can cause contention issues and heavy resource use.
* Provide a reachable IP address or fully qualified domain name (FQDN) for the `[automationhub]` and `[automationcontroller]` hosts to ensure users can sync and install content from {HubName} from a different node.
Do not use 'localhost'.
* `admin` is the default user ID for the initial log in to {PlatformNameShort} and cannot be changed in the inventory file.
* Use of special characters for `pg_password` is limited. The `!`, `#`, `0` and `@` characters are supported. Use of other special characters can cause the setup to fail.
* Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.
* The inventory file variables `registry_username` and `registry_password` are only required if a non-bundle installer is used.
