
[id="con-cluster-platform-ext-database_{context}"]

= Multi-machine cluster installation with an external managed database

[role="_abstract"]
This scenario includes installation of multiple {ControllerName} nodes and an {HubName} instance and configures communication with a remote PostgreSQL instance as its database. This remote PostgreSQL can be a server you manage, or can be provided by a cloud service such as Amazon RDS. In this scenario, all {ControllerName} are active and can execute jobs, and any node can receive HTTP requests.

[NOTE]
====
* Running in a cluster setup requires any database that {ControllerName} uses to be external--PostgreSQL must be installed on a machine that is not one of the primary or secondary tower nodes. When in a redundant setup, the remote PostgreSQL version requirements is *PostgreSQL 13*.
** See link:https://docs.ansible.com/automation-controller/latest/html/administration/clustering.html[Clustering] for more information on configuring a clustered setup.
* Provide a reachable IP address for the `[automationhub]` host to ensure users can sync content from Private Automation Hub from a different node.
====



// This installs the Platform server on a single machine ???? Is this correct?
