[id="con-controller-job-scheduling-improvements"]

= Job scheduling improvements

When jobs are created using a schedule, a workflow, the UI or the API, they are first created in _Pending_ state. 
To determine when and where to run this job, a background task called the _Task Manager_ collects all pending and running jobs and determines where capacity is available to run the job. 

In previous versions of {ControllerName}, scheduling slowed as the number of pending and running jobs increased, and the Task Manager was vulnerable to timing out without making any progress. 
This resulted in a situation where thousands of jobs were pending, despite available capacity, but no jobs were starting.

Optimizations in the job scheduler now make scheduling faster, as well as introducing safeguards to ensure the scheduler commits its progress even if it is nearing time out. 
Additionally, work that previously occurred in the Task Manager that blocked its progress has been decoupled into separate, non-blocking work units executed by the Dispatcher.