
[id="installing-the-aap-setup-bundle_{context}"]

= Installing the AAP Setup Bundle

The “bundle” version is strongly recommended for disconnected installations as it comes with the RPM content for AAP as well as the default execution environment images that will be uploaded to your Private Automation Hub during the installation process.

.Procedure

== Downloading the Setup Bundle

. Download the AAP setup bundle package by navigating to the https://access.redhat.com/downloads/content/480[Red Hat Ansible Automation Platform download] page and clicking btn:[Download Now] for the Ansible Automation Platform {PlatformVers} Setup Bundle.

=== Installing the Setup Bundle

The download and installation of the setup bundle needs to be located on the automation controller. From the controller, untar the bundle, edit the inventory file, and run the setup.

. Untar the bundle
+
----
$ tar xvf \
   ansible-automation-platform-setup-bundle-2.4.tar.gz
$ cd ansible-automation-platform-setup-bundle-2.4
----
+
. Edit the inventory file to include the required options

.. automationcontroller group
.. automationhub group
.. admin_password
.. pg_password
.. automationhub_admin_password
.. automationhub_pg_host, automationhub_pg_port
.. automationhub_pg_password
+
*Example Inventory*
+
----
[automationcontroller]
automationcontroller.example.org ansible_connection=local

[automationcontroller:vars]
peers=execution_nodes

[automationhub]
automationhub.example.org

[all:vars]
admin_password='password123'

pg_database='awx'
pg_username='awx'
pg_password='dbpassword123'

receptor_listener_port=27199

automationhub_admin_password='hubpassword123'

automationhub_pg_host='automationcontroller.example.org'
automationhub_pg_port='5432'

automationhub_pg_database='automationhub'
automationhub_pg_username='automationhub'
automationhub_pg_password='dbpassword123'
automationhub_pg_sslmode='prefer'
----
NOTE: The inventory should be kept intact after installation since it is used for backup, restore, and upgrade functions.  Consider keeping a backup copy in a secure location, given that the inventory file contains passwords.
+
. Run the AAP setup bundle executable as the root user
+
----
$ sudo -i
# cd /path/to/ansible-automation-platform-setup-bundle-2.4
# ./setup.sh
----
+
. Once installation is complete, navigate to the Fully Qualified Domain Name (FQDN) for the Automation controller node that was specified in the installation inventory file.

. Log in with the administrator credentials specified in the installation inventory file.
