[id="proc-pulling-the-secret"]

= Pulling the secret for OpenShift Container Platform deployments

[NOTE]
====
This does not apply to {PlatformNameShort} on {Azure}.
====

If you are using the default {ExecEnvShort} provided with {ControllerName} to run on remote execution nodes, you must add a pull secret in {ControllerName} that contains the credential for pulling the {ExecEnvShort} image.

To do this, create a pull secret on the {ControllerName} namespace and configure the `ee_pull_credentials_secret` parameter in the Operator as follows:

.Procedure
. Create a secret using the following command:
+
----
oc create secret generic ee-pull-secret \
     --from-literal=username=<username> \
     --from-literal=password=<password> \
     --from-literal=url=registry.redhat.io

oc edit automationcontrollers <instance name>
----

. Add `ee_pull_credentials_secret` and `ee-pull-secret` to the specification using:
+
----
spec.ee_pull_credentials_secret=ee-pull-secret
----

. To manage instances from the {ControllerName} UI, you must have System Administrator or System Auditor permissions.
