
[id="proc-configuring-known-proxies_{context}"]

= Configuring known proxies

[role="_abstract"]

To configure a list of known proxies for your {ControllerName}, add the proxy IP addresses to the *PROXY_IP_ALLOWED_LIST* field in the settings page for your {ControllerName}.

.Procedure

. On your {ControllerName}, navigate to menu:Settings[Miscellaneous System].
. In the *PROXY_IP_ALLOWED_LIST* field, enter IP addresses that are allowed to connect to your {ControllerName}, following the syntax in the example below:
+
.Example *PROXY_IP_ALLOWED_LIST* entry
----
[
  "example1.proxy.com:8080",
  "example2.proxy.com:8080"
]
----

[IMPORTANT]
====
* `PROXY_IP_ALLOWED_LIST` requires proxies in the list are properly sanitizing header input and correctly setting an ``X-Forwarded-For`` value equal to the real source IP of the client. {ControllerNameStart} can rely on the IP addresses and hostnames in `PROXY_IP_ALLOWED_LIST` to provide non-spoofed values for the `X-Forwarded-For` field.
* Do not configure `HTTP_X_FORWARDED_FOR` as an item in `REMOTE_HOST_HEADERS`unless *all* of the following conditions are satisfied:
** You are using a proxied environment with ssl termination;
** The proxy provides sanitization or validation of the `X-Forwarded-For` header to prevent client spoofing;
** `/etc/tower/conf.d/remote_host_headers.py` defines `PROXY_IP_ALLOWED_LIST` that contains only the originating IP addresses of trusted proxies or load balancers.
====
