

[id="defining-node-types"]

= Defining {AutomationMesh} node types

[role="_abstract"]
The examples in this section demonstrate how to set the node type for the hosts in your inventory file.

You can set the `node_type` for single nodes in the control plane or execution plane inventory groups.
To define the node type for an entire group of nodes, set the `node_type` in the `vars` stanza for the group.

* The allowed values for `node_type` in the control plane `[automationcontroller]` group are `hybrid` (default) and `control`.
* The allowed values for `node_type` in the `[execution_nodes]` group are `execution` (default) and `hop`.

.Hybrid node

The following inventory consists of a single hybrid node in the control plane:

-----
[automationcontroller]
control-plane-1.example.com
-----

.Control node

The following inventory consists of a single control node in the control plane:

-----
[automationcontroller]
control-plane-1.example.com node_type=control
-----

If you set `node_type` to `control` in the `vars` stanza for the control plane nodes, then all of the nodes in control plane are control nodes.

-----
[automationcontroller]
control-plane-1.example.com

[automationcontroller:vars]
node_type=control
-----

.Execution node

The following stanza defines a single execution node in the execution plane:

-----
[execution_nodes]
execution-plane-1.example.com
-----

.Hop node
The following stanza defines a single hop node and an execution node in the execution plane. The `node_type` variable is set for every individual node.

-----
[execution_nodes]
execution-plane-1.example.com node_type=hop
execution-plane-2.example.com
-----

If you want to set the `node_type` at the group level, you must create separate groups for the execution nodes and the hop nodes.

-----
[execution_nodes]
execution-plane-1.example.com
execution-plane-2.example.com

[execution_group]
execution-plane-2.example.com

[execution_group:vars]
node_type=execution

[hop_group]
execution-plane-1.example.com

[hop_group:vars]
node_type=hop

----- 


.Peer connections
Create node-to-node connections using the `peers=` host variable.
The following example connects `control-plane-1.example.com` to `execution-node-1.example.com` and `execution-node-1.example.com` to `execution-node-2.example.com`:

-----
[automationcontroller]
control-plane-1.example.com peers=execution-node-1.example.com

[automationcontroller:vars]
node_type=control

[execution_nodes]
execution-node-1.example.com peers=execution-node-2.example.com
execution-node-2.example.com
-----

[role="_additional-resources"]
.Additional resources

* See the example {AutomationMesh} topologies in this guide for more examples of how to implement mesh nodes.
