// Used in
// assemblies/platform/assembly-installing-aap-operator-cli.adoc
// titles/aap-operator-installation/

[id="proc-cli-get-controller-pwd{context}"]

= Fetching {ControllerNameStart} login details from the {OCPShort} CLI

To login to the {ControllerNameStart}, you need the web address and the password.

== Fetching the {ControllerName} web address

A {OCP} route exposes a service at a host name, so that external clients can reach it by name.
When you created the {ControllerName} instance, a route was created for it.
The route inherits the name that you assigned to the {ControllerName} object in the YAML file.

Use the following command to fetch the routes:

-----
oc get routes
-----

In the following example, the value for _name_ in the `AutomationController` YAML definition is `_example_`.

-----
$ oc get routes

NAME      HOST/PORT                                              PATH   SERVICES          PORT   TERMINATION     WILDCARD
example   example-ansible-automation-platform.apps-crc.testing          example-service   http   edge/Redirect   None
-----

The address for the {ControllerName} instance is `example-ansible-automation-platform.apps-crc.testing`.

== Fetching the {ControllerName} password

The YAML block for the {ControllerName} instance assigns values to the _name_ and _admin_user_ keys.
Use these values in the following command to fetch the password for the {ControllerName} instance.

-----
oc get secret/<controller_name>-<admin_user>-password -o yaml
-----


In the following example, the value for _name_ is `_example_` and the value assigned to the _admin_user_ key is `_admin_`.

-----
oc get secret/example-admin-password -o yaml
-----

The password for the {ControllerName} instance is listed in the `metadata` field in the output:

-----
$ oc get secret/example-admin-password -o yaml

apiVersion: v1
data:
  password: ODhLSzJVanByTXVtVEdmUmVQMzdxZXJXazByT3VYUDM=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Secret","metadata":{"labels":{"app.kubernetes.io/component":"automationcontroller","app.kubernetes.io/managed-by":"automationcontroller-operator","app.kubernetes.io/name":"example","app.kubernetes.io/operator-version":"","app.kubernetes.io/part-of":"example"},"name":"example-admin-password","namespace":"ansible-automation-platform"},"stringData":{"password":"88KK2UjprMumTGfReP37qerWk0rOuXP3"}}'
  creationTimestamp: "2021-12-03T00:02:24Z"
  labels:
    app.kubernetes.io/component: automationcontroller
    app.kubernetes.io/managed-by: automationcontroller-operator
    app.kubernetes.io/name: example
    app.kubernetes.io/operator-version: ""
    app.kubernetes.io/part-of: example
  name: example-admin-password
  namespace: ansible-automation-platform
  resourceVersion: "185013"
  uid: 391b22f0-52a2-4240-b942-665f1f589359

-----

For this example, the password is `88KK2UjprMumTGfReP37qerWk0rOuXP3`.
