:_content-type: PROCEDURE

[id="using-postinstall_{context}"]

= Using postinstall feature of containerized {PlatformNameShort}

[role="_abstract"]


Use the experimental postinstaller feature of containerized {PlatformNameShort} to define and load the configuration during the initial installation. This uses a configuration-as-code approach, where you simply define your configuration to be loaded as simple YAML files. 

. To use this optional feature, you need to uncomment the following vars in the inventory file:
+
----
controller_postinstall=true
----
+

. The default is false, so this must be enabled to activate the postinstaller. An {PlatformNameShort} license is required for this feature and must reside on the local filesystem so it can be automatically loaded:
+
----
controller_license_file=/full_path_to/manifest_file.zip
----
+

. You can pull your configuration-as-code from a Git based repo. To do this, set the following variables to dictate where you pull the content from and where it will be stored for upload to the {PlatformNameShort} controller:
+
----
controller_postinstall_repo_url=https://your_cac_scm_repo
controller_postinstall_dir=/full_path_to_where_you_want_the pulled_content_to_reside
----

Definition files use the link:https://console.redhat.com/ansible/automation-hub/namespaces/infra/[infra certified collections]. The link:https://console.redhat.com/ansible/automation-hub/repo/validated/infra/controller_configuration/[controller_configuration] collection is preloaded as part of the installation and use the installation controller credentials you supply in the inventory file for access into the {PlatformNameShort} controller, so you simply need to provide the YAML configuration files. You can setup {PlatformNameShort} configuration attributes such as credentials, LDAP settings, users/teams, organizations, projects, inventory/hosts, job and workflow templates.

The following example shows a sample *your-config.yml* file defining and loading controller job templates. The example demonstrates a simple change to the preloaded demo example provided with an AAP installation.

----
/full_path_to_your_configuration_as_code/
├── controller
    	└── job_templates.yml

---
controller_templates:
 - name: Demo Job Template
   execution_environment: Default execution environment
   instance_groups:
 	- default
   inventory: Demo Inventory
----