[id="controller-select-capacity"]

= Selecting the correct capacity

Selecting a capacity out of the CPU-bound or the memory-bound capacity limits is selecting between the minimum or maximum number of forks.
In the xref:controller-memory-relative-capacity[previous examples], the CPU capacity permits a maximum of 16 forks while the memory capacity permits 20. 
For some systems, the disparity between these can be large and you might want to have a balance between these two.

The instance field `capacity_adjustment` enables you to select how much you want to consider. 
It is represented as a value between 0.0 and 1.0. 
If set to a value of 1.0, then the largest value is used.
The previous example involves memory capacity, so a value of 20 forks can be selected. 
If set to a value of 0.0 then the smallest value is used.
A value of 0.5 is a 50/50 balance between the two algorithms, which is 18:

----
16 + (20 - 16) * 0.5 = 18
----

.Procedure

View or edit the capacity:

. From the *Instances Groups* list view, select the desired instance.
. Select the *Instances* tab and adjust the *Capacity Adjustment* slider.
+
[NOTE]
====
The slider adjusts whether the instance capacity algorithm yields less forks (towards the left) or yields more forks (towards the right).
====
