

[id="proc-definining-node-types"]

= Defining {AutomationMesh} node types

[role="_abstract"]
You can a define node type either by its default value assigned by the inventory group or by using the `node_type` host variable. Specify the `node_type` either as part of the inventory group or within the inventory `vars` group.  This section provides examples of how you can define node types in your inventory file.  Nodes in `[execution_nodes]` default execution node_type. Hybrid node types can be overridden to be control type via `node_type=control`. Execution node type can be overridden to be hope node type via `node_type=hop`

.Hybrid node

Nodes in `[automationcontroller]` default to the *hybrid node* type. In the below example, we create a single hybrid node:

-----
[automationcontroller]
control-plane-1.example.com
-----

.Control node

Convert hybrid node types to control nodes using `node_type=control`:

-----
[automationcontroller]
control-plane-1.example.com node_type=control
-----

.Execution node
Nodes in the`[execution_nodes]` inventory group default to the *execution node* type. In the below example, we create a single execution node:

-----
[execution_nodes]
execution-node-1.example.com
-----

.Hop node
Convert execution nodes to hop nodes using `node_type=control`:

-----
[execution_nodes]
execution-node-1.example.com node_type=hop
-----

.Peer connections
Create node-to-node connections using the `peers=` host variable. In the example below, we connect `control-plane-1.example.com` to `execution-node-1.example.com`, and `execution-node-1.example.com` to `execution-node-2.example.com `

-----
[automationcontroller]
control-plane-1.example.com peers=execution-node-1.example.com

[automationcontroller:vars]
node_type=control

[execution_nodes]
execution-node-1.example.com peers=execution-node-2.example.com
execution-node-2.example.com
-----

[role="_additional-resources"]
.Additional resources

* See the example {AutomationMesh} topologies in this guide for more examples of how to implement mesh nodes.
