// Used in
// assemblies/platform/assembly-installing-aap-operator-cli.adoc
// titles/aap-operator-installation/

[id="proc-install-cli-aap-operator{context}"]

= Subscribing a namespace to an operator using the {OCPShort} CLI

Use this procedure to subscribe a namespace to an operator.

.Procedure

. Create a project for the operator
+
-----
oc new-project ansible-automation-platform
-----
+
. Create a file called [filename]`sub.yaml`.
. Add the following YAML code to the [filename]`sub.yaml` file.
+
-----
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: ansible-automation-platform
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform-operator
  namespace: ansible-automation-platform
spec:
  targetNamespaces:
    - ansible-automation-platform
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: ansible-automation-platform
spec:
  channel: 'stable-2.4'
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: example
  namespace: ansible-automation-platform
spec:
  replicas: 1

-----
+
This file creates a `Subscription` object called `_ansible-automation-platform_` that subscribes the `ansible-automation-platform` namespace to the `ansible-automation-platform-operator` operator.
+
It then creates an `AutomationController` object called `_example_` in the `ansible-automation-platform` namespace.
+
To change the Automation controller name from `_example_`, edit the _name_ field in the `kind: AutomationController` section of [filename]`sub.yaml` and replace `_<automation_controller_name>_` with the name you want to use:
+
[subs="+quotes"]
-----
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: __<automation_controller_name>__
  namespace: ansible-automation-platform
-----
. Run the [command]`*oc apply*` command to create the objects specified in the [filename]`sub.yaml` file:
+
-----
oc apply -f sub.yaml
-----

To verify that the namespace has been successfully subscribed to the `ansible-automation-platform-operator` operator, run the [command]`*oc get subs*` command:

-----
$ oc get subs -n ansible-automation-platform
-----

For further information about subscribing namespaces to operators, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{OCPLatest}/html/operators/user-tasks#olm-installing-operator-from-operatorhub-using-cli_olm-installing-operators-in-namespace[Installing from OperatorHub using the CLI] in the {OCP} _Operators_ guide.

