// Module included in the following assemblies: 
// assembly-platform-whats-next.adoc

:_content-type: PROCEDURE

[id="updating-ee-image-locations_{context}"]

= Updating execution environment image locations

[role="_abstract"]
If you installed {PrivateHubName} separately from {PlatformNameShort}, you can update your execution environment image locations to point to your {PrivateHubName}.

.Procedure
. Navigate to the directory that contains `setup.sh`
. Create `./group_vars/automationcontroller` by running the following command: 
+
----
touch ./group_vars/automationcontroller
----
+
. Paste the following content into `./group_vars/automationcontroller`. Adjust the settings to fit your environment:
+
----
# Automation Hub Registry
registry_username: 'your-automation-hub-user'
registry_password: 'your-automation-hub-password'
registry_url: 'automationhub.example.org'
registry_verify_ssl: False

## Execution Environments
control_plane_execution_environment: 'automationhub.example.org/ee-supported-rhel8:latest'

global_job_execution_environments:
  - name: "Default execution environment"
    image: "automationhub.example.org/ee-supported-rhel8:latest"
  - name: "Ansible Engine 2.9 execution environment"
    image: "automationhub.example.org/ee-29-rhel8:latest"
  - name: "Minimal execution environment"
    image: "automationhub.example.org/ee-minimal-rhel8:latest"
----
+
. Run the `./setup.sh` script
+
----
$ ./setup.sh
----

.Verification

. Log into {PlatformNameShort} as a user with system administrator access. 
. Navigate to menu:Administration[Execution Environments].
. In the *Image* column, confirm that the execution environment image location has changed from the default value of `<registry url>/ansible-automation-platform-<version>/<image name>:<tag>` to `<automation hub url>/<image name>:<tag>`. 



