[id="change-ssl-installer_{context}"]

= Changing the SSL certificate and key using the installer

[role="_abstract"]
The following procedure describes how to change the SSL certificate and key in the inventory file.

.Procedure

. Copy the new SSL certificates and keys to a path relative to the {PlatformNameShort} installer.
. Add the absolute paths of the SSL certificates and keys to the inventory file. 
Refer to the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/index#ref-hub-variables[{ControllerNameStart} variables] and
link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/index#ref-controller-variables[{HubNameStart} variables] sections of the 
link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/index[{PlatformName} Installation Guide]
for guidance on setting these variables.
+
--
** {ControllerNameStart}: `web_server_ssl_cert`, `web_server_ssl_key`, `custom_ca_cert`
** {HubNameStart}: `automationhub_ssl_cert`, `automationhub_ssl_key`, `custom_ca_cert`
--
+
[NOTE]
====
The `custom_ca_cert` must be the root certificate authority that signed the intermediate certificate authority.
This file is installed in `/etc/pki/ca-trust/source/anchors`.
====
. Run the installer.

