[id="proc-controller-inv-source-aap"]

= {PlatformName}

Use the following procedure to configure an {ControllerName}-sourced inventory.

.Procedure
. In the *Create new source* page, select menu:Source[]
. From the menu, select *{PlatformName}*.
. The *Create Source* window expands with the required *Credential* field.
Choose from an existing GCE Credential. 
For more information, refer to xref:controller-credentials[Credentials].
. Optional: You can specify the verbosity, host filter, enabled variables or values, and update options as described in xref:proc-controller-add-source[Adding a source].
. Use the *Source Variables* field to override variables used by the `gcp_compute` inventory plugin. 
Enter variables using either JSON or YAML syntax. 
Use the radio button to toggle between the two. 
For more information on these variables, see link:https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/inventory/controller[Controller inventory plugin].
This requires your Red Hat Customer login.

