// this info is duplicated here: https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/1.2/html/installing_and_upgrading_private_automation_hub/installing_online_or_offline#doc-wrapper

[id="installing-the-aap-setup-bundle_{context}"]

= Downloading and installing the {PlatformNameShort} setup bundle

[role="_abstract"]
The “bundle” version is strongly recommended for disconnected installations because it includes the RPM content for {PlatformNameShort} as well as the default {ExecEnvShort} images that will be uploaded to your {PrivateHubName} during the installation process.

.Procedure

. Download the {PlatformNameShort} setup bundle package by navigating to the link:{PlatformDownloadUrl}[{PlatformName} download] page and clicking btn:[Download Now] for the {PlatformNameShort} {PlatformVers} setup bundle.

. From {ControllerName}, untar the bundle:
+
----
$ tar xvf \
   ansible-automation-platform-setup-bundle-2.4-1.tar.gz
$ cd ansible-automation-platform-setup-bundle-2.4-1
----
+
. Edit the inventory file to include the required options:

.. automationcontroller group
.. automationhub group
.. admin_password
.. pg_password
.. automationhub_admin_password
.. automationhub_pg_host, automationhub_pg_port
.. automationhub_pg_password
+
*Example Inventory*
+
----
[automationcontroller]
automationcontroller.example.org ansible_connection=local

[automationcontroller:vars]
peers=execution_nodes

[automationhub]
automationhub.example.org

[all:vars]
admin_password='password123'

pg_database='awx'
pg_username='awx'
pg_password='dbpassword123'

receptor_listener_port=27199

automationhub_admin_password='hubpassword123'

automationhub_pg_host='automationcontroller.example.org'
automationhub_pg_port='5432'

automationhub_pg_database='automationhub'
automationhub_pg_username='automationhub'
automationhub_pg_password='dbpassword123'
automationhub_pg_sslmode='prefer'
----
+
. Run the {PlatformNameShort} setup bundle executable as the root user:
+
----
$ sudo -i
# cd /path/to/ansible-automation-platform-setup-bundle-2.4-1
# ./setup.sh
----
+
. When installation is complete, navigate to the Fully Qualified Domain Name (FQDN) for the {ControllerName} node that was specified in the installation inventory file.

. Log in using the administrator credentials specified in the installation inventory file.

[NOTE]
====
The inventory must be kept intact after installation because it is used for backup, restore, and upgrade functions. Consider keeping a backup copy in a secure location, given that the inventory file contains passwords.
====