[id="proc-customizing-pod-specs"]

== Customizing the pod specification

You can use the following procedure to customize the pod. 

.Procedure
. In the {ControllerName} UI, navigate to menu:Administration[Instance Groups].
. Check btn:[Customize pod specification].
. In the *Pod Spec Override* field, specify the namespace by using the toggle to enable and expand the *Pod Spec Override* field.
. Click btn:[Save].
. Optional: Click btn:[Expand] to view the entire customization window if you wish to provide additional customizations.

The image used at job launch time is determined by the execution environment associated with the job. 
If a Container Registry credential is associated with the execution environment, then {ControllerName} uses `ImagePullSecret` to pull the image. 
If you prefer not to give the service account permission to manage secrets, you must pre-create the `ImagePullSecret`, specify it on the pod specification, and omit any credential from the execution environment used.