[id="benchmark-postgresql"]

= Benchmarking storage performance for the {PlatformNameShort} PostgreSQL database

Check whether the minimum {PlatformNameShort} PostgreSQL database requirements are met by using the Flexible I/O Tester (fio) tool. Fio is a tool used to benchmark write/read IOPS performance of the storage system.

.Prerequisites
 * You have installed the Flexible I/O Tester (`fio`) storage performance benchmarking tool. 
+
To install `fio`, run the following command as the root user:
+
[literal, options="nowrap" subs="+attributes"]
----
# yum -y install fio
----

* You have adequate disk space to store the `fio` test data log files.
+
The examples shown in the procedure require at least 60GB disk space in the `/tmp` directory:
+
--
** `numjobs` sets the number of jobs run by the command.
** `size=10G` sets the file size generated by each job.
--
+
* You have adjusted the value of the `size` parameter. Adjusting this value reduces the amout of test data.

.Procedure

. Run a random write test:
+
[literal, options="nowrap" subs="+attributes"]
----
$ fio --name=write_iops --directory=/tmp --numjobs=3 --size=10G \
--time_based --runtime=60s --ramp_time=2s --ioengine=libaio --direct=1 \
--verify=0 --bs=4K --iodepth=64 --rw=randwrite \
--group_reporting=1 > /tmp/fio_benchmark_write_iops.log \
2>> /tmp/fio_write_iops_error.log
----
. Run a random read test:
+
[literal, options="nowrap" subs="+attributes"]
----
$ fio --name=read_iops --directory=/tmp \
--numjobs=3 --size=10G --time_based --runtime=60s --ramp_time=2s \
--ioengine=libaio --direct=1 --verify=0 --bs=4K --iodepth=64 --rw=randread \
--group_reporting=1 > /tmp/fio_benchmark_read_iops.log \
2>> /tmp/fio_read_iops_error.log
----

. Review the results:
+
In the log files written by the benchmark commands, search for the line beginning with `iops`.
This line shows the minimum, maximum, and average values for the test.
+
The following example shows the line in the log file for the random read test:
+
[literal, options="nowrap" subs="+attributes"]
----
$ cat /tmp/fio_benchmark_read_iops.log
read_iops: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
[…]
   iops        : min=50879, max=61603, avg=56221.33, stdev=679.97, samples=360
[…]
----
+
You must review, monitor, and revisit the log files according to your own business requirements, application workloads, and new demands.

