

[id="proc-installing-with-internet_{context}"]


= Installing with internet access

[role="_abstract"]
Choose the {PlatformName} installer if your {RHEL} environment is connected to the internet. Installing with internet access retrieves the latest required repositories, packages, and dependencies. Choose one of the following ways to set up your {PlatformNameShort} installer.

.Tarball install

. Navigate to the link:{PlatformDownloadUrl}[{PlatformName} download] page.
. Click btn:[Download Now] for the *Ansible Automation Platform <latest-version> Setup*.
. Extract the files:
+
-----
$ tar xvzf ansible-automation-platform-setup-<latest-version>.tar.gz
-----

.RPM install

. Install Ansible Automation Platform Installer Package
+
v.{PlatformVers} for RHEL 8 for x86_64
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms ansible-automation-platform-installer
----
+
v.{PlatformVers} for RHEL 9 for x86-64
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms ansible-automation-platform-installer
----

[NOTE]
`dnf install` enables the repo as the repo is disabled by default.

When you use the RPM installer, the files are placed under the `/opt/ansible-automation-platform/installer` directory.
