//Used in downstream/titles/aap-installation-guide/platform/assembly-disconnected-installation.adoc

:_newdoc-version: 2.15.1
:_template-generated: 2024-02-05
:_mod-docs-content-type: PROCEDURE

[id="building-the-custom-execution-environment_{context}"]
= Building the custom {ExecEnvShort}

[role="_abstract"]

Before creating the new custom {ExecEnvShort}, an API token from the private hub will be needed in order to download content.  

Generate a token by taking the following steps:

. Log in to your private hub.

. Choose "Collections" from the left-hand menu.

. Choose the"API token" under the "Collections" section of the menu.
+

. Once you have the token, set the following environment variable so that {Builder} can access the token:

+
----
$ export ANSIBLE_GALAXY_SERVER_PRIVATE_HUB_TOKEN=<your_token>
----
+

. Create the custom {ExecEnvShort} by using the command:

+
----
$ cd $HOME/custom-ee
$ ansible-builder build -f execution-environment.yml -t private-hub.example.com/custom-ee:latest -v 3
----
+

[NOTE]

====
If the build fails with an error that the private hub certificate is signed by an unknown authority, you can pull the required image into the local image cache by running the command:

----
$ podman pull private-hub.example.com/ee-minimal-rhel8:latest --tls-verify=false
----

Alternately, you can add the private hub CA certificate to the podman certificate store:

----
$ sudo mkdir /etc/containers/certs.d/private-hub.example.com
$ sudo cp $HOME/custom-ee/files/hub-ca.crt /etc/containers/certs.d/private-hub.example.com
----
====
