[id="proc-set-custom-pod-timeout"]

= Set a custom pod timeout

You can set `awx_container_group_pod_pending_timeout` higher if long running jobs are being killed. 
This can be done using `extra_settings` on the {ControllerName} specification 

With extra_settings, you can pass multiple custom settings using the awx-operator. 
The parameter extra_settings is appended to `/etc/tower/settings.py` and can be an alternative to the `extra_volumes` parameter.

[cols="20%,20%,20%",options="header"]
|====
| Name | Description |Default
| `extra_settings` | Extra settings | ‘’
|====

Example configuration of extra_settings parameter
[options="nowrap" subs="+quotes,attributes"]
----
 spec:
    extra_settings:
      - setting: MAX_PAGE_SIZE
        value: "500"

      - setting: AUTH_LDAP_BIND_DN
        value: "cn=admin,dc=example,dc=com"
----

This is used if you are consistently launching many more jobs than kubernetes can schedule, and jobs are spending periods longer than `awx_container_group_pod_pending_timeout` in pending. 

Jobs are not launched until control capacity is available. 
If many more jobs are being launched than the container group has capacity to run, consider scaling up your kubernetes worker nodes.
