[id="proc-import-mesh-ca_{context}"]

= Importing a Certificate Authority (CA) certificate
A Certificate Authority (CA) is used to certify and sign execution nodes in an {AutomationMesh} environment. Users who wish to provide their own CA can do so by specifying the path to the certificate and the private RSA key file in the `inventory` file of their {PlatformName} installer.

NOTE: Users are not required to have a CA prior to their {AutomationMesh} installation. Users without a CA can proceed with their {PlatformNameShort} installation where the installer will generate a CA for the user using OpenSSL.

.Prerequisites
To import your own CA certificate, it must meet the following requirements:

* asdasd
* asdasd

.Procedure
* In the `inventory` file, add the following variables and specify a path to both the certificate file (`.crt`) and the private RSA key (`.key`), following the example below:
[subs="+quotes"]
+
----
[all:vars]
mesh_ca_keyfile=/tmp/__<mesh_CA>__.key
mesh_ca_certfile=/tmp/__<mesh_CA>__.crt
----

.Optional: Assigning CA certificates to individual nodes
Users can also assign CA certificates to individual nodes by adding the `mesh_node_certfile=` and `mesh_node_keyfile=` fields to each node, following the example below:
----
[automationcontroller]
121-addr.tatu.home ansible_host=192.168.111.121  node_type=hybrid mesh_node_certfile=/tmp/192.168.111.121.crt mesh_node_keyfile=/tmp/192.168.111.121.key
----
