[id="configure-saml-controller"]

= Configure SAML on {ControllerName}

[role=_abstract]
Use this procedure to enable simplified login authentication for users through {RHSSO}.

.Procedure
. Log in to {PlatformNameShort} as the admin user.
. Select *Settings* to configure {PlatformNameShort} settings.
. Select *SAML settings* from the Authentication pane.
. Click btn:[Edit].
. Enter the *SAML Service Provider Entity ID*. This is usually the URL for the service with the entry point hostname for the controller instance.
+
[NOTE]
====
This must match the settings on the {RHSSO} client_id name.
====
+
. Enter the keypair to use as a service provider (SP) and include the certificate content in *SAML Service Provider Public Certificate*.
+
-----
-----BEGIN CERTIFICATE——
... cert text ...
-----END CERTIFICATE——
-----
+
. Create a private key for the controller to use as a service provider (SP) and enter it in the *SAML Service Provider Private Key* field.
. Provide the URL, display name, and the name of your app in the *SAML Service Provider Organization Info* field. Refer to the documentation for example syntax.
+
-----
{
  "en-US": {
     "url": "https://rhsso.usersys.redhat.com:8443",
     "displayname": "RH-SSO Solutions Engineering",
     "name": "RH-SSO"
    }
}
-----
+
. Provide the name and email address of the support contact for your service provider in the *SAML Service Provider Technical Contact* field.
+
-----
{
  “givenName”: “<contact-name>”,
  “emailAddress”: “<contact-email>”
}
-----
+
. Provide the name and email address of the support contact for your service provider in the *SAML Service Provider Support Contact* field.
. Use the *SAML Enabled Identity Providers* field to configure the Entity ID, SSO URL and certificate for each identity provider (IdP) in use. Multiple SAML IdPs are supported. Some IdPs may provide user data using attribute names that differ from the default OIDs. Attribute names can be overridden for each IdP.
+
-----
{
   "RHSSO": {
      "attr_last_name": "last_name",
      "attr_username": "username",
      "entity_id": "https://rhsso.usersys.redhat.com:8443/auth/realms/tower",
      "attr_user_permanent_id": "name_id",
      "url": "https://rhsso.usersys.redhat.com:8443/auth/realms/<realm-name>/protocol/saml",
      "attr_email": "email",
      "x509cert": "",
      "attr_first_name": "first_name",
      "attr_groups": "groups"
   }
}
-----
+
. Use the *SAML Organization Map* field to configure the users placed into an organization based on their username and email address, for example:
+
-----
{
   "Default": {
      "users": true
   },
   "Systems Engineering": {
      "admins": [
         "acheron@redhat.com",
         "jparrill@redhat.com",
         "covenant@redhat.com",
         "olympia@redhat.com"
      ],
      "remove_admins": false,
      "remove_users": false,
      "users": true
   }
}
-----
+
. Use the *SAML Team Map* field to map team members (users) from social authorization accounts.
. Use the *SAML Team Attribute Mapping* field to translate user team membership.
. Use the *SAML Security Config* field to define key value pairs that are passed to the underlying python-saml security setting.
. Use the *SAML Service Provider Extra Configuration Data* field to define key value pairs to be passed to the underlying python-saml Service Provider configuration setting.
. Use the *SAML IDP to EXTRA_DATA Attribute Mapping* to define a list of tuples that maps IDP attributes to extra_attributes. Each attribute will be a list of values, even if only 1 value.
. Use the *SAML User Flags Attribute Mapping* field to map super users and system auditors from SAML.
. Click btn:[Save].
. Go to menu:Settings[Miscellaneous] and make sure the *Base URL* of the system is properly set to your entrypoint.
