
[id="proc-add-merge-subscriptions_{context}"]

= Adding subscriptions to a subscription allocation

Once an allocation is created, you can add the subscriptions you need for {PlatformNameShort} to run properly. This step is necessary before you can download the manifest and add it to {PlatformNameShort}.

.Procedure
. From the link:https://access.redhat.com/management/subscription_allocations/[Subscription Allocations] page, click on the name of the *Subscription Allocation* to which you would like to add a subscription.
. Click the *Subscriptions* tab.
. Click btn:[Add Subscriptions].
. Enter the number of {PlatformNameShort} Entitlement(s) you plan to add.
. Click btn:[Submit].

.Verification
After your subscription has been accepted, subscription details are displayed. A status of _Compliant_ indicates your subscription is in compliance with the number of hosts you have automated within your subscription count. Otherwise, your status will show as _Out of Compliance_, indicating you have exceeded the number of hosts in your subscription.

Other important information displayed include the following:

Hosts automated:: Host count automated by the job, which consumes the license count
Hosts imported:: Host count considering all inventory sources (does not impact hosts remaining)
Hosts remaining:: Total host count minus hosts automated
