[id="controller-deprovision-instances"]

= Deprovisioning instances

Re-running the setup playbook does not automatically deprovision instances since clusters do not currently distinguish between an instance that was taken offline intentionally or due to failure. 
Instead, shut down all services on the {ControllerName} instance and then run the deprovisioning tool from any other instance.

.Procedure

. Shut down the instance or stop the service with the command: `automation-controller-service stop`.
. Run the following deprovision command from another instance to remove it from the {ControllerName} cluster:
+
[literal, options="nowrap" subs="+attributes"]
----
$ awx-manage deprovision_instance --hostname=<name used in inventory file>
----

.Example
[literal, options="nowrap" subs="+attributes"]
----
awx-manage deprovision_instance --hostname=hostB
----

Deprovisioning instance groups in {ControllerName} does not automatically deprovision or remove instance groups.
For more information, see the xref:controller-deprovision-instance-group[Deprovisioning instance groups] section.
