[id="approving-the-imported-collection_{context}"]

= Approving the Imported Collection


After you have imported collections with either the GUI or the CLI method, you must approve them by using the GUI. After they are approved, they are available for use.

.Procedure

. Login to private automation hub web console.

. Go to menu:Collections[Approval].

. Click btn:[Approve] for the collection you wish to approve.

. The collection is now available for use in your private automation hub.

NOTE: The collection is added to the "Published" repository regardless of its source.

. Import any dependency for the collection using these same steps.

Recommended collections depend on your use case. Ansible and Red Hat provide link:https://console.redhat.com/ansible/automation-hub[these collections.]

== Custom Execution Environments

Use the ansible-builder program to create custom execution environment images. For disconnected environments, custom EE images can be built in the following ways:

* Build an EE image on an internet-facing system and import it to the
disconnected environment
* Build an EE image entirely on the disconnected environment with some modifications to the normal process of using ansible-builder
* Create a minimal base container image that includes all of the necessary modifications for a disconnected environment, then build custom EE images from the base container image

=== Transferring a Custom EE Images Across a Disconnected Boundary

A custom execution environment image can be built on an internet-facing machine using the existing documentation.  Once an execution environment has been created it is available in the local podman image cache. You can then transfer the custom EE image across a disconnected boundary. To transfer the custom EE image across a disconnected boundary, first save the image:

. Save the image:
----
$ podman image save localhost/custom-ee:latest | gzip -c custom-ee-latest.tar.gz
----

Transfer the file across the disconnected boundary by using an existing mechanism such as sneakernet, one-way diode, etc..  After the image is available on the disconnected side, import it into the local podman cache, tag it, and push it to the disconnected hub:

----
$ podman image load -i custom-ee-latest.tar.gz
$ podman image tag localhost/custom-ee <hub_fqdn>/custom-ee:latest
$ podman login <hub_fqdn> --tls-verify=false
$ podman push <hub_fqdn>/custom-ee:latest
----
