[id="proc-set-custom-pod-timeout"]

.Extra settings
With `extra_settings`, you can pass multiple custom settings using the awx-operator. 
The parameter `extra_settings` is appended to `/etc/tower/settings.py` and can be an alternative to the `extra_volumes` parameter.

[cols="20%,20%,20%",options="header"]
|====
| Name | Description |Default
| `extra_settings` | Extra settings | ‘’
|====

.Example configuration of `extra_settings` parameter

[options="nowrap" subs="+quotes,attributes"]
----
 spec:
    extra_settings:
      - setting: MAX_PAGE_SIZE
        value: "500"

      - setting: AUTH_LDAP_BIND_DN
        value: "cn=admin,dc=example,dc=com"

      - setting: SYSTEM_TASK_ABS_MEM
        value: "500"
----

= Custom pod timeouts

A container group job in {ControllerName} transitions to the `running` state just before you submit the pod to the Kubernetes API. 
{ControllerNameStart} then expects the pod to enter the `Running` state before `AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` seconds has elapsed. 
You can set `AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` to a higher value if you want {ControllerName} to wait for longer before cancelling jobs that fail to enter the `Running` state.
`AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` is how long {ControllerName} waits from creation of a pod until the Ansible work begins in the pod. 
You can also extend the time if the pod cannot be scheduled becaus of resource constraints. 
You can do this using `extra_settings` on the {Controllername} specification.
The default value is two hours. 

This is used if you are consistently launching many more jobs than Kubernetes can schedule, and jobs are spending periods longer than `AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` in _pending_. 

Jobs are not launched until control capacity is available. 
If many more jobs are being launched than the container group has capacity to run, consider scaling up your Kubernetes worker nodes.
