

[id="proc-attaching-subscriptions_{context}"]

= Attaching your {PlatformName} subscription

[role="_abstract"]
You *must* have valid subscriptions attached on all nodes before installing {PlatformName}. Attaching your {PlatformNameShort} subscription allows you to access subcription-only resources, such as {HubName} repositories.

To attach subscriptions to all your {PlatformNameShort} nodes, start by obtaining the `pool_id` of your Red Hat subscription, then run the `*subscription-manager attach*` command.

.Procedure

. Obtain the `pool_id` for your {PlatformName} subscription:
+
-----
# subscription-manager list --available --all | grep "Ansible Automation Platform" -B 3 -A 6
-----
+
.Example
An example output of the `*subsciption-manager list*` command. Obtain the `pool_id` as seen in the `Pool ID:` section:
+
-----
Subscription Name: Red Hat Ansible Automation, Premium (5000 Managed Nodes)
  Provides: Red Hat Ansible Engine
  Red Hat Ansible Automation Platform
  SKU: MCT3695
  Contract: ````
  Pool ID: <pool_id>
  Provides Management: No
  Available: 4999
  Suggested: 1
-----
+
. Attach the subscription:
+
-----
# subscription-manager attach --pool=<pool_id>
-----

You have now attached your {PlatformName} subscriptions to all nodes.

.Verification

* Verify the subscription was successfully attached:

-----
# subscription-manager list --consumed
-----

.Troubleshooting

* If you are unable to locate certain packages that came bundled with the {PlatformNameShort} installer, or if you are seeing a `_Repositories disabled by configuration_` message, try enabling the repository using the command:
+
----
subscription-manager repos --enable ansible-automation-platform-2.1-for-rhel-8-x86_64-rpms
----
