[id="proc-securing_secrets_in_inventory_{context}"]

= Securing secrets in the inventory file

You can encrypt sensitive or secret variables with Ansible Vault. 
However, encrypting the variable names as well as the variable values makes it hard to find the source of the values. 
To circumvent this, you can encrypt the variables individually using `ansible-vault encrypt_string`, or encrypt a file containing the variables.

.Procedure

. Create a file labeled `credentials.yml` to store the encrypted credentials.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ cat credentials.yml

admin_password: my_long_admin_pw
pg_password: my_long_pg_pw
registry_password: my_long_registry_pw
----
+
. Encrypt the `credentials.yml` file using `ansible-vault`.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ ansible-vault encrypt credentials.yml
New Vault password:
Confirm New Vault password:
Encryption successful
----
+
[IMPORTANT]
====
Store your encrypted vault password in a safe place.
====
+
. Verify that the `credentials.yml` file is encrypted.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ cat credentials.yml
$ANSIBLE_VAULT;1.1;
AES256363836396535623865343163333339613833363064653364656138313534353135303764646165393765393063303065323466663330646232363065316666310a373062303133376339633831303033343135343839626136323037616366326239326530623438396136396536356433656162333133653636616639313864300a353239373433313339613465326339313035633565353464356538653631633464343835346432376638623533613666326136343332313163343639393964613265616433363430633534303935646264633034383966336232303365383763
----
+
. Run `setup.sh` for installation of {PlatformNameShort} {PlatformVers} and pass both `credentials.yml` and the `--ask-vault-pass option`.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ ANSIBLE_BECOME_METHOD='sudo' ANSIBLE_BECOME=True ANSIBLE_HOST_KEY_CHECKING=False ./setup.sh -e @credentials.yml -- --ask-vault-pass
----