[id="proc-create-keycloak-instance_{context}"]

= Creating a Keycloak Instance

When the SSO operator is installed you can create a Keycloak instance for use with {PlatformNameShort}.

From here you provide an external Postgres or one will be created for you.

Use this procedure to create a keycloak instance.

.Procedure
. Navigate to menu:Operator[Installed Operators].
. Select the RH-SSO project.
. Select the Red Hat Single Sign-On Operator.
. On the Red Hat Single Sign-On Operator details page select btn:[Keycloak].
. Click btn:[Create].
. Click btn:[YAML view].
+
The default Keycloak customer resource is as follows:
+
[options="nowrap" subs="+quotes"]
----
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
	app: sso
  namespace: aap
spec:
  externalAccess:
	enabled: true
  instances: 1
----

. When deployment is complete, a route to launch the Administrative console is available.
You can find the credentials for the administrator in the `credential-<custom-resource>` (example keycloak) secret in the namespace.
