[id="proc-hub-ingress-options_{context}"]

= Configuring the Ingress type for your {ControllerName} operator

The {PlatformName} operator installation form allows you to further configure your {ControllerName} operator Ingress under *Advanced configuration*.

.Procedure

. Click *Advanced Configuration*.
. Under *Ingress type*, click the drop-down menu and select *Ingress*.
. Under *Ingress annotations*, enter any annotations to add to the ingress.
. Under *Ingress TLS secret*, click the drop-down menu and select a secret from the list.

After you have configured your {HubName} operator, click *Create* at the bottom of the form view. {OCP} will now create the pods. This may take a few minutes.

You can view the progress by navigating to menu:Workloads[Pods] and locating the newly created instance.

.Verification

Verify that the following operator pods provided by the {PlatformNameShort} Operator installation from {HubName} are running:
[cols="a,a,a"]
|===
| automation-controller-operator-controller-manager | {HubName} | {ControllerName}

|
* automation-hub-operator-controller-manager
* Resource-operator-controller-manager
|
* controller
* controller-postgres
|
* Api
* <deployment-name>-ui
* Content
* Worker
* Postgres

|===

[NOTE]
====
A missing pod can indicate the need for a pull secret. Pull secrets are required for protected or private image registries. See link:https://docs.openshift.com/container-platform/4.11/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets] for more information.
====
