

// [id="proc-editing-installer-inventory-file_{context}"]


= Editing the {PlatformName} installer inventory file

[role="_abstract"]
You can use the {PlatformName} installer inventory file to specify your installation scenario.


[NOTE]
====
* Using *external databases*: ensure the database sections of your inventory file are properly setup.
* Add {HubName} information in the `[automationhub]` group
* {HubName} and {ControllerName} cannot be installed on the same node.
* {ControllerName} will not configure replication or failover for the database that it uses. {ControllerName} should work with any replication you have.
* The database server should be on the same network or in the same data center as the {ControllerName} server for performance reasons.
* A container registry service is required to install the {PlatformNameShort}. By default, the {PlatformNameShort} uses `registry.redhat.io`, which requires a Red Hat registry service account. See the https://access.redhat.com/RegistryAuthentication#creating-registry-service-accounts-6[Creating Registry Service Accounts] guide to create a registry service account.
* For *upgrading an existing cluster*: When upgrading a cluster, you may decide that you want to also reconfigure your cluster to omit existing instances or instance groups. Omitting the instance or the instance group from the inventory file will not be enough to remove them from the cluster. In addition to omitting instances or instance groups from the inventory file, you must also link:https://docs.ansible.com/ansible-tower/3.8.3/html/administration/clustering.html#ag-cluster-deprovision[deprovision instances or instance groups] before starting the upgrade. Otherwise, omitted instances or instance groups will continue to communicate with the cluster, which can cause issues with tower services during the upgrade.
* For *clustered installations*: If you are creating a clustered setup, you must replace `localhost` with the hostname or IP address of all instances. All nodes/instances must be able to reach any others using this hostname or address. In other words, you cannot use the `localhost ansible_connection=local` on one of the nodes AND all of the nodes should use the same format for the host names.
====

[IMPORTANT]
====
* Root access to remote machines is required. With Ansible, this can be achieved in different ways:
* `ansible_user=root ansible_ssh_pass=”your_password_here”` inventory host or group variables
* `ansible_user=root ansible_ssh_private_key_file=”path_to_your_keyfile.pem”` inventory host or group variables
* `ANSIBLE_BECOME_METHOD=’sudo’ ANSIBLE_BECOME=True ./setup.sh`

For more information on `become` plugins, see link:https://docs.ansible.com/ansible/latest/user_guide/become.html#understanding-privilege-escalation[Understanding privilege escalation].
====

.Procedure

. Navigate to the installer
.. [bundled installer]
+
-----
$ cd ansible-automation-platform-setup-bundle-<latest-version>
-----
+
.. [online installer]
+
-----
$ cd ansible-automation-platform-setup-<latest-version>
-----
+
. Open the `inventory` file with a text editor.
. Edit `inventory` file parameters to specify your installation scenario. Follow the example below.
