
[id="proc-deploy-eda-controller-with-aap-operator-ocp_{context}"]



.Prerequisites

* You have installed {OperatorPlatform} on {OCPShort}.
* You have installed and configured {ControllerName}.

.Procedure

. Select menu:Operators[Installed Operators].

. Locate and select your installation of {PlatformNameShort}.

. Under *Provided APIs*, locate the {EDAName} modal and click *Create instance*. 
+
This takes you to the Form View to customize your installation. 
+
[IMPORTANT]
====
To ensure that you can run concurrent {EDAName} activations efficiently, you must set your maximum number of activations in proportion to the resources available on your cluster. You can do this by adjusting your {EDAName} settings in the YAML view. 

When you activate an {EDAName} rulebook under standard conditions, it uses approximately 250 MB of memory. However, the actual memory consumption can vary significantly based on the complexity of your rules and the volume and size of the events processed. In scenarios where a large number of events are anticipated or the rulebook complexity is high, conduct a preliminary assessment of resource usage in a staging environment. This ensures that your maximum number of activations is based on the capacity of your resources. 
====
+
. Click btn:[YAML view] to update your YAML key values. 

. Copy and paste the following string at the end of the `spec` key value section:
+
----
extra_settings:
  - setting: EDA_MAX_RUNNING_ACTIVATIONS
    value: '12'
----
+
. Click btn[Reload] and btn[Save]. Return to the Form view.

. In the *Name* field, enter the name you want for your new {EDAcontroller} deployment. 
+
[IMPORTANT]
====
If you have other {PlatformNameShort} components installed in your current {OCPShort} namespace, ensure that you provide a unique name for your {EDAcontroller} when you create your {EDAName} custom resource. Otherwise, naming conflicts can occur and impact {EDAcontroller} deployment.
====
+
. Specify your controller URL. 
+
If you deployed {ControllerName} in Openshift as well, you can find the URL in the navigation panel under menu:Networking[Routes].
+
[NOTE]
====
This is the only required customization, but you can customize other options using the UI form or directly in the YAML configuration tab, if desired.
====

. Click btn:[Create].
This deploys {EDAcontroller} in the namespace you specified. 
+
After a couple minutes when the installation is marked as *Successful*, you can find the URL for the {EDAName} UI on the *Routes* page in the Openshift UI. 

. From the navigation panel, select menu:Networking[Routes] to find the new Route URL that has been created for you. 
+
Routes are listed according to the name of your custom resource.

. Click the new URL to navigate to {EDAName} in the browser.

. From the navigation panel, select menu:Workloads[Secrets] and locate the Admin Password k8s secret that was created for you, unless you specified a custom one.
+
Secrets are listed according to the name of your custom resource and appended with `-admin-password.`
+
[NOTE]
====
You can use the password value in the secret to log in to the {EDAcontroller} UI. The default user is `admin`.
====





