
[id="proc-operator-external-db-controller"]

= Configuring an external database for {ControllerName} on {PlatformName} operator

[role="_abstract"]
For users who prefer to deploy {PlatformNameShort} with an external database, they can do so by configuring a secret with instance credentials and connection information, then applying it to their cluster using the `oc create` command.

By default, the {PlatformName} operator automatically creates and configures a managed PostGreSQL pod in the same namespace as your {PlatformNameShort} deployment. A user may instead choose to use an external database if they prefer to use a dedicated node to ensure dedicated resources or to manually manage backups, upgrades, or performance tweaks. The following section outlines the steps to configure an external database for your {ControllerName} on a {PlatformNameShort} operator.

.Prerequisite
The external database must be a PostgreSQL database that is the version supported by the current release of {PlatformNameShort}.

NOTE: {PlatformNameShort} 2.0 and 2.1 supports PostgreSQL 12

.Procedure

The external postgres instance credentials and connection information will need to be stored in a secret, which will then be set on the {ControllerName} spec.

. Create a `postgres_configuration_secret` .yaml file, following the template below:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-configuration
  namespace: <target_namespace>
stringData:
  host: <external_ip_or_url_resolvable_by_the_cluster>
  port: <external_port> <1>
  database: <desired_database_name>
  username: <username_to_connect_as>
  password: <password_to_connect_with> <2>
  sslmode: prefer <3>
  type: unmanaged
type: Opaque
----
<1> External port defaults to `5432`
<2> Value for variable `password` should not contain single or double quotes (', ") or backslashes (\) to avoid any issues during deployment, backup or restoration.
<3> The variable `sslmode` is valid for `external` databases only. The allowed values are: `*prefer*`, `*disable*`, `*allow*`, `*require*`, `*verify-ca*`, and `*verify-full*`.
. Apply `external-postgres-configuration-secret.yml` to your cluster using the `oc create` command.
+
----
$ oc create -f external-postgres-configuration-secret.yml
----
. When creating your `AutomationController` custom resource object, specify the secret on your spec, following the example below:
+
----
apiVersion: awx.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controller-dev
spec:
  postgres_configuration_secret: external-postgres-configuration
----
