[id="proc-synchronizing-rpm-repositories-by-using-reposync_{context}"]

= Synchronizing RPM repositories by using reposync

To perform a reposync you need a RHEL host that has access to the Internet. After the repositories are synced,  you can move the repositories to the disconnected network hosted from a web server.

.Procedure

. Attach the BaseOS and AppStream required repositories:
+
----
# subscription-manager repos \
    --enable rhel-8-for-x86_64-baseos-rpms \
    --enable rhel-8-for-x86_64-appstream-rpms
----

. Perform the reposync:
+
----
# dnf install yum-utils
# reposync -m --download-metadata --gpgcheck \
    -p /path/to/download
----

.. Make certain that you use reposync with `--download-metadata` and without `--newest-only`. See [RHEL 8] Reposync.

.. If not using `--newest-only` the repos downloaded will be ~90GB.

.. If using `--newest-only` the repos downloaded will be ~14GB.

. If you plan to use Red Hat Single Sign-On (RHSSO) you must also sync these repositories.

.. jb-eap-7.3-for-rhel-8-x86_64-rpms
.. rh-sso-7.4-for-rhel-8-x86_64-rpms

+
After the reposync is completed your repositories are ready to use with a web server.

. After the reposync is completed your repositories are ready to use with a web server.

. Move the repositories to your disconnected network.
