[id="proc-set-custom-pod-timeout"]

= Custom pod timeouts

A container group job in {ControllerName} will transition to the `running` state just before you submit the pod to the kubernetes API. 
{ControllerNameStart} then expects the pod to enter the `Running` state before `awx_container_group_pod_pending_timeout` seconds has elapsed. 
You can set `awx_container_group_pod_pending_timeout` to a higher value if you want {ControllerName} to wait for longer before cancelling jobs that fail to enter the `Running` state.

For further information about pod scheduling, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{OCPLatest}/html/nodes/controlling-pod-placement-onto-nodes-scheduling[Controlling pod placement onto nodes].

.Extra settings
With `extra_settings`, you can pass multiple custom settings using the awx-operator. 
The parameter `extra_settings` is appended to `/etc/tower/settings.py` and can be an alternative to the `extra_volumes` parameter.

[cols="20%,20%,20%",options="header"]
|====
| Name | Description |Default
| `extra_settings` | Extra settings | ‘’
|====

.Example configuration of `extra_settings` parameter

[options="nowrap" subs="+quotes,attributes"]
----
 spec:
    extra_settings:
      - setting: MAX_PAGE_SIZE
        value: "500"

      - setting: AUTH_LDAP_BIND_DN
        value: "cn=admin,dc=example,dc=com"

      - setting: SYSTEM_TASK_ABS_MEM
        value: "500"
----

This is used if you are consistently launching many more jobs than kubernetes can schedule, and jobs are spending periods longer than `AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` in pending. 

Jobs are not launched until control capacity is available. 
If many more jobs are being launched than the container group has capacity to run, consider scaling up your kubernetes worker nodes.
