[id="proc-import-mesh-ca_{context}"]

= Importing a Certificate Authority (CA) certificate

A Certificate Authority (CA) is used to certify and sign execution nodes in an {AutomationMesh} environment. Users who wish to provide their own CA can do so by specifying the path to the certificate and the private RSA key file in the `inventory` file of their {PlatformName} installer.

NOTE: Users are not required to have a CA prior to their {AutomationMesh} installation. Users without a CA can proceed with their {PlatformNameShort} installation where the installer will generate a CA for the user using OpenSSL.

.Procedure

. Open the `inventory` file for editing.
. Add the `mesh_ca_keyfile` variable and specify the full path to the CA certificate file (.crt).
. Add the `mesh_ca_certfile` variable and specify the full path to the private RSA key (.key).
. Save the changes to the inventory file.

.Example
[subs="+quotes"]
----
[all:vars]
mesh_ca_keyfile=/tmp/__<mesh_CA>__.key
mesh_ca_certfile=/tmp/__<mesh_CA>__.crt
----

With the CA files added to the inventory file, run the installer to apply the CA. This process copies and stores the CA on each control node on your network. By default, the certfile and keyfile will be added to `/etc/receptor/tls/ca/`.

.Optional: Assigning CA certificates to individual nodes
Users can also assign CA certificates to individual nodes by adding the `mesh_node_certfile=` and `mesh_node_keyfile=` fields to each node, following the example below:
----
[automationcontroller]
121-addr.tatu.home ansible_host=192.168.111.121  node_type=hybrid mesh_node_certfile=/tmp/192.168.111.121.crt mesh_node_keyfile=/tmp/192.168.111.121.key
----
