// Used in
// assemblies/platform/assembly-installing-aap-operator-cli.adoc
// titles/aap-operator-installation/

[id="proc-cli-get-controller-pwd{context}"]

= Fetching {ControllerNameStart} login details from the {OCPShort} CLI

To login to the {ControllerNameStart}, you need the web address and the password.

== Fetching the {ControllerName} web address

A {OCP} route exposes a service at a host name, so that external clients can reach it by name.
When you created the {ControllerName} instance, a route was created for it.
The route inherits the name that you assigned to the {ControllerName} object in the YAML file.

Use the following command to fetch the routes:

[subs="+quotes"]
-----
oc get routes -n __<controller_namespace>__
-----

In the following example, the `_example_` {ControllerName} is running in the `_ansible-automation-platform_` namespace.

-----
$ oc get routes -n ansible-automation-platform

NAME      HOST/PORT                                              PATH   SERVICES          PORT   TERMINATION     WILDCARD
example   example-ansible-automation-platform.apps-crc.testing          example-service   http   edge/Redirect   None
-----

The address for the {ControllerName} instance is `example-ansible-automation-platform.apps-crc.testing`.

== Fetching the {ControllerName} password

The YAML block for the {ControllerName} instance in [filename]`sub.yaml` assigns values to the _name_ and _admin_user_ keys.
Use these values in the following command to fetch the password for the {ControllerName} instance.

-----
oc get secret/<controller_name>-<admin_user>-password -o yaml
-----

The default value for _admin_user_ is `_admin_`. Modify the command if you changed the admin username in [filename]`sub.yaml`.

The following example retrieves the password for an {ControllerName} object called `_example_`: 

-----
oc get secret/example-admin-password -o yaml
-----

The password for the {ControllerName} instance is listed in the `metadata` field in the output:

-----
$ oc get secret/example-admin-password -o yaml

apiVersion: v1
data:
  password: ODzLODzLODzLODzLODzLODzLODzLODzLODzLODzLODzL
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Secret","metadata":{"labels":{"app.kubernetes.io/component":"automationcontroller","app.kubernetes.io/managed-by":"automationcontroller-operator","app.kubernetes.io/name":"example","app.kubernetes.io/operator-version":"","app.kubernetes.io/part-of":"example"},"name":"example-admin-password","namespace":"ansible-automation-platform"},"stringData":{"password":"88TG88TG88TG88TG88TG88TG88TG88TG"}}'
  creationTimestamp: "2021-11-03T00:02:24Z"
  labels:
    app.kubernetes.io/component: automationcontroller
    app.kubernetes.io/managed-by: automationcontroller-operator
    app.kubernetes.io/name: example
    app.kubernetes.io/operator-version: ""
    app.kubernetes.io/part-of: example
  name: example-admin-password
  namespace: ansible-automation-platform
  resourceVersion: "185185"
  uid: 39393939-5252-4242-b929-665f665f665f

-----

For this example, the password is `88TG88TG88TG88TG88TG88TG88TG88TG`.
