[id="completing-post-installation-tasks_{context}"]

= Completing Post Installation Tasks

== Adding Controller Subscription

.Procedure

. Navigate to the FQDN of the {ControllerNameStart}. Login with admin and the password you specified as `admin_password` in your inventory file.

. Click btn:[Browse] and select the __manifest.zip__ you created earlier.

. Click btn:[Next].

. Uncheck btn:[User analytics] and btn:[Automation analytics]. These rely on an Internet connection and should be turned off.

. Click btn:[Next].

. Read the End User License Agreement and click btn:[Submit] if you agree.

== Updating the CA trust store

=== Self-Signed Certificates

By default, AAP hub and controller are installed using self signed certificates. This creates an issue where the controller does not trust the hub’s certificate and will not download the execution environments from the hub. The solution is to import the hub’s CA cert as a trusted cert on the controller. You can use SCP or directly copy and paste from one file into another to perform this action. The steps below are copied from a KB article found at https://access.redhat.com/solutions/6707451.

=== Copying the root certificate on the private {HubName} to the {ControllerName} using secure copy (SCP)

If SSH is available as the root user between the controller and the private automation hub, use SCP to copy the root certificate on the private automation hub to the controller and run `update-ca-trust` on the controller to update the CA trust store.

On the {ControllerNameStart}
----
$ sudo -i
# scp <hub_fqdn>:/etc/pulp/certs/root.crt
/etc/pki/ca-trust/source/anchors/automationhub-root.crt
# update-ca-trust
----

=== Copying and Pasting

If SSH is unavailable as root between the private automation hub and the controller, copy the contents of the file __/etc/pulp/certs/root.crt__ on the private automation hub and paste it into a new file on the controller called __/etc/pki/ca-trust/source/anchors/automationhub-root.crt__. After the new file is created, run the command `update-ca-trust` in order to update the CA trust store with the new certificate.

On the {PrivateHubNameStart}
----
$ sudo -i
# cat /etc/pulp/certs/root.crt
(copy the contents of the file, including the lines with 'BEGIN CERTIFICATE' and
'END CERTIFICATE')
----

On the {ControllerNameStart}
----
$ sudo -i
# vi /etc/pki/ca-trust/source/anchors/automationhub-root.crt
(paste the contents of the root.crt file from the private automation hub into the new file and write to disk)
# update-ca-trust
----
