[id="proc-controller-credential-create-openshift-account"]

= Creating a service account in an Openshift cluster

Creating a service account in an Openshift or Kubernetes cluster  to be used to run jobs in a container group through {ControllerName}. 
After you create the service account, its credentials are provided to {ControllerName} in the form of an Openshift or Kubernetes API bearer token credential. 

After you create a service account, use the information in the new service account to configure {ControllerName}.

.Procedure
. To create a service account, download and use the link:https://docs.ansible.com/automation-controller/latest/html/userguide/_downloads/7a0708e6c2113e9601bf252270fa6c50/containergroup-sa.yml[sample service account] and change it as required to obtain the previous credentials.
. Apply the configuration from the link:https://docs.ansible.com/automation-controller/latest/html/userguide/_downloads/7a0708e6c2113e9601bf252270fa6c50/containergroup-sa.yml[sample service account]:
+
[literal, options="nowrap" subs="+attributes"]
----
oc apply -f containergroup-sa.yml
----
. Get the secret name associated with the service account:
+
[literal, options="nowrap" subs="+attributes"]
----
export SA_SECRET=$(oc get sa containergroup-service-account -o json | jq '.secrets[0].name' | tr -d '"')
----
. Get the token from the secret:
+
[literal, options="nowrap" subs="+attributes"]
----
oc get secret $(echo ${SA_SECRET}) -o json | jq '.data.token' | xargs | base64 --decode > containergroup-sa.token
----
. Get the CA cert:
+
[literal, options="nowrap" subs="+attributes"]
----
oc get secret $SA_SECRET -o json | jq '.data["ca.crt"]' | xargs | base64 --decode > containergroup-ca.crt
----
. Use the contents of `containergroup-sa.token` and `containergroup-ca.crt` to provide the information for the xref:ref-controller-credential-openShift[OpenShift or Kubernetes API Bearer Token] required for the container group.

 