

// [id="proc-choosing-obtaining-installer_{context}"]


= Choosing and obtaining a {PlatformName} installer

[role="_abstract"]
Choose the {PlatformName} installer you need based on your Red Hat Enterprise Linux environment internet connectivity. Review the scenarios below and determine which {PlatformName} installer meets your needs.

[NOTE]
====
A valid Red Hat customer account is required to access {PlatformName} installer downloads on the Red Hat Customer Portal.
====

.Installing with internet access

Choose the {PlatformName} installer if your Red Hat Enterprise Linux environment is connected to the internet. Installing with internet access retrieves the latest required repositories, packages, and dependencies. Choose one of the following ways to set up your {PlatformNameShort} installer.

*Tarball install*

. Navigate to the link:{PlatformDownloadUrl}[{PlatformName} download] page.
. Click btn:[Download Now] for the *Ansible Automation Platform <latest-version> Setup*.
. Extract the files:
+
-----
$ tar xvzf ansible-automation-platform-setup-<latest-version>.tar.gz
-----

*RPM install*

. Install Ansible Automation Platform Installer Package
+
v.{PlatformVers} for RHEL 8 for x86_64
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms ansible-automation-platform-installer
----
+
v.{PlatformVers} for RHEL 9 for x86-64
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms ansible-automation-platform-installer
----

[NOTE]
`dnf install` enables the repo as the repo is disabled by default.

When you use the RPM installer, the files are placed under the `/opt/ansible-automation-platform/installer` directory.

.Installing without internet access

Use the {PlatformName} *Bundle* installer if you are unable to access the internet, or would prefer not to install separate components and dependencies from online repositories. Access to {RHEL} repositories is still needed. All other dependencies are included in the tar archive.

. Navigate to the link:{PlatformDownloadUrl}[{PlatformName} download] page.
. Click btn:[Download Now] for the *Ansible Automation Platform <latest-version> Setup Bundle*.
. Extract the files:
+
-----
$ tar xvzf ansible-automation-platform-setup-bundle-<latest-version>.tar.gz
-----
