[id="proc-enable-pods-ref-images"]

== Enabling pods to reference images from other secured registries

This section describes how to create image pull secrets.

The .dockercfg file (or `$HOME/.docker/config.json` for newer Docker clients) is a Docker credentials file that stores your information if you have previously logged into a secured or insecure registry.

.Procedure
. To pull a secured container image that is not from the {OCP} internal registry, you must create a pull secret from your Docker credentials and add it to your service account.
+
If you already have a `.dockercfg` file for the secured registry, you can create a secret from that file by running:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ oc create secret generic <pull_secret_name> \ 
--from-file=.dockercfg=<path/to/.dockercfg> \ 
--type=kubernetes.io/dockercfg
----
+
Or if you have a `$HOME/.docker/config.json` file:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ oc create secret generic <pull_secret_name> \ 
--from-file=.dockerconfigjson=<path/to/.docker/config.json> \ 
--type=kubernetes.io/dockerconfigjson
----

. If you do not already have a Docker credentials file for the secured registry, you can create a secret by running:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ oc create secret docker-registry <pull_secret_name> \
--docker-server=<registry_server> \
--docker-username=<user_name> \ 
--docker-password=<password> \ 
--docker-email=<email>
----
+
. To use a secret for pulling images for pods, you must add the secret to your service account. 
The name of the service account in this example should match the name of the service account the pod uses.
The default is the default service account.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ oc secrets link default <pull_secret_name> --for=pull
----
+
. To use a secret for pushing and pulling build images, the secret must be mountable inside a pod. 
You can do this by running:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ oc secrets link builder <pull_secret_name>
----
+ 
. For builds, you must also reference the secret as the pull secret from within your build configuration.

When the container group is successfully created, the Details tab of the newly created container group remains, which allows you to review and edit your container group information. 
This is the same menu that is opened if you click btn:[Edit] from the *Instance Group* link. 
You can also edit Instances and review Jobs associated with this instance group.

