



// [id="proc-verify-controller-installation_{context}"]

= Verifying {ControllerName} installation

[role="_abstract"]
Once the installation completes, you can verify your {ControllerName} has been installed successfully by logging in with the admin credentials you inserted into the `inventory` file.

.Procedure
. Navigate to the IP address specified for the {ControllerName} node in the `inventory` file.
. Log in with the Admin credentials you set in the `inventory` file.

[NOTE]
====
The {ControllerName} server is accessible from port 80 (*https://<TOWER_SERVER_NAME>/*) but will redirect to port 443 so 443 needs to be available also.
====

[IMPORTANT]
====
If the installation fails and you are a customer who has purchased a valid license for {PlatformName}, please contact Ansible via the Red Hat Customer portal at https://access.redhat.com/.
====

Your {ControllerName} is now ready for initial configuration.


[role="_additional-resources"]
== Next steps

* See link:https://docs.ansible.com/ansible-tower/latest/html/administration/index.html[Automation Controller Administration Guide] for administration through customer scripts, management jobs, and more.
* For quick setup of {ControllerName}, see the link:https://docs.ansible.com/ansible-tower/latest/html/quickstart/index.html[Automation Controller Quick Setup Guide].
* Review {ControllerName} functionality in the link:https://docs.ansible.com/ansible-tower/latest/html/userguide/index.html[Automation Controller User Guide].
