//Used in downstream/titles/aap-installation-guide/platform/assembly-disconnected-installation.adoc

:_newdoc-version: 2.15.1
:_template-generated: 2024-02-05
:_mod-docs-content-type: PROCEDURE

[id="creating-the-custom-execution-environment-definition_{context}"]
= Creating the custom {ExecEnvShort} definition

[role="_abstract"]

Once the {Builder} RPM is installed, use the following steps to create your custom {ExecEnvShort}.

. Create a directory for the build artifacts used when creating your custom {ExecEnvShort}.	Any new files created with the steps below will be created under this directory.
+
----
$ mkdir $HOME/custom-ee $HOME/custom-ee/files
$ cd $HOME/custom-ee/
----
+

. Create an `execution-environment.yml` file that defines the requirements for your custom {ExecEnvShort}. 
+
[NOTE]

====
Version 3 of the execution environment definition format is required, so ensure the `execution-environment.yml` file contains `version: 3` explicitly before continuing.
====
+
.. Override the base image to point to the minimal execution environment available in your {PrivateHubName}.

.. Define the additional build files needed to point to any disconnected content sources that will be used in the build process.
Your custom `execution-environment.yml` file should look similar to the following example:

+
----
$ cat execution-environment.yml
---
version: 3

images:
  base_image:
    name: private-hub.example.com/ee-minimal-rhel8:latest

dependencies:
  python: requirements.txt
  galaxy: requirements.yml

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
  - src: files/pip.conf
    dest: configs
  - src: files/hub-ca.crt
    dest: configs
  # uncomment if custom RPM repositories are required
  #- src: files/custom.repo
  #  dest: configs

additional_build_steps:
  prepend_base:
    # copy a custom pip.conf to override the location of the PyPI content
    - ADD _build/configs/pip.conf /etc/pip.conf
    # remove the default UBI repository definition
    - RUN rm -f /etc/yum.repos.d/ubi.repo
    # copy the hub CA certificate and update the trust store
    - ADD _build/configs/hub-ca.crt /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
    # if needed, uncomment to add a custom RPM repository configuration
    #- ADD _build/configs/custom.repo /etc/yum.repos.d/custom.repo

  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg

...
----
+

. Create an `ansible.cfg` file under the `files/` subdirectory that points to your {PrivateHubName}.
+
----
$ cat files/ansible.cfg
[galaxy]
server_list = private_hub

[galaxy_server.private_hub]
url = https://private-hub.example.com/api/galaxy/
----
+
. Create a `pip.conf` file under the `files/` subdirectory which points to the internal PyPI mirror (a web server or something like Nexus):
+
----
$ cat files/pip.conf
[global]
index-url = https://<pypi_mirror_fqdn>/
trusted-host = <pypi_mirror_fqdn>
----
+

. Optional: If a `bindep.txt` file is being used to add RPMs the custom {ExecEnvShort}, create a `custom.repo` file under the `files/` subdirectory that points to your disconnected Satellite or other location hosting the RPM repositories.  If this step is necessary, uncomment the steps in the example `execution-environment.yml` file that correspond with the `custom.repo` file.
+

The following example is for the UBI repos. Other local repos can be added to this file as well. The URL path may need to change depending on where the mirror content is located on the web server. 
+
----
$ cat files/custom.repo
[ubi-8-baseos]
name = Red Hat Universal Base Image 8 (RPMs) - BaseOS
baseurl = http://<ubi_mirror_fqdn>/repos/ubi-8-baseos
enabled = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
gpgcheck = 1

[ubi-8-appstream]
name = Red Hat Universal Base Image 8 (RPMs) - AppStream
baseurl = http://<ubi_mirror_fqdn>/repos/ubi-8-appstream
enabled = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
gpgcheck = 1
----
+
. Add the CA certificate used to sign the private automation hub web server certificate. If the private automation hub uses self-signed certificates provided by the installer:
+
.. Copy the file `/etc/pulp/certs/pulp_webserver.`crt` from your private automation hub and name it `hub-ca.crt`.

.. Add the `hub-ca.crt` file to the `files/`` subdirectory.
+

If the {PrivateHubName} uses user-provided certificates signed by a certificate authority:
+
.. Make a copy of that CA certificate and name it `hub-ca.crt`.
.. Add the `hub-ca.crt` file to the `files/`` subdirectory.
+
. Once the preceeding steps have been completed, create your python `requirements.txt` and ansible collection `requirements.yml` files, with the content needed for your custom {ExecEnvShort} image. 
+

[NOTE]
====
Any required collections must already be uploaded into your {PrivateHubName}.
====
+
The following files should exist under the `custom-ee/` directory, with `bindep.txt` and `files/custom.repo` being optional:

----
$ cd $HOME/custom-ee
$ tree .
.
├── bindep.txt
├── execution-environment.yml
├── files
│   ├── ansible.cfg
│   ├── custom.repo
│   ├── hub-ca.crt
│   └── pip.conf
├── requirements.txt
└── requirements.yml

1 directory, 8 files
----




[role="_additional-resources"]
.Additional resources

For more information on the Version 3 format and requirements, see link:https://ansible-builder.readthedocs.io/en/stable/definition/[Execution Environment Definition: Version 3 Format] .
