[id="ref-controller-smart-host-filter"]

= Smart Host Filters

You can use a search filter to populate hosts for an inventory. This feature uses the the fact searching feature.

{ControllerNameStart} stores facts generated by an Ansible playbook during a Job Template in the database whenever `use_fact_cache=True` is set per-Job Template. 
New facts are merged with existing facts and are per-host. 
These stored facts can be used to filter hosts with the `/api/v2/hosts` endpoint, using the `GET` query parameter `host_filter`.

For example:
[literal, options="nowrap" subs="+attributes"]
----
/api/v2/hosts?host_filter=ansible_facts__ansible_processor_vcpus=8
----

The `host_filter` parameter permits:

* grouping with ()
* use of the boolean and operator:
** `__` to reference related fields in relational fields
** `__` is used on ansible_facts to separate keys in a JSON key path
** `[] is used to denote a json array in the path specification
** `""` can be used in the value when spaces are wanted in the value
* "classic" Django queries may be embedded in the `host_filter`

.Examples:

[literal, options="nowrap" subs="+attributes"]
----
/api/v2/hosts/?host_filter=name=localhost
/api/v2/hosts/?host_filter=ansible_facts__ansible_date_time__weekday_number="3"
/api/v2/hosts/?host_filter=ansible_facts__ansible_processor[]="GenuineIntel"
/api/v2/hosts/?host_filter=ansible_facts__ansible_lo__ipv6[]__scope="host"
/api/v2/hosts/?host_filter=ansible_facts__ansible_processor_vcpus=8
/api/v2/hosts/?host_filter=ansible_facts__ansible_env__PYTHONUNBUFFERED="true"
/api/v2/hosts/?host_filter=(name=localhost or name=database) and (groups__name=east or groups__name="west coast") and ansible_facts__an
----

You can search `host_filter` by *host name*, *group name*, and *Ansible facts*.

Group search has the following format:

[literal, options="nowrap" subs="+attributes"]
----
groups.name:groupA
----

Fact search has the following format:

[literal, options="nowrap" subs="+attributes"]
----
ansible_facts.ansible_fips:false
----

You can also perform Smart Search searches, which consist of a host name and host description.

[literal, options="nowrap" subs="+attributes"]
----
host_filter=name=my_host
----

[NOTE]
====
If a search term in `host_filter` is of string type, to make the value a number (for example, `2.66`) or a JSON keyword (for example, `null`, `true` or `false`) valid, add double quotations around the value to prevent the controller from parsing it as a non-string:

[literal, options="nowrap" subs="+attributes"]
----
host_filter=ansible_facts__packages__dnsmasq[]__version="2.66"
----
====