[id="ref-controller-example-workload-reqs"]

= Example workload requirements

For this example capacity planning exercise, use the following workload requirements: 

*Execution capacity*

* To run the 10 concurrent jobs requires at least 60 units of execution capacity. 

** You calculate this by using the following equation: (10 jobs * 5 forks) + (10 jobs * 1 base task impact of a job) = 60 execution capacity

*Control capacity*

* To control 10 concurrent jobs requires at least 10 units of control capacity.

* To calculate the number of events per hour that you need to support 300 managed hosts and 1,000 tasks per hour per host, use the following equation:

** 1000 tasks * 300 managed hosts per hour = 300,000 events per hour at minimum. 

** You must run the job to see exactly how many events it produces, because this is dependent on the specific task and verbosity. For example, a debug task printing “Hello World” produces 6 job events with the verbosity of 1 on one host. With a verbosity of 3, it produces 34 job events on one host. Therefore, you must estimate that the task produces at least 6 events. This would produce closer to 3,000,000 events per hour, or approximately 833 events per second.

*Determining quantity of execution and control nodes needed*

To determine how many execution and control nodes you need, reference the experimental results in the following table that shows the observed event processing rate of a single control node with 5 execution nodes of equal size (API Capacity column). The default “forks” setting of job templates is 5, so using this default, the maximum number of jobs a control node can dispatch to execution nodes makes 5 execution nodes of equal CPU/RAM use 100% of their capacity, arriving to the previously mentioned 1:5 ratio of control to execution capacity.