:_content-type: REFERENCE

[id="accessing-control-auto-hub-eda-control_{context}"]

= Accessing {ControllerName}, {HubName}, and {EDAcontroller}

[role="_abstract"]


After the installation completes, these are the default protocol and ports used:

* http/https protocol

* Ports 8080/8443 for {ControllerName}

* Ports 8081/8444 for {HubName}

* Ports 8082/8445 for {EDAcontroller}


These can be changed. Consult the *README.md* for further details. It is recommended that you leave the defaults unless you need to change them due to port conflicts or other factors.


.Accessing {ControllerName} UI

The {ControllerName} UI is available by default at:

----
https://<your_rhel_host>:8443
----

Log in as the admin user with the password you created for *controller_admin_password*.

If you supplied the license manifest as part of the installation, the {PlatformNameShort} dashboard is displayed. If you did not supply a license file, the *Subscription* screen is displayed where you must supply your license details. This is documented here: link:{BaseURL}/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_operations_guide/assembly-aap-activate[Chapter 1. Activating Red Hat Ansible Automation Platform]. 

.Accessing {HubName} UI

The {HubName} UI is available by default at:

----
https://<hub node>:8444
----

Log in as the admin user with the password you created for *hub_admin_password*.


.Accessing {EDAName} UI

The {EDAName} UI is available by default at:
----
https://<eda node>:8445
----

Log in as the admin user with the password you created for *eda_admin_password*.
