[id="ref-controller-set-up-kerberos-packages"]

= Set up the Kerberos packages

First set up the Kerberos packages in {Controllername} so that you can successfully generate a Kerberos ticket. 

Use the following commands to install the packages:

[literal, options="nowrap" subs="+attributes"]
----
yum install krb5-workstation
yum install krb5-devel
yum install krb5-libs
----

When installed, edit the `/etc/krb5.conf` file, as follows, to provide the address of the AD, the domain, and additional information:

[literal, options="nowrap" subs="+attributes"]
----
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = WEBSITE.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 WEBSITE.COM = {
  kdc = WIN-SA2TXZOTVMV.website.com
  admin_server = WIN-SA2TXZOTVMV.website.com
 }

[domain_realm]
 .website.com = WEBSITE.COM
 website.com = WEBSITE.COM
----

When the configuration file has been updated, use the following commands to authenticate and get a valid token:

[literal, options="nowrap" subs="+attributes"]
----
[root@ip-172-31-26-180 ~]# kinit username
Password for username@WEBSITE.COM:
[root@ip-172-31-26-180 ~]#
----

Check if you have a valid ticket.

[literal, options="nowrap" subs="+attributes"]
----
[root@ip-172-31-26-180 ~]# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: username@WEBSITE.COM

Valid starting     Expires            Service principal
01/25/23 11:42:56  01/25/23 21:42:53  krbtgt/WEBSITE.COM@WEBSITE.COM
  renew until 02/01/23 11:42:56
[root@ip-172-31-26-180 ~]#
----

When you have a valid ticket, you can check to ensure that everything is working as expected from the command line. 

To test this, your inventory should resemble the following:

[literal, options="nowrap" subs="+attributes"]
----
[windows]
win01.WEBSITE.COM

[windows:vars]
ansible_user = username@WEBSITE.COM
ansible_connection = winrm
ansible_port = 5986
----

You must also:

* Ensure that the hostname is the proper client hostname matching the entry in AD and is not the IP address.
* In the username declaration, ensure that the domain name (the text after `@`) is properly entered with regard to upper- and lower-case letters, as Kerberos is case sensitive. 
* For {ControllerName}, you must also ensure that the inventory looks the same.

[NOTE]
====
If you encounter a `Server not found in Kerberos database` error message, and your inventory is configured using FQDNs (*not IP addresses*), ensure that the service principal name is not missing or mis-configured.
====

Playbooks should run as expected. 
You can test this by running the playbook as the `awx` user.

When you have verified that playbooks work properly, you can integrate with {ControllerName}. 

Generate the Kerberos ticket as the `awx` user. 
{ControllerNameStart} automatically picks up the generated ticket for authentication.

[NOTE]
====
The python `kerberos` package must be installed. 
Ansible is designed to check if the `kerberos` package is installed and, if so, it uses kerberos authentication.
====