[id="ref-general-inventory-variables"]

= General variables

[cols="50%,50%",options="header"]
|====
| *Variable* | *Description*
| *`registry_password`* | Password credential for access to `registry_url`.

Used for both `[automation controller]` and `[automation hub]` groups.

Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.

The same applies in `registry_username`, but this is only if `registry_url` is registry.redhat.io.  
When it is `registry.redhat.io`, username and password are required if not using bundle installer.
| *`registry_url`* | Used for both `[automation controller]` and `[automation hub]` groups.

The default is `‘registry.redhat.io’`.
| *`registry_username`* | User credential for access to `registry_url`.

Used for both `[automation controller]` and `[automation hub]` groups.

Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.
|====



