[id="ref-instances-prerequisites"]

= Prerequisites

* Ensure that you have the minimum requirements for the RHEL virtual machine before proceeding. 
For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements[{PlatformName} system requirements].
* RHEL nodes must properly be subscribed to.
* RHEL subscription and with *baseos* and *appstream* repositories must be enabled.
* {PlatformNameShort} subscriptions and the proper {PlatformName} channel must be enabled:
+
[literal, options="nowrap" subs="+attributes"]
----
ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms for RHEL 8
ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms for RHEL 9
----

* The system that is going to run the `ansible-playbook` must have the `ansible.receptor` collection installed:
** If your system has access to the internet, use:
+
[literal, options="nowrap" subs="+attributes"]
----
ansible-galaxy install -r requirements.yml
----
+
Installing the receptor collection dependency from the `requirements.yml` file consistently retrieves the receptor version specified there. 
Additionally, it retrieves any other collection dependencies that might be needed in the future.

** If your system does not have access to the internet, see link:https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#downloading-a-collection-from-automation-hub[Downloading a collection from Automation Hub] to configure link:https://console.redhat.com/ansible/automation-hub[Automation Hub] in Ansible Galaxy locally.