:_content-type: REFERENCE

[id="accessing-control-auto-hub-eda-control_{context}"]
= accessing control auto hub {EDAName} controller

[role="_abstract"]
Write a short introductory paragraph that provides an overview of the module.

Accessing controller, automation hub, and EDA controller

Once the installation completes, these are the default protocol and ports used:

* https protocol

* Port 443 for controller

* Port 444 for automation hub

* Port 445 for EDA controller

These can be changed. Consult the README.md for further details. it is recommended that you leave the defaults unless you need to change them due to port conflicts or other factors.

.Accessing Automation Controller UI

The automation controller UI is available by default at:

----
https://<your_rhel_host>:443
----

Login as the admin user with the password you created for *controller_admin_password*.

If you supplied the license manifest as part of the installation, the AAP dashboard is displayed.If you did not supply a license file, the Subscription screen is displayed where you must supply your license details. This is documented here: https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_operations_guide/assembly-aap-activate. 

.Accessing Automation Hub UI

The automation hub UI is available by default at:
----
https://<hub node>:444
----

.Accessing Automation EDA UI

The Automation EDA UI is available by default at:
----
https://<eda node>:445
----
