[id="ref-controller-search-tips"]

= Rules for searching

These searching tips assume that you are not searching hosts. 
//Most of this section still applies to hosts but with some subtle differences. 

* The typical syntax of a search consists of a field, followed by a value. 
* A colon is used to separate the field that you want to search from the value. 
* If the search has no colon (see example 3) it is treated as a simple string search where `?search=foobar` is sent. 

The following are examples of syntax used for searching:

. `name:localhost` In this example, the user is searching for the string `localhost` in the name attribute. 
If that string does not match something from *Fields* or *Related Fields*, the entire search is treated as a string. 
. `organization.name:Default` This example shows a Related Field Search.
The period in `organization.name` separates the model from the field. 
Depending on how deep or complex the search is, you can have multiple periods in that part of the query.
. `foobar` This is a simple string (key term) search that finds all instances of the search term using an `icontains` search against the name and description fields. 
If you use a space between terms, for example `foo bar`, then results that contain both terms are returned. 
If the terms are wrapped in quotes, for example, `"foo bar"`, {ControllerName} searches for the string with the terms appearing together. 
+
Specific name searches search against the API name. For example, `Management job` in the user interface is `system_job` in the API.
. `organization:Default` This example shows a Related Field search but without specifying a field to go along with the organization. 
This is supported by the API and is analogous to a simple string search but carried out against the organization (does an `icontains` search against both the name and description).



