[id="ref-guidelines-hosts-groups"]

= Guidelines for hosts and groups

.Databases
* When using an external database, ensure the `[database]` sections of your inventory file are properly set up.
* To improve performance, do not colocate the database and the {ControllerName} on the same server.


.{HubNameStart}
* If there is an `[automationhub]` group, you must include the variables `automationhub_pg_host` and `automationhub_pg_port`.
* Add {HubNameMain} information in the `[automationhub]` group.
* Do not install {HubNameMain} and {ControllerName} on the same node.
* Provide a reachable IP address or fully qualified domain name (FQDN) for the `[automationhub]` and `[automationcontroller]` hosts to ensure that users can synchronize and install content from {HubNameMain} and {ControllerName} from a different node. 
Do not use `localhost`.

.{PrivateHubNameStart}
* Do not install {PrivateHubName} and {ControllerName} on the same node.
* You can use the same PostgreSQL (database) instance, but they must use a different (database) name.
* If you install {PrivateHubName} from an internal address, and have a certificate which only encompasses the external address, it can result in an installation you cannot use as a container registry without certificate issues.

[IMPORTANT]
====
You must separate the installation of {ControllerName} and {HubNameMain} because the `[database]` group does not distinguish between the two if both are installed at the same time. 

If you use one value in `[database]` and both {ControllerName} and {HubNameMain} define it, they would use the same database.
====

.{ControllerNameStart}
* {ControllerNameStart} does not configure replication or failover for the database that it uses.
* {ControllerName} works with any replication that you have.


.Clustered installations
* When upgrading an existing cluster, you can also reconfigure your cluster to omit existing instances or instance groups. 
Omitting the instance or the instance group from the inventory file is not enough to remove them from the cluster. 
In addition to omitting instances or instance groups from the inventory file, you must also deprovision instances or instance groups before starting the upgrade. See xref:ref-deprovisioning[Deprovisioning nodes or groups]. 
Otherwise, omitted instances or instance groups continue to communicate with the cluster, which can cause issues with {ControllerName} services during the upgrade.
* If you are creating a clustered installation setup, you must replace `[localhost]` with the hostname or IP address of all instances. 
Installers for {ControllerName} and {HubName} do not accept `[localhost]`
All nodes and instances must be able to reach any others by using this hostname or address. 
You cannot use the localhost `ansible_connection=local` on one of the nodes. 
Use the same format for the host names of all the nodes.
+
Therefore, this does not work:
+
[options="nowrap" subs="+quotes,attributes"]
----
[automationhub]
localhost ansible_connection=local
hostA
hostB.example.com
172.27.0.4
----
+
Instead, use these formats:
+
[options="nowrap" subs="+quotes,attributes"]
----
[automationhub]
hostA
hostB
hostC
----
+
or
+
[options="nowrap" subs="+quotes,attributes"]
----
[automationhub]
hostA.example.com
hostB.example.com
hostC.example.com
----

