

// [id="ref-platform-system-requirements_{context}"]

= {PlatformName} system requirements

Use this information when planning your {PlatformName} installations and designing {AutomationMesh} topologies that fit your use case.


[role="_abstract"]

Your system must meet the following minimum system requirements to install and run {PlatformName}.

.Red Hat Ansible Automation Platform system requirements

.Base system

[cols="a,a,a"]
|===
|  | Required | Notes

h| Subscription | Valid Red Hat Ansible Automation Platform |

h| OS | Red Hat Enterprise Linux 8.4 or later 64-bit (x86) |{PlatformName} is also supported on OpenShift, see link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index[Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform] for more information.

h| Ansible | version 2.11 (to install) | {PlatformNameShort} ships with execution environments that contain ansible-core {AnsibleCoreVers}.

h| Python | 3.8 or later |
|===

The following are necessary for you to work with project updates and collections:

* Ensure that the following domain names are part of either the firewall or the proxy's allowlist for successful connection and download of collections from {HubName} or Galaxy server:
** `galaxy.ansible.com`
** `cloud.redhat.com`
** `console.redhat.com`
** `sso.redhat.com`
* SSL inspection must be disabled either when using self signed certificates or for the Red Hat domains.

== Automation controller

{ControllerNameStart} is a distributed system, where different software components can be co-located or deployed across multiple compute nodes.
In the installer, node types of control, hybrid, execution, and hop are provided as abstractions to help the user design the topology appropriate for their use case.
The following table provides recommendations for node sizing:

[NOTE]
====
On all nodes except hop nodes, allocate a minimum of 20 GB to `/var/lib/awx` for execution environment storage.
====

[cols="a,a,a"]
|===



| *Execution nodes*| *Required* | *Notes*

h| RAM | 16 GB  |


h| CPUs | 4|

* Runs automation. Increase memory and CPU to increase capacity for running more forks



|*Control nodes* | *Required* | *Notes*

h| RAM | 16 GB  |


h| CPUs | 4|

* Processes events and runs cluster jobs including project updates and cleanup jobs. Increasing CPU and memory can help with job event processing.



| *Hybrid nodes*| *Required* | *Notes*

h| RAM | 16 GB  |


h| CPUs | 4|
* Runs both automation and cluster jobs, comments for both execution and control nodes apply to this node type.



|*Hop nodes*| *Required* | *Notes*

h| RAM | 16 GB  |


h| CPUs | 4|

* Serves to route traffic from one part of the Automation Mesh to another (for example, could be a bastion host into another network). RAM could affect throughput, CPU activity is low. Network bandwidth and latency generally a more important factor than either RAM/CPU.

h| Disk: service node | 40 GB dedicated hard disk space |

* *{ControllerName}*: dedicate a minimum of 20 GB to `/var/` for file and working directory storage
* Storage volume should be rated for a minimum baseline of 1500 IOPS.
* Projects are stored on control and hybrid, and for the duration of jobs, also on execution nodes. If the cluster has many large projects, consider having twice the GB in /var/lib/awx/projects, to avoid disk space errors.

|*Database node*| *Required* | *Notes*

h| RAM | 16 GB  |


h| CPUs | 4|

h| Disk | 20 GB dedicated hard disk space|

* Minimum dedicated hard disk space is 20 GB
* 150 GB+ recommended
* Storage volume should be rated for a high baseline IOPS (1500 or more).





h| Browser | A currently supported version of Mozilla FireFox or Google Chrome |

h| Database | PostgreSQL version 13 |

|===

[role="_additional-resources"]
.Additional resources
////
Optional. Delete if not used.
////
* To authorize the use of {ControllerName}, see link:https://docs.ansible.com/automation-controller/latest/html/userguide/import_license.html?extIdCarryOver=true&sc_cid=7013a00000388B5AAI[Import a subscription].


== Automation hub

{HubNameStart} enables you to discover and use new certified automation content from Red Hat Ansible and Certified Partners. 
On {HubNameMain}, you can discover and manage Ansible Collections, which are supported automation content developed by Red Hat and its partners for use cases such as cloud automation, network automation, and security automation.

Automation hub has the following system requirements:

[cols="a,a,a"]
|===
| | Required | Notes

h| RAM | 8 GB minimum |

* 8 GB RAM (minimum and recommended for Vagrant trial installations)
* 8 GB RAM (minimum for external standalone PostgreSQL databases)
* For capacity based on forks in your configuration, see additional resources

h| CPUs | 2 minimum |

* For capacity based on forks in your configuration, see additional resources

h| Disk: service node | 60 GB dedicated hard disk space |

* Storage volume should be rated for a minimum baseline of 1500 IOPS.

|*Database node*| *Required* | *Notes*

h| RAM | 16 GB  |


h| CPUs | 4|

h| Disk | 20 GB dedicated hard disk space|

* Minimum dedicated hard disk space is 20 GB
* 150 GB+ recommended
* Storage volume should be rated for a high baseline IOPS (1500 or more).

h| Browser | A currently supported version of Mozilla FireFox or Google Chrome |

h| Database | PostgreSQL version 13 |

|===

[NOTE]
====
* All {ControllerName} data is stored in the database. Database storage increases with the number of hosts managed, number of jobs run, number of facts stored in the fact cache, and number of tasks in any individual job.
For example, a playbook run every hour (24 times a day) across 250, hosts, with 20 tasks will store over 800000 events in the database every week.

* If not enough space is reserved in the database, old job runs and facts will need cleaned on a regular basis. Refer to link:https://docs.ansible.com/ansible-tower/3.8.3/html/administration/management_jobs.html#ag-management-jobs[Management Jobs] in the _Automation Controller Administration Guide_ for more information
====


.Amazon EC2

* Instance size of m5.large or larger
* An instance size of m4.xlarge or larger if there are more than 100 hosts

.Additional notes for {PlatformName} requirements

* Actual RAM requirements vary based on how many hosts {ControllerName} will manage simultaneously (which is controlled by the `forks` parameter in the job template or the system `ansible.cfg` file). To avoid possible resource conflicts, Ansible recommends 1 GB of memory per 10 forks + 2 GB reservation for {ControllerName}, see link:https://docs.ansible.com/automation-controller/latest/html/userguide/jobs.html#at-capacity-determination-and-job-impact[Automation controller Capacity Determination and Job Impact] for further details. If `forks` is set to 400, 42 GB of memory is recommended.
* A larger number of hosts can of course be addressed, though if the fork number is less than the total host count, more passes across the hosts are required. These RAM limitations are avoided when using rolling updates or when using the provisioning callback system built into {ControllerName}, where each system requesting configuration enters a queue and is processed as quickly as possible; or in cases where {ControllerName} is producing or deploying images such as AMIs. All of these are great approaches to managing larger environments. For further questions, please contact Ansible support via the Red Hat Customer portal at https://access.redhat.com/.
* The requirements for systems managed by {PlatformNameShort} are the same as for Ansible. See link:https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html[Getting Started] in the Ansible _User Guide_.

.PostgreSQL requirements

{PlatformName} uses PostgreSQL 13.

* PostgreSQL user passwords are hashed with SCRAM-SHA-256 secure hashing algorithm before storing in the database.
* To determine if your {ControllerName} instance has access to the database, you can do so with the command, `awx-manage check_db`.


.PostgreSQL Configurations

Optionally, you can configure the PostgreSQL database as separate nodes that are not managed by the {PlatformName} installer. When the {PlatformNameShort} installer manages the database server, it configures the server with defaults that are generally recommended for most workloads. However, you can adjust these PostgreSQL settings for standalone database server node where ``ansible_memtotal_mb`` is the total memory size of the database server:

-----
max_connections == 1024
shared_buffers == ansible_memtotal_mb*0.3
work_mem == ansible_memtotal_mb*0.03
maintenance_work_mem == ansible_memtotal_mb*0.04
-----

Refer to the link:https://wiki.postgresql.org/wiki/Main_Page[PostgreSQL documentation] for more detail on tuning your PostgreSQL server.

While {PlatformName} depends on Ansible Playbooks and requires the installation of the latest stable version of Ansible before installing {ControllerName}, manual installations of Ansible are no longer required.

Upon new installations, {ControllerName} installs the latest release package of Ansible {PlatformVers}.

If performing a bundled {PlatformNameShort} installation, the installation program attempts to install Ansible (and its dependencies) from the bundle for you.

If you choose to install Ansible on your own, the {PlatformNameShort} installation program will detect that Ansible has been installed and will not attempt to reinstall it.


[NOTE]
====
You must install Ansible using a package manager such as `dnf`, and the latest stable version of the package manager must be installed for {PlatformName} to work properly.
Ansible version 2.11 is required for versions {PlatformVers} and later.
====
