:_content-type: REFERENCE

[id="accessing-control-auto-hub-eda-control_{context}"]

= Accessing controller, automation hub, and {EDAName} controller

[role="_abstract"]


Once the installation completes, these are the default protocol and ports used:

* https protocol

* Port 443 for controller

* Port 444 for automation hub

* Port 445 for EDA controller

These can be changed. Consult the *README.md* for further details. It is recommended that you leave the defaults unless you need to change them due to port conflicts or other factors.

.Accessing Automation Controller UI

The automation controller UI is available by default at:

----
https://<your_rhel_host>:443
----

Login as the admin user with the password you created for *controller_admin_password*.

If you supplied the license manifest as part of the installation, the {PlatformNameShort} dashboard is displayed. If you did not supply a license file, the *Subscription* screen is displayed where you must supply your license details. This is documented here: link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_operations_guide/assembly-aap-activate[Chapter 1. Activating Red Hat Ansible Automation Platform]. 

.Accessing {HubNameStart} UI

The {HubName} UI is available by default at:

----
https://<hub node>:444
----

Login as the admin user with the password you created for *hub_admin_password*.


.Accessing {EDAName} UI

The {EDAName} UI is available by default at:
----
https://<eda node>:445
----

Login as the admin user with the password you created for *eda_admin_password*.


.Uninstalling containerized {PlatformNameShort}

To uninstall a containerized deployment, execute the *uninstall.yml* playbook.
----
$ ansible-playbook -i inventory ansible.containerized_installer.uninstall
----

This will stop all systemd units and containers and then delete all resources used by the containerized installer such as:

* config and data directories/files
* systemd unit files
* podman containers and images
* RPM packages

To keep container images, you can set the *container_keep_images* variable to true.
----
$ ansible-playbook -i inventory ansible.containerized_installer.uninstall -e container_keep_images=true
----