[id="ref-controller-inv-debugging-tips"]

= Debugging tips

It is important to set the `strict` parameter to `true` so that you can debug problems with your templates. 
If the template fails to render, an error occurs in the associated inventory update for that constructed inventory.

When encountering errors, increase verbosity to get more details.

Giving a default, such as `| default("running")` is a generic use of Jinja2 templates in Ansible. 
Doing this avoids errors from the template when you set `strict: true`. 

You can also set `strict: false`, and so enable the template to produce an error, which results in the host not getting included in that group. However, doing this makes it difficult to debug issues in the future if your templates continue to grow in complexity.

You might still have to debug the intended function of the templates if they are not producing the expected inventory content. 
For example, if a `groups` group has a complex filter (like `shutdown_in_product_dev`) but does not contain any hosts in the resultant constructed inventory, then use the `compose` parameter to help debug. 

For example:
[literal, options="nowrap" subs="+attributes"]
----
source_vars:

plugin: constructed
strict: true
groups:
  shutdown_in_product_dev: state | default("running") == "shutdown" and account_alias == "product_dev"
compose:
  resolved_state: state | default("running")
  is_in_product_dev: account_alias == "product_dev"

limit: ``
----

Running with a blank `limit` returns all hosts. 
You can use this to inspect specific variables on specific hosts, giving insight into where problems in the `groups` lie.
