[id="controller-secret-handling-operational-use"]

= Secret handling for operational use

The operational secrets found in {ControllerName} are as follows:

* `/etc/tower/SECRET_KEY`: A secret key used for encrypting automation secrets in the database. 
If the `SECRET_KEY` changes or is unknown, you cannot access encrypted fields in the database.
* `/etc/tower/tower.{cert,key}`: An SSL certificate and key for the {ControllerName} web service. 
A self-signed certificate or key is installed by default; you can provide a locally appropriate certificate and key.
* A database password in `/etc/tower/conf.d/postgres.py` and a message bus password in `/etc/tower/conf.d/channels.py`.

These secrets are stored unencrypted on the {ControllerName} server, because they are all needed to be read by the {ControllerName} service at startup in an automated fashion. All secrets are protected by UNIX permissions, and restricted to root and the {ControllerName} awx service user.

If you need to hide these secrets, the files that these secrets are read from are interpreted by Python. 
You can adjust these files to retrieve these secrets by some other mechanism anytime a service restarts. 
This is a customer provided modification that might need to be reapplied after every upgrade. 
Red Hat Support and Red Hat Consulting have examples of such modifications.

[NOTE]
====
If the secrets system is down, {ControllerName} cannot get the information and can fail in a way that is recoverable once the service is restored. 
Using some redundancy on that system is highly recommended.
====

If you believe the `SECRET_KEY` that {ControllerName} generated for you has been compromised and needs to be regenerated, you can run a tool from the installer that behaves much like the {ControllerName} backup and restore tool.

[IMPORTANT]
====
Ensure that you backup your {ControllerName} database before you generate a new secret key.
====

To generate a new secret key:

. Follow the procedure described in the xref:controller-backup-and-restore[Backing up and Restoring] section.
. Use the inventory from your install (the same inventory with which you run backups and restores), and run the following command:
+
[literal, options="nowrap" subs="+attributes"]
----
setup.sh -k.
----

A backup copy of the previous key is saved in `/etc/tower/`.
