[id="controller-secret-handling-automation-use"]

= Secret handling for automation use

{ControllerNameStart} stores a variety of secrets in the database that are either used for automation or are a result of automation. 

These secrets include the following:

* All secret fields of all credential types, including passwords, secret keys, authentication tokens, and secret cloud credentials.
* Secret tokens and passwords for external services defined {ControllerName} settings.
* "password" type survey field entries.

To encrypt secret fields, {ControllerName} uses AES in CBC mode with a 256-bit key for encryption, PKCS7 padding, and HMAC using SHA256 for authentication. 

The encryption or decryption process derives the AES-256 bit encryption key from the `SECRET_KEY`, the field name of the model field and the database assigned auto-incremented record ID. 
Therefore, if any attribute used in the key generation process changes, the {ControllerName} fails to correctly decrypt the secret. 

{ControllerNameStart} is designed so that:

* The `SECRET_KEY` is never readable in playbooks that {ControllerName} launches.
* These secrets are never readable by {ControllerName} users.
* No secret field values are ever made available by the {ControllerName} REST API. 

If a secret value is used in a playbook, it is recommended that you use `no_log` on the task so that it is not accidentally logged.
