[id="ref-controller-group-name-vars-filtering"]

= Filtering on group name and variables

You can filter on a combination of groups and variables.
For example, you can filter hosts that match a group variable value and also match a host variable value.

There are two approaches to executing this filter:

* Define two groups: one group to match the group variable and the other group to match the host variable value.
Use the `limit` pattern to return the hosts that are in both groups. 
This is the recommended approach.
* Define one group. In the definition, include the condition that the group and host variables must match specific values.
Use the `limit` pattern to return all the hosts in the new group.

.Example:

The following inventory file defines four hosts and sets group and host variables.
It defines a product group, a sustaining group, and it sets two hosts to a shutdown state.

The goal is to create a filter that returns only production hosts that are shutdown.

[literal, options="nowrap" subs="+attributes"]
----
[account_1234]
host1
host2 state=shutdown

[account_4321]
host3
host4 state=shutdown

[account_1234:vars]
account_alias=product_dev

[account_4321:vars]
account_alias=sustaining
----

The goal here is to return only shutdown hosts that are present in the group with the `account_alias` variable equal to `product_dev`. 
There are two approaches to this, both shown in YAML format. The first one suggested is recommended.

. *Construct 2 groups, limit to intersection*:
+
[literal, options="nowrap" subs="+attributes"]
----
source_vars:
+
plugin: constructed
strict: true
groups:
  is_shutdown: state | default("running") == "shutdown"
  product_dev: account_alias == "product_dev"

limit: is_shutdown:&product_dev
----
+
This constructed inventory input creates a group for both categories and uses the `limit` (host pattern) to only return hosts that
are in the intersection of those two groups, which is documented in link:https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.htm[Patterns: targeting hosts and groups].
+
When a variable is or is not defined (depending on the host), you can give a default.
For example, use `| default("running")` if you know what value it should have when it is not defined. 
This helps with debugging, as described in xref:ref-controller-inv-debugging-tips[Debugging tips].
+
. *Construct 1 group, limit to group*:
+
[literal, options="nowrap" subs="+attributes"]
----
source_vars:
+
plugin: constructed
strict: true
groups:
  shutdown_in_product_dev: state | default("running") == "shutdown" and account_alias == "product_dev"

limit: shutdown_in_product_dev
----
+
This input creates one group that only includes hosts that match both criteria. 
The limit is then just the group name by itself, returning *host2*. 
The same as the previous approach.
