[id="ref-controller-verify-your-project"]

= Verify your project

To verify that a signed Ansible project has not been altered, you can use `ansible-sign` to check whether the signature is valid and that the checksums of the files match what the checksum manifest says they should be. 
The `ansible-sign project gpg-verify` command can be used to automatically verify both of these conditions.

[literal, options="nowrap" subs="+attributes"]
----
$ ansible-sign project gpg-verify .
[OK   ] GPG signature verification succeeded.
[OK   ] Checksum validation succeeded.
----

[NOTE]
====
By default, `ansible-sign` makes use of your default GPG keyring to look for a matching public key. 
You can specify a keyring file with the `--keyring` option, or a different GPG home with the `--gnugpg-home` option.
====

If verification fails for any reason, information is displayed to help you debug the cause. 
More verbosity can be enabled by passing the global `--debug` flag, immediately after `ansible-sign` in your commands.

[NOTE]
====
When a GPG credential is used in a project, content verification automatically takes place on future project synchronizations.
====
