

// [id="ref-platform-install-settings_{context}"]

= {PlatformName} installation settings

[role="_abstract"]
You can use the following settings when installing {HubName}:

* `automationhub_importer_settings`: Dictionary of settings/configuration to pass to `galaxy-importer`. It will end up in `/etc/galaxy-importer/galaxy-importer.cfg`
* `automationhub_require_content_approval`: Whether or not {HubName} enforces the approval mechanism before collections are made available
* `automationhub_disable_https`: Whether or not {HubName} should be deployed with TLS enabled
* `automationhub_disable_hsts`: Whether or not {HubName} should be deployed with the HTTP Strict Transport Security (HSTS) web-security policy mechanism enabled
* `automationhub_ssl_validate_certs`: Whether or not {HubName} should validate certificate when requesting itself (default = False) because by default, Platform deploys with self-signed certificates
* `automationhub_ssl_cert`: Same as `web_server_ssl_cert` but for {HubName} UI and API
* `automationhub_ssl_key`: Same as `web_server_ssl_key` but for {HubName} UI and API
* `automationhub_backup_collections`: {HubName} provides artifacts in `/var/lib/pulp`. By default, this is set to `true` so {ControllerName} automatically backs up the artifacts by default. If a partition (e.g., LVM, NFS, CephFS, etc.)  was mounted there, an enterprise organization would ensure it is always backed up. If this is the case, you can set `automationhub_backup_collections = false` and the backup/restore process will not have to backup/restore `/var/lib/pulp`.
