[id="ref-container-resource-requirements"]

= Containers resource requirements

You can configure the resource requirements of tasks and the web containers, at both the lower end (requests) and the upper end (limits). The execution environment control plane is used for project updates, but is normally the same as the default execution environment for jobs.

Setting resource requests and limits is a best practice because a container thaat has both defined is given a higher _Quality of Service_ class. 
This means that if the underlying node is resource constrained and the cluster has to reap a pod to prevent running memory or other failure, the control plane pod is less likely to be reaped.

These requests and limits apply to the control pods for {ControllerName} and if limits are set, determine the _capacity_ of the instance. 
By default, controlling a job takes 1 unit of capacity. 
The memory and CPU limits of the task container are used to determine the capacity of control nodes. 
For more information on how this is calculated, see link:https://docs.ansible.com/automation-controller/latest/html/userguide/jobs.html#resource-determination-for-capacity-algorithm[Resouce determination]. 

See also xref:ref-schedule-jobs-worker-nodes[Jobs scheduled on the worker nodes]


[cols="30%,30%,30%",options="header"]
|====
| Name | Description | Default
| `web_resource_requirements` | Web container resource requirements | requests: {CPU: 100m, memory: 128Mi}
| `task_resource_requirements` | Task container resource requirements | requests: {CPU: 100m, memory: 128Mi}
| `ee_resource_requirements` | EE control plane container resource requirements | requests: {CPU: 100m, memory: 128Mi}
| `redis_resource_requirements` | Redis control plane container resource requirements | requests: {CPU:100m, memory: 128Mi}
|====

Because the use of `topology_spread_constraints` to maximally spread control nodes onto separate underlying kubernetes worker nodes is also recommended, a reasonable set of requests and limits would be limits whose sum is equal to the actual resources on the node. 
If only `limits` are set, then the request is automatically set to be equal to the limit. But because some variablity of resource usage between the containers in the control pod is permitted, you can set `requests` to a lower amount, for example to 25% of the resources available on the node. 
An example of container customization for a cluster where the worker nodes have 4 CPUs and 16 GB of RAM could be:

[options="nowrap" subs="+quotes,attributes"]
----
spec:
  ...
  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  redis_resource_requirements
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  ee_resource_requirements:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 4Gi
----
