[id="ref-genera-inventory-variables"]

= General variables

[cols="50%,50%",options="header"]
|====
| *Variable* | *Description*
| *`enable_insights_collection`* | The default install registers the node to the {InsightsName} Service if the node is registered with Subscription Manager. 
Set to `False` to disable.

Default = `true`
| *`registry_password`* | `registry_password` is only required if a non-bundle installer is used.

Password credential for access to `registry_url`.

Used for both `[automationcontroller]` and `[automationhub]` groups.

Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.

When `registry_url` is `registry.redhat.io`, username and password are required if not using bundle installer.
| *`registry_url`* | Used for both `[automationcontroller]` and `[automationhub]` groups.

Default = `registry.redhat.io`.
| *`registry_username`* | `registry_username` is only required if a non-bundle installer is used.

User credential for access to `registry_url`.

Used for both `[automationcontroller]` and `[automationhub]` groups, but only if the value of `registry_url` is `registry.redhat.io`.

Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.
|====



