[id="ref-requests-limits"]

== Requests and limits

If the node where a Pod is running has sufficient resources available, it is possible for a container to use more resources than its request for that resource specifies. 
However, a container is not allowed to use more than its resource limit.

For example, if you set a memory request of 256 MiB for a container, and that container is in a Pod scheduled to a Node with 8GiB of memory and no other Pods, then the container can try to use more RAM.

If you set a memory limit of 4GiB for that container, the kubelet and container runtime enforce the limit. 
The runtime prevents the container from using more than the configured resource limit. 

If a process in the container tries to consume more than the allowed amount of memory, the system kernel terminates the process that attempted the allocation, with an _Out Of Memory_ (OOM) error.

You can implement limits in two ways:

* Reactively: the system intervenes once it sees a violation.
* By enforcement: the system prevents the container from ever exceeding the limit. 

Different runtimes can have different ways to implement the same restrictions.

[NOTE]
====
If you specify a limit for a resource, but do not specify any request, and no admission-time mechanism has applied a default request for that resource, then Kubernetes copies the limit you specified and uses it as the requested value for the resource.
====
