[id="ref-container-resource-requirements"]

= Containers resource requirements

You can configure the resource requirements of task and the web containers, at both the lower end (requests) and the upper end (limits).

Setting resource requests and limits is a best practice because when a container has both defined, it is given a higher _Quality of Service_ class. 
This means that if the underlying node is resource constrained and the cluster has to reap a pod to prevent running memory or other failure, the control plane pod is less likely to be reaped.

[cols="30%,30%,30%",options="header"]
|====
| Name | Description | Default
| `web_resource_requirements` | Web container resource requirements | requests: {CPU: 100m, memory: 128Mi}
| `task_resource_requirements` | Task container resource requirements | requests: {CPU: 100m, memory: 128Mi}
| `ee_resource_requirements` | EE control plane container resource requirements | requests: {CPU: 100m, memory: 128Mi}
|====

An example of customization could be:

[options="nowrap" subs="+quotes,attributes"]
----
spec:
  ...
  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  ee_resource_requirements:
    requests:
      cpu: 250m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 2Gi
----
