[id="ref-genera-inventory-variables"]

= General variables

[cols="50%,50%",options="header"]
|====
| *Variable* | *Description*
| *`enable_insights_collection`* | The default install registers the node to the {InsightsName} Service if the node is registered with Subscription Manager. 
Set to `False` to disable.

Default = `true`
| *`nginx_user_http_config`* | List of nginx configurations for `/etc/nginx/nginx.conf` under the http section. 

Each element in the list is provided into `http nginx config` as a separate line. 

Default = empty list
| *`registry_password`* | `registry_password` is only required if a non-bundle installer is used.

Password credential for access to `registry_url`.

Used for both `[automationcontroller]` and `[automationhub]` groups.

Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.

When `registry_url` is `registry.redhat.io`, username and password are required if not using a bundle installer.
| *`registry_url`* | Used for both `[automationcontroller]` and `[automationhub]` groups.

Default = `registry.redhat.io`.
| *`registry_username`* | `registry_username` is only required if a non-bundle installer is used.

User credential for access to `registry_url`.

Used for both `[automationcontroller]` and `[automationhub]` groups, but only if the value of `registry_url` is `registry.redhat.io`.

Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.
| *`routable_hostname`* | `routable hostname` is used if the machine running the installer can only route to the target host through a specific URL, for example, if you use shortnames in your inventory, but the node running the installer can only resolve that host using FQDN.

If `routable_hostname` is not set, it should default to `ansible_host`. If you do not set `ansible_host`, `inventory_hostname` is used as a last resort.

This variable is used as a host variable for particular hosts and not under the `[all:vars]` section. 
For further information, see link:https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#assigning-a-variable-to-one-machine-host-variables[Assigning a variable to one machine:host variables].
|====



