[id="ref-controller-additional-build-files"]

= additional_build_files

Specifies files that are to be added to the build context directory. 
These can then be referenced or copied by `additional_build_steps` during any build stage. 

The format is a list of dictionary values, each with a `src` and `dest` key and value.

Each list item must be a dictionary containing the following (non-optional) keys:

[cols= "10%, 40%"]
|====
| *src* | Specifies the source files to copy into the build context directory.
  
This can be an absolute path, for example, `/home/user/.ansible.cfg`, or a path that is relative to the file. 
Relative paths can be a glob expression matching one or more files, for example, `files/\*.cfg`. 
Note that an absolute path must *not* include a regular expression. 
If `src` is a directory, the entire contents of that directory are copied to `dest`.
| *dest* a| Specifies a subdirectory path underneath the `_build` subdirectory of the build context directory that contains the source files, for example, `files/configs`. 

This cannot be an absolute path or contain `..` within the path. 
This directory is created for you if it does not exist.

[NOTE]
====
When using an `ansible.cfg` file to pass a token and other settings for a private account to an {HubName} server, listing the configuration file path here (as a string) enables it to be included as a build argument in the initial phase of the build.
====
|====