//[id="ref-aap-components"]

= {PlatformName} platform components

Red Hat Ansible Automation Platform consists of the following components:

.{HubNameMain}
A repository for certified content of Ansible Content Collections.
{HubNamemain} is the centralized repository for Red Hat and its partners to publish content, and for customers to discover certified, supported Ansible Content Collections.
{CertifiedCon} provides users with content that has been tested and is supported by Red Hat.

.{PrivateHubNameStart}
{PrivateHubNameStart} provides both disconnected and on premise solution for synchronizing content.
You can synchronize collections and execution environment images from Red Hat cloud automation hub, storing and serving your own custom automation collections and execution images.
You can also use other sources such as {Galaxy} or other container registries to provide content to your {PrivateHubName}.
{PrivateHubNameStart} can integrate into your enterprise directory and your CI/CD pipelines.


.{ControllerNameStart}
An enterprise framework for controlling, securing, and managing Ansible automation with a user interface (UI) and RESTful application programming interface (API).

.{CatalogNameStart}
{CatalogNameStart} is a service within {PlatformName}.
{CatalogNameStart} enables you to organize and govern product catalog sources on Ansible {ControllerName} across various environments.

Using {CatalogName} you can:

* Apply multi-level approval to individual platform inventories.
* Organize content in the form of products from your platforms into portfolios.
* Choose portfolios to share with specific groups of users.
* Set boundaries around values driving execution of user requests.

.{AutomationMeshStart}
{AutomationMeshStart} is an overlay network intended to ease the distribution of work across a large and dispersed collection of workers through nodes that establish peer-to-peer connections with each other using existing networks.

{AutomationMeshStart} provides:

* Dynamic cluster capacity that scales independently, allowing you to create, register, group, ungroup and deregister nodes with minimal downtime.
* Control and execution plane separation that enables you to scale playbook execution capacity independently from control plane capacity.
* Deployment choices that are resilient to latency, reconfigurable without outage, and that dynamically re-reroute to choose a different path when outages exist.
* Mesh routing changes.
* Connectivity that includes bi-directional, multi-hopped mesh communication possibilities which are Federal Information Processing Standards (FIPS) compliant.

.{ExecEnvNameStart}
A solution that includes the Ansible execution engine and hundreds of modules that help users automate all aspects of IT environments and processes.
Execution environments automate commonly used operating systems, infrastructure platforms, network devices, and clouds.

.{Galaxy}
A hub for finding, reusing, and sharing Ansible content.
Community-provided Galaxy content, in the form of prepackaged roles, can help start automation projects. Roles for provisioning infrastructure, deploying applications, and completing other tasks can be dropped into Ansible Playbooks and be applied immediately to customer environments.

.{Navigator}
A _textual user interface_ (TUI) that becomes the primary command line interface into the automation platform, covering use cases from content building, running automation locally in an execution environment, running automation in {PlatformNameShort}, and providing the foundation for future _integrated development environments_ (IDEs).
