[id="ref-controller-system-requirements"]

== {ControllerNameStart} system requirements

{ControllerNameStart} is a distributed system, where different software components can be co-located or deployed across multiple compute nodes.
In the installer, node types of control, hybrid, execution, and hop are provided as abstractions to help you design the topology appropriate for your use case.

The following tables provides recommendations for node sizing:

[NOTE]
====
On all nodes except hop nodes, allocate a minimum of 20 GB to `/var/lib/awx` for execution environment storage.
====

.Execution nodes
Runs automation. Increases memory and CPU to increase capacity for running more forks

[cols="a,a",options="header"]
|===
h| Requirement | Required
| *RAM* | 16 GB  
| *CPUs* | 4
|===

.Control nodes 
Processes events and runs cluster jobs including project updates and cleanup jobs. 
Increasing CPU and memory can help with job event processing.


|===
h| Requirement | Required
| *RAM* | 16 GB  
| *CPUs* | 4
|===

.Hybrid nodes
Runs both automation and cluster jobs, comments for both execution and control nodes apply to this node type.

[cols="a,a,options="header"]
|===
h| Requirement | Required
| *RAM* | 16 GB  
| *CPUs* | 4
|===

.Hop nodes
Serves to route traffic from one part of the Automation Mesh to another (for example, could be a bastion host into another network). 
RAM could affect throughput, CPU activity is low. 
Network bandwidth and latency are generally a more important factor than either RAM or CPU.

[cols="a,a,options="header"]
|===
h| Requirement | Required
| *RAM* | 16 GB  
| *CPUs* | 4
|===

.Database

[cols="a,a,a,options="header"]
|===
h| Service| Required | Notes
h| Disk: service node | 40 GB dedicated hard disk space |

* *{ControllerName}*: dedicate a minimum of 20 GB to `/var/` for file and working directory storage
* Storage volume should be rated for a minimum baseline of 1500 IOPS.
* Projects are stored on control and hybrid, and for the duration of jobs, also on execution nodes. If the cluster has many large projects, consider having twice the GB in /var/lib/awx/projects, to avoid disk space errors.
h| Disk: database node | 20 GB dedicated hard disk space |

* 150 GB+ recommended
* Storage volume should be rated for a high baseline IOPS (1500 or more).
|===


* All {ControllerName} data is stored in the database. 
Database storage increases with the number of hosts managed, number of jobs run, number of facts stored in the fact cache, and number of tasks in any individual job.
For example, a playbook run every hour (24 times a day) across 250, hosts, with 20 tasks will store over 800000 events in the database every week.

* If not enough space is reserved in the database, old job runs and facts will need cleaned on a regular basis. 
Refer to link:https://docs.ansible.com/ansible-tower/3.8.3/html/administration/management_jobs.html#ag-management-jobs[Management Jobs] in the _Automation Controller Administration Guide_ for more information

* Actual RAM requirements vary based on how many hosts {ControllerName} will manage simultaneously (which is controlled by the `forks` parameter in the job template or the system `ansible.cfg` file). 
To avoid possible resource conflicts, Ansible recommends 1 GB of memory per 10 forks + 2 GB reservation for {ControllerName}, see link:https://docs.ansible.com/automation-controller/latest/html/userguide/jobs.html#at-capacity-determination-and-job-impact[Automation controller Capacity Determination and Job Impact] for further details. If `forks` is set to 400, 42 GB of memory is recommended.
* A larger number of hosts can of course be addressed, though if the fork number is less than the total host count, more passes across the hosts are required. 
These RAM limitations are avoided when using rolling updates or when using the provisioning callback system built into {ControllerName}, where each system requesting configuration enters a queue and is processed as quickly as possible; or in cases where {ControllerName} is producing or deploying images such as AMIs. 
All of these are great approaches to managing larger environments. For further questions, please contact Ansible support through the Red Hat Customer portal at https://access.redhat.com/.

[role="_additional-resources"]
.Additional resources
////
Optional. Delete if not used.

////
* link:https://docs.ansible.com/automation-controller/latest/html/userguide/import_license.html?extIdCarryOver=true&sc_cid=7013a00000388B5AAI[Import a subscription].