

[id="ref-multi-node-cluster-inventory_{context}"]

= Example {PlatformName} multi-node inventory file


[role="_abstract"]
This example describes how you can populate the inventory file for a multi-node cluster installation of {ControllerName}.

[IMPORTANT]
====
* You cannot install {ControllerName} and {HubName} on the same node.
* Provide a reachable IP address for the `[automationhub]` host to ensure users can sync content from Private Automation Hub from a different node.
* Do not use special characters for `pg_password`. It may cause the setup to fail.
* Enter your Red Hat customer account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry. You can also replace the url in `registry_url` with a different container registry, provided that the registry has execution environment images.
====



-----
[automationcontroller]
host1
host11
host12


[automationhub]
host2

[database]
host3

[all:vars]
ansible_become=true

admin_password='<password>'

pg_host='dbnode.example.com'
pg_port='5432'

pg_database='tower'
pg_username='tower'
pg_password='<password>'

registry_url='registry.redhat.io'
registry_username='<username>'
registry_password='<password>'
-----
