// As an admin, I want to view top template details
// Module included in the following assemblies:
// assembly-evaluating-automation-return.adoc


[id="con-jobs-explorer"]

= Creating a filtered and sorted view of jobs

You can view a list of jobs, filtered by attributes you choose, using the *Job Explorer*.

Filter options include:

* Status
* Job
* Cluster
* Organization
* Template

You can sort results by a set of parameters by using the *Sort by* options from the filter toolbar.

.Procedure

. Navigate to menu:Insights[Job Explorer].
. In the filter toolbar, click the *Filter by* drop-down menu and select *Job*.
. In that same toolbar, select a time range. Job Explorer will now display jobs within that time range.
. To further refine results, return to the filter toolbar and select a different attribute to filter results by, including job status, cluster, or organization.

The *Job Explorer* view will update and present a list of jobs based on the attributes you selected.

== Viewing more information about an individual job

You can click on the arrow icon next to the job *Id/Name* column to view more details related to that job.

== Reviewing job details on Ansible Tower

Click the job in the *Id/Name* column to view the job itself on the Ansible Tower job details page. For more information on viewing job details on Ansible Tower, see _Jobs_ in the Ansible Tower https://docs.ansible.com/ansible-tower/3.4.3/html/userguide/jobs.html[User Guide].
