// Module included in the following assemblies:
// assembly-automation-savings-planner.adoc


[id="con-review-savings-calculations_{context}"]

= Review savings calculations for your automation plans

The {planner} offers a calculation of how much time and money you can save by automating a job. {InsightsName} takes data from the plan details and the associated job template to provide you with an accurate projection of your cost savings when you complete this savings plan.

To do so, navigate to your savings planner page, click the name of an existing plan, then navigate to the *Statistics* tab.

The statistics chart displays a projection of your monetary and time savings based on the information you provided when creating a savings plan. Primarily, the statistics chart subtracts the automated cost from the manual cost of executing the plan to provide the total resources saved upon automation. The chart then displays this data by year to show you the cumulative benefits for automating the plan over time.

Click between *Money* and *Time* to view the different types of savings for automating the plan.
