// user story:
// Module included in the following assemblies:
// assembly-evaluating-automation-return.adoc


[id="proc-view-failed-jobs"]

= Example: Reviewing failed jobs

You can view more detail about failed jobs across your organization by drilling down on the graph on the *Cluster* view and using the *Job Explorer* to refine results. Clicking on a specific portion in a graph will open that information in the *Job Explorer*, preserving contextual information created when using filters on the *Clusters* view.

.Procedure

. Navigate to menu:Insights[Clusters].
. In the filter toolbar, apply filters for clusters and time range of your choosing.
. Click on a segment on the graph.

You will redirected to the *Job Explorer* view, which will present a list of successful and failed jobs corresponding to that day on the bar graph.

To view only failed jobs:

. Click the *Filter by* drop-down menu and select *Status*.
. Select the *Failed* filter.

The view will update to show only failed jobs run on that day.

Add additional context to the view by applying additional filters and selecting attributes to sort results by. Link out and review more information for failed jobs on the Ansible Tower job details page.
