ifdef::context[:parent-context: {context}]

[id="aap-azure-hub-spoke-peering"]
= Hub-and-spoke peering (Transit routes)

:context: aap-azure-hub-spoke-peering

// [role="_abstract"]
// You can use these instructions to install 

[NOTE]
====
Updating route tables incorrectly can break your network. Only execute the steps in these procedures if you are confident that you can reverse any unexpected network behavior.
====

== Prerequisites

* You have deployed Ansible Automation Platform on Microsoft Azure.
* You have configured and tested an Azure VNet hub-and-spoke implementation in your Azure tenant.
* You have configured transit routing between your spoke networks, including your VPNs.
* You have identified the following:
** The CIDR block(s) of your existing VNets (including VPNs & direct connects) that will need access to Ansible Automation Platform on Azure UIs.
** The CIDR block(s) of your existing VNets (including VPNs & direct connects) that will contain hosts or endpoints for Ansible automation.
** The CIDR blocks of the Ansible Automation Platform Kubernetes network from the managed resource group of the application. Refer to xref:proc-azure-find-cluster-cidr[Finding the CIDR Block of the managed application Kubernetes cluster] for instructions.

include::aap-on-azure/proc-azure-hub-spoke-peering.adoc[leveloffset=+1]
include::aap-on-azure/proc-azure-find-cluster-cidr.adoc[leveloffset=+2]
include::aap-on-azure/proc-azure-nw-peering-aap-subnet.adoc[leveloffset=+2]
include::aap-on-azure/proc-azure-update-route-tables.adoc[leveloffset=+2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

