// Module included in the following assemblies:
// assembly-repo-sync.adoc

[id="proc-basic-repo-sync"]


.Procedure
//[ddacosta] For 2.5 this will be Log in to Ansible Automation Platform and select Automation Content. Automation hub opens in a new tab. From the navigation ...
. Log in to {HubName}.
. From the navigation panel, select {MenuACAdminRepositories}.
. Locate your repository in the list and click *Sync*.
+
All collections in the configured remote are downloaded to your custom repository. To check the status of the collection sync, select {MenuACAdminTasks} from the navigation panel.
+
[NOTE]
====
To limit repository synchronization to specific collections within a remote, you can identify specific collections to be pulled by using a requirements.yml file. See xref:proc-create-remote_remote-management[Create a remote] for more information.
====

[role="_additional-resources"]
.Additional resources
For more information about using requirements files, see link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#install-multiple-collections-with-a-requirements-file[Install multiple collections with a requirements file] in the _Using Ansible collections_ guide.
