// Module included in the following assemblies:
// assembly-collection-import-export.adoc

[id="proc-import-collection"]

= Importing an automation content collection in {HubName}

As an automation content creator, you can import a collection to use in a custom repository. To use a collection in your custom repository, you must first import the collection into your namespace so the {HubName} administrator can approve it. 

.Procedure
. Log in to {PlatformName}.
. From the navigation panel, select menu:Collections[Namespaces]. The *Namespaces* page displays all of the namespaces available.
. Click btn:[View Collections].
. Click btn:[Upload Collection].
. Navigate to the collection tarball file, select the file and click btn:[Open].
. Click btn:[Upload].
+
The *My Imports* screen displays a summary of tests and notifies you if the collection upload is successful or has failed.
+
[NOTE]
====
If the collection is not approved, it is not displayed in the published repository.
====

[role="_additional-resources"]
.Additional resources
* See xref:con-approval-pipeline[Approval pipeline] for more information about collection and repository approvals.
