//this module appears in assembly-collections-and-content-signing-in-pah

[id="proc-downloading-signature-public-keys"]

= Downloading signature public keys

After you sign and approve collections, download the signature public keys from the {HubName} UI.
You must download the public key before you add it to the local system keyring.

.Procedure

. Log in to your {PrivateHubName} instance in the {HubName} UI.

. In the navigation panel, select menu:Signature Keys[].
The Signature Keys dashboard displays a list of multiple keys: collections and container images.

* To verify collections, download the key prefixed with `collections-`.
* To verify container images, download the key prefixed with `container-`.


. Choose one of the following methods to download your public key:

* Select the menu icon and click btn:[Download Key] to download the public key.
* Select the public key from the list and click the _Copy to clipboard_ icon.
* Click the drop-down menu under the *_Public Key_* tab and copy the entire public key block.

Use the public key that you copied to verify the content collection that you are installing.
