// Module included in the following assemblies:
// assembly-basic-repo-management.adoc

[id="proc-provide-repository-access"]

= Providing access to a custom {HubName} repository

By default, private repositories and the automation content collections are hidden from all users in the system. Public repositories can be viewed by all users, but cannot be modified. Use this procedure to provide access to your custom repository.

.Procedure
. Log in to {PlatformName}.
. From the navigation panel, select menu:Collections[Repositories].
. Locate your repository in the list and click the btn:[More Actions] icon *{MoreActionsIcon}*, then select *Edit*.
. Select the *Access* tab.
. Select a group for *Repository owners*.
+
See link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/getting_started_with_automation_hub/index#assembly-user-access[Configuring user access for your local {HubName}] for information about implementing user access.
+
. Select the roles you want assigned to the selected group.
. Click btn:[Save].
