[id="proc-create-credential"]

= Creating a credential in {ControllerName}

To pull container images from a password or token-protected registry, you must create a credential in automation controller.

In earlier versions of {PlatformNameShort}, you were required to deploy a registry to store {ExecEnvShort} images. 
On {PlatformNameShort} 2.0 and later, the system operates as if you already have a container registry up and running. 
To store {ExecEnvShort} images, add the credentials of only your selected container registries.

.Procedure
. Navigate to {ControllerName}.
. From the navigation panel, select menu:Resources[Credentials].
. Click btn:[Add] to create a new credential.
. Enter an authorization *Name*, *Description*, and *Organization*.
. Select the *Credential Type*.
. Enter the *Authentication URL*. This is the container registry address.
. Enter the *Username* and *Password or Token* required to log in to the container registry.
. Optional: To enable SSL verification, select *Verify SSL*.
. Click btn:[Save].

//[dcd-This should be replaced with a link; otherwise, it's not helpful]For more information, please reference the Pulling from Protected Registries section of the Execution Environment documentation.
