// Module included in the following assemblies:
// assembly-working-with-namespaces.adoc
[id="proc-delete-namespace"]

= Deleting a namespace

You can delete unwanted namespaces to manage storage on your {HubName} server.
You must first ensure that the namespace does not contain a collection with dependencies.

.Prerequisites
* The namespace you are deleting does not have a collection with dependencies.
* You have *Delete namespace* permissions.

.Procedure
//[ddacosta] For 2.5 this will be Log in to Ansible Automation Platform and select Automation Content. Automation hub opens in a new tab. From the navigation ...
. Log in to your {PrivateHubName}.
. From the navigation panel, select {MenuACNamespaces}.
. Click the namespace to be deleted.
. Click the btn:[More Actions] icon *{MoreActionsIcon}*, then click btn:[Delete namespace].
+
NOTE: If the btn:[Delete namespace] button is disabled, the namespace contains a collection with dependencies. Review the collections in this namespace, and delete any dependencies. See link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/getting_started_with_automation_hub/uploading-content-hub#delete-collection[Deleting a collection on automation hub] for information.

The namespace that you deleted, as well as its associated collections, is now deleted and removed from the namespace list view.
