// Module included in the following assemblies:
// assembly-basic-repo-management.adoc

[id="proc-create-repository"]

= Creating a custom repository in {HubName}

You can use {PlatformName} to create a repository and configure it to make it private or hide it from search results.

.Procedure
. Log in to {PlatformName}.
. From the navigation panel, select menu:Collections[Repositories].
. Click btn:[Add repository].
. Enter a *Repository name*.
. Enter a *Description* that indicates the purpose of the repository.
. To retain previous versions of your repository each time you make a change, select *Retained number of versions*. The number of retained versions can range anywhere between 0 and unlimited. To save all versions, leave this set to null.
+
[NOTE]
====
If you have a problem with a change to your custom repository, you can xref:proc-revert-repository-version[revert to a different repository version] that you have retained.
====
+
. Select the *Pipeline* for the repository. This option defines who can publish a collection into the repository.
+
Staging:: Anyone is allowed to publish automation content into the repository.
Approved:: Collections added to this repository are required to go through the approval process by way of the staging repository. When auto approve is enabled, any collection uploaded to a staging repository is automatically promoted to all of the approved repositories.
None:: Any user with permissions on the repository can publish to the repository directly and it is not part of the approval pipeline.
+
. Optional: To hide the repository from search results, select *Hide from search*. This is selected by default.
. Optional: To make the repository private, select *Make private*. This hides the repository from anyone who does not have permissions to view the repository.
. To sync the content from a remote into this repository, select *Remote* and select the remote that contains the collections you want included in your custom repository. For more information, see xref:proc-basic-repo-sync[Repository sync].
. Click btn:[Save].

[role="_additional-resources"]
.Next steps
* After the repository is created, the details page is displayed.
+
From here, you can provide access to your repository, review or add collections, and work with the saved versions of your custom repository.
