////
Base the file name and the ID on the module title. For example:
* file name: proc-doing-procedure-a.adoc
* ID: [id="doing-procedure-a_{context}"]
* Title: = Doing procedure A

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
////

[id="proc-doing-one-procedure_{context}"]

////
The `context` attribute enables module reuse. Every module ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
////

= Adding a README to your container repository


[role="_abstract"]
Add a README to your container repository to provide instructions to your users on how to work with the container. 
{HubNameStart} container repositories support Markdown for creating a README. 
By default, the README is empty.

.Prerequisites

* You have permissions to change containers.

.Procedure

. From the navigation panel, select menu:Execution Environments[Execution Environments].
. Select your container repository.
. On the *Detail* tab, click btn:[Add].
. In the *Raw Markdown* text field, enter your README text in Markdown.
. Click btn:[Save] when you are finished.

After you add a README, you can edit it at any time by clicking btn:[Edit] and repeating steps 4 and 5.
