:_content-type: PROCEDURE

[id="ppah-online-offline-install_{context}"]
= ppah-online-offline-install

Write a short introductory paragraph that provides an overview of the module. The introduction should include what the module will help the user do and why it will be beneficial to the user. Include key words that relate to the module to maximize search engine optimization.

.Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts the steps in this module.
* Prerequisites can be full sentences or sentence fragments; however, prerequisite list items must be parallel.

.Procedure

. Make each step an instruction.

. Include one command or action for each step with the exception of simple follow-step, for example:
.. Do this thing and then select *Next*.
.. Do this other thing and then select *Next*.

. Use an unnumbered bullet (*) if the procedure includes only one step.

.Verification

. Provide an example of expected command output or a pop-up window that the user receives when the procedure is successful.

. List actions for the user to complete, such as entering a command, to determine the success or failure of the procedure.

. Make each step an instruction.

. Include one command or action per step.

. Use an unnumbered bullet (*) if the verification includes only one step.

[role="_additional-resources"]
.Additional resources
* A bulleted list of links to other closely-related material. These links can include `link:` and `xref:` macros.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

