
[id="pushing-container-images-from-your-local"]

= Pushing container images from your local environment

.Procedure
. From a terminal, log into podman, or any container client currently in use:
+
----
> podman pull <__container-name__>
----
+
. After the image is pulled, add tags:
+
----
> podman tag <container-name> _<server-address>_/<container-name>:<tag name>
----
+
. Sign the image after changes have been made, and push it back up:
+
----
> podman push _<server-address>_/<container-name>:<tag name>
--tls-verify=false --sign-by<reference to the gpg key on your local>
----
+
If the image is not signed, it can only be pushed with any current signature embedded.

. Push the image without signing it:
+
----
> podman push _<server-address>_/<container-name>:<tag name>
--tls-verify=false
----
+
. Navigate to {HubName}. 

. From the navigation panel, select menu:Execution Environments[Execution Environments].

. To display the new {ExecEnvShort}, click the *Refresh* icon.

. Click the name of the image.

.Troubleshooting

The details page displays whether or not the image has been signed. 
If it displays *Unsigned* you can sign the image from {HubName} with the following steps:

. Click the image name to open the details page.

. Click the btn:[More Actions] icon *{MoreActionsIcon}*.
Three options are available:
* *Use in Controller*
* *Delete*
* *Sign*

. Click *Sign* from the drop-down menu.

The signing service signs the image. 
After the image is signed, the status changes to "signed".
