// Module included in the following assemblies:
// assembly-basic-remote-management.adoc

[id="proc-create-remote_{context}"]

= Creating a remote configuration in {HubName}

You can use {PlatformName} to create a remote configuration to an external collection source and sync the content from those collections to your custom repositories.

.Procedure
. Log in to {PlatformName}.
. From the navigation panel, select menu:Collections[Remotes].
. Click btn:[Add Remote].
. Enter a *Name* for the remote configuration.
. Enter the *URL* for the remote server, including the path for the specific repository.
+
[NOTE]
====
You can find the remote server URL and repository path by navigating to menu:Automation Hub[Repositories], selecting your repository, and clicking btn:[Copy CLI configuration].
====
+
. Configure the credentials to the remote server by entering a *Token* or *Username* and *Password* required to access the external collection.
+
[NOTE]
====
Generate a token from the navigation panel, by selecting menu:Collections[API token], clicking btn:[Load token] and copying the token that is loaded.
====
+
. To access collections from {Console}, enter the *SSO URL* to sign in to the identity provider (IdP).
. Select or create a *YAML requirements* file to identify the collections and version ranges to synchronize with your custom repository. For example, to only download the kubernetes and AWS collection versions 5.0.0 or later the requirements file would look like this:
+
-----
Collections:
 	  - name: community.kubernetes
	  - name: community.aws
 		version:”>=5.0.0”
-----
+
[NOTE]
====
All collection dependencies are downloaded during the Sync process.
====
+
. Optional: To configure your remote further, use the options available under *Advanced configuration*:
.. If there is a corporate proxy in place for your organization, enter a *Proxy URL*, *Proxy Username* and *Proxy Password*.
.. Enable or disable transport layer security using the *TLS validation* checkbox.
.. If digital certificates are required for authentication, enter a *Client key* and *Client certificate*.
.. If you are using a self-signed SSL certificate for your server, enter the PEM encoded client certificate used for authentication in the *CA certificate* field.
.. To accelerate the speed at which collections in this remote can be downloaded, specify the number of collections that can be downloaded in tandem in the *Download concurrency* field.
.. To limit the number of queries per second on this remote, specify a *Rate Limit*.
+
[NOTE]
====
Some servers can have a specific rate limit set and if exceeded, synchronization will fail.
====
