////
Base the file name and the ID on the module title. For example:
* file name: con-my-concept-module-a.adoc
* ID: [id="con-my-concept-module-a_{context}"]
* Title: = My concept module A
////

////
The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
////

[id="con-proxy-support_{context}"]

////
The `context` attribute enables module reuse. Every module ID includes {context}, which ensures that the module has a unique ID so you can include it multiple times in the same guide.
////

= Proxy support for {ControllerName}


[role="_abstract"]
Proxy servers act as an intermediary for requests from clients seeking resources from other servers. A client connects to the proxy server, requesting some service or available resource from a different server, and the proxy server evaluates the request as a way to simplify and control its complexity.

Using SSL offloading or using a proxy that handles SSL for {ControllerName} is supported. The proxy/load balancer needs to be configured to pass the remote host information.

When offloading SSL to the load balancer or proxy, set ``nginx_disable_https=true`` as an extra variable passed to the setup playbook. Refer to xref:`um_setup_playbook` for information on applying extra variables to the setup playbook.

Sessions in {ControllerName} associate an IP address upon creation. {ControllerNameStart} policy requires that any use of the session match the original associated IP address.
