:imagesdir: images
[[catalog_lifecycle]]
= Automation Services Catalog life cycle

== Overview

This document describes the maintenance schedule for security patches and feature enhancements that Red Hat will provide for the Automation Services Catalog. 
Automation Services Catalog is supplied by Red Hat specifically at cloud.redhat.com. Red Hat owns the process of upgrading and maintaining the presentation of cloud.redhat.com.

include::aap-common/making-open-source-more-inclusive.adoc[leveloffset=+1]

== Maintenance and Updates Statement for Automation Services Catalog

.Glossary 
* *Maintenance* - Security and Application Bug fixes.
* *Update* - Application Feature Enhancements

Red Hat will maintain the presentation of the Automation Services Catalog offering. This will include the securing of the service(s) and their dependencies within cloud.redhat.com. Maintenance and Updates will be delivered by Red Hat to the platform.

.Schedule
Automation Services Catalog follows an agile schedule. This means that maintenance and updates will be pushed to the production environment as needed after quality assurance testing has been completed successfully.

.Service Outages
Red Hat will endeavour, with best intentions, to have Automation Services Catalog available at all times. Maintenance at times may require the service to become unavailable for a period of time, Red Hat will notify users of any intended outage.
