// For each release of AAP, make a copy of this file and rename it to aap-rn-xx.adoc where xx is the release number; for example, 24 for the 2.4 release.
// Save the renamed copy of this file to the release-notes/topics directory topic files for the release notes reside.
//Only include release note types that have updates for a given release. For example, if there are no Technology previews for the release, remove that section from this file.


= Overview of the {PlatformNameShort} 2.4 release 

== New features and enhancements

{PlatformNameShort} 2.4 includes the following enhancements:

* Previously, the {ExecEnvShort} container images were based on RHEL 8 only. With {PlatformNameShort} 2.4 onwards, the {ExecEnvShort} container images are now also available on RHEL 9. 
The {ExecEnvShort} includes the following container images:
** ansible-python-base
** ansible-python-toolkit
** ansible-builder
** ee-minimal
** ee-supported

* The ansible-builder project recently released {Builder} version 3, a much-improved and simplified approach to creating execution environments. 
You can use the following configuration YAML keys with {Builder} version 3:
** additional_build_files
** additional_build_steps
** build_arg_defaults
** dependencies
** images
** options
** version

* {PlatformNameShort} 2.4 and later versions can now run on ARM platforms, including both the control plane and the execution environments.

* Added an option to configure the SSO logout URL for {HubName} if you need to change it from the default value.

* Updated the ansible-lint RPM package to version 6.14.3.

* Updated Django for potential denial-of-service vulnerability in file uploads (link:https://access.redhat.com/security/cve/CVE-2023-24580[CVE-2023-24580]).

* Updated sqlparse for ReDOS vulnerability (link:https://access.redhat.com/security/cve/CVE-2023-30608[CVE-2023-30608]).

* Updated Django for potential denial-of-service in Accept-Language headers (link:https://access.redhat.com/security/cve/CVE-2023-23969[CVE-2023-23969]).

* {PlatformNameShort} 2.4 adds the ability to install {ControllerName}, {HubName}, and {EDAName} on IBM Power (ppc64le), IBM Z (s390x), and IBM® LinuxONE (s390x) architectures.

.Additional resources

* For more information about using {Builder} version 3, see link:https://ansible.readthedocs.io/projects/builder/en/stable/[{Builder} Documentation] and link:https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html[Execution Environment Setup Reference].

== Technology Preview

include::../snippets/technology-preview.adoc[]

The following are Technology Preview features: 

* Starting with {PlatformNameShort} 2.4, the Platform Resource Operator can be used to create the following resources in {ControllerName} by applying YAML to your OpenShift cluster:
** Inventories
** Projects
** Instance Groups
** Credentials
** Schedules
** Workflow Job Templates
** Launch Workflows

You can now configure the Controller Access Token for each resource with the `connection_secret` parameter, rather than the `tower_auth_secret` parameter. This change is compatible with earlier versions, but the `tower_auth_secret` parameter is now deprecated and will be removed in a future release.

[role="_additional-resources"]
.Additional resources

* For the most recent list of Technology Preview features, see link:https://access.redhat.com/articles/ansible-automation-platform-preview-features[Ansible Automation Platform - Preview Features].

* For information about execution node enhancements on OpenShift deployments, see link:https://docs.ansible.com/automation-controller/latest/html/administration/instances.html[Managing Capacity With Instances].

== Deprecated and removed features

include::../snippets/deprecated-features.adoc[]

The following functionality was deprecated and removed in {PlatformNameShort} 2.4:

* On-premise component {CatalogName} is now removed from {PlatformNameShort} 2.4 onwards.

* With the {PlatformNameShort} 2.4 release, the {ExecEnvShort} container image for Ansible 2.9 (*ee-29-rhel-8*) is no longer loaded into the {ControllerName} configuration by default.

* Although you can still synchronize content, the use of synclists is deprecated and will be removed in a later release. Instead, {PrivateHubName} administrators can upload manually-created requirements files from the `rh-certified` remote.

* You can now configure the Controller Access Token for each resource with the `connection_secret` parameter, rather than the `tower_auth_secret` parameter. This change is compatible with earlier versions, but the `tower_auth_secret` parameter is now deprecated and will be removed in a future release.

* Smart inventories have been deprecated in favor of constructed inventories and will be removed in a future release.

== Bug fixes

{PlatformNameShort} 2.4 includes the following bug fixes:

* Updated the installation program to ensure that collection auto signing cannot be enabled without enabling the collection signing service.

* Fixed an issue with restoring backups when the installed {ControllerName} version is different from the backup version.

* Fixed an issue with not adding user defined galaxy-importer settings to `galaxy-importer.cfg` file.

* Added missing `X-Forwarded-For` header information to nginx logs.

* Removed unnecessary receptor peer name validation when IP address is used as the name.

* Updated the `outdated base_packages.txt` file that is included in the bundle installer.

* Fixed an issue where upgrading the {PlatformNameShort} did not update the nginx package by default.

* Fixed an issue where an *awx* user was created without creating an *awx* group on execution nodes.

* Fixed the assignment of package version variable to work with flat file inventories. 

* Added a FQDN check for the {HubName} hostname required to run the Skopeo commands.

* Fixed the front end URL for Red Hat Single Sign On (SSO) so it is now properly configured after you specify the `sso_redirect_host` variable.

* Fixed the variable precedence for all component `nginx_tls_files_remote` variables.

* Fixed the *setup.sh* script to escalate privileges if necessary for installing {PlatformNameShort}. 

* Fixed an issue when restoring a backup to an {HubName} with a different hostname.
