// This is the release notes file for AAP 2.4 bundle installer release 2.4-3 dated November 28, 2023
[id="bundle-installer-24-3"]

= Bundle installer release 2.4-3 - November 28, 2023

link:https://access.redhat.com/errata/RHBA-2023:7561[Red Hat Errata Advisory]

//Ansible Automation Platform
== {PlatformNameShort}

.Security fixes

* receptor: golang: crypto/tls: panic when processing post-handshake message on QUIC connections (CVE-2023-39321).

* receptor: golang: crypto/tls: lack of a limit on buffered post-handshake (CVE-2023-39322).

.Bug fixes

* Fixed an ansible-lint compatibility issue with ansible-core.

* Receptor now cleans up timed out connections.

//Ansible Builder
== {Builder}

.New features and enhancements

* Updated the default package manager to microdnf instead of dnf.

//Automation controller
== {ControllerNameStart}

.New features and enhancements

* Added a setting to enable the queuing for Rsyslog to handle higher work volumes (`LOG_AGGREGATOR_ACTION_MAX_DISK_USAGE_GB`).

* Updated API endpoints to only show the product version header when the requester is authenticated.

.Bug fixes

* Fixed wsrelay connection in IPv6 environments (OpenShift clusters) so that it no longer fails to make connections.

* Fixed a bug that prevented the dispatcher from exiting when the database failed.

//Event-Driven Ansible
== {EDAName}

.New features and enhancements

* Enhanced the conditions to support non alpha numeric keys, using the square bracket syntax.

* Added the ability to turn off autocomplete on the {EDAName} login screen.

* Added support for running workflow templates in the Controller as one of the actions. The action is `run_workflow_template`. For more information about the `run_workflow_template` action, see link:https://ansible.readthedocs.io/projects/rulebook/en/latest/actions.html#run-workflow-template[Actions - run_workflow_template].

* Added a separate worker queue for {EDAName} activations to not interfere with application tasks such as project updates.

* Improved the error messages received when an error occurs updating projects so they are easier to understand.

* Improved the management of workers with a standalone RQ scheduler.

* Added a new field at the ruleset level called `match_multiple_rules` that is false by default (or when the attribute is missing). This value can be set to true which will allow for multiple rule matching.

.Bug fixes

* Fixed the {ControllerName} URL check when installing {EDAName} without controller.

* Fixed a bug where the controller URL was not being set when running the workflow template. The controller URL is now set for both the workflow template and job template.

* Added the ability to skip SSL verification when syncing a Git project.

* Updated the Controller job URL for the workflow template to point to the correct job.

* Fixed a bug where sometimes an activation was set as `failed` when it should be stopped.

* Fixed a bug where only the first event was displayed when a fact matches multiples rules.

* Fixed a bug where *Fired count* and *Number of rules* had incorrect values.

* Updated the help text on the *Variables* field.

* Fixed a bug where ports for the source were not exposed correctly.

* Fixed a bug where activations reported an incorrect state when the workers were not running.

* Fixed an issue where background tasks were executed 60 seconds later than the scheduled time.

* Fixed a bug where audit event timestamps were incorrectly sorted.

* Fixed an unhandled exception that occurred when the request did not contain valid JSON.

* Fixed a bug that occurred when a long-running activation on {OCPShort} was incorrectly marked as failed.

* Fixed a 401 error response from AWX when port 443 was present in the controller URL.

* Fixed a bug where ansible-rulebook would shutdown before it created an audit rule record.

* Fixed a bug where editing a project to add a credential was not working.

* Fixed a bug where the `restarted_at` field was missing in the activation view.

* Fixed a bug where restarting a running activation in {OCPShort} resulted in unexpected behavior.

* Added `name` and `status` filters to the `/activations/{id}/instances` endpoint.

* Fixed a bug where deleting an activation caused an error.

* Fixed a bug where the status of activations waiting for available workers was set to `failed` when it should have been set to `pending`.

* Fixed a bug where the activation's status was set incorrectly in {OCPShort} when the activation workers were exhausted.

* Fixed a bug where an audit rule with multiple actions was marked as `successful` when one of the actions failed.

* Fixed a bug where the rule's *Fire count* would take 5 minutes to update.

* Updated session stats to be sent when a rule fires in addition to being sent at timed intervals.

* Fixed a bug that caused intermittent race conditions when deactivating activations.

* Updated the welcome title in the {EDAName} UI.

* Added a help message for the *Image* field in the *Create Decision Environment* form.

* Added a check for a rulebook's existence before running an activation.

* Implemented bracket accessors for conditions to enable certain characters that are not supported for event keys with dot notation.

* Fixed a bug where {EDAName} activation pods were receiving out of memory errors on RHEL 9.

* Fixed a bug where activations got stuck in a running state after disabling the activation when there were more activations than workers.

* Fixed a bug where busy workers prevented other asynchronous tasks.
