// This is the release notes for Automation Controller 4.2, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[controller-420-intro]]
= Automation Controller

Automation controller replaces Ansible Tower.
Automation controller introduces a distributed, modular architecture with a decoupled control and execution plane.
The name change reflects these enhancements and the overall position within the Ansible Automation Platform suite.

Automation controller provides a standardized way to define, operate and delegate automation across the enterprise. It also introduces new, exciting technologies and an enhanced architecture that enables automation teams to scale and deliver automation rapidly to meet ever-growing business demand.

.Enhancements

* Introduced the mesh visualizer feature that generates a visual representation of your mesh topology
* Automation controller now automatically mounts the system trust store in execution environments during job runs for VM-based installs
* Added log format for 4XX errors to allow customization of 4xx error messages that are produced when the API encounters an issue with a request
* Added ability to use labels in inventory files
* Added ability to flag users as superusers and auditors in SAML integration
* Automation controller now uses Python 3.9

See link:https://docs.ansible.com/automation-controller/latest/html/release-notes/relnotes.html#release-notes-for-4-x[automation controller Release Notes for 4.x] for a full list of new features and enhancements.
