// This is the release notes for Automation controller 4.1, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[controller-41-intro]]
= Automation controller

Automation controller replaces Ansible Tower.
Automation controller introduces a distributed, modular architecture with a decoupled control and execution plane.
The name change reflects these enhancements and the overall position within the Ansible Automation Platform suite.

Automation controller provides a standardized way to define, operate and delegate automation across the enterprise. It also introduces new, exciting technologies and an enhanced architecture that enables automation teams to scale and deliver automation rapidly to meet ever-growing business demand.


.Automation controller 4.1 new features and enhancements

* Separate control and execution layers.
* Automation execution environments are container images that provide a standardized way to build and distribute environments where automation runs.
* Automation mesh allows distributed execution across on-premises environments, the hybrid cloud, and the edge. It replaces Ansible Tower and isolated nodes.


.Automation controller 4.1 deprecated and removed features

* Support for custom Python virtual environments for execution.

See https://docs.ansible.com/automation-controller/latest/html/release-notes/relnotes.html#release-notes-for-4-x[Automation controller Release Notes for 4.x] for a full list of new features and enhancements.
