// This is the release notes for AAP 2.4 documentation, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[docs-2.4-intro]]
= Ansible Automation Platform Documentation

The documentation set for Red Hat Ansible Automation Platform 2.4 has had significant updates to improve the experience for our customers and the Ansible community.

.Enhancements

* With the removal of the on-premise component Automation Services Catalog from Ansible Automation Platform 2.4 onwards, all Automation Services Catalog documentation is removed from the Ansible Automation Platform 2.4 documentation.

* The following documents are created to help you install and use Event-Driven Ansible, the newest capability of Ansible Automation Platform:

** link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/getting_started_with_event-driven_ansible_guide/index[Getting Started with Event-Driven Ansible]

** link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/event-driven_ansible_controller_user_guide/index[Event Driven Ansible User Guide]

In addition, sections of the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_planning_guide/index[Ansible Automation Platform Planning Guide]
and the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/index[Ansible Automation Platform Installation Guide] are updated to include instructions for planning and installing Event-Driven Ansible.

* The automation hub documentation has had significant reorganization to combine the content spread across 9 separate documents into the following documents:

_Getting started with automation hub_::
Use this guide to perform the initial steps required to use Red Hat automation hub as the default source for Ansible collections content.

_Managing content with automation hub_::
Use this guide to understand how to create and manage collections, content and repositories in automation hub.

_Red Hat Ansible Automation Platform Installation Guide_::
Use this guide to learn how to install Ansible Automation Platform based on supported installation scenarios.

* The name of the _Managing Red Hat Certified and Ansible Galaxy collections in automation hub Guide_ has changed to include validated content and is now _Managing Red Hat Certified, validated, and Ansible Galaxy content in automation hub_.
+
[NOTE]
====
This content has been moved to the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/managing_content_in_automation_hub/index#managing-cert-valid-content[Managing Red Hat Certified, validated, and Ansible Galaxy content in automation hub] topic in the _Managing content with automation hub_ guide.
====

* The Ansible Automation Platform 2.4 Release Notes are restructured to improve the experience for our customers and the Ansible Community. Users can now view the latest updates based on the Ansible Automation Platform versions, instead of their release timeline.

* The document link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/managing_repositories_in_automation_hub/index[Managing repositories in automation hub] is created to help you create and manage custom repositories in automation hub.
+
[NOTE]
====
This content has been moved to the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/managing_content_in_automation_hub/index#repo-management[Repository management with automation hub] topic in the _Managing content with automation hub_ guide.
====
