// This is the release notes for Event-Driven Ansible 1.0 for AAP 2.4 release, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[eda-24-intro]]
= {EDAName}

{EDAName} is the newest capability of {PlatformNameShort} that is designed to enable automated response with user-defined, rules-based workflows. {EDAName} works by receiving events from third party tools, deciding on the actions to take, and acting automatically.

{EDAName} is included in {PlatformNameShort}, making the platform even more capable as a single enterprise automation solution. Using {EDAName}, domain experts can easily create end-to-end fully automated Ops As Code scenarios for a broad array of use cases across the IT landscape. By eliminating high-volume routine tasks and automatically responding to changing conditions, teams are free to innovate more efficiently, and act consistently and accurately at scale.

.Known issues

* Certain characters, such as hyphen (-), forward slash (/), and period (.), are not supported in the event keys.

* Both contributor and editor roles cannot set the AWX token. The AWX token can be set by users with administrator roles only. 

* Activation-job pods do not have request limits.

* The onboarding wizard does not request a controller token creation.

* Users cannot filter through a list of tokens under the *Controller Token* tab. 

* Only the users with administrator rights can set or modify their passwords. 

* If there is a failure, an activation with restart policy set to `Always` is unable to restart the failed activation. 

* Disabling and enabling an activation causes the restart count to increase by one count. This behavior results in an incorrect `restart` count. 

* When all workers are busy with activation processes, other asynchronous tasks are not executed, such as importing projects.

* Podman pods must be executed with memory limits.

* Long running activations with loads of events can cause an out of disk space issue.

* Users can add multiple tokens even when only the first AWX token is used. 

* A race condition occurs when creating and rapidly deleting an activation causes multiple errors. 

* When users filter any list, only the items that are on the list get filtered. 

* When ongoing activations start multiple jobs, a few jobs are not recorded in the audit logs. 

* When a job template fails, a few key attributes are missing in the event payload. 

* Restart policy in a Kubernetes deployment does not restart successful activations that are marked as failed.

* An incorrect status is reported for activations that are disabled or enabled. 

* If the `run_job_template` action fails, the rule is not counted as executed. 

* RHEL 9.2 activations cannot connect to the host.

* When there are more activations than available workers, disabling the activations incorrectly shows them in running state. 

* {EDAName} activation pods are running out of memory on RHEL 9.

* Restarting the {EDAName} server can cause activation states to become stale.

* Bulk deletion of rulebook activation lists is not consistent, and the deletion can be either successful or unsuccessful.

* When users access the detail screen of a rule audit, the related rulebook activation link is broken. 
