// This is the release notes for Event-Driven Ansible 1.0 for AAP 2.4 release, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[eda-24-intro]]
= {EDAName}

{EDAName} is a new way to enhance and expand automation by improving IT speed and agility while enabling consistency and resilience. {EDAName} is designed for simplicity and flexibility.

.Known issues

* Both contributor and editor roles cannot set the AWX token. Only users with administrator roles can set the AWX token. 

* Activation-job pods do not have request limits.

* The onboarding wizard does not request a controller token creation.

* Users cannot filter through a list of tokens under the *Controller Token* tab. 

* Only the users with administrator rights can set or change their passwords. 

* If there is a failure, an activation with restart policy set to `Always` is unable to restart the failed activation. 

* Disabling and enabling an activation causes the restart count to increase by one count. This behavior results in an incorrect `restart` count. 

* You must run Podman pods with memory limits.

* Users can add multiple tokens even when only the first AWX token is used. 

* A race condition occurs when creating and rapidly deleting an activation causes errors. 

* When users filter any list, only the items that are on the list get filtered. 

* When ongoing activations start multiple jobs, a few jobs are not recorded in the audit logs. 

* When a job template fails, a few key attributes are missing in the event payload. 

* Restart policy in a Kubernetes deployment does not restart successful activations that are marked as failed.

* An incorrect status is reported for activations that are disabled or enabled. 

* If the `run_job_template` action fails, the rule is not counted as executed. 

* RHEL 9.2 activations cannot connect to the host.

* Restarting the {EDAName} server can cause activation states to become stale.

* Bulk deletion of rulebook activation lists is not consistent, and the deletion can be either successful or unsuccessful.

* When users access the detail screen of a rule audit, the related rulebook activation link is broken. 

* Long running activations with loads of events can cause an out of disk space issue. Resolved in xref:rpm-24-6[installer release 2.4-6].

* Certain characters, such as hyphen (-), forward slash (/), and period (.), are not supported in the event keys. Resolved in xref:rpm-24-3[installer release 2.4-3].

* When there are more activations than available workers, disabling the activations incorrectly shows them in running state. Resolved in xref:rpm-24-3[installer release 2.4-3].

* {EDAName} activation pods are running out of memory on RHEL 9. Resolved in xref:rpm-24-3[installer release 2.4-3].

* When all workers are busy with activation processes, other asynchronous tasks are not executed, such as importing projects. Resolved in xref:rpm-24-3[installer release 2.4-3].