// This is the release notes file for AAP 2.4 errata bundle dated October 19 2023.

= {PlatformNameShort} 2.4 - October 19, 2023

link:https://access.redhat.com/errata/RHBA-2023:5886[Red Hat Errata Release]

//Ansible Automation Platform
== {PlatformNameShort}

.New features and enhancements

* receptor has been updated to 1.4.2.

.Security fixes

* receptor: golang: net/http, x/net/http2: rapid stream resets can cause excessive work [CVE-2023-44487] (CVE-2023-39325)

* receptor: HTTP/2: Multiple HTTP/2 enabled web servers are vulnerable to a DDoS attack (Rapid Reset Attack) (CVE-2023-44487)

* receptor: golang: crypto/tls: slow verification of certificate chains containing large RSA keys (CVE-2023-29409)

//Automation controller
== {ControllerNameStart}

.New features and enhancements

* Added a new *Subscription Usage* page to the controller UI to view historical usage of licenses. 

.Security fixes

* Upgraded Django to address CVE-2023-41164 automation-controller: Potential denial of service vulnerability in django.utils.encoding.uri_to_iri(). 

.Bug fixes

* Resolved an issue where Operator would time out if upgrading to a newer version of automation controller took too long. 

//Automation Platform Operator
== Automation Platform Operator

.New features and enhancements

* Added a scheduler deployment to handle more rulebook activations. 

//Event-Driven Ansible
== {EDAName}

.New features and enhancements

* {EDAName} default and activation workers now have their own separate deployments, which can be scaled independently. 

* {EDAName} application `extra_settings` are now correctly configured in the application settings. 

* The default resource requests and limits for {EDAName} have been updated based on performance data. 
