// This is the release notes for Automation Platform Operator 2.4, the version number is removed from the topic title as part of the release notes restructuring efforts.

[[operator-240-intro]]
= Automation Platform Operator

Ansible Automation Platform Operator provides cloud-native, push-button deployment of new Ansible Automation Platform instances in your OpenShift environment.

.Enhancements

* Starting with Ansible Automation Platform 2.4, the Platform Resource Operator can be used to create the following resources in Controller by applying YAML to your Openshift cluster:
** Inventories
** Projects
** Instance Groups
** Credentials
** Schedules
** Workflow Job Templates
** Launch Workflows

One notable change is that you can now configure the Controller Access Token for each resource with the `connection_secret` parameter, rather than the old `tower_auth_secret` parameter.  This change is backwards compatible, but the `tower_auth_secret` parameter is now deprecated and will be removed in a future release.

.Bug fixes

* Enabled configuration of resource requirements for automation controller `init` containers.

* Added *securityContext* for EDA Operator deployments to be Pod Security Admission compliant.

* Resolved error `Controller: Error 413 Entity too large` when doing bulk updates.

* Ansible token is now obfuscated in YAML job details.

