[[platform-introduction]]
= Overview of {PlatformName}

{PlatformName} simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles.
{PlatformNameShort} works across multiple IT domains including operations, networking, security, and development, as well as across diverse hybrid environments.
Simple to adopt, use, and understand, {PlatformNameShort} provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

[[whats-included]]
== What is included in {PlatformNameShort}

[cols="a,a,a,a,a"]
|===
| {PlatformNameShort} | {ControllerNameStart} | {HubNameStart} | {EDAcontroller} | {InsightsShort}

|2.4 | 4.4|
* 4.7
* hosted service|
1.0
| hosted service

|===

== {PlatformName} life cycle

Red Hat provides different levels of maintenance for each {PlatformNameShort} release. For more information, see link:https://access.redhat.com/support/policy/updates/ansible-automation-platform[{PlatformName} Life Cycle].

== Upgrading {PlatformNameShort}

When upgrading, do not use `yum update`. Use the installation program instead. The installation program performs all of the necessary actions required to upgrade to the latest versions of {PlatformNameShort}, including {ControllerName} and {PrivateHubName}.

.Additional resources
* For information about the components included in {PlatformNameShort}, see the table in xref:whats-included[What is included in {PlatformNameShort}].

* For more information about upgrading {PlatformNameShort}, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_upgrade_and_migration_guide/index[{PlatformName} upgrade and migration guide].

* For procedures related to using the {PlatformNameShort} installer, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/red_hat_ansible_automation_platform_installation_guide/index[{PlatformNameShort} installation guide].
