// Module included in the following assemblies:
// downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc

[id="con-credential-management-planning_{context}"]

= Credential management planning

//[role="_abstract"]

Credentials are used for authentication when launching jobs against machines, synchronizing with inventory sources, and importing project content from a version control system. {ControllerNameStart} manages three sets of secrets:

* User passwords for *local automation controller users*. See the xref:con-user-authentication-planning[User Authentication Planning] section of this guide for additional details.
* Secrets for automation controller *operational use* (database password, message bus password, and so on).
* Secrets for *automation use* (SSH keys, cloud credentials, external password vault credentials, and so on).

Implementing a privileged access or credential management solution to protect credentials from compromise is a highly recommended practice. Organizations should audit the use of, and provide additional programmatic control over, access and privilege escalation.

You can further secure automation credentials by ensuring they are unique and stored only in {ControllerName}. Services such as OpenSSH can be configured to allow credentials on connections only from specific addresses. Use different credentials for automation from those used by system administrators to log into a server. Although direct access should be limited where possible, it can be used for disaster recovery or other ad-hoc management purposes, allowing for easier auditing.

Different automation jobs might need to access a system at different levels. For example, you can have low-level system automation that applies patches and performs security baseline checking, while a higher-level piece of automation deploys applications. By using different keys or credentials for each piece of automation, the effect of any one key vulnerability is minimized. This also allows for easy baseline auditing.
