// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="con-install-secure-host_{context}"]

= Install from a security installation host

[role="_abstract"]

The {PlatformNameShort} (AAP) installer can be run from one of the infrastructure servers, such as an {ControllerName}, or from an external system that has SSH access to the AAP infrastructure servers. The AAP installer is also used not just for installation, but for subsequent day-two operations, such as backup and restore, as well as upgrades. To reduce the requirement for logging in to one of the infrastructure servers to execute these functions, performing installation and day-two operations from a dedicated external server is recommended. This is referred to from here on as the installation host. The installation host must only be used for management of AAP and must not run any other services or software.

The installation host must be a Red Hat Enterprise Linux (RHEL) server that has been installed and configured in accordance with link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/index[RHEL hardening guidance] and any security profile requirements relevant to your organization (CIS, STIG, and so on). Obtain the AAP installer as described in the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_planning_guide/index#choosing_and_obtaining_a_red_hat_ansible_automation_platform_installer[Automation Platform Planning Guide], and create the installer inventory file as describe in the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_installation_guide/index#proc-editing-installer-inventory-file_platform-install-scenario[Automation Platform Installation Guide]. This inventory file is used for upgrades, adding infrastructure components, and day-two operations by the installer, so preserve the file after installation for future operational use.

Access to the installation host must be restricted only to those personnel who are responsible for managing the AAP infrastructure. Over time, it will contain sensitive information, such as the installer inventory (which contains the initial login credentials for AAP), copies of user-provided PKI keys and certificates, backup files, and so on. The installation host must also be used for logging in to the AAP infrastructure servers through SSH when necessary for infrastructure management and maintenance.