// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="con-controller-stig-considerations_{context}"]

= Automation controller STIG considerations

[role="_abstract"]

For organizations that use the Defense Information Systems Agency (DISA) Security Technical Implementation Guides (STIGs) as a part of their overall security strategy, a link:https://www.redhat.com/en/blog/disa-releases-first-ansible-stig[STIG for the Ansible Automation Platform automation controller] is now available. The STIG only covers the {ControllerName} component of {PlatformNameShort} at this time. When applying the STIG to an {ControllerName}, there are a number of considerations to keep in mind.

The {ControllerName} STIG overview document states that it is meant to be used in conjunction with the STIG for Red Hat Enterprise Linux 8. This version of the {ControllerName} STIG was released prior to a STIG for Red Hat Enterprise Linux 9 being available, so Red Hat Enterprise Linux 8 should be used as the underlying host OS when applying the {ControllerName} STIG. Certain Red Hat Enterprise Linux 8 STIG controls will conflict with {PlatformNameShort} installation and operation, which can be mitigated as described below.