// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="con-rhel-host-planning_{context}"]

= Red Hat Enterprise Linux host planning

[role="_abstract"]

The security of {PlatformNameShort} relies in part on the configuration of the underlying Red Hat Enterprise Linux servers. For this reason, the underlying Red Hat Enterprise Linux hosts for each {PlatformNameShort} component must be installed and configured in accordance with the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/security_hardening/index[Security hardening for Red Hat Enterprise Linux 8] or link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/security_hardening/index[Security hardening for Red Hat Enterprise Linux 9] (depending on which operating system will be used), as well as any security profile requirements (CIS, STIG, HIPAA, and so on) used by your organization.

Note that applying certain security controls from the STIG or other security profiles may conflict with {PlatformNameShort} support requirements. Some examples are listed in the xref:con-controller-stig-considerations_{context}[{ControllerNameStart} STIG considerations] section, although this is not an exhaustive list. To maintain a supported configuration, be sure to discuss any such conflicts with your security auditors so the {PlatformNameShort} requirements are understood and approved.
