// Module included in the following assemblies:
// downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc

[id="con-automation-credentials_{context}"]

= Automation use secrets

[role="_abstract"]

{ControllerNameStart} stores a variety of secrets in the database that are either used for automation or are a result of automation. Automation use secrets include:

* All secret fields of all credential types (passwords, secret keys, authentication tokens, secret cloud credentials).
* Secret tokens and passwords for external services defined in {ControllerName} settings.
* “password” type survey fields entries.

You can grant users and teams the ability to use these credentials without actually exposing the credential to the user. This means that if a user moves to a different team or leaves the organization, you don’t have to re-key all of your systems.

{ControllerName} uses SSH (or the Windows equivalent) to connect to remote hosts . To pass the key from the {ControllerName} to SSH, the key must be decrypted before it can be written to a named pipe. {ControllerNameStart} then uses that pipe to send the key to SSH (so that it is never written to disk). If passwords are used, the {ControllerName} handles those by responding directly to the password prompt and decrypting the password before writing it to the prompt.

As an administrator with superuser access, you can define a custom credential type in a standard format using a YAML/JSON-like definition, enabling the assignment of new credential types to jobs and inventory updates. This enables you to define a custom credential type that works in ways similar to existing credential types. For example, you can create a custom credential type that injects an API token for a third-party web service into an environment variable, which your playbook or custom inventory script can consume.

To encrypt secret fields, {PlatformNameShort} uses AES in CBC mode with a 256-bit key for encryption, PKCS7 padding, and HMAC using SHA256 for authentication. The encryption/decryption process derives the AES-256 bit encryption key from the `SECRET_KEY`, the field name of the model field, and the database-assigned auto-incremented record ID. Thus, if any attribute used in the key generation process changes, {PlatformNameShort} fails to correctly decrypt the secret. {PlatformNameShort} is designed such that the `SECRET_KEY` is never readable in playbooks {PlatformNameShort} launches, so that these secrets are never readable by {PlatformNameShort} users, and no secret field values are ever made available through the {PlatformNameShort} REST API. If a secret value is used in a playbook, you must use `no_log` on the task so that it is not accidentally logged. For more information, see link:https://docs.ansible.com/ansible/latest/reference_appendices/logging.html#protecting-sensitive-data-with-no-log[Protecting sensitive data with no log].
