// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="proc-file-systems-mounted-noexec.adoc_{context}"]

= File systems mounted with "noexec"

[role="_abstract"]

The Red Hat Enterprise Linux 8 STIG requires that a number of file systems are mounted with the `noexec` option to prevent execution of binaries located in these file systems. The {PlatformNameShort} installer runs a preflight check that will fail if any of the following file systems are mounted with the `noexec` option:

* `/tmp`
* `/var`
* `/var/tmp`

To install {PlatformNameShort}, you must re-mount these file systems with the `noexec` option removed. Once installation is complete, proceed with the following steps:

. Reapply the `noexec` option to the `/tmp` and `/var/tmp` file systems.
. Change the {ControllerName} job execution path from `/tmp` to an alternate directory that does not have the `noexec` option enabled.
. To make this change, log in to the {ControllerName} UI as an administrator, navigate to menu:Settings[Jobs] settings.
. Change the "Job execution path" setting to the alternate directory.

During normal operations, the file system which contains the `/var/lib/awx` subdirectory (typically `/var`) must not be mounted with the `noexec` option, or the {ControllerName} cannot run automation jobs in execution environments.

In environments where STIG controls are routinely audited, discuss waiving the STIG controls related to file system `noexec` with your security auditor.