// Module included in the following assemblies: 
// downstream/assemblies/assembly-hardening-aap.adoc

[id="ref-automation-controller-authentication_{context}"]

= Automation controller authentication

[role="_abstract"]

{ControllerNameStart} currently supports the following external authentication mechanisms:

* Azure Activity Directory
* GitHub single sign-on
* Google OAuth2 single sign-in
* LDAP
* RADIUS
* SAML
* TACACS+
* Generic OIDC

Choose an authentication mechanism that adheres to your organization's authentication policies, and refer to the link:https://docs.ansible.com/automation-controller/latest/html/administration/configure_tower_in_tower.html#authentication[Controller Configuration - Authentication] documentation to understand the prerequisites for the relevant authentication mechanism. The authentication mechanism used must ensure that the authentication-related traffic between {PlatformNameShort} and the authentication back-end is encrypted when the traffic occurs on a public or non-secure network (for example, LDAPS or LDAP over TLS, HTTPS for OAuth2 and SAML providers, etc.).

In {ControllerName}, any “system administrator” account can edit, change, and update any inventory or automation definition. Restrict these account privileges to the minimum set of users possible for low-level {ControllerName} configuration and disaster recovery.



