// Module included in the following assemblies:  
// downstream/assemblies/assembly-hardening-aap.adoc

[id="ref-automation-controller-operational-secrets_{context"]

= Automation controller operational secrets

[role="abstract"]

{ControllerNameStart} contains the following secrets used operationally:app-name: 

.{ControllerNameStart} operational secrets
|===
| *File* | *Details* 
| `/etc/tower/SECRET_KEY` | A secret key used for encrypting automation secrets in the database. If the SECRET_KEY changes or is unknown, no encrypted fields in the database will be accessible.

| `/etc/tower/tower.cert`

`/etc/tower/tower.key`| SSL certificate and key for the {ControllerName} web service. A self-signed cert/key is installed by default; you can provide a locally appropriate certificate and key (see xref:<insert link to table 4>[link_Installing with user-provided PKI certificates] below).

| `/etc/tower/conf.d/postgres.py` | Contains the password used by the {ControllerName} to connect to the database.

| `/etc/tower/conf.d/channels.py` | Contains the secret used by the automation controller for websocket broadcasts.
|===

These secrets are all stored unencrypted on the {ControllerNameStart} server, as the {ControllerName} service must read them all in an automated fashion at startup. All files are protected by Unix permissions, and restricted to the root user or the {ControllerName} service user awx.  These files should be routinely monitored to ensure there has been no unauthorized access or modification.

[NOTE]
====
{ControllerNameStart} was formerly named Ansible Tower. These file locations retain the previous product name.
====