
ifdef::context[:parent-context: {context}]



[id="assembly-multi-machine-cluster-scenario"]
= Installing {PlatformName} components on a multi-machine cluster


:context: cluster-scenario

[role="_abstract"]
You can install {PlatformNameShort} as clustered {ControllerName} with {HubName} with an external managed database. In this mode, multiple {ControllerName} nodes are installed and active. Any node can receive HTTP requests and all nodes can execute jobs. This installs the {PlatformNameShort} server in a cluster and configures it to talk to a remote instance of PostgreSQL as its database. This remote PostgreSQL can be a server you manage, or can be provided by a cloud service such as Amazon RDS.

[IMPORTANT]
====
The {PlatformNameShort} installer allows you to deploy *only one* {HubName} per inventory. You can use the {PlatformNameShort} installer for a standalone instance of {HubName} and run the installer any number of times with any number of different inventories to deploy multiple {HubName} nodes.
====

include::platform/ref-multi-node-cluster-installation.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
