
ifdef::context[:parent-context: {context}]

////
 Base the file name and the ID on the assembly title. For example:
* file name: assembly-my-user-story.adoc
* ID: [id="assembly-my-user-story_{context}"]
* Title: = My user story

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken. Include {context} in the ID so the assembly can be reused.
////

[id="assembly-installing_on_rhel_{context}"]
= Installing Ansible content navigator on RHEL

:context: install-navigator-rhel

////
The `context` attribute enables module reuse. Every module ID includes {context}, which ensures that the module has a unique ID so you can include it multiple times in the same guide.
////

[role="_abstract"]
You can install Ansible content navigator on Red Hat Enterprise Linux (RHEL) 8 with `pip`, a downloaded tarball, or a downloaded RPM.

== Prerequisites

* You have installed RHEL 8 or later.

include::navigator/proc-installing-navigator-rhel-pip.adoc[leveloffset=+1]
include::navigator/proc-installing-navigator-rhel-tar.adoc[leveloffset=+1]
include::navigator/proc-installing-navigator-rhel-rpm.adoc[leveloffset=+1]

You have now installed Ansible-navigator and can use this tool to evaluate your playbooks, view your collections and inventories, and delve into the module-level documentation.

////
Restore the context to what it was before this assembly.
////
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]