
ifdef::context[:parent-context: {context}]



[id="migrating-ansible-versions"]
= Migrating between Ansible Core versions

:context: migrating-ansible-versions



[role="_abstract"]
Migrating between versions of Ansible Core requires you to update your playbooks, plugins and other parts of your Ansible infrastructure to ensure they work with the latest version. This process requires that changes are validated against the updates made to each successive version of Ansible Core. If you intend to migrate from Ansible 2.9 to Ansible 2.11, you first need to verify that you meet the requirements of Ansible 2.10, and from there make updates to 2.11.

== Ansible Porting Guides

The Ansible _Porting Guide_ is a series of documents that provide information on the behavioral changes between consecutive Ansible versions. Refer to the guides when migrating from version of Ansible to a newer version.



[role="_additional-resources"]
== Additional resources

* Refer to the link:https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.9.html#ansible-2-9-porting-guide[Ansible 2.9] for behavior changes between Ansible 2.8 and Ansible 2.9.
* Refer to the link:https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.10.html[Ansible 2.10] for behavior changes between Ansible 2.9 and Ansible 2.10.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
