////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]



[id="creating-content"]
= My user story
////
If the assembly covers a task, start the title with a verb in the gerund form, such as Creating or Configuring.
////

:context: creating-content


[role="_abstract"]
This paragraph is the assembly introduction. It explains what the user will accomplish by working through the modules in the assembly and sets the context for the user story the assembly is based on. The text that immediately follows the `[role="_abstract"]` tag is used for search metadata.



////
The following include statements pull in the module files that comprise the assembly. Include any combination of concept, procedure, or reference modules required to cover the user story. You can also include other assemblies.
////

include::modules/TEMPLATE_CONCEPT_explaining_a_concept.adoc[leveloffset=+1]

////
[leveloffset=+1] ensures that when a module title is a level 1 heading (= Title), the heading will be interpreted as a level-2 heading (== Title) in the assembly. Use [leveloffset=+2] and [leveloffset=+3] to nest modules in an assembly.
////

include::modules/TEMPLATE_PROCEDURE_doing_one_procedure.adoc[leveloffset=+2]
include::modules/TEMPLATE_PROCEDURE_reference-material.adoc[leveloffset=2]

[role="_additional-resources"]
== Additional resources (or Next steps)
////
Optional. Delete if not used.
////
* A bulleted list of links to other material closely related to the contents of the assembly, including xref links to other assemblies in your collection.
* For more details on writing assemblies, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

////
Restore the context to what it was before this assembly.
////
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
